-- Unidade de medida REAL para 74 insumos, vinda do relatório de saldo do Wik,
-- e a correção das regras de dedução que esse relatório expôs.
--
-- ---------------------------------------------------------------------------
-- O que mudou desde a 0064
-- ---------------------------------------------------------------------------
-- A 0064 cadastrou os 503 itens da "LISTA DE MAT.PRIMA", que NÃO traz unidade
-- de medida, e por isso deduziu a unidade por regra, marcando o quanto se
-- podia confiar em cada dedução (`insumos.unidade_confianca`).
--
-- Em 10/09/2026 chegou um segundo relatório do Wik — "Saldo de estoque de
-- Matéria-Prima", 16 páginas, filtro "Estoque Positivo" — e ele TEM a coluna
-- UND. MED. Ou seja: para os itens que têm saldo, existe a unidade de
-- verdade, e não há mais o que deduzir.
--
-- 74 referências do relatório de saldo casaram com a lista de preços (68 pela
-- descrição exata, 6 pela referência exata quando a descrição vinha truncada
-- de forma diferente nos dois relatórios). Nenhuma ficou sem par.
--
-- ---------------------------------------------------------------------------
-- O que a conferência revelou
-- ---------------------------------------------------------------------------
-- Das 74 unidades deduzidas, **70 estavam certas e 4 erradas** — e as 4
-- estavam justamente na faixa de confiança ALTA, que é a que entra no custo
-- sem passar por conferência. Duas causas, as duas consertadas em
-- `server/src/lib/insumoUnidade.js`:
--
--   1. ORDEM DAS REGRAS. "ETIQUETA DE TAMANHO OG PIQUET" e "ETQUETA DE
--      TAMANHO MISS MANU MALHA" caíam na regra de malharia (PIQUET, MALHA)
--      antes da regra de etiqueta, e saíam em QUILO. São etiquetas, contadas
--      por peça. As regras de etiqueta, tag e botão passaram a vir antes das
--      de malharia.
--
--   2. "TECIDO" NÃO QUER DIZER PLANO. "TECIDO DYNAMIC FIT-UV50+" e "TECIDO
--      FITNESS FURADINHO" estão estocados em QUILO — são malha, e a palavra
--      "TECIDO" no começo do nome não avisa. A regra que dava confiança ALTA
--      para qualquer coisa começada por "TECIDO" foi rebaixada para MÉDIA:
--      quando nenhuma palavra diz se é plano ou malha, o item vai para a fila
--      de conferência em vez de virar custo calado.
--
--      Isso AUMENTA a fila de conferência de 135 para 162 itens. É o
--      resultado certo: o relatório provou que aquela categoria não era
--      confiável, e fila maior é melhor que custo errado com cara de certo.
--
--   3. De bônus, o relatório resolveu o caso que estava marcado como o mais
--      traiçoeiro da lista: as **14 entretelas de gola e punho** em estoque
--      estão TODAS em UN. Nesta casa elas entram já cortadas, por peça — não
--      é mais leitura, é dado. Essa regra subiu de "palpite" para confiança
--      alta.
--
-- ---------------------------------------------------------------------------
-- O que esta migration faz
-- ---------------------------------------------------------------------------
-- 1. Grava a unidade REAL dos 74 e zera `unidade_confianca` neles — deixam de
--    ser dedução do sistema e passam a ser dado do ERP. Saem da fila para
--    sempre, e passam a poder entrar no custo sem ressalva.
-- 2. Guarda nas observações o código numérico do Wik (que a lista de preços
--    não trazia), o subgrupo, e o saldo por cor com a data.
-- 3. Melhora o `tipo` a partir do subgrupo do Wik (TEC BLUSA → tecido,
--    BOTÃO → aviamento, ETIQUETAS → etiqueta…).
-- 4. Vincula o fornecedor por nome EXATO, para os que ainda estavam sem.
-- 5. Reclassifica os 63 itens SEM prova cuja dedução mudou com as regras
--    corrigidas — e só esses; quem já foi confirmado por gente não é tocado.
--
-- ⚠️ O QUE ELA NÃO FAZ: não lança estoque. O relatório traz saldo por cor, e
--    o cadastro de insumo aqui é por referência (uma linha por artigo, não
--    por cor) — somar as cores num saldo só perderia a informação de cor, e
--    inventar saldo no cadastro é estoque que aparece do nada. O saldo por
--    cor está escrito nas observações de cada insumo, pronto para virar
--    inventário quando alguém decidir fazer o inventário de verdade.
--
-- ⚠️ Não altera o motor de cálculo (REGRA 1). Nenhuma tabela nova, nenhuma
--    coluna nova (REGRA 4) — só dado.
--
-- ---------------------------------------------------------------------------
-- O que ainda falta
-- ---------------------------------------------------------------------------
-- O relatório de saldo sai com filtro "Estoque Positivo", então cobre só as
-- 74 referências que têm saldo. As outras 429 continuam com unidade deduzida.
-- **O mesmo relatório sem esse filtro resolveria as 503 de uma vez** — é o
-- caminho mais curto para acabar com a dedução de unidade neste sistema.

-- ---------------------------------------------------------------------------
-- 1. As 74 unidades confirmadas pelo ERP
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE _saldo_wik (
  codigo      VARCHAR(60),
  unidade     VARCHAR(20),
  tipo        VARCHAR(30),
  fornecedor_nome TEXT,
  observacoes TEXT
) ON COMMIT DROP;

INSERT INTO _saldo_wik (codigo, unidade, tipo, fornecedor_nome, observacoes) VALUES
  ('TEC MALHA CONF', 'kg', 'tecido', 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 475. Subgrupo no Wik: TEC BLUSA. Saldo no Wik em 10/09/2026 (1.393,1500 kg no total, por cor): AZUL MARINHO: 63,7000 · BEGE: 131,4400 · CANELA: 126,4400 · ETERIO: 79,8000 · EXTREME(VERDE MILITAR): 194,1600 · GRAFITE: 79,2000 · MARRON LUXO: 208,4400 · MARSALA: 46,1300 · MOCHA MOUSSE: 48,3700 · MOSTARDA: 3,0000 · PRETO: 217,3000 · ROSA BEBE: 64,7000 · VERMELHO: 130,4700. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC ROVACEL', 'm', 'tecido', 'ROVACH INDUSTRIA TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 210. Subgrupo no Wik: TEC CAMISA. Saldo no Wik em 10/09/2026 (2.303,0000 m no total, por cor): TEC ROV AZUL MARINHO(0530): 495,0000 · TEC ROV BRANCO(0001): 400,0000 · TEC ROV KAKI(0687): 200,0000 · TEC ROV MARRON(3027): 308,0000 · TEC ROV MILITAR(2038): 500,0000 · TEC ROV PRETO(0011): 400,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC PIQUE DUPL', 'kg', 'tecido', 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 355. Subgrupo no Wik: TEC POLO PIQUE. Saldo no Wik em 10/09/2026 (809,9400 kg no total, por cor): BRANCO: 229,1200 · BROWN(MARRON): 116,2900 · CHOCOLATE (BEGE): 115,2500 · MARINA(AZUL MARINHO): 76,5500 · MARSALA: 128,8000 · PRETO: 74,0500 · VERDE MILITAR: 69,8800. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('BOT PER 18 HBN', 'un', 'aviamento', 'IBG INDUSTRIA DE BOTOES GUAIRA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 222. Subgrupo no Wik: BOTÃO. Saldo no Wik em 10/09/2026 (216.144,0000 un no total, por cor): AMARELO ESCURO(B201): 21600 · AMARELO(A642): 9792 · AZUL CLARO(7910): 15552 · AZUL MARINHO(8091): 36432 · AZUL PETROLEO (7232): 1440 · BRANCO(200): 14400 · CHUMBO(9272): 16560 · CINZA(7239): 14832 · GRAFITE (9199): 1440 · MARRON CAFÉ(9561): 6480 · MARSALA(8262): 5616 · PRETO: 34560 · PRETO(232): 14400 · ROSA CLARO(7246): 4320 · TERRA COTA(9842): 2880 · VERDE(9471): 6480 · VINHO(8853): 9360. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('BOT FIOR 18 PER', 'un', 'aviamento', 'IBG INDUSTRIA DE BOTOES GUAIRA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 223. Subgrupo no Wik: BOTÃO. Saldo no Wik em 10/09/2026 (5.472,0000 un no total, por cor): AMDEIRADO(783): 2592 · AZUL(2437): 1440 · CINZA(717): 1440. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('BOT PER OG', 'un', 'aviamento', 'IBG INDUSTRIA DE BOTOES GUAIRA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 470. Subgrupo no Wik: BOTÃO. Saldo no Wik em 10/09/2026 (189.194,0000 un no total, por cor): AZUL CLARO OG(7237): 36000 · AZUL JEANS(8886): 4320 · AZUL MARINHO OG(8042): 3552 · BEGE(9750): 18496 · BRANCO(200): 32400 · MARRON CAFE OG(A983): 2664 · MARSALA(8262): 18720 · PRETO(232): 6930 · ROSA CHICLETE(7996): 10080 · ROSA PINK(AM2): 1440 · ROSA(9813): 10800 · VERDE(9471): 40192 · VERMELHO(8301): 3600. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('CAR 1,0CM DONI', 'm', 'aviamento', 'ETICAL ETIQUETAS CARUARU', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 500. Subgrupo no Wik: CADARCO. Saldo no Wik em 10/09/2026 (7.235,0000 m no total, por cor): AZUL MARINHO: 1600,0000 · MARRON CAFE: 1300,0000 · OFF WHITE: 1365,0000 · PRETO: 1470,0000 · VERDE MILITAR: 1500,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('CAR 1CM TRA DO', 'm', 'aviamento', 'ETICAL ETIQUETAS CARUARU', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 501. Subgrupo no Wik: CADARCO. Saldo no Wik em 10/09/2026 (4.900,0000 m no total, por cor): BRANCO: 1600,0000 · CINZA: 1400,0000 · PRETO: 1900,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC FIBRA BAMB', 'm', 'tecido', 'EDINE MALHAS', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 474. Subgrupo no Wik: D - TEC CAMISARIA. Saldo no Wik em 10/09/2026 (5.558,0000 m no total, por cor): AZUL MARINHO: 939,3000 · BEGE CHINO: 578,6000 · CINZA CHUMBO: 397,8000 · MARRON MUSTANG: 166,8000 · MARSALA: 642,4000 · PRETO: 1399,8000 · TERRA COTA: 456,3000 · VERDE MILITAR: 977,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC ROVAFLEX', 'm', 'tecido', 'ROVACH INDUSTRIA TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 476. Subgrupo no Wik: D - TEC CAMISARIA. Saldo no Wik em 10/09/2026 (1.040,0000 m no total, por cor): TEC ROVAF MARROM(3027): 601,0000 · TEC ROVAF VINHO(1636): 439,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT PUN OG', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 11. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (6.400,0000 un no total, por cor): UNICA: 800 · UNICA: 1400 · UNICA: 1600 · UNICA: 2600. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA TNT', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 216. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (7.897,0000 un no total, por cor): UNICA: 2195 · UNICA: 2147 · UNICA: 1722 · UNICA: 1833. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA PADRE', 'un', 'aviamento', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 262. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (435,0000 un no total, por cor): UNICA: 95 · UNICA: 143 · UNICA: 83 · UNICA: 45 · UNICA: 69. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOL INF', 'un', 'aviamento', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 275. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (399,0000 un no total, por cor): UNICA: 17 · UNICA: 109 · UNICA: 101 · UNICA: 52 · UNICA: 112 · UNICA: 8. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA DUP', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 472. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (6.150,0000 un no total, por cor): UNICA: 2035 · UNICA: 1587 · UNICA: 1710 · UNICA: 818. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('ENT PUN CHA', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 473. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (23.043,0000 un no total, por cor): UNICA: 400 · UNICA: 8904 · UNICA: 6437 · UNICA: 4413 · UNICA: 2889. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA TR', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 477. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (8.778,0000 un no total, por cor): UNICA: 200 · UNICA: 2563 · UNICA: 2238 · UNICA: 2409 · UNICA: 1368. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA TRA', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 478. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (2.517,0000 un no total, por cor): UNICA: 339 · UNICA: 241 · UNICA: 1433 · UNICA: 504. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('ENT GOLA ITAL', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 479. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (5.128,0000 un no total, por cor): UNICA: 200 · UNICA: 1631 · UNICA: 1485 · UNICA: 962 · UNICA: 850. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA ITAL A', 'un', 'aviamento', 'CHARGEURS PCC BRASIL TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 480. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (447,0000 un no total, por cor): UNICA: 388 · UNICA: 45 · UNICA: 14. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA PAULO', 'un', 'aviamento', 'COLARINHOS HP', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 481. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (879,0000 un no total, por cor): UNICA: 34 · UNICA: 411 · UNICA: 49 · UNICA: 385. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('ENT GOLA PA 29', 'un', 'aviamento', 'COLARINHOS HP', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 482. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (430,0000 un no total, por cor): UNICA: 62 · UNICA: 215 · UNICA: 153. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT GOLA ENT', 'un', 'aviamento', 'CONE SUL AVIAMENTOS', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 483. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (365,0000 un no total, por cor): UNICA: 155 · UNICA: 31 · UNICA: 179. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ENT PUN HP136', 'un', 'aviamento', 'CENTAURO AVIAMENTOS E TECIDOS LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 499. Subgrupo no Wik: ENTRETELAS. Saldo no Wik em 10/09/2026 (2.371,0000 un no total, por cor): UNICA: 1109 · UNICA: 1262. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ SLIM', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 15. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (757,0000 un no total, por cor): UNICA: 757. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN 00 (2)', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 218. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (13.792,0000 un no total, por cor): PRETO: 2481 · PRETO: 3989 · PRETO: 5865 · PRETO: 1457. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HOG', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 219. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (1.500,0000 un no total, por cor): CINZA: 1500. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN 00 (3)', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 234. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (31.940,0000 un no total, por cor): BEGE: 8736 · BEGE: 3650 · BEGE: 9190 · BEGE: 3959 · PRETO: 3885 · PRETO: 235 · PRETO: 2040 · PRETO: 245. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ HBN 004', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 235. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (31.532,0000 un no total, por cor): BEGE: 12684 · PRETO: 18848. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM OG 001', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 266. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (64,0000 un no total, por cor): PRETO: 64. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN 00 (4)', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 267. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (5.960,0000 un no total, por cor): BEGE: 5624 · PRETO: 336. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN 00 (5)', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 268. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (2.768,0000 un no total, por cor): PRETO: 2768. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM MM', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 269. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (5.120,0000 un no total, por cor): UNICA: 5120. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('ETQ TAM MM 003', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 270. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (1.673,0000 un no total, por cor): PRETO: 1673. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('ETQ SLIM FIT', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 276. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (12.529,0000 un no total, por cor): BEGE: 3889 · PRETO: 8640. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ SLIM PREM', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 277. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (5.584,0000 un no total, por cor): BEGE: 1084 · PRETO: 4500. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ PALA HOG', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 286. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (10.868,0000 un no total, por cor): CINZA: 10868. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TN', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 331. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (3.618,0000 un no total, por cor): UNICA: 3618. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN 00', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 48. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (18.362,0000 un no total, por cor): PRETO: 1060 · PRETO: 2489 · PRETO: 4368 · PRETO: 5759 · PRETO: 2933 · PRETO: 1365 · PRETO: 388. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ AJ S/T', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 488. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (12.217,0000 un no total, por cor): UNICA: 12217. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ OG F30', 'un', 'etiqueta', 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 489. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (11.362,0000 un no total, por cor): UNICA: 3694 · UNICA: 2629 · UNICA: 3012 · UNICA: 2027. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ S/T OG F30', 'un', 'etiqueta', 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 490. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (1.522,0000 un no total, por cor): UNICA: 1522. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ OG S/COMP', 'un', 'etiqueta', 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 491. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (3.526,0000 un no total, por cor): UNICA: 780 · UNICA: 292 · UNICA: 1287 · UNICA: 1167. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ OG PIQ', 'un', 'etiqueta', 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 492. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (5.016,0000 un no total, por cor): UNICA: 785 · UNICA: 1263 · UNICA: 1660 · UNICA: 1308. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ OG TAM', 'un', 'etiqueta', 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 493. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (10.675,0000 un no total, por cor): UNICA: 3909 · UNICA: 3056 · UNICA: 2383 · UNICA: 1327. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ MM S/T', 'un', 'etiqueta', 'ETICAL', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 495. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (6.784,0000 un no total, por cor): UNICA: 6784. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ MM DIAG', 'un', 'etiqueta', 'ETICAL', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 497. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (16.066,0000 un no total, por cor): CINZA: 1920 · CINZA: 1250 · CINZA: 1825 · CINZA: 1300 · MARRON: 1125 · MARRON: 900 · MARRON: 1525 · MARRON: 600 · PRETO: 1400 · PRETO: 1319 · PRETO: 1563 · PRETO: 1339. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM TN FEM', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 498. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (927,0000 un no total, por cor): UNICA: 327 · UNICA: 187 · UNICA: 229 · UNICA: 184. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('CAR 1CM RIS DO', 'm', 'etiqueta', 'ETICAL ETIQUETAS CARUARU', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 502. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (6.000,0000 m no total, por cor): BEGE/PRETO: 2100,0000 · PRETO/BRANCO: 1900,0000 · PRETO/OFF: 2000,0000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ SINT ETIPRI', 'un', 'etiqueta', 'ETICAL ETIQUETAS CARUARU', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 503. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (3.100,0000 un no total, por cor): PRETO: 3100. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ PAL HBN', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 7. Subgrupo no Wik: ETIQUETAS. Saldo no Wik em 10/09/2026 (4.420,0000 un no total, por cor): BEGE: 3510 · PRETO: 910. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC MEIA MALHA', 'kg', 'tecido', 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 465. Subgrupo no Wik: FIO 30. Saldo no Wik em 10/09/2026 (135,3000 kg no total, por cor): HOLANDA-VERDE: 55,7800 · UNICA: 79,5200. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('RET PUN PA', 'kg', 'aviamento', 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 485. Subgrupo no Wik: GOLA E PUNHO. Saldo no Wik em 10/09/2026 (141,2340 kg no total, por cor): BRANCO: 28,4000 · BROWN(MARRON): 18,6520 · CHOCOLATE (BEGE): 18,1420 · MARINA(AZUL MARINHO): 16,5180 · MARSALA: 20,4940 · PRETO: 15,0260 · VERDE MILITAR: 24,0020. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('RET GOL PA', 'kg', 'aviamento', 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 486. Subgrupo no Wik: GOLA E PUNHO. Saldo no Wik em 10/09/2026 (128,9550 kg no total, por cor): BRANCO: 34,8800 · BROWN(MARRON): 20,1400 · CHOCOLATE (BEGE): 19,4400 · MARINA(AZUL MARINHO): 14,6980 · MARSALA: 25,1540 · PRETO: 6,4300 · VERDE MILITAR: 8,2130. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('LACRE TN', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 330. Subgrupo no Wik: LACRE. Saldo no Wik em 10/09/2026 (3.729,0000 un no total, por cor): UNICA: 3729. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM MM 002', 'un', NULL, 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 233. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (8.316,0000 un no total, por cor): PRETO: 558 · PRETO: 1434 · PRETO: 1009 · PRETO: 1603 · PRETO: 2328 · PRETO: 1384. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HBN', 'un', NULL, 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 265. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (3.066,0000 un no total, por cor): PRETO: 2439 · UNICA: 627. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por referência exata.'),
  ('FIX OG', 'un', NULL, 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 289. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (4.732,0000 un no total, por cor): UNICA: 4732. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ TAM HOGA', 'un', NULL, 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 352. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (4.020,0000 un no total, por cor): UNICA: 370 · UNICA: 1601 · UNICA: 1610 · UNICA: 439. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC FITNES FUR', 'kg', NULL, 'MALHARIA INDAIAL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Corrige a dedução automática, que dizia "m". Código do Wik: 456. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (2.851,7800 kg no total, por cor): AZUL MARINHO: 491,8800 · AZUL ROYAL: 399,8100 · GRAFITE: 378,7900 · MARSALA: 316,8200 · ROSA: 317,1800 · ROXO: 357,5900 · VERDE: 335,7500 · VERDE MILITAR: 253,9600. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('RETILINEA GOLA', 'kg', NULL, 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 466. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (50,4430 kg no total, por cor): AZUL MARINHO: 6,4980 · BEGE: 3,9480 · HOLANDA-VERDE: 28,6330 · MARRON: 4,1170 · MARSALA: 2,2880 · PRETO: 4,9590. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('RETILINEA PUNH', 'kg', NULL, 'MALHAS WILSON LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Confere com a dedução automática. Código do Wik: 467. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (145,5290 kg no total, por cor): AZUL MARINHO: 28,4600 · HOLANDA-VERDE: 29,8350 · MARRON: 27,2860 · MARSALA: 14,0900 · MESCLA: 17,5460 · PRETO: 28,3120. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC DYNAMIC', 'kg', NULL, 'NANETE TEXTIL LTDA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): kg. Corrige a dedução automática, que dizia "m". Código do Wik: 469. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (69,2300 kg no total, por cor): BRANCO: 15,7600 · PRETO: 33,1000 · SQUASH(BEGE): 20,3700. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('BOT BORDA', 'un', NULL, 'IBG INDUSTRIA DE BOTOES GUAIRA', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 471. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (129.888,0000 un no total, por cor): BORDA AZUL(A449): 12384 · BORDA BRANCA(A473): 32976 · BORDA MARRON(A446): 15552 · BORDA MARSALA(A447): 18000 · BORDA PRETA(A448): 31248 · BORDA TERRA COTA(A419): 2880 · BORDA VERDE(A450): 16848. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TEC TRIC', 'm', NULL, 'TECIDOS MARTINS', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): m. Confere com a dedução automática. Código do Wik: 487. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (534,4000 m no total, por cor): UNICA: 534,4000. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ETQ OG S/T', 'un', NULL, 'ETIQUETAS REI', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 494. Subgrupo no Wik: SEM SUBGRUPO. Saldo no Wik em 10/09/2026 (1.012,0000 un no total, por cor): UNICA: 1012. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG HBN', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 16. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (2.701,0000 un no total, por cor): UNICA: 2701. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG MM', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 250. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (17.570,0000 un no total, por cor): UNICA: 17570. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG OG', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 252. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (23,0000 un no total, por cor): UNICA: 23. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG AJ', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 318. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (2.594,0000 un no total, por cor): UNICA: 2594. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG TN', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 329. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (3.291,0000 un no total, por cor): UNICA: 3291. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG HEBRON REL', 'un', 'etiqueta', NULL, 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 416. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (10.183,0000 un no total, por cor): UNICA: 10183. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('TAG TN F', 'un', 'etiqueta', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 484. Subgrupo no Wik: TAG. Saldo no Wik em 10/09/2026 (3.337,0000 un no total, por cor): UNICA: 3337. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.'),
  ('ZIPER', 'un', 'aviamento', 'SEM FORNECEDOR', 'Unidade CONFIRMADA pelo relatório "Saldo de estoque de Matéria-Prima" do Wik (10/09/2026): un. Confere com a dedução automática. Código do Wik: 213. Subgrupo no Wik: ZIPER. Saldo no Wik em 10/09/2026 (4.183,0000 un no total, por cor): BEGE: 50 · BEGE: 453 · MARRON: 66 · MARRON: 173 · MARSALA: 200 · MARSALA: 300 · PRETO: 2595 · PRETO: 108 · PRETO: 43 · VERDE: 95 · VERDE: 100. NÃO lançado como estoque — entrada de estoque é por nota ou inventário. Casado com a lista de preços por descrição exata.');

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM _saldo_wik;
  IF n <> 74 THEN
    RAISE EXCEPTION 'Esperava 74 referências confirmadas pelo relatório de saldo, vieram %. Migration abortada.', n;
  END IF;
END $$;

-- Só toca em quem ainda está com unidade DEDUZIDA. Se alguém já confirmou a
-- unidade na tela (unidade_confianca IS NULL), a decisão da pessoa vence — ela
-- pode saber de algo que nem o relatório sabe.
UPDATE insumos i
   SET unidade = s.unidade,
       unidade_confianca = NULL,
       tipo = COALESCE(s.tipo, i.tipo),
       fornecedor_id = COALESCE(
         i.fornecedor_id,
         (SELECT f.id FROM fornecedores f
           WHERE upper(btrim(f.nome)) = upper(btrim(s.fornecedor_nome))
           ORDER BY f.id LIMIT 1)),
       observacoes = COALESCE(NULLIF(i.observacoes, ''), '') ||
         CASE WHEN COALESCE(i.observacoes, '') = '' THEN '' ELSE E'\n' END || s.observacoes,
       atualizado_em = now()
  FROM _saldo_wik s
 WHERE s.codigo = i.codigo
   AND i.unidade_confianca IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. Os 63 que continuam sem prova, mas cuja dedução mudou com as regras
--    corrigidas. Mesma trava: quem já foi confirmado por gente não é tocado,
--    e quem acabou de ser confirmado pelo relatório acima também não (o
--    UPDATE anterior já zerou o `unidade_confianca` deles).
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE _reclass_wik (
  codigo      VARCHAR(60),
  unidade     VARCHAR(20),
  tipo        VARCHAR(30),
  confianca   VARCHAR(20),
  observacoes TEXT
) ON COMMIT DROP;

INSERT INTO _reclass_wik (codigo, unidade, tipo, confianca, observacoes) VALUES
  ('ENT GOLA HBN', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('ENT PALA', 'un', 'aviamento', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela que não é de gola/punho — pode vir em rolo (metro) ou já cortada (peça): CONFIRA'),
  ('PT001', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TC-BEL', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TCBLU', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC TRA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC LIV', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('01TM', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('01TF', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC FLORAL', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('EDGM01', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('TPCB01', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('ENT PAT', 'un', 'aviamento', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela que não é de gola/punho — pode vir em rolo (metro) ou já cortada (peça): CONFIRA'),
  ('TEC DAKOTA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('ENT PUN HBN', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('ENT CALÇA', 'un', 'aviamento', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela que não é de gola/punho — pode vir em rolo (metro) ou já cortada (peça): CONFIRA'),
  ('ETQ TAM MM 001', 'un', 'etiqueta', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: etiqueta — contada por peça'),
  ('ENT PUN INF', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('ENT PUN INFT', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('TEC FLORAL 001', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC SCAPE', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('ENT 001', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('TEC PT', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC NEV', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC MINI OT', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC ORFEU', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC NEW GLUE', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC LEGEN', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC FRANK', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC NEVADA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC NEW WEST2', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC HOPE STR', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC MOULINE', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('KIT GOLA PIQUE', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: gola/punho pronto — entra na peça já cortado, contado por peça'),
  ('TEC VALERIA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC MEGA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC ORIENTE', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC SKINNY', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC ADONIS', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO MERCERI', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO ACETINA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO COTON L', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO PASSA F', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO PIEMONT', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO AREZAN', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO BIARRIT', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO LISTRAD', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO DAS REF', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('ENTRETELA DE G', 'un', 'aviamento', 'alta', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: entretela de gola/punho — as 14 que o Wik tem em estoque estão todas em UN, cortadas por peça'),
  ('TECIDO NEW JO', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO SAVANA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO NEW PAR', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO KLHOE T', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO ECO IRIS', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO FLAMÊ 1', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO MANTOV', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECIDO ACETINA (2)', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TECC01', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('45168', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC CONJUNTO', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC BELLAGIO', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC MALHA FURA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA'),
  ('TEC-STELLA', 'm', 'tecido', 'media', 'Reclassificado em 10/09/2026 com as regras corrigidas pelo relatório de saldo: começa por "TECIDO" mas nenhuma palavra diz se é plano (metro) ou malha (quilo) — tratado como metro, CONFIRA');

UPDATE insumos i
   SET unidade = r.unidade,
       tipo = r.tipo,
       unidade_confianca = r.confianca,
       observacoes = COALESCE(NULLIF(i.observacoes, ''), '') ||
         CASE WHEN COALESCE(i.observacoes, '') = '' THEN '' ELSE E'\n' END || r.observacoes,
       atualizado_em = now()
  FROM _reclass_wik r
 WHERE r.codigo = i.codigo
   AND i.unidade_confianca IS NOT NULL;
