// Verbetes do módulo Análises — Dashboard Executivo (/dashboard,
// DashboardPage.jsx), Ficha de Precificação (/ficha-precificacao,
// FichaPrecificacaoPage.jsx — a ficha original de composição de preço,
// preservada como estava), Central de Alertas (/alertas, AlertasPage.jsx) e
// Simulador de Cenários (/simulador, SimuladorPage.jsx). Nenhum verbete deste
// módulo sugere um valor "certo" pra digitar num campo de cálculo — Ficha de
// Precificação e Simulador só mostram o que a tela exibe e como ela funciona.

export const verbetesAnalises = [
  {
    id: 'analises-dashboard-indicadores',
    modulo: 'analises',
    tela: 'Dashboard Executivo',
    titulo: 'Indicadores consolidados e evolução diária (Dashboard)',
    rota: '/dashboard',
    perguntas: [
      'dashboard executivo',
      'faturamento consolidado de todos os canais',
      'lucro liquido do periodo',
      'margem consolidada',
      'ticket medio geral',
      'quantos pedidos no periodo',
      'vendas por canal',
      'grafico de faturamento e lucro',
      'comparar com periodo anterior',
      'filtrar dashboard por empresa',
      'filtrar dashboard por canal de venda',
    ],
    resposta:
      'O **Dashboard Executivo** consolida faturamento, lucro e margem de toda a operação — todos os canais de venda juntos (manual e marketplace) — num período escolhido, com filtro opcional por empresa. Os indicadores do topo (Faturamento, Lucro líquido, Pedidos, Peças vendidas, Ticket médio e Margem consolidada) mostram a variação em relação ao período anterior equivalente.\n\nO card **Vendas por Canal** lista a participação de cada canal no faturamento — clicar num canal filtra o dashboard inteiro só por ele (clicar de novo tira o filtro). Ao lado, o gráfico **Evolução Diária** compara faturamento e lucro dia a dia no período. No rodapé, o selo de confiança mostra sobre quantos pedidos o cálculo foi feito, de quantos existem no período.',
    relacionados: ['analises-dashboard-top-produtos'],
  },
  {
    id: 'analises-dashboard-top-produtos',
    modulo: 'analises',
    tela: 'Dashboard Executivo',
    titulo: 'Top produtos por lucro e referências abaixo da margem mínima',
    rota: '/dashboard',
    perguntas: [
      'top produtos por lucro',
      'produtos que mais consomem margem',
      'produto com pior margem',
      'referencias abaixo da margem minima',
      'quais produtos estao vendendo com margem baixa',
    ],
    resposta:
      'No Dashboard Executivo, o card **Top 10 Produtos por Lucro** mostra as referências que mais lucro deram no período; ao lado, **Top 10 Produtos que Mais Consomem Margem** lista as referências com a menor margem no período, considerando só quem vendeu 2 ou mais unidades (pra não destacar um caso isolado). Clicar numa referência em qualquer uma das tabelas abre a ficha do produto.\n\nQuando existe alguma, aparece também o card **Referências Abaixo da Margem Mínima**, com todas as referências cuja margem apurada no período ficou abaixo do limite configurado em Configurações → Parâmetros.',
    relacionados: ['analises-dashboard-indicadores', 'analises-alertas'],
  },
  {
    id: 'analises-ficha-precificacao',
    modulo: 'analises',
    tela: 'Ficha de Precificação',
    titulo: 'Ficha de Precificação — composição do preço de uma referência',
    rota: '/ficha-precificacao',
    perguntas: [
      'ficha de precificacao',
      'composicao do preco de venda',
      'grafico de rosca do preco',
      'onde o preco esta entre minimo e premium',
      'percentual de materiais sobre o custo',
      'percentual de mao de obra industrial',
      'percentual de despesas indiretas',
      'percentual de impostos do custo',
      'ultimas referencias consultadas na ficha',
      'preco praticado vs preco sugerido',
    ],
    resposta:
      'A **Ficha de Precificação** mostra, pra uma referência escolhida, a composição completa do preço de venda: um gráfico de rosca com a fatia de Materiais, Industrial, Indireto, Impostos, Taxas e Lucro dentro do preço, mais um indicador de "Onde o preço está" — uma faixa visual entre o preço mínimo, ideal e premium, com uma marca mostrando onde o preço ativo (praticado ou sugerido) cai nessa faixa.\n\nOs quatro indicadores no topo mostram % de Custo com Materiais, % de Mão de Obra Industrial, % de Despesas Indiretas e % de Impostos, todos sobre o custo total da peça. É a mesma ficha de composição de preço de sempre, preservada como estava, só que agora acessível como tela própria do módulo Análises. Sem nenhuma referência selecionada, a tela mostra atalhos pras últimas referências consultadas.',
    relacionados: ['analises-simulador'],
  },
  {
    id: 'analises-alertas',
    modulo: 'analises',
    tela: 'Central de Alertas',
    titulo: 'Central de Alertas — referências fora dos limites configurados',
    rota: '/alertas',
    perguntas: [
      'central de alertas',
      'referencias fora do limite',
      'alerta de margem baixa',
      'alerta de custo alto',
      'filtrar alertas por empresa',
      'filtrar alertas por marca',
      'filtrar alertas por categoria',
      'referencia nao avaliavel nos alertas',
      'quantas referencias tem alerta',
      'onde configuro os limites dos alertas',
      'margem la debaixo do esperado quais referencias',
    ],
    resposta:
      'A **Central de Alertas** mostra, agora, quais referências estão fora de cada limite configurado em Configurações → Parâmetros (por exemplo, % de materiais acima do esperado, margem abaixo do mínimo). Dá pra filtrar por empresa, marca e categoria. Cada grupo de alerta mostra o limite configurado e a lista de referências fora dele, com o valor apurado e o desvio — clicar na seta de uma linha abre a ficha do produto.\n\nReferência com material cadastrado mas valor unitário zerado entra num grupo separado, **"Não avaliável — falta custo de material"**: mostrar "0%, dentro do limite" nesse caso seria uma aprovação falsa, então ela fica de fora do grupo de alerta normal até o custo ser preenchido de verdade. O selo de confiança no rodapé mostra quantas referências foram avaliadas, de quantas existem no total.',
    relacionados: ['analises-dashboard-top-produtos'],
  },
  {
    id: 'analises-simulador',
    modulo: 'analises',
    tela: 'Simulador de Cenários',
    titulo: 'Simulador de Cenários — testar ajustes hipotéticos sem alterar o produto',
    rota: '/simulador',
    perguntas: [
      'simulador de cenarios',
      'testar aumento de custo sem salvar',
      'simular reajuste de preco',
      'ajuste hipotetico de material',
      'ajuste hipotetico de frete',
      'ajuste hipotetico de impostos',
      'simular nova margem',
      'comparar cenario atual com cenario simulado',
      'diferenca entre preco base e preco simulado',
      'simulacao nao altera o produto de verdade',
      'simular aumento no preco do tecido',
    ],
    resposta:
      'O **Simulador de Cenários** testa ajustes hipotéticos de custo, frete, impostos, taxas/comissão e margem desejada de uma referência, sem alterar nenhum dado real do produto. Depois de escolher a referência, o card **Valores base** mostra os números atuais dela (custo de materiais, industrial, indireto, % de impostos, % de taxas, margem desejada e preço sugerido), pra referência.\n\nO card **Ajustes do cenário** tem campos pra ajustar, hipoteticamente: preço do tecido/materiais, custo da facção/industrial e energia/rateio indireto (em %), frete extra não previsto (em R$), impostos e comissão/taxas (em pontos percentuais somados à base), e uma nova margem desejada (deixando em branco mantém a margem base). Qualquer alteração já recalcula o cenário simulado, mostrado lado a lado com o cenário atual — subtotal de produção, custo total, preço sugerido e lucro dos dois — e a diferença entre o preço simulado e o preço sugerido base, em R$ e em %.',
    relacionados: ['analises-ficha-precificacao'],
  },

  // --- Telas novas (10/09/2026): mix B2B x B2C e preço por canal.
  {
    id: 'analises-mix-tributario-parametros',
    modulo: 'analises',
    tela: 'Mix B2B × B2C',
    titulo: 'Mix B2B × B2C — pra que serve e o prazo da opção do Simples Nacional',
    rota: '/analises/mix-tributario',
    perguntas: [
      'mix tributario b2b b2c',
      'mix b2b x b2c o que e',
      'prazo pra optar pelo simples nacional',
      'quanto falta pra 30 09 2026',
      'filtro de empresa no mix tributario',
      'janela de meses do mix tributario',
      'mix tributario por empresa',
      'a tela recomenda qual regime tributario',
      'mix tributario decide o regime',
      'para que serve a tela mix b2b b2c',
    ],
    resposta:
      'A tela **Mix B2B × B2C** mede quanto do faturamento de cada empresa vai para cliente que aproveita crédito de IBS/CBS (venda com CNPJ) e quanto vai para consumidor final (CPF e a maior parte do marketplace). Ela existe por causa de um prazo real: a janela pra optar pelo Simples Nacional ou pelo regime regular vai de 1 a 30 de setembro de 2026, com efeito em 2027 — enquanto esse prazo não vence, a tela mostra "Faltam N dia(s) para 30/09/2026" no topo.\n\n**A tela mede o mix; ela não recomenda regime tributário** — essa decisão é do contador, com o número na mão. O filtro **Empresa** existe porque a opção do Simples é decidida por CNPJ: sem esse filtro, o número mostrado é do grupo inteiro e não serve pra basear a opção de uma empresa específica. O filtro **Janela** escolhe quantos meses de histórico entram na conta (6, 12 ou 24 meses).',
    relacionados: ['analises-mix-tributario-classificacao', 'analises-mix-tributario-tabelas', 'gloss-regime-tributario'],
  },
  {
    id: 'analises-mix-tributario-classificacao',
    modulo: 'analises',
    tela: 'Mix B2B × B2C',
    titulo: 'Como cada venda é classificada em B2B ou B2C, e por que o resultado é uma faixa',
    rota: '/analises/mix-tributario',
    perguntas: [
      'como e classificado b2b ou b2c',
      'cnpj e b2b cpf e b2c',
      'marketplace conta como b2b ou b2c',
      'so o que esta documentado toggle',
      'presuncao do canal',
      'por que pj conta e pf nao',
      'faixa de b2b na duvida',
      'venda sem documento como e contada',
      'confianca confirmada declarada presumida',
      'botao como cada venda e classificada',
    ],
    resposta:
      'A classificação é feita **pelo documento** primeiro: CNPJ no cadastro do cliente é **B2B**, CPF é **B2C**, e os dígitos verificadores são conferidos de verdade (não basta o tamanho do número). Quando não há documento, entra o **canal**: pedido de marketplace conta como consumidor final, mas com confiança **presumida** — o marketplace não informa o documento de quem comprou. O botão **"Só o que está documentado"** desliga essa presunção: ligado, marketplace deixa de contar como B2C e vira "não classificado".\n\nAinda sem documento nem canal, o campo **PJ/PF** do cadastro decide de um jeito assimétrico: no banco, **PF é o valor padrão da coluna** (ninguém afirmou nada), enquanto **PJ é algo que alguém digitou**. Por isso, PJ sem documento entra como B2B com confiança **declarada**, e PF sem documento **não entra em lado nenhum**. É por causa desse faturamento não classificado que o indicador **"B2B na dúvida"** aparece como uma faixa (por exemplo "31% – 44%") em vez de um número só — o mínimo é a conta assumindo que todo esse faturamento fosse B2C, o máximo é assumindo que fosse todo B2B, e a faixa fecha sozinha conforme o cadastro dos clientes vai sendo preenchido com documento.',
    relacionados: ['analises-mix-tributario-parametros', 'analises-mix-tributario-tabelas'],
  },
  {
    id: 'analises-mix-tributario-tabelas',
    modulo: 'analises',
    tela: 'Mix B2B × B2C',
    titulo: 'A tabela "De onde veio cada real" e o ranking de clientes B2B',
    rota: '/analises/mix-tributario',
    perguntas: [
      'de onde veio cada real tabela',
      'tabela de criterios do mix tributario',
      'ranking de clientes b2b',
      'quais clientes sao b2b',
      'documento mascarado do cliente',
      'grafico empilhado por mes do mix',
      'faturamento nao classificado no grafico',
      'variacao de b2b entre dois meses',
      'quantos pedidos por criterio de classificacao',
    ],
    resposta:
      'Abaixo dos indicadores, o gráfico de colunas empilhado mostra o faturamento mês a mês já separado em B2B, B2C e "não classificado" (a parte de cima de cada barra) — quando aparece, o texto logo abaixo compara a participação de B2B entre o primeiro e o último mês do período (é a diferença entre dois meses medidos, não uma projeção).\n\nA tabela **"De onde veio cada real"** mostra, por critério de classificação (documento, canal, PJ/PF), quantos pedidos, quanto faturamento e qual a **confiança** de cada um (confirmada, declarada, presumida ou nenhuma) — é o mesmo faturamento total, só que separado pelo que o sistema realmente sabia na hora de classificar. Já a tabela **"Os clientes do lado B2B"** lista, do maior faturamento pro menor, os clientes classificados como B2B no período, com o documento mascarado (só os quatro últimos dígitos aparecem) e o critério usado pra classificar cada um — são estes clientes que, a partir de 2027, passam a comparar o crédito que a nota da empresa dá com o de outro fornecedor.',
    relacionados: ['analises-mix-tributario-classificacao', 'analises-mix-tributario-parametros'],
  },
  {
    id: 'analises-preco-por-canal-parametros',
    modulo: 'analises',
    tela: 'Preço por Canal',
    titulo: 'Preço por Canal — escolher a referência e os parâmetros de Pix e frete',
    rota: '/analises/preco-por-canal',
    perguntas: [
      'preco por canal o que e',
      'para que serve a tela preco por canal',
      'escolher referencia no preco por canal',
      'considerar pix no preco por canal',
      'incluir frete subsidiado no custo',
      'peso do produto no preco por canal',
      'preco por canal grava o preco',
      'custo de producao no preco por canal',
      'imposto da empresa no preco por canal',
    ],
    resposta:
      'A tela **Preço por Canal** junta o custo e o imposto que já existem no motor de cálculo do produto com a tabela de comissão de cada marketplace, e responde duas perguntas: por quanto vender em cada canal pra bater cada faixa de margem, e que margem o preço praticado hoje realmente entrega em cada canal. **Ela não grava preço** — só lê o custo/imposto do motor e mostra a conta; mudar o preço de verdade é feito na Ficha do produto, por uma pessoa.\n\nDepois de escolher a **Referência**, dois checkboxes ajustam a conta: **"Considerar Pix"** usa a condição em que o canal subsidia parte da comissão (alguns marketplaces cobram uma comissão menor em compra no Pix), e **"Incluir o frete subsidiado no custo"** soma ao custo a parte do frete que a empresa banca. Os indicadores do topo mostram o **Custo de produção** (materiais + industrial + indireto, o mesmo número da Ficha), o **Imposto da empresa**, o **Preço praticado** (ou "não informado") e o **Peso cadastrado** — sem peso, o sistema não acha a faixa de frete por peso, o frete subsidiado fica de fora da conta, e o preço calculado sai otimista.',
    relacionados: ['analises-preco-por-canal-tabela-canais', 'analises-preco-por-canal-preco-praticado'],
  },
  {
    id: 'analises-preco-por-canal-tabela-canais',
    modulo: 'analises',
    tela: 'Preço por Canal',
    titulo: 'A tabela por canal: faixas de margem, comissão e "vender por"',
    rota: '/analises/preco-por-canal',
    perguntas: [
      'tabela de preco por canal marketplace',
      'coluna vender por o que significa',
      'coluna comissao da faixa',
      'coluna fixo por peca',
      'coluna margem que sobra',
      'para ter percentual na tabela de canal',
      'faixa em que a margem nao cabe',
      'ressalva do canal no preco por canal',
      'tipo de anuncio no preco por canal',
    ],
    resposta:
      'Cada card de canal (marketplace, com o tipo de anúncio quando existe mais de um) tem uma linha por faixa de margem cadastrada pra aquele canal: **"Para ter"** mostra o rótulo e o percentual dessa faixa, **"Vender por"** é o preço calculado pra bater essa margem naquele canal específico, **"Comissão da faixa"** e **"Fixo por peça"** vêm da tabela de taxas daquele marketplace, e **"Margem que sobra"** é a margem real depois de aplicar comissão e taxa fixa sobre o preço calculado. A coluna **Observação** explica linhas que não fecharam (motivo), preços presos num degrau da tabela de comissão, ou avisos — quando está tudo certo e a faixa não tem ressalva, ela diz apenas que o preço é consistente com a própria faixa da tabela.\n\nQuando alguma faixa de margem simplesmente não cabe no preço daquele canal, ela some da tabela principal e vai para **"Faixas em que essa margem não cabe no preço"**, um bloco que só abre se você clicar — com o motivo de cada faixa impossível. Avisos do canal como um todo (ressalvas) aparecem no topo do card, antes da tabela.',
    relacionados: ['analises-preco-por-canal-parametros', 'analises-preco-por-canal-preco-praticado'],
  },
  {
    id: 'analises-preco-por-canal-preco-praticado',
    modulo: 'analises',
    tela: 'Preço por Canal',
    titulo: 'O que o preço praticado hoje entrega de margem em cada canal',
    rota: '/analises/preco-por-canal',
    perguntas: [
      'preco praticado hoje entrega quanto de margem',
      'margem do preco praticado por canal',
      'aviso de margem abaixo do minimo no canal',
      'preco praticado nao informado no preco por canal',
      'margem minima configurada no preco por canal',
      'preco por canal decide qual preco usar',
    ],
    resposta:
      'Logo abaixo do nome de cada canal, quando existe um preço praticado cadastrado no produto, a tela mostra uma frase com o preço praticado, a margem que ele entrega **naquele canal específico** e a comissão (mais a taxa fixa, se houver) usada na conta. Esse bloco muda de tom conforme o resultado: quando a margem calculada fica abaixo da margem mínima configurada em Configurações → Parâmetros, aparece com um alerta visual; caso contrário, aparece como confirmação — mas em nenhum dos dois casos a tela diz que o preço deveria mudar, só mostra o número. Quando não há preço praticado (ou não dá pra calcular a margem dele naquele canal), aparece o motivo no lugar da margem.\n\nComo a tela **não grava nada**, essa margem é só uma leitura de "com o preço que está lá hoje, é isso que sobra depois da comissão desse canal" — decidir se vale mudar o preço, e pra qual valor, é feito fora desta tela, na Ficha do produto.',
    relacionados: ['analises-preco-por-canal-parametros', 'analises-preco-por-canal-tabela-canais'],
  },
];
