// Verbetes do módulo Compras — lista de compras (/compras, ComprasListPage.jsx),
// o lançamento/edição de cada compra (/compras/:id, CompraFormPage.jsx — como
// "Nova compra" cria a compra na hora e já navega pro id real, sem uma rota
// fixa tipo "/compras/novo", os verbetes sobre essa tela apontam pra /compras,
// a lista), o Relatório de Compras (/compras/relatorio,
// RelatorioComprasPage.jsx), a lista de Fornecedores (/fornecedores,
// FornecedoresListPage.jsx) e a ficha de fornecedor (/fornecedores/novo —
// rota fixa e navegável, igual a /produtos/novo — e /fornecedores/:id,
// FornecedorFichaPage.jsx).

export const verbetesCompras = [
  {
    id: 'compras-listar-filtrar',
    modulo: 'compras',
    tela: 'Compras',
    titulo: 'Ver e filtrar as compras lançadas',
    rota: '/compras',
    perguntas: [
      'onde vejo as compras',
      'lista de compras',
      'filtrar compras por categoria',
      'buscar compra por fornecedor',
      'buscar compra por numero de documento',
      'compra pendente',
      'compra recebida',
      'compra cancelada',
      'exportar compras',
      'para que serve o modulo de compras',
      'compra de material de escritorio',
    ],
    resposta:
      'A tela **Compras** lista o lançamento de todas as compras da empresa — de matéria-prima a material de escritório. As abas no topo filtram por categoria de compra (as mesmas categorias cadastradas em Configurações → Listas); também dá pra buscar por fornecedor ou número da compra/documento.\n\nCada linha mostra número, data, fornecedor, categoria, documento, total líquido e situação: **Pendente**, **Recebido** ou **Cancelado**. A lista pode ser exportada em CSV/XLSX, e o botão **Nova compra** já cria a compra e abre a ficha dela pra começar a lançar itens.',
    relacionados: ['compras-criar-fornecedor-cabecalho', 'compras-relatorio'],
  },
  {
    id: 'compras-criar-fornecedor-cabecalho',
    modulo: 'compras',
    tela: 'Compra',
    titulo: 'Criar uma compra e vincular o fornecedor',
    rota: '/compras',
    perguntas: [
      'como crio uma compra',
      'nova compra',
      'vincular fornecedor na compra',
      'buscar fornecedor na compra',
      'cadastrar fornecedor rapido na compra',
      'trocar fornecedor da compra',
      'categoria da compra',
      'numero do documento nota ou cupom',
      'situacao da compra pendente recebido cancelado',
      'forma e condicao de pagamento da compra',
      'desconto e frete da compra',
      'excluir compra',
    ],
    resposta:
      'Clicando em **Nova compra** (na lista, opcionalmente já dentro de uma categoria escolhida na aba), o sistema cria a compra na hora e abre a ficha dela. No card **Fornecedor**, busque por nome, CPF/CNPJ ou telefone e clique em **Selecionar** — ou, se ainda não existe, clique em **Novo fornecedor** pra cadastrar rapidinho (nome, telefone, CPF/CNPJ) sem sair da tela da compra. Dá pra trocar o fornecedor depois clicando em **Trocar fornecedor**.\n\nO card **Dados da Compra** guarda data, categoria, número do documento (nota/cupom), situação, forma e condição de pagamento, desconto em R$, valor do frete e observação — cada campo salva sozinho ao sair dele. O botão **Excluir** (no topo da ficha) apaga a compra inteira, sem volta.',
    relacionados: ['compras-listar-filtrar', 'compras-lancar-itens-totais'],
  },
  {
    id: 'compras-lancar-itens-totais',
    modulo: 'compras',
    tela: 'Compra',
    titulo: 'Lançar itens da compra e ver os totais',
    rota: '/compras',
    perguntas: [
      'lancar item na compra',
      'adicionar item na compra',
      'descricao unidade quantidade valor unitario da compra',
      'editar item da compra',
      'remover item da compra',
      'total bruto da compra',
      'total liquido da compra',
      'como o desconto e o frete entram no total da compra',
    ],
    resposta:
      'No card **Lançar Item**, cada item da compra tem descrição livre, unidade (com sugestões das unidades cadastradas), quantidade e valor unitário — clicar em **Adicionar** já lança o item e limpa o formulário pra continuar digitando o próximo. Na tabela **Itens da Compra**, cada campo é editável direto na linha (salva ao sair do campo), e o ícone de lixeira remove o item.\n\nO card **Totais** mostra Total Bruto (soma dos itens), Desconto, Frete e Total Líquido — os dois últimos vêm dos campos de desconto e frete lançados no card Dados da Compra, não item a item.',
    relacionados: ['compras-criar-fornecedor-cabecalho'],
  },
  {
    id: 'compras-relatorio',
    modulo: 'compras',
    tela: 'Relatório de Compras',
    titulo: 'Relatório de Compras por período, categoria e fornecedor',
    rota: '/compras/relatorio',
    perguntas: [
      'relatorio de compras',
      'quanto gastei em compras',
      'total gasto no periodo de compras',
      'ticket medio de compras',
      'compras por categoria',
      'compras por fornecedor',
      'imprimir relatorio de compras',
      'quanto gastei em compra esse mes',
    ],
    resposta:
      'A tela **Relatório de Compras** soma as compras lançadas num período, com filtro opcional por categoria e por fornecedor. Mostra o Total Gasto no Período, a Quantidade de Compras e o Ticket Médio, além de duas quebras: **Por Categoria** e **Por Fornecedor** (quantidade e total de cada uma), e a lista completa das compras do período. O botão **Imprimir** gera uma versão só do relatório, sem os filtros.',
    relacionados: ['compras-listar-filtrar'],
  },
  {
    id: 'fornecedores-listar-buscar',
    modulo: 'compras',
    tela: 'Fornecedores',
    titulo: 'Ver e buscar fornecedores cadastrados',
    rota: '/fornecedores',
    perguntas: [
      'onde vejo os fornecedores',
      'lista de fornecedores',
      'buscar fornecedor por nome',
      'buscar fornecedor por cnpj',
      'buscar fornecedor por telefone',
      'fornecedor ativo ou inativo',
      'novo fornecedor',
      'malharia que vendeu pra mim cadastro onde',
    ],
    resposta:
      'A tela **Fornecedores** lista o cadastro usado nos lançamentos de compra: nome, CPF/CNPJ, telefone, categoria principal e se está ativo. Dá pra buscar por nome, CPF/CNPJ ou telefone. Clicar numa linha (ou no botão **Novo fornecedor**) abre a ficha completa do fornecedor.',
    relacionados: ['fornecedores-cadastro-completo', 'compras-criar-fornecedor-cabecalho'],
  },
  {
    id: 'fornecedores-cadastro-completo',
    modulo: 'compras',
    tela: 'Ficha de Fornecedor',
    titulo: 'Cadastro completo de fornecedor (identificação, endereço, dados comerciais)',
    rota: '/fornecedores/novo',
    perguntas: [
      'cadastrar fornecedor completo',
      'editar dados do fornecedor',
      'pessoa fisica ou juridica no fornecedor',
      'inscricao estadual isenta',
      'buscar cep do fornecedor',
      'condicao de pagamento padrao do fornecedor',
      'chave pix do fornecedor',
      'dados bancarios do fornecedor',
      'desativar fornecedor',
      'remover fornecedor',
    ],
    resposta:
      'A ficha de fornecedor tem quatro blocos: **Identificação** (Pessoa Jurídica ou Física, razão social/nome, nome fantasia, CNPJ/CPF, Inscrição Estadual — com checkbox "Isento"), **Contato** (telefone/WhatsApp, e-mail), **Endereço** (com botão pra buscar o endereço automaticamente a partir do CEP, preenchendo logradouro/bairro/cidade/UF — se o CEP não for encontrado ou a consulta falhar, é só preencher manualmente) e **Comercial** (categoria principal, condição de pagamento padrão, chave PIX, dados bancários, observações, e o alternador **Ativo?**).\n\nO botão **Salvar** grava o cadastro (obrigatório preencher o nome). Em fornecedor já existente, o botão **Remover** apaga o cadastro. Desativar (alternador "Ativo?" para "Não") mantém o cadastro salvo sem excluir — útil pra fornecedor que parou de ser usado sem perder o histórico das compras já lançadas com ele.',
    relacionados: ['fornecedores-listar-buscar'],
  },

  // --- Telas novas (10/09/2026): insumos e notas, cotações, pedidos de
  // ==========================================================================
  // Insumos e Notas — /compras/insumos
  // ==========================================================================
  {
    id: 'compras-insumos-cadastro',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'Cadastrar um insumo (matéria-prima)',
    rota: '/compras/insumos',
    perguntas: [
      'como cadastro um insumo',
      'novo insumo',
      'cadastrar malha zíper linha etiqueta',
      'unidade de compra e unidade de consumo do insumo',
      'fator de conversao do insumo',
      'lote minimo do insumo',
      'multiplo de compra do insumo',
      'perda de corte do insumo',
      'fornecedor habitual do insumo',
      'prazo prometido do insumo',
      'tipo de insumo tecido aviamento embalagem etiqueta',
      'preciso digitar o custo ao cadastrar o insumo',
    ],
    resposta:
      'Em **Insumos e Notas**, o botão **Novo insumo** abre um formulário curto de propósito: só **Nome** e **Unidade de compra** são obrigatórios. O resto — código do fornecedor, tipo (Tecido, Aviamento, Embalagem, Etiqueta, Serviço, Outro), especificação, cor, largura, gramatura — é o que melhora a conta quando existe, mas não trava o cadastro.\n\nO bloco **Compra** guarda fornecedor habitual, **Prazo prometido (dias)** — o prazo real é medido sozinho a partir do terceiro recebimento cronometrado e passa a valer no lugar deste —, **Lote mínimo** (o fornecedor não vende menos que isso) e **Múltiplo de compra**. No bloco **Perda**, a **Perda de corte (%)** é digitada em porcentagem e gravada como fração; deixar em branco não vale zero — a necessidade de material sai subestimada e a ordem de produção avisa disso. Se o insumo tem unidade de consumo diferente da de compra (comprado em kg, usado em metro, por exemplo), o **Fator de conversão** diz quanto de uma unidade cabe na outra.\n\nO custo **não se digita aqui** — ele entra pela nota fiscal, que é o que faz o custo da peça reagir ao preço real do material. Um insumo recém-criado aparece como "sem custo" na lista até a primeira nota ser lançada, e isso é diferente de custo R$ 0,00.',
    relacionados: ['compras-insumos-importar-nota', 'compras-insumos-ficha'],
  },
  {
    id: 'compras-insumos-ficha',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'Ver a ficha de um insumo (saldo, custo, fichas que usam, movimentos, prazos)',
    rota: '/compras/insumos',
    perguntas: [
      'ficha do insumo',
      'ver saldo do insumo',
      'quais fichas tecnicas usam este insumo',
      'historico de custo do insumo',
      'desde quando esse preco esta assim',
      'movimentos de entrada e saida do insumo',
      'prazo medido versus prazo prometido do insumo',
      'clicar no insumo abre o que',
      'quantos lotes ou fornecedores tem o saldo do insumo',
    ],
    resposta:
      'Clicar numa linha da lista de insumos abre a **ficha do insumo** (não o cadastro — o cadastro fica a um clique dali, no ícone de lápis). No topo aparecem quatro números: **Saldo** (somado de todos os lotes/fornecedores), **Custo atual**, **Fichas que usam** este insumo e **Prazo prometido**, com a nota de que o prazo medido passa a valer a partir do terceiro recebimento cronometrado.\n\nAbaixo, quatro abas. **Fichas** mostra quais referências de produto usam o insumo, o consumo por peça e o valor gravado "na ficha" — quando esse valor está diferente do custo atual, é a aba **Fichas desatualizadas** (fora desta tela de ficha) que mostra a diferença e permite aplicar. **Custo** é o histórico de cada mudança de preço, com data, fornecedor e a nota fiscal de origem — quando não há "de" (primeiro registro), a tela escreve "primeira", nunca R$ 0,00. **Movimentos** lista as últimas 200 entradas e saídas (entrada por nota, consumo na produção, ajuste, remessa e retorno de facção, perda, inventário). **Prazos** mostra quanto tempo cada recebimento cronometrado levou de verdade.',
    relacionados: ['compras-insumos-cadastro', 'compras-insumos-fichas-defasadas'],
  },
  {
    id: 'compras-insumos-importar-nota',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'Importar o XML da nota fiscal e dar entrada nos insumos',
    rota: '/compras/insumos',
    perguntas: [
      'importar nota fiscal de compra',
      'importar xml da nota',
      'entrada de mercadoria por nota fiscal',
      'como o sistema calcula o custo real do insumo',
      'frete rateado na nota',
      'credito de icms na nota',
      'vincular item da nota a um insumo',
      'fator de conversao ao importar a nota',
      'nota ja foi importada antes',
      'item sem insumo vinculado nao deixa lancar',
    ],
    resposta:
      'Em **Importar nota fiscal**, você envia o arquivo **XML** que o fornecedor mandou. O sistema lê emitente, itens, impostos, frete e parcelas, e calcula o **custo real** de cada item: o valor da nota mais o frete rateado, menos o imposto que a empresa recupera (crédito de ICMS) — por isso o custo real pode ficar diferente do valor unitário que está escrito na nota.\n\nPara cada item da nota é preciso escolher **"Vira qual insumo?"** — o sistema nunca casa por nome parecido automaticamente, então cada linha chega sem vínculo (a não ser que já exista uma decisão anterior salva para aquele fornecedor). Quando a unidade da nota é diferente da unidade de estoque do insumo (nota em quilo, estoque em metro, por exemplo), o campo **Conversão** entra; deixe em branco quando for a mesma unidade. Enquanto houver item sem insumo vinculado, o botão **Lançar a nota** fica bloqueado — lançar assim faria entrar estoque sem saber do quê. Uma nota já importada antes (mesma chave) também trava o lançamento.\n\nDepois de lançada, a tela mostra quais insumos tiveram o custo atualizado (de tal valor para tal valor) e oferece o atalho para ver quais fichas de referência ficaram desatualizadas com essa mudança.',
    relacionados: ['compras-insumos-cadastro', 'compras-insumos-fichas-defasadas', 'compras-insumos-notas-lancadas'],
  },
  {
    id: 'compras-insumos-fichas-defasadas',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'Entender a aba "Fichas desatualizadas" e aplicar o custo novo',
    rota: '/compras/insumos',
    perguntas: [
      'ficha desatualizada',
      'o custo do insumo subiu e agora',
      'aplicar custo novo na ficha tecnica',
      'por que a ficha nao atualiza sozinha quando o insumo muda de preco',
      'marcar fichas para atualizar custo',
      'linhas que nao puderam ser comparadas',
      'atualizar custo em varias fichas de uma vez',
      'diferenca entre custo na ficha e custo de hoje',
    ],
    resposta:
      'Quando uma nota fiscal muda o preço de um insumo, o sistema **não altera a ficha técnica das referências sozinho** — a aba **Fichas desatualizadas** só mostra o que ficou para trás: cada linha traz a referência, o insumo, o valor gravado "na ficha", o custo de hoje e a diferença entre os dois. Aplicar essa mudança é uma decisão de quem usa o sistema, feita marcando as linhas desejadas e clicando em **Atualizar X fichas** (com confirmação, porque isso muda o custo da peça e, com ele, o preço mínimo e a margem calculados a partir dela).\n\nUma linha pode aparecer como **impedida**, sem entrar na comparação — a tela mostra o motivo de cada uma. Quando não há nenhuma ficha desatualizada nem impedida, a aba mostra que tudo está em dia.',
    relacionados: ['compras-insumos-importar-nota', 'compras-insumos-ficha'],
  },
  {
    id: 'compras-insumos-notas-lancadas',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'Consultar as notas fiscais já lançadas',
    rota: '/compras/insumos',
    perguntas: [
      'lista de notas fiscais lancadas',
      'onde vejo as notas de insumo ja importadas',
      'nota veio do xml ou foi digitada',
      'chave de acesso da nota fiscal',
      'quantos itens tem essa nota',
      'total e custo real da nota',
      'nota fiscal digitada manualmente',
      'empresa em que a nota foi lancada',
    ],
    resposta:
      'A aba **Notas lançadas** lista todas as notas de entrada de insumo já lançadas: número, fornecedor (ou emitente, quando o fornecedor ainda não está cadastrado), empresa, data de emissão, quantidade de itens, valor total da nota, custo real calculado e a origem — **XML** (importada) ou **digitada**. Cada nota mostra também os últimos dígitos da chave de acesso, quando ela veio por XML, ou "sem chave" quando foi lançada manualmente.',
    relacionados: ['compras-insumos-importar-nota'],
  },
  {
    id: 'compras-insumos-indicadores',
    modulo: 'compras',
    tela: 'Insumos e Notas',
    titulo: 'O que significam os indicadores do topo (sem custo, valor em estoque, prazo medido)',
    rota: '/compras/insumos',
    perguntas: [
      'insumo sem custo o que quer dizer',
      'valor em estoque dos insumos',
      'quantos insumos tem prazo medido',
      'insumo sem fornecedor',
      'diferenca entre sem custo e custo zero',
      'total de insumos cadastrados',
      'para que servem os cartoes no topo da tela de insumos',
      'quantos insumos ainda nao tem custo conhecido',
    ],
    resposta:
      'A faixa de indicadores no topo de **Insumos e Notas** resume o cadastro inteiro: **Insumos** (total cadastrado), **Sem custo** (insumos em que nenhuma nota fiscal foi lançada ainda — a tela escreve "sem custo", nunca R$ 0,00, porque são coisas diferentes), **Valor em estoque** (soma de saldo × custo atual, contando só quem tem custo conhecido) e **Com prazo medido** (insumos com três ou mais recebimentos cronometrados, ponto em que o prazo real passa a valer mais que o prometido no cadastro).',
    relacionados: ['compras-insumos-cadastro', 'compras-insumos-ficha'],
  },

  // ==========================================================================
  // Cotações — /compras/cotacoes
  // ==========================================================================
  {
    id: 'compras-cotacao-criar',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Criar uma cotação e convidar fornecedores',
    rota: '/compras/cotacoes',
    perguntas: [
      'nova cotacao',
      'criar cotacao de compra',
      'cotar preco com varios fornecedores',
      'convidar fornecedor para responder a cotacao',
      'itens da cotacao insumo cadastrado ou texto livre',
      'prazo de resposta da cotacao',
      'por que a quantidade tem que ser igual para todos',
      'fornecedor que nao respondeu tambem aparece',
    ],
    resposta:
      'O botão **Nova cotação** abre um formulário com **Descrição** (como a equipe vai chamar a cotação) e **Prazo de resposta**. Na tabela de itens, cada linha pode vir de um **insumo cadastrado** (preenche descrição e unidade sozinho) ou de texto livre, mais unidade e quantidade — a mesma cotação pergunta a mesma lista e a mesma quantidade para todos os fornecedores convidados, porque é isso que torna as respostas comparáveis depois.\n\nAbaixo, você marca quais **fornecedores** são convidados a responder. Um convidado que não responde também é informação: é o que mostra, na lista de cotações, que aquela cotação teve uma resposta só e portanto não comparou nada.',
    relacionados: ['compras-cotacao-registrar-proposta', 'compras-cotacao-lista-indicadores', 'fornecedores-cadastro-completo'],
  },
  {
    id: 'compras-cotacao-registrar-proposta',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Registrar a proposta que um fornecedor mandou',
    rota: '/compras/cotacoes',
    perguntas: [
      'registrar proposta de fornecedor na cotacao',
      'lancar preco cotado pelo fornecedor',
      'preco em branco na cotacao significa o que',
      'prazo de entrega da proposta',
      'condicao de pagamento da proposta',
      'frete da proposta do fornecedor',
      'trocar de fornecedor no formulario de resposta',
      'fornecedor nao cotou um item',
    ],
    resposta:
      'O botão **Registrar proposta** abre o formulário para digitar o que um fornecedor específico respondeu: escolha o **Fornecedor** entre os convidados — trocar de fornecedor no seletor traz de volta o que ele já tinha respondido antes, em vez de abrir a grade em branco —, e preencha **Prazo de entrega (dias)**, **Condição de pagamento** e **Frete da proposta**.\n\nNa tabela de itens, cada linha recebe o **preço unitário cotado**. Deixar um item **em branco** significa que aquele fornecedor não cotou aquele item — é diferente de ter cotado por zero, e a matriz de comparação trata os dois casos de forma distinta.',
    relacionados: ['compras-cotacao-criar', 'compras-cotacao-matriz'],
  },
  {
    id: 'compras-cotacao-matriz',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Ler a matriz de comparação de preços da cotação',
    rota: '/compras/cotacoes',
    perguntas: [
      'matriz de comparacao da cotacao',
      'comparar preco entre fornecedores',
      'menor preco cotado de um item',
      'total da proposta por fornecedor',
      'coluna nao cotou na matriz',
      'quem ainda nao respondeu a cotacao',
      'total se fosse tudo pelo menor preco',
      'selo menor na matriz de comparacao',
      'itens ja decididos na cotacao',
    ],
    resposta:
      'Na tela de detalhe da cotação, a **Matriz de comparação** põe cada item numa linha e cada fornecedor convidado numa coluna. A célula mostra o preço unitário cotado e o total daquela linha (preço × quantidade); quando o fornecedor não respondeu aquele item, a célula mostra "não cotou". O menor preço de cada linha vem marcado com o selo **menor** — mas isso é só a marcação de qual número é o menor, a escolha de fechar com ele continua sendo feita à parte, item por item.\n\nA linha **Total da proposta**, no fim da tabela, soma cada coluna só com os itens que aquele fornecedor cotou — por isso duas colunas com quantidades diferentes de itens cotados não são diretamente comparáveis pelo total. Os indicadores no topo do detalhe mostram quantos fornecedores já responderam, quantos itens já foram decididos, o total do que já foi escolhido e, como referência, o total que daria se cada item fosse fechado pelo seu menor preço — este último é só um cálculo de referência, não uma recomendação de compra.',
    relacionados: ['compras-cotacao-registrar-proposta', 'compras-cotacao-escolher-vencedor'],
  },
  {
    id: 'compras-cotacao-escolher-vencedor',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Escolher o fornecedor vencedor de um item (motivo quando não é o menor preço)',
    rota: '/compras/cotacoes',
    perguntas: [
      'escolher vencedor da cotacao',
      'fechar item da cotacao com um fornecedor',
      'motivo da escolha obrigatorio',
      'por que preciso justificar quando nao escolho o menor preco',
      'fechar a malha com um fornecedor e o aviamento com outro',
      'diferenca no total ao escolher fornecedor mais caro',
      'selo escolhido na matriz da cotacao',
      'campo motivo da escolha opcional ou obrigatorio',
    ],
    resposta:
      'Clicar em **Escolher**, na célula de um fornecedor, abre o resumo daquele item: o preço deste fornecedor, o menor preço cotado (e de quem), e a diferença no total do item entre os dois. O vencedor é escolhido **item a item** — é normal fechar a malha com um fornecedor e o aviamento com outro na mesma cotação.\n\nQuando o fornecedor escolhido **não** é o de menor preço, o campo **Motivo da escolha** passa a ser obrigatório — sem ele, quem abrir a cotação daqui a alguns meses vai ler a escolha como erro. Quando é o menor preço, o motivo é opcional. O sistema não diz qual fornecedor deveria ser escolhido: só exige que a escolha, quando foge do menor preço, venha explicada por escrito (prazo de entrega, qualidade, forma de pagamento — o que fez sentido para quem decidiu).',
    relacionados: ['compras-cotacao-matriz', 'compras-cotacao-gerar-pedidos'],
  },
  {
    id: 'compras-cotacao-gerar-pedidos',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Gerar pedidos de compra a partir da cotação',
    rota: '/compras/cotacoes',
    perguntas: [
      'gerar pedido de compra a partir da cotacao',
      'transformar cotacao em pedido',
      'cotacao fechada vira pedido de compra sozinha',
      'pedido nasce em rascunho',
      'um pedido por fornecedor vencedor',
      'onde ficam os pedidos gerados pela cotacao',
      'botao gerar pedidos desabilitado',
      'preciso escolher vencedor de todos os itens para gerar pedido',
    ],
    resposta:
      'O botão **Gerar pedidos**, no detalhe da cotação, só fica disponível depois que pelo menos um item tem vencedor escolhido. Ele cria **um pedido de compra por fornecedor vencedor** — se a malha ficou com um fornecedor e o aviamento com outro, nascem dois pedidos, um para cada um.\n\nOs pedidos nascem em **rascunho** e ainda precisam ser aprovados na tela Pedidos de Compra antes de poder receber mercadoria — gerar o pedido não compromete a empresa com o gasto sozinho, aprovar é que faz isso.',
    relacionados: ['compras-cotacao-escolher-vencedor', 'compras-pedido-aprovar', 'compras-pedido-origem'],
  },
  {
    id: 'compras-cotacao-lista-indicadores',
    modulo: 'compras',
    tela: 'Cotações',
    titulo: 'Ver e filtrar as cotações (abertas, vencidas, sem resposta)',
    rota: '/compras/cotacoes',
    perguntas: [
      'lista de cotacoes',
      'cotacao rascunho aberta fechada cancelada',
      'cotacao passou do prazo de resposta',
      'cotacao sem nenhuma resposta',
      'quantas propostas ainda faltam chegar',
      'abrir cotacao para resposta',
      'cotacao fechada ja virou pedido',
      'buscar cotacao por numero ou descricao',
    ],
    resposta:
      'A lista de **Cotações** filtra por situação — **Rascunho**, **Aberta**, **Fechada**, **Cancelada** — e busca por número ou descrição. Uma cotação nasce em rascunho; o botão **Abrir para resposta**, no detalhe, muda ela para aberta, liberando para registrar propostas.\n\nOs indicadores do topo mostram: **Cotações abertas** (enviadas e ainda esperando resposta ou decisão, sem contar as canceladas), **Propostas que faltam chegar** (soma dos convidados sem resposta nas cotações abertas), **Passaram do prazo** (cotações abertas cujo prazo de resposta já venceu e ainda têm convidado sem responder), **Sem nenhuma resposta** (abertas em que ninguém respondeu ainda, portanto nada dá pra comparar) e **Já decididas** (cotações com vencedor escolhido em pelo menos um item — o que não quer dizer que já viraram pedido de compra).',
    relacionados: ['compras-cotacao-criar', 'compras-cotacao-matriz'],
  },

  // ==========================================================================
  // Pedidos de Compra — /compras/pedidos
  // ==========================================================================
  {
    id: 'compras-pedido-aprovar',
    modulo: 'compras',
    tela: 'Pedidos de Compra',
    titulo: 'Aprovar um pedido de compra (previsão de entrega obrigatória)',
    rota: '/compras/pedidos',
    perguntas: [
      'aprovar pedido de compra',
      'previsao de entrega obrigatoria para aprovar',
      'por que preciso informar a previsao de entrega',
      'quem aprovou o pedido e quando',
      'pedido sem previsao de entrega nao aparece atrasado',
      'aprovar pedido compromete a empresa',
      'pedido aprovado pode receber mercadoria',
      'nao consigo aprovar o pedido de compra',
    ],
    resposta:
      'Aprovar é o que separa "alguém digitou o pedido" de "a casa se comprometeu com o gasto" — o sistema grava quem aprovou e quando. Para aprovar, é obrigatório informar a **Previsão de entrega**: sem prazo prometido não existe atraso a medir, e um pedido sem essa data nunca vai aparecer em nenhuma lista de cobrança.\n\nUm pedido não aprovado não recebe mercadoria — a tela de Recebimentos só oferece pedidos aprovados (ou parcialmente recebidos) para conferir a chegada.',
    relacionados: ['compras-pedido-confronto', 'compras-pedido-cancelar', 'compras-recebimento-abrir'],
  },
  {
    id: 'compras-pedido-cancelar',
    modulo: 'compras',
    tela: 'Pedidos de Compra',
    titulo: 'Cancelar um pedido de compra',
    rota: '/compras/pedidos',
    perguntas: [
      'cancelar pedido de compra',
      'motivo do cancelamento do pedido',
      'pedido cancelado continua existindo',
      'por que nao apaga o pedido cancelado',
      'pedido cancelado sai das somas',
      'como excluir um pedido de compra',
      'pedido cancelado aparece na lista',
      'desistir de um pedido de compra',
    ],
    resposta:
      'Cancelar um pedido de compra exige escrever o **motivo do cancelamento** — o pedido continua existindo depois, com o motivo gravado; cancelar não apaga nada, é o que permite entender, meses depois, por que aquela compra não aconteceu. Na lista de pedidos, um pedido cancelado continua aparecendo, mas fica fora das somas dos indicadores do topo.',
    relacionados: ['compras-pedido-aprovar'],
  },
  {
    id: 'compras-pedido-confronto',
    modulo: 'compras',
    tela: 'Pedidos de Compra',
    titulo: 'Ver o confronto entre o que foi pedido e o que chegou',
    rota: '/compras/pedidos',
    perguntas: [
      'quantidade pedida x quantidade recebida',
      'pedido de compra parcial',
      'quantidade pendente do pedido',
      'valor pedido x valor recebido',
      'a quantidade recebida e um contador',
      'cancelar recebimento devolve a quantidade do pedido',
      'situacao do item nao chegou chegou em parte completo veio a mais',
      'dias de atraso do pedido de compra',
      'confronto pedido de compra x recebimento',
    ],
    resposta:
      'No detalhe de um pedido, o card **Confronto: o que foi pedido × o que chegou** põe as duas quantidades lado a lado, item por item — o pedido nunca é reescrito para o que chegou. Cada linha mostra quantidade e valor pedidos, quantidade e valor recebidos, o quanto ainda está pendente e a **Situação do item**: Não chegou, Chegou em parte, Completo ou Veio a mais.\n\nA quantidade recebida **não é um contador** que alguém digita: ela é sempre a soma dos recebimentos não cancelados vinculados àquele pedido. É por isso que cancelar um recebimento devolve a quantidade pendente na hora, sem precisar editar o pedido manualmente. O card também mostra os dias de atraso, contados contra a previsão de entrega prometida na aprovação — sem previsão, a tela mostra "sem previsão", nunca zero dias de atraso.',
    relacionados: ['compras-pedido-aprovar', 'compras-recebimento-cancelar'],
  },
  {
    id: 'compras-pedido-indicadores-lista',
    modulo: 'compras',
    tela: 'Pedidos de Compra',
    titulo: 'Indicadores e filtros da lista de Pedidos de Compra',
    rota: '/compras/pedidos',
    perguntas: [
      'pedidos de compra atrasados',
      'comprometido e nao recebido',
      'pedidos esperando aprovacao',
      'pedido sem previsao de entrega',
      'filtrar so os pedidos atrasados',
      'buscar pedido por numero ou fornecedor',
      'pior atraso entre os pedidos',
      'exportar lista de pedidos de compra',
    ],
    resposta:
      'A lista de **Pedidos de Compra** filtra por situação (Rascunho, Aguardando aprovação, Aprovado, Recebido em parte, Recebido, Cancelado), tem o filtro **Só os atrasados** e busca por número ou fornecedor. Os indicadores mudam junto com os filtros aplicados.\n\n**Comprometido e não recebido** soma o valor dos pedidos aprovados ou recebidos em parte — dinheiro já prometido ao fornecedor. **Pedidos atrasados** conta os que passaram da data prometida, com o valor parado e o pior atraso em dias. **Esperando aprovação** conta rascunhos e pedidos aguardando aprovação, que ainda não podem receber mercadoria. **Sem previsão de entrega** conta pedidos vivos sem essa data — o defeito que a exigência de previsão na aprovação existe justamente para impedir.',
    relacionados: ['compras-pedido-aprovar', 'compras-pedido-confronto'],
  },
  {
    id: 'compras-pedido-origem',
    modulo: 'compras',
    tela: 'Pedidos de Compra',
    titulo: 'De onde nasce um pedido de compra',
    rota: '/compras/pedidos',
    perguntas: [
      'como surge um pedido de compra',
      'pedido de compra sem cotacao',
      'criar pedido de compra direto',
      'nao tem botao de novo pedido de compra',
      'entregas deste pedido',
      'pedido de compra so nasce da cotacao',
      'nao acho onde criar um pedido de compra novo',
      'ordem em que a compra acontece cotacao pedido recebimento',
    ],
    resposta:
      'A lista de Pedidos de Compra não tem um botão de criar um pedido direto: pedidos de compra nascem de uma **cotação com vencedor escolhido**, na tela Cotações, usando o botão **Gerar pedidos**. É a ordem em que a compra acontece na vida real — primeiro se cota e se decide o fornecedor, depois o pedido formaliza o que foi decidido.\n\nNo detalhe do pedido, o card **Entregas deste pedido** lista os recebimentos já abertos contra ele. Se o pedido está aprovado e ainda não tem nenhum recebimento, a tela linka direto para a tela Recebimentos para começar a conferência da doca; se o pedido ainda não foi aprovado, ele simplesmente não pode receber mercadoria ainda.',
    relacionados: ['compras-cotacao-gerar-pedidos', 'compras-pedido-aprovar', 'compras-recebimento-abrir'],
  },

  // ==========================================================================
  // Recebimentos — /compras/recebimentos
  // ==========================================================================
  {
    id: 'compras-recebimento-abrir',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Abrir a conferência de uma entrega',
    rota: '/compras/recebimentos',
    perguntas: [
      'conferir uma entrega',
      'abrir recebimento',
      'novo recebimento',
      'escolher pedido para receber',
      'pedido aprovado nao aparece para receber',
      'localizacao da mercadoria recebida',
      'data do recebimento',
      'quantidade pendente ja vem preenchida no recebimento',
      'onde a mercadoria foi guardada no galpao',
    ],
    resposta:
      'O botão **Conferir uma entrega** abre o formulário para escolher o **Pedido de compra** que está chegando — só aparecem pedidos com situação Aprovado ou Recebido em parte, porque pedido não aprovado não recebe mercadoria. Ao escolher o pedido, o sistema já traz as linhas que ainda faltavam, com a quantidade pendente preenchida, para quem confere só corrigir o que realmente veio.\n\nOs outros campos são a **Data do recebimento** e **Onde a mercadoria foi colocada** — texto livre, do mesmo jeito que aparece em Onde Está a Peça, por exemplo "Corredor B · prateleira 3".',
    relacionados: ['compras-pedido-aprovar', 'compras-recebimento-bipar', 'compras-recebimento-nao-move-estoque'],
  },
  {
    id: 'compras-recebimento-bipar',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Bipar código de barras na conferência',
    rota: '/compras/recebimentos',
    perguntas: [
      'bipar codigo de barras no recebimento',
      'leitor de codigo de barras na conferencia',
      'codigo lido nao corresponde a nenhuma linha',
      'cada leitura soma quanto na linha',
      'contagem por codigo de barras',
      'pistola de codigo de barras nao funciona no recebimento',
      'como acelerar a contagem da doca',
      'codigo bipado errado como corrigir',
    ],
    resposta:
      'Na conferência de uma entrega em aberto, o campo de **Leitura por código de barras** aceita o leitor bipando direto (ele "digita" o código e aperta Enter sozinho). Cada leitura soma **1** na quantidade recebida da linha correspondente — o sistema procura primeiro por um código já lido igual, depois por descrição ou nome do insumo que contenha o texto bipado.\n\nQuando o código não corresponde a nenhuma linha da entrega, a tela avisa em vez de somar em qualquer lugar, para não distorcer a contagem — quem confere corrige a quantidade manualmente nesse caso. O código lido fica gravado na linha mesmo quando bate: é o registro que explica, depois, de onde veio cada unidade contada.',
    relacionados: ['compras-recebimento-abrir', 'compras-recebimento-confronto-rodape'],
  },
  {
    id: 'compras-recebimento-divergencia',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Fechar a conferência com divergência (motivo obrigatório)',
    rota: '/compras/recebimentos',
    perguntas: [
      'fechar recebimento com divergencia',
      'motivo da divergencia obrigatorio',
      'diferenca entre quantidade pedida e recebida',
      'item que chegou sem estar no pedido',
      'sistema recusa fechar sem explicar a divergencia',
      'nao consigo fechar a conferencia',
      'item chegou a mais do que foi pedido',
      'item chegou a menos do que foi pedido',
    ],
    resposta:
      'Quando alguma linha da entrega não bate com o que foi pedido — recebeu mais, recebeu menos, ou chegou um item que nem estava no pedido — fechar a conferência exige escrever o **Motivo da divergência**. O servidor recusa fechar sem essa explicação; é o que impede a divergência de simplesmente sumir e reaparecer como falta de material semanas depois.\n\nUm item que chegou sem estar no pedido original **não é recusado** pela tela: ele aparece marcado como "não estava no pedido" e conta como divergência, porque é um caso real que acontece na doca.',
    relacionados: ['compras-recebimento-confronto-rodape', 'compras-recebimento-cancelar'],
  },
  {
    id: 'compras-recebimento-cancelar',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Cancelar um recebimento',
    rota: '/compras/recebimentos',
    perguntas: [
      'cancelar recebimento',
      'cancelar entrega ja conferida',
      'motivo do cancelamento do recebimento',
      'cancelar recebimento desfaz a entrega',
      'pedido volta a ficar pendente depois de cancelar recebimento',
      'excluir um recebimento',
      'lancei o recebimento errado como desfazer',
      'recebimento cancelado ainda aparece na lista',
    ],
    resposta:
      'Cancelar um recebimento exige escrever o **motivo**. Cancelar desfaz a entrega: a quantidade que tinha sido contada deixa de contar no pedido de compra na hora, e o pedido volta a aparecer como pendente naquelas linhas — o motivo fica gravado no próprio recebimento.',
    relacionados: ['compras-pedido-confronto', 'compras-recebimento-divergencia'],
  },
  {
    id: 'compras-recebimento-nao-move-estoque',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Por que o recebimento não move estoque nem lança custo',
    rota: '/compras/recebimentos',
    perguntas: [
      'recebimento move o estoque',
      'recebimento lanca o custo do insumo',
      'diferenca entre recebimento e nota fiscal de entrada',
      'entrega chegou sem nota fiscal o que fazer',
      'quem atualiza o custo do insumo entao',
      'recebimento sem nota fiscal vinculada',
      'recebimento e conferencia de doca',
      'porque tem duas telas pedido e recebimento separadas',
    ],
    resposta:
      'O recebimento é a **conferência física** do que chegou na doca — ele não mexe no estoque e não lança custo de insumo nenhum. Quem faz isso é a **nota fiscal de entrada**, lançada em Compras › Insumos e Notas. É normal a mercadoria chegar antes da nota fiscal, e a tela avisa isso quando um recebimento está sem nota vinculada.\n\nOs recebimentos sem nota fiscal formam a fila de trabalho de quem cuida do fiscal: enquanto a nota não é lançada, o custo do insumo recebido não entra no sistema — mesmo que a mercadoria já esteja fisicamente guardada.',
    relacionados: ['compras-recebimento-abrir', 'compras-insumos-importar-nota'],
  },
  {
    id: 'compras-recebimento-confronto-rodape',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Ler o rodapé de confronto do recebimento (Qtd. Comprada × Recebida, Valor Compra × Recebimento)',
    rota: '/compras/recebimentos',
    perguntas: [
      'confronto da entrega no recebimento',
      'quantidade comprada x quantidade recebida',
      'valor compra x valor recebimento',
      'valor unitario do recebimento em branco',
      'itens sem pedido contam como divergencia no rodape',
      'porque o pedido nao e reescrito para o que chegou',
      'valor recebimento maior que valor compra',
      'de onde vem o preco quando nao digito o valor do recebimento',
    ],
    resposta:
      'O card **Confronto da entrega**, no rodapé da conferência, mostra quatro números lado a lado: **Qtd. Comprada** (soma do que o pedido mandou vir nas linhas desta entrega), **Qtd. Recebida** (soma do que a doca contou), **Valor Compra** (quantidade pedida × preço do pedido) e **Valor Recebimento** (quantidade recebida × preço que veio nesta entrega — ou o preço do pedido, quando o campo de valor unitário do recebimento é deixado em branco).\n\nAs duas colunas ficam lado a lado de propósito: o pedido não é reescrito para o que chegou. É essa diferença que permite cobrar o fornecedor depois. Linhas que chegaram sem estar no pedido original também entram na contagem de divergência deste rodapé.',
    relacionados: ['compras-recebimento-bipar', 'compras-recebimento-divergencia', 'compras-pedido-confronto'],
  },
  {
    id: 'compras-recebimento-lista-indicadores',
    modulo: 'compras',
    tela: 'Recebimentos',
    titulo: 'Indicadores e filtros da lista de Recebimentos',
    rota: '/compras/recebimentos',
    perguntas: [
      'recebimentos em conferencia',
      'recebimentos ja conferidos',
      'recebimentos com divergencia',
      'recebimentos sem nota fiscal',
      'filtrar so os recebimentos divergentes',
      'buscar recebimento por fornecedor ou numero do pedido',
      'exportar lista de recebimentos',
      'quantas entregas estao abertas agora',
    ],
    resposta:
      'A lista de **Recebimentos** filtra por situação (Em conferência, Conferido, Cancelado), tem os filtros **Só divergentes** e **Sem nota fiscal**, e busca por fornecedor, número do recebimento ou número do pedido — essa busca é feita sobre a lista já carregada, não no servidor.\n\nOs indicadores do topo mostram: **Em conferência agora** (entregas abertas, ainda sendo contadas na doca — enquanto não fecham, não contam no pedido), **Já conferidas** (entregas fechadas, a partir das quais o pedido de compra vira parcial ou recebido), **Fechadas com divergência** (chegaram diferente do pedido, com motivo escrito — cada uma é uma cobrança em aberto com o fornecedor) e **Ainda sem nota fiscal** (mercadoria que chegou antes da nota; sem ela o custo do insumo não entra).',
    relacionados: ['compras-recebimento-abrir', 'compras-recebimento-nao-move-estoque'],
  },
];
