// Verbetes do módulo Compras — lista de compras (/compras, ComprasListPage.jsx),
// o lançamento/edição de cada compra (/compras/:id, CompraFormPage.jsx — como
// "Nova compra" cria a compra na hora e já navega pro id real, sem uma rota
// fixa tipo "/compras/novo", os verbetes sobre essa tela apontam pra /compras,
// a lista), o Relatório de Compras (/compras/relatorio,
// RelatorioComprasPage.jsx), a lista de Fornecedores (/fornecedores,
// FornecedoresListPage.jsx) e a ficha de fornecedor (/fornecedores/novo —
// rota fixa e navegável, igual a /produtos/novo — e /fornecedores/:id,
// FornecedorFichaPage.jsx).

export const verbetesCompras = [
  {
    id: 'compras-listar-filtrar',
    modulo: 'compras',
    tela: 'Compras',
    titulo: 'Ver e filtrar as compras lançadas',
    rota: '/compras',
    perguntas: [
      'onde vejo as compras',
      'lista de compras',
      'filtrar compras por categoria',
      'buscar compra por fornecedor',
      'buscar compra por numero de documento',
      'compra pendente',
      'compra recebida',
      'compra cancelada',
      'exportar compras',
      'para que serve o modulo de compras',
      'compra de material de escritorio',
    ],
    resposta:
      'A tela **Compras** lista o lançamento de todas as compras da empresa — de matéria-prima a material de escritório. As abas no topo filtram por categoria de compra (as mesmas categorias cadastradas em Configurações → Listas); também dá pra buscar por fornecedor ou número da compra/documento.\n\nCada linha mostra número, data, fornecedor, categoria, documento, total líquido e situação: **Pendente**, **Recebido** ou **Cancelado**. A lista pode ser exportada em CSV/XLSX, e o botão **Nova compra** já cria a compra e abre a ficha dela pra começar a lançar itens.',
    relacionados: ['compras-criar-fornecedor-cabecalho', 'compras-relatorio'],
  },
  {
    id: 'compras-criar-fornecedor-cabecalho',
    modulo: 'compras',
    tela: 'Compra',
    titulo: 'Criar uma compra e vincular o fornecedor',
    rota: '/compras',
    perguntas: [
      'como crio uma compra',
      'nova compra',
      'vincular fornecedor na compra',
      'buscar fornecedor na compra',
      'cadastrar fornecedor rapido na compra',
      'trocar fornecedor da compra',
      'categoria da compra',
      'numero do documento nota ou cupom',
      'situacao da compra pendente recebido cancelado',
      'forma e condicao de pagamento da compra',
      'desconto e frete da compra',
      'excluir compra',
    ],
    resposta:
      'Clicando em **Nova compra** (na lista, opcionalmente já dentro de uma categoria escolhida na aba), o sistema cria a compra na hora e abre a ficha dela. No card **Fornecedor**, busque por nome, CPF/CNPJ ou telefone e clique em **Selecionar** — ou, se ainda não existe, clique em **Novo fornecedor** pra cadastrar rapidinho (nome, telefone, CPF/CNPJ) sem sair da tela da compra. Dá pra trocar o fornecedor depois clicando em **Trocar fornecedor**.\n\nO card **Dados da Compra** guarda data, categoria, número do documento (nota/cupom), situação, forma e condição de pagamento, desconto em R$, valor do frete e observação — cada campo salva sozinho ao sair dele. O botão **Excluir** (no topo da ficha) apaga a compra inteira, sem volta.',
    relacionados: ['compras-listar-filtrar', 'compras-lancar-itens-totais'],
  },
  {
    id: 'compras-lancar-itens-totais',
    modulo: 'compras',
    tela: 'Compra',
    titulo: 'Lançar itens da compra e ver os totais',
    rota: '/compras',
    perguntas: [
      'lancar item na compra',
      'adicionar item na compra',
      'descricao unidade quantidade valor unitario da compra',
      'editar item da compra',
      'remover item da compra',
      'total bruto da compra',
      'total liquido da compra',
      'como o desconto e o frete entram no total da compra',
    ],
    resposta:
      'No card **Lançar Item**, cada item da compra tem descrição livre, unidade (com sugestões das unidades cadastradas), quantidade e valor unitário — clicar em **Adicionar** já lança o item e limpa o formulário pra continuar digitando o próximo. Na tabela **Itens da Compra**, cada campo é editável direto na linha (salva ao sair do campo), e o ícone de lixeira remove o item.\n\nO card **Totais** mostra Total Bruto (soma dos itens), Desconto, Frete e Total Líquido — os dois últimos vêm dos campos de desconto e frete lançados no card Dados da Compra, não item a item.',
    relacionados: ['compras-criar-fornecedor-cabecalho'],
  },
  {
    id: 'compras-relatorio',
    modulo: 'compras',
    tela: 'Relatório de Compras',
    titulo: 'Relatório de Compras por período, categoria e fornecedor',
    rota: '/compras/relatorio',
    perguntas: [
      'relatorio de compras',
      'quanto gastei em compras',
      'total gasto no periodo de compras',
      'ticket medio de compras',
      'compras por categoria',
      'compras por fornecedor',
      'imprimir relatorio de compras',
      'quanto gastei em compra esse mes',
    ],
    resposta:
      'A tela **Relatório de Compras** soma as compras lançadas num período, com filtro opcional por categoria e por fornecedor. Mostra o Total Gasto no Período, a Quantidade de Compras e o Ticket Médio, além de duas quebras: **Por Categoria** e **Por Fornecedor** (quantidade e total de cada uma), e a lista completa das compras do período. O botão **Imprimir** gera uma versão só do relatório, sem os filtros.',
    relacionados: ['compras-listar-filtrar'],
  },
  {
    id: 'fornecedores-listar-buscar',
    modulo: 'compras',
    tela: 'Fornecedores',
    titulo: 'Ver e buscar fornecedores cadastrados',
    rota: '/fornecedores',
    perguntas: [
      'onde vejo os fornecedores',
      'lista de fornecedores',
      'buscar fornecedor por nome',
      'buscar fornecedor por cnpj',
      'buscar fornecedor por telefone',
      'fornecedor ativo ou inativo',
      'novo fornecedor',
      'malharia que vendeu pra mim cadastro onde',
    ],
    resposta:
      'A tela **Fornecedores** lista o cadastro usado nos lançamentos de compra: nome, CPF/CNPJ, telefone, categoria principal e se está ativo. Dá pra buscar por nome, CPF/CNPJ ou telefone. Clicar numa linha (ou no botão **Novo fornecedor**) abre a ficha completa do fornecedor.',
    relacionados: ['fornecedores-cadastro-completo', 'compras-criar-fornecedor-cabecalho'],
  },
  {
    id: 'fornecedores-cadastro-completo',
    modulo: 'compras',
    tela: 'Ficha de Fornecedor',
    titulo: 'Cadastro completo de fornecedor (identificação, endereço, dados comerciais)',
    rota: '/fornecedores/novo',
    perguntas: [
      'cadastrar fornecedor completo',
      'editar dados do fornecedor',
      'pessoa fisica ou juridica no fornecedor',
      'inscricao estadual isenta',
      'buscar cep do fornecedor',
      'condicao de pagamento padrao do fornecedor',
      'chave pix do fornecedor',
      'dados bancarios do fornecedor',
      'desativar fornecedor',
      'remover fornecedor',
    ],
    resposta:
      'A ficha de fornecedor tem quatro blocos: **Identificação** (Pessoa Jurídica ou Física, razão social/nome, nome fantasia, CNPJ/CPF, Inscrição Estadual — com checkbox "Isento"), **Contato** (telefone/WhatsApp, e-mail), **Endereço** (com botão pra buscar o endereço automaticamente a partir do CEP, preenchendo logradouro/bairro/cidade/UF — se o CEP não for encontrado ou a consulta falhar, é só preencher manualmente) e **Comercial** (categoria principal, condição de pagamento padrão, chave PIX, dados bancários, observações, e o alternador **Ativo?**).\n\nO botão **Salvar** grava o cadastro (obrigatório preencher o nome). Em fornecedor já existente, o botão **Remover** apaga o cadastro. Desativar (alternador "Ativo?" para "Não") mantém o cadastro salvo sem excluir — útil pra fornecedor que parou de ser usado sem perder o histórico das compras já lançadas com ele.',
    relacionados: ['fornecedores-listar-buscar'],
  },
];
