// Verbetes do módulo Configurações — Parâmetros (/configuracoes,
// ConfiguracoesPage.jsx), Empresas (/empresas, EmpresasPage.jsx), Custos
// Indiretos (/custos-indiretos, CustosIndiretosPage.jsx), Taxas (/taxas,
// TaxasPage.jsx com sub-abas Venda/Marketplace — TaxasVendaPage.jsx e
// MarketplaceTaxasPage.jsx), Listas (/listas, ListasPage.jsx), Produtos de
// Marketplace (/configuracoes/marketplace, ProdutosMarketplacePage.jsx),
// Acessos (/acessos, AcessosPage.jsx com sub-abas Usuários/Grupos —
// UsuariosPage.jsx e GruposPage.jsx), Integrações (/integracoes,
// IntegracoesPage.jsx com sub-abas por marketplace + Wik Sistemas —
// WikIntegracaoCard.jsx, WikImportarProdutosCard.jsx,
// WikImportarFichaCustoCard.jsx, WikFichaCustoDiagnosticoCard.jsx) e Saúde
// dos Dados (/saude-dados, SaudeDadosPage.jsx com QualidadeDadosPage.jsx e
// ConferenciaDadosPage.jsx). Nenhum verbete de Parâmetros, Empresas ou Taxas
// sugere um valor "certo" pra digitar num campo — só descreve o que cada
// campo faz e onde ele é usado (Regra 1).

export const verbetesConfiguracoes = [
  {
    id: 'config-parametros-faixas-margem',
    modulo: 'configuracoes',
    tela: 'Parâmetros',
    titulo: 'Faixas de margem (régua de Mínima a Premium) e o teto de preço',
    rota: '/configuracoes',
    perguntas: [
      'onde configuro a margem minima',
      'faixas de margem',
      'regua de margens',
      'margem ideal margem premium',
      'preco maximo recomendado teto',
      'exemplo ao vivo do preco',
      'onde essas faixas de margem sao usadas',
      'ordem das faixas nao fecha',
    ],
    resposta:
      'Em **Parâmetros**, o card **Faixas de margem** tem uma régua visual com cinco pontos editáveis, na ordem: Mínima, Atenção, Ideal, Saudável até e Premium (cada faixa precisa ficar maior ou igual à anterior — o sistema avisa se a ordem não fechar). Essas faixas são usadas na Ficha de Precificação, na Central de Alertas e na Lucratividade.\n\nO campo **Preço máximo recomendado (teto)** fica fora da régua — é um multiplicador sobre o preço premium, não uma margem. Um bloco **"Com estes valores, uma peça de custo X sai a:"** mostra ao vivo o preço mínimo, sugerido, premium e teto que resultariam dos valores atuais da régua, sem precisar salvar antes de ver o efeito.',
    relacionados: ['config-parametros-alertas', 'analises-ficha-precificacao'],
  },
  {
    id: 'config-parametros-alertas',
    modulo: 'configuracoes',
    tela: 'Parâmetros',
    titulo: '"Quando o sistema deve reclamar" — limites da Central de Alertas',
    rota: '/configuracoes',
    perguntas: [
      'quando o sistema deve reclamar',
      'limite de materiais acima de',
      'limite de mao de obra',
      'limite de impostos no parametros',
      'limite de frete',
      'limite de custo indireto',
      'lucro minimo por peca',
      'onde configuro os limites dos alertas',
    ],
    resposta:
      'O card **Quando o sistema deve reclamar**, em Parâmetros, tem os limites que alimentam a Central de Alertas e os avisos na Ficha do Produto: % de materiais acima do custo, % de mão de obra acima do custo, % de impostos acima do preço, % de frete acima do industrial, % de custo indireto acima do custo, e o lucro mínimo por peça (abaixo disso a peça entra na Central de Alertas).',
    relacionados: ['config-parametros-faixas-margem', 'analises-alertas'],
  },
  {
    id: 'config-parametros-kits-marketplace-calendario',
    modulo: 'configuracoes',
    tela: 'Parâmetros',
    titulo: 'Parâmetros de Kits, Marketplace e alertas do Calendário',
    rota: '/configuracoes',
    perguntas: [
      'desconto do kit vs avulso',
      'margem alvo do kit',
      'custo de embalagem do marketplace',
      'pilula vermelha e amarela da margem',
      'quando o evento do calendario vira urgente',
      'primeiro aviso do calendario',
    ],
    resposta:
      'Três cards menores em Parâmetros: **Kits** (desconto do kit frente às peças avulsas, e a margem alvo usada só na formação de preço de kits), **Marketplace** (custo fixo de embalagem por pedido, somado na lucratividade de marketplace, e os dois limites de margem que decidem se a "pílula" de margem de um pedido aparece vermelha, amarela ou verde) e **Alertas do calendário** (a partir de quantos dias antes do prazo um evento aparece no sino de notificações, e a partir de quantos dias ele vira urgente).',
    relacionados: ['config-parametros-faixas-margem'],
  },
  {
    id: 'config-empresas',
    modulo: 'configuracoes',
    tela: 'Empresas',
    titulo: 'Empresas / Pessoas Jurídicas — regime tributário e alíquotas',
    rota: '/empresas',
    perguntas: [
      'cadastrar empresa',
      'regime tributario da empresa',
      'aliquota media provisoria',
      'aliquota efetiva do simples nacional',
      'icms pis cofins ipi iss',
      'outros impostos da empresa',
      'percentual total de impostos sobre o preco',
      'remover empresa',
      'cada produto tem uma empresa',
      'onde cadastro o cnpj da empresa',
      'cnpj da pessoa juridica',
    ],
    resposta:
      'A tela **Empresas** cadastra cada Pessoa Jurídica da operação, com seu próprio regime tributário e alíquotas — cada produto é associado a uma delas pra saber qual conjunto de impostos usar na formação de preço.\n\nO alternador **"Usar alíquota média provisória?"** troca todo o detalhamento fiscal por uma % única, usada em todos os cálculos (Ficha de Custo, preço e lucratividade) — útil enquanto os dados fiscais detalhados ainda não estão prontos. Sem isso ativado, o regime **Simples Nacional** pede a alíquota efetiva (conforme Fator R e anexo da empresa, não a nominal da tabela), e os demais regimes pedem ICMS, PIS, COFINS, IPI e ISS separados, mais "Outros impostos/taxas fiscais". Um totalizador mostra o % total de impostos sobre o preço de venda resultante. Uma empresa só pode ser removida se não tiver produtos vinculados a ela.',
    relacionados: ['gloss-regime-tributario'],
  },
  {
    id: 'config-custos-indiretos',
    modulo: 'configuracoes',
    tela: 'Custos Indiretos',
    titulo: 'Custos Indiretos — rateio do custo fixo por peça',
    rota: '/custos-indiretos',
    perguntas: [
      'custos indiretos',
      'rateio do custo fixo',
      'producao mensal para o rateio',
      'custo indireto por peca',
      'grupos de custos indiretos instalacoes tecnologia',
      'adicionar novo custo indireto',
      'total fixo do mes',
    ],
    resposta:
      'A tela **Custos Indiretos** lista o custo fixo que não é de nenhuma peça em particular (aluguel, energia, sistema, contabilidade, etc.), rateado por toda a produção do mês. No topo, um simulador mostra a conta ao vivo: Total fixo do mês ÷ Produção do mês (editável, muda o rateio na hora) = Custo indireto por peça, que entra no custo de toda peça cadastrada.\n\nOs itens aparecem agrupados automaticamente por natureza (Instalações, Tecnologia, Administrativo, Logística, Outros) com base em palavras do próprio nome do item — é só uma organização da tela, não fica gravada em lugar nenhum. Cada grupo mostra o subtotal e o % do total; grupos pequenos começam recolhidos. **Novo custo** adiciona um item ao final.',
    relacionados: ['gloss-custo-indireto', 'gloss-rateio'],
  },
  {
    id: 'config-taxas-venda',
    modulo: 'configuracoes',
    tela: 'Taxas — Venda',
    titulo: 'Taxas de Venda — comissões e taxas descontadas do preço',
    rota: '/taxas',
    perguntas: [
      'taxas de venda',
      'cadastrar taxa de canal de venda',
      'taxa percentual ou taxa fixa',
      'simulador de taxas de venda',
      'quanto eu recebo depois das taxas',
      'desativar taxa de venda',
      'taxas inativas nao contam',
      'taxa desativada ainda entra no calculo',
    ],
    resposta:
      'A sub-aba **Venda** de Taxas lista tudo que é descontado do preço antes do dinheiro chegar (comissão de canal, taxa de cartão, etc.). Cada taxa pode ser cobrada como **%** (percentual do valor), **R$** (valor fixo por venda) ou **% + R$** (os dois juntos) — o campo que não se aplica ao tipo escolhido fica tracejado e não conta na conta.\n\nUm simulador no topo mostra, pra um valor de venda digitado, quanto as taxas ativas tirariam e quanto sobraria. A tabela separa taxas ativas das desativadas (que ficam ocultas por padrão, atrás de "Mostrar taxas desativadas") — taxa desativada não entra em nenhum cálculo. No rodapé, um totalizador mostra o efeito conjunto de todas as taxas ativas sobre uma venda de referência de R$ 100.',
    relacionados: ['config-taxas-marketplace', 'gloss-taxa-venda'],
  },
  {
    id: 'config-taxas-marketplace',
    modulo: 'configuracoes',
    tela: 'Taxas — Marketplace',
    titulo: 'Taxas de Marketplace — tabelas de comissão e frete do Mercado Livre e Shopee',
    rota: '/taxas',
    perguntas: [
      'taxas de marketplace configuracao',
      'tabela de comissao do mercado livre',
      'tabela de comissao da shopee',
      'faixa de frete subsidiado',
      'grade de frete por peso e valor',
      'simulador de comissao e frete',
      'tipo de anuncio classico ou premium',
      'subsidio pix shopee',
      'atualizar tabela quando o marketplace reajustar',
      'quanto a shopee cobra de comissao por venda',
      'quanto o mercado livre cobra de comissao',
    ],
    resposta:
      'A sub-aba **Marketplace** de Taxas guarda as tabelas de comissão e frete que o Mercado Livre e a Shopee cobram dos vendedores — usadas na tela Taxas Cobradas (dentro do módulo Marketplace) pra conferir se a cobrança real bateu com o esperado. É preciso reajustar aqui à mão sempre que o marketplace anuncia mudança nas taxas.\n\nA tabela **Comissão** tem faixas por valor do anúncio (e, no Mercado Livre, por tipo de anúncio — Clássico ou Premium), com comissão %, comissão fixa em R$ e, na Shopee, subsídio Pix. A tabela **Frete Subsidiado** é uma grade cruzando faixa de peso × faixa de valor do pedido, com o custo de frete de cada cruzamento — só entra na conta se o produto tiver peso cadastrado e a loja usar frete subsidiado (configurável em Integrações). Um simulador no topo (valor do anúncio, peso, tipo de anúncio) destaca ao vivo qual faixa de comissão e qual célula da grade de frete se aplicam.',
    relacionados: ['config-taxas-venda', 'mkt-taxas-cobradas'],
  },
  {
    id: 'config-listas',
    modulo: 'configuracoes',
    tela: 'Listas',
    titulo: 'Listas — valores usados nos menus suspensos do sistema',
    rota: '/listas',
    perguntas: [
      'onde edito as listas suspensas',
      'adicionar categoria nova',
      'adicionar marca nova',
      'adicionar colecao nova',
      'reordenar itens da lista',
      'desativar valor de lista',
      'por que nao apaga o valor da lista',
      'quantas listas existem no sistema',
    ],
    resposta:
      'A tela **Listas** edita os valores usados nos menus suspensos em todo o sistema: Categorias, Marcas, Coleções, Linhas, Materiais, Unidades, Tipos de Custo Industrial, Operações (Vendas), Canais de Venda, Formas de Pagamento, Condições de Pagamento, Vendedores e Categorias de Compra — um índice à esquerda mostra a contagem de cada lista e leva pra ela.\n\nDentro de uma lista, cada valor pode ser renomeado, reordenado (setas pra cima/baixo — a ordem escolhida aqui é a ordem no menu suspenso) e desativado. Como o sistema não consegue contar automaticamente quantos registros usam cada valor, remover sempre **desativa** em vez de apagar: nada se perde, e produtos/pedidos que já usam aquele valor continuam funcionando normalmente — dá pra reativar depois.',
    relacionados: [],
  },
  {
    id: 'config-marketplace-selecao-produtos',
    modulo: 'configuracoes',
    tela: 'Produtos de Marketplace',
    titulo: 'Selecionar quais referências são "de marketplace"',
    rota: '/configuracoes/marketplace',
    perguntas: [
      'produtos de marketplace configuracao',
      'quais produtos estao no marketplace',
      'adicionar referencia a selecao de marketplace',
      'colar lista de referencias do marketplace',
      'gerar fichas de estoque do marketplace em lote',
      'tirar produto da selecao de marketplace',
      'referencia ambigua na colagem',
    ],
    resposta:
      'A tela **Produtos de Marketplace** (em Configurações) administra a lista de referências marcadas como anunciadas nos marketplaces — usada pra filtrar as telas de Produtos e Estoque, e pra puxar de uma vez só todas as fichas de estoque dessas referências, prontas pra imprimir (botão **Gerar fichas de estoque**).\n\nDá pra adicionar uma referência por vez (buscando por referência, código ou descrição — só aparece quem ainda não está na seleção), ou várias de uma vez colando a coluna de referências de uma planilha: o sistema confere antes de gravar, mostrando o que vai ser adicionado, o que já estava na seleção, o que não foi encontrado no cadastro e o que ficou ambíguo (mais de um produto batendo com a mesma referência colada) — nada é adivinhado por descrição. O ícone de X na lista da seleção tira a referência dela.',
    relacionados: [],
  },
  {
    id: 'config-acessos-usuarios',
    modulo: 'configuracoes',
    tela: 'Acessos — Usuários',
    titulo: 'Usuários — perfis, módulos liberados e grupos',
    rota: '/acessos',
    perguntas: [
      'cadastrar usuario novo',
      'perfil administrador ou limitado',
      'quais modulos um usuario pode ver',
      'resetar senha de usuario',
      'desativar usuario',
      'vincular usuario a um grupo',
      'excluir usuario',
      'so admin ve a aba usuarios',
    ],
    resposta:
      'A sub-aba **Usuários** (dentro de Acessos, só visível pra quem é administrador) cadastra quem tem acesso ao sistema e o que cada um pode ver. O perfil **Administrador** tem acesso irrestrito a todos os módulos; o perfil **Limitado** só enxerga os módulos marcados manualmente (Produto, Estoque, Vendas, Marketplace, Viagens, Compras, Análises, Configurações). Dá pra buscar por nome/e-mail e filtrar por perfil, ativo/inativo e grupo.\n\nCada usuário pode ser vinculado a um ou mais grupos (cadastrados na sub-aba Grupos) direto no card dele. O botão **Resetar senha** define uma nova senha (mínimo 10 caracteres) sem precisar da senha antiga e **desconecta essa pessoa de todos os aparelhos**. O alternador **Ativo?** desliga o acesso sem apagar o cadastro (não é possível desativar ou excluir o próprio usuário logado). **Excluir** apaga o usuário definitivamente.',
    relacionados: ['config-acessos-grupos'],
  },
  {
    id: 'config-acessos-grupos',
    modulo: 'configuracoes',
    tela: 'Acessos — Grupos',
    titulo: 'Grupos de usuários (usados no Calendário)',
    rota: '/acessos',
    perguntas: [
      'cadastrar grupo de usuarios',
      'para que serve grupo de usuarios',
      'membros do grupo',
      'desativar grupo',
      'excluir grupo',
      'grupo no calendario',
      'quem pode gerenciar grupos sem ser admin',
    ],
    resposta:
      'A sub-aba **Grupos** cadastra grupos de usuários usados pra liberar visibilidade/edição de eventos do Calendário pra várias pessoas de uma vez, em vez de pessoa por pessoa — diferente da sub-aba Usuários, **não precisa ser administrador** pra gerenciar Grupos (quem não é admin, ao abrir Acessos, já cai direto aqui, sem ver a sub-aba Usuários).\n\n**Novo grupo** pede um nome e a marcação dos membros (usuários existentes) numa lista de checkboxes. Cada grupo já cadastrado pode ser editado, ativado/desativado (o alternador ao lado do nome) ou excluído — excluir um grupo faz os eventos que liberavam visibilidade pra ele deixarem de liberar.',
    relacionados: ['config-acessos-usuarios'],
  },
  {
    id: 'config-integracoes-marketplaces',
    modulo: 'configuracoes',
    tela: 'Integrações',
    titulo: 'Conectar e configurar uma loja de marketplace (Mercado Livre, Shopee, TikTok Shop)',
    rota: '/integracoes',
    perguntas: [
      'conectar mercado livre',
      'conectar shopee',
      'conectar tiktok shop',
      'client id client secret',
      'sincronizar pedidos agora',
      'copiar credenciais de outra loja',
      'frete subsidiado da loja',
      'empresa base de imposto da integracao',
      'percentual de nota fiscal da loja',
      'erro na ultima sincronizacao da loja',
      'desativar uma loja conectada',
      'remover conexao de loja',
      'mercado livre parou de puxar pedido novo',
      'integracao nao esta trazendo pedido da loja',
    ],
    resposta:
      'A tela **Integrações** conecta o Mercado Livre, a Shopee e a TikTok Shop pra puxar os pedidos pagos automaticamente pra dentro do sistema a cada 5 minutos, como pedidos de venda em aberto. Cada plataforma tem sua sub-aba, com uma tabela das lojas já conectadas (nome editável, conta externa, status Conectado/Não autorizado, ativa?, última sincronização) e o botão **Conectar loja** pra cadastrar uma nova, pedindo as credenciais do app da plataforma (Client ID/Secret no Mercado Livre, Partner ID/Key na Shopee, App Key/Secret + Service ID na TikTok Shop) — ou, se já existe outra loja da mesma plataforma, dá pra reaproveitar as credenciais dela em vez de digitar de novo.\n\nCada loja tem um botão **Conectar** (login/autorização OAuth) ou **Sincronizar agora** (força a busca de pedidos na hora, sem esperar o próximo ciclo). O botão **Mais** expande campos extras por loja: se usa frete subsidiado, a empresa (CNPJ) usada como base de imposto e o % do valor vendido que sai na nota fiscal — além de mostrar o erro da última tentativa, se houver (incluindo erro específico de faturamento/repasse ou, no Mercado Livre, de publicidade).',
    relacionados: ['config-integracoes-wik-estoque', 'mkt-importar-pedidos'],
  },
  {
    id: 'config-integracoes-wik-estoque',
    modulo: 'configuracoes',
    tela: 'Integrações — Wik Sistemas',
    titulo: 'Wik Sistemas (ERP) — sincronização de saldo de estoque',
    rota: '/integracoes',
    perguntas: [
      'integracao com o wik',
      'sincronizar estoque do wik',
      'credencial do wik email senha',
      'testar conexao com o wik',
      'testar conexao completa do wik',
      'token rejeitado pelo wik',
      'id da empresa por marca no wik',
      'so conferir sem aplicar wik',
      'sincronizar agora wik estoque',
      'atualizar estoque do wik agora mesmo',
    ],
    resposta:
      'Na sub-aba **Wik Sistemas (ERP)** de Integrações, o card de sincronização de estoque puxa o saldo direto da API do Wik pras referências já cadastradas, atualizando sozinho a cada 15 minutos. Pede email e senha de login do Wik; os botões **Testar conexão** (só confirma o login) e **Testar conexão completa** (login + uma chamada de saldo de estoque + uma de tamanhos, mostrando status HTTP e corpo bruto de cada uma — útil pra diagnóstico) não mexem em nenhum dado.\n\nO card mostra o status do token (válido, rejeitado, erro, ainda não testado) e a data da última sincronização — token **rejeitado** exige abrir chamado no suporte do Wik, o sistema já para de tentar sozinho pra não piorar o bloqueio. Uma tabela liga cada marca ao Id da empresa correspondente no Wik (a Wik cadastra em 4 empresas: matriz, filial, Hoggar/Miss Manu e Origem). **Sincronizar agora** aplica direto; **Só conferir (sem aplicar)** mostra uma prévia (variantes novas, variantes com saldo mudando, linhas com erro) antes de confirmar — como o Wik libera só 3 requisições por segundo, a busca pode levar minutos.',
    relacionados: ['config-integracoes-wik-produtos-ficha', 'config-integracoes-marketplaces'],
  },
  {
    id: 'config-integracoes-wik-produtos-ficha',
    modulo: 'configuracoes',
    tela: 'Integrações — Wik Sistemas',
    titulo: 'Wik Sistemas — importar catálogo de produtos e Ficha de Custo',
    rota: '/integracoes',
    perguntas: [
      'importar produtos do wik',
      'importar ficha de custo do wik',
      'catalogo completo de produtos do wik',
      'custo total aprovado no wik',
      'produto sem marca ou categoria na importacao do wik',
      'ficha editada manualmente protegida do wik',
      'diagnostico da ficha de custo do wik',
      'materiais sem custo individual no wik',
    ],
    resposta:
      'Dois outros cards da sub-aba Wik Sistemas: **Importar catálogo completo de produtos** traz todos os produtos ativos do Wik (marca, categoria e estoque de cada variante, usando o maior saldo quando o mesmo produto aparece em mais de uma loja), criando só os que ainda não existem aqui — roda sozinho a cada 6 horas, com botões pra atualizar na hora ou só conferir antes.\n\n**Importar Ficha de Custo do Wik** traz o custo total já calculado e aprovado no Wik pra produto sem ficha, e atualiza produto que já veio de lá antes — nunca mexe em ficha editada manualmente aqui (fica "protegida"). Os materiais entram só como referência (nome e quantidade), sem custo individual, porque o Wik não expõe isso separado do total. Também roda sozinha a cada 6 horas.\n\nUm terceiro card, **Testar Ficha de Custo (Audaces) — em investigação**, é uma ferramenta de diagnóstico técnico: digitando a referência de um produto já importado, mostra a resposta crua da API do Wik pra ajudar a entender como ela liga a ficha técnica ao produto — não é uma tela de uso rotineiro.',
    relacionados: ['config-integracoes-wik-estoque'],
  },
  {
    id: 'config-saude-dados-qualidade',
    modulo: 'configuracoes',
    tela: 'Saúde dos Dados — Qualidade do Dado',
    titulo: 'Qualidade do Dado — o que está incompleto nos cadastros',
    rota: '/saude-dados',
    perguntas: [
      'qualidade do dado',
      'material cadastrado sem valor',
      'preco sugerido zero',
      'produto sem empresa associada',
      'empresa sem imposto configurado',
      'pedidos de marketplace estimados nao liberados',
      'itens de marketplace sem produto vinculado',
      'variantes de estoque zeradas'
    ],
    resposta:
      'A seção **Qualidade do Dado** (dentro de Saúde dos Dados) é um raio-x do que está incompleto antes de confiar em qualquer painel agregado (Dashboard Executivo, Indicadores de Estoque, Central de Alertas) — não corrige nem apaga nada sozinha.\n\nCobre três blocos: **A — Referências/produtos** (total de referências, com custo de material > 0, material cadastrado sem valor, preço sugerido zerado, sem empresa/categoria/marca associada, e empresas sem nenhum imposto configurado — cada lista leva direto pra ficha do registro); **B — Pedidos de marketplace** (confirmados vs. estimados/ainda não liberados pela plataforma, e itens sem produto vinculado); **C — Estoque** (variantes ativas, com EAN, com saldo, zeradas).',
    relacionados: ['config-saude-dados-conferencia', 'analises-alertas'],
  },
  {
    id: 'config-saude-dados-conferencia',
    modulo: 'configuracoes',
    tela: 'Saúde dos Dados — Conferência de Dados',
    titulo: 'Conferência de dados de teste — registros com "cara de teste"',
    rota: '/saude-dados',
    perguntas: [
      'conferencia de dados de teste',
      'registro com cara de dado de teste',
      'nome sem vogais suspeito',
      'excluir cliente de teste',
      'excluir fornecedor de teste',
      'apagar dado de teste em massa',
    ],
    resposta:
      'A seção **Conferência de dados de teste** (dentro de Saúde dos Dados) lista clientes, fornecedores, viagens e pedidos com "cara" de dado de teste — nome sem vogais ou curto demais, quantidade ou valor muito fora do normal — cada um com o motivo da suspeita marcado. É só um raio-x: nenhum item é apagado ou alterado por aqui, e a tela **não tem** (e não vai ter) um botão de "apagar todos" — clicar num item abre a ficha dele pra decidir com calma se apaga, corrige ou ignora, já que excluir um registro é definitivo.',
    relacionados: ['config-saude-dados-qualidade'],
  },
];
