// Verbetes do módulo Estoque — controle por variante (referência + cor +
// tamanho), com EAN próprio (/estoque), bipagem (/estoque/bipagem),
// importação de saldo (/estoque/importacao), importação de EAN
// (/estoque/ean) e ficha de estoque pra impressão (/estoque/ficha). Cada
// tela foi lida até o fim antes de escrever o verbete.

export const verbetesEstoque = [
  {
    id: 'estoque-ver-variantes-referencia',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ver as variantes (cor/tamanho) de uma referência',
    rota: '/estoque',
    perguntas: [
      'como vejo o estoque de um produto',
      'quantidade em estoque da referencia',
      'ver variantes de uma referencia',
      'estoque por cor e tamanho',
      'selecionar referencia no estoque',
      'onde vejo a grade de estoque',
      'quantidade atual da variante',
      'estoque de uma referencia especifica',
      'tabela de variantes do estoque',
      'nao acho o estoque de um produto',
      'saldo zerado de uma referencia onde vejo',
    ],
    resposta:
      'Na tela **Estoque**, escolha a referência no campo de seleção — abre uma tabela com cada variante dela (cor, tamanho), o EAN, a quantidade atual e um toggle de "ativa". É essa tabela que mostra a grade completa daquela referência, variante por variante.\n\nCada linha também tem controles pra editar o EAN, mover estoque (entrada/saída) e excluir a variante direto ali, sem precisar abrir outra tela (ver os verbetes específicos de cada ação).',
    relacionados: ['estoque-movimentar-entrada-saida', 'estoque-adicionar-variante', 'gloss-grade'],
  },
  {
    id: 'estoque-buscar-em-todo-estoque',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Buscar uma variante em todo o estoque (por referência, descrição ou EAN)',
    rota: '/estoque',
    perguntas: [
      'como busco pelo ean no estoque',
      'buscar variante por ean',
      'achar produto pelo codigo de barras',
      'buscar em todo o estoque',
      'busca geral do estoque',
      'encontrar variante sem saber a referencia',
      'pesquisar estoque por descricao',
      'onde bipa pra buscar em vez de ler',
    ],
    resposta:
      'Além de selecionar uma referência específica, a tela Estoque tem um campo de **busca geral**, que procura por referência, descrição ou **EAN** em todas as variantes do sistema de uma vez — útil quando você tem só o código de barras em mãos e não sabe de qual produto ele é.\n\nO resultado aparece numa tabela com referência, descrição, cor, tamanho, EAN (editável ali mesmo, clicando no lápis) e quantidade — sem precisar selecionar a referência primeiro.',
    relacionados: ['estoque-ver-variantes-referencia', 'gloss-ean'],
  },
  {
    id: 'estoque-adicionar-variante',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Adicionar uma variante nova (cor/tamanho) a uma referência',
    rota: '/estoque',
    perguntas: [
      'como adiciono uma variante',
      'criar cor e tamanho novo no estoque',
      'adicionar variante a referencia',
      'nova cor no produto',
      'novo tamanho na grade',
      'cadastrar variante de estoque',
      'quantidade inicial da variante',
      'aumentar a grade de uma referencia',
    ],
    resposta:
      'Depois de selecionar uma referência na tela Estoque, no fim da tabela de variantes tem o formulário **Adicionar variante**: preencha Cor, Tamanho e a quantidade inicial, e clique em adicionar. A variante nova entra na grade daquela referência, junto das demais.\n\nO EAN da variante nova pode ser gerado depois (ou preenchido na hora, editando o campo EAN na tabela) — e se um EAN pra essa combinação de cor/tamanho já tinha sido importado antes (ver o verbete de importar EAN), ele é aplicado automaticamente nessa variante recém-criada.',
    relacionados: ['estoque-ver-variantes-referencia', 'estoque-importar-ean'],
  },
  {
    id: 'estoque-movimentar-entrada-saida',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Registrar entrada ou saída de estoque de uma variante',
    rota: '/estoque',
    perguntas: [
      'como registro entrada de estoque',
      'como registro saida de estoque',
      'ajustar quantidade da variante',
      'dar entrada manual no estoque',
      'dar baixa no estoque manual',
      'motivo do movimento de estoque',
      'corrigir quantidade de uma variante',
      'aumentar estoque de uma cor e tamanho',
      'diminuir estoque manualmente',
    ],
    resposta:
      'Em cada linha da tabela de variantes, na coluna **Movimentar**, digite a quantidade, opcionalmente um motivo, e clique na seta pra cima (entrada) ou pra baixo (saída) — o ajuste é aplicado na hora, direto naquela variante.\n\nToda movimentação feita por aqui (assim como pela bipagem, importação de saldo etc.) fica registrada no histórico de movimentos da variante, com o tipo, a quantidade e a quantidade resultante — é o que permite auditar depois de onde veio cada mudança de estoque.',
    relacionados: ['estoque-bipagem', 'estoque-ver-variantes-referencia'],
  },
  {
    id: 'estoque-ativar-desativar-excluir-variante',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ativar, desativar ou excluir uma variante',
    rota: '/estoque',
    perguntas: [
      'como desativo uma variante',
      'variante inativa o que significa',
      'ativar variante de novo',
      'como excluo uma variante',
      'remover cor e tamanho do estoque',
      'nao consigo excluir variante',
      'variante ja vendida nao exclui',
      'apagar variante de estoque',
      'desativar cor descontinuada',
    ],
    resposta:
      'Cada variante tem um toggle **Ativa?** — desativar não apaga nada, só marca a variante como fora de uso (por exemplo, uma cor descontinuada); ela some das opções normalmente oferecidas mas o histórico continua existindo. A linha de uma variante inativa fica esmaecida na tabela.\n\nPra excluir de verdade, use o ícone de lixeira na linha — mas o sistema **não deixa excluir uma variante que já teve venda registrada** (ela fica bloqueada, com o histórico de movimentos junto). Se ela nunca foi vendida, a exclusão pede confirmação e também apaga o histórico de movimentos daquela variante.',
    relacionados: ['estoque-selecao-em-massa'],
  },
  {
    id: 'estoque-selecao-em-massa',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ativar, desativar ou excluir várias variantes de uma vez',
    rota: '/estoque',
    perguntas: [
      'ativar varias variantes de uma vez',
      'desativar em lote no estoque',
      'excluir varias variantes juntas',
      'selecionar todas as variantes da referencia',
      'marcar varias linhas no estoque',
      'acao em massa no estoque',
      'checkbox selecionar tudo estoque',
    ],
    resposta:
      'Na tabela de variantes de uma referência, marque as caixinhas das linhas desejadas (ou a do cabeçalho, pra selecionar todas as variantes daquela referência de uma vez) — aparece uma barra com **Ativar selecionadas**, **Desativar selecionadas** e **Excluir selecionadas**.\n\nA exclusão em lote segue a mesma regra da individual: variantes que já tiveram venda registrada não são excluídas, e o sistema avisa quantas foram excluídas e quais ficaram bloqueadas (com cor e tamanho de cada uma).',
    relacionados: ['estoque-ativar-desativar-excluir-variante'],
  },
  {
    id: 'estoque-corrigir-cor-tamanho-em-massa',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Corrigir um valor de cor ou tamanho em várias referências de uma vez',
    rota: '/estoque',
    perguntas: [
      'digitei a cor errada em varias referencias',
      'corrigir cor em massa',
      'corrigir tamanho em massa',
      'trocar azl por azul em tudo',
      'padronizar nome de cor',
      'ferramenta corrigir cor tamanho',
      'renomear cor em varias referencias de uma vez',
      'erro de digitacao na cor repetido',
    ],
    resposta:
      'O card **Corrigir cor/tamanho em massa**, no topo da tela Estoque, resolve o caso de um valor digitado errado (ex.: "Azl" em vez de "Azul") que se repetiu em várias referências diferentes — em vez de corrigir uma por uma.\n\nEscolha o campo (Cor ou Tamanho), digite o valor atual exato e clique em **Buscar** — aparece a lista de todas as variantes com esse valor, em qualquer referência. Digite o valor novo e clique em **Aplicar** pra corrigir todas de uma vez. Se alguma correção esbarrar numa variante que já existe com o valor novo na mesma referência, ela fica de fora e aparece listada como conflito, sem travar as demais.',
    relacionados: ['estoque-ver-variantes-referencia'],
  },
  {
    id: 'estoque-filtro-marketplace',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ver só as referências de marketplace no Estoque',
    rota: '/estoque',
    perguntas: [
      'filtrar estoque so marketplace',
      'ver so produtos de marketplace no estoque',
      'toggle marketplace no estoque',
      'estoque so das referencias do marketplace',
      'quantas referencias de marketplace tenho',
    ],
    resposta:
      'O toggle **Somente produtos do marketplace**, na tela Estoque, restringe tanto o seletor de referência quanto a busca geral às referências marcadas como "produto de marketplace" (esse marcador é definido na ficha de cada produto, ou em Configurações › Produtos de Marketplace). Ligado, ele mostra também quantas referências entram nesse filtro.\n\nÉ o mesmo marcador usado nas Fichas de Estoque em lote e no filtro da lista de Produtos — mudar aqui ou lá reflete em todos os lugares, porque é o mesmo campo do produto.',
    relacionados: ['produto-marketplace-selecionar', 'estoque-ficha-marketplace-lote'],
  },
  {
    id: 'estoque-bipagem',
    modulo: 'estoque',
    tela: 'Bipagem',
    titulo: 'Usar a bipagem (leitor de código de barras)',
    rota: '/estoque/bipagem',
    perguntas: [
      'como uso a bipagem',
      'bipar produto',
      'leitor de codigo de barras',
      'dar entrada bipando',
      'dar saida bipando',
      'bipagem nao encontra o ean',
      'estoque ficou negativo na bipagem',
      'quantidade por leitura na bipagem',
      'ultimas leituras da bipagem',
      'bipagem entrada ou saida',
    ],
    resposta:
      'Na tela **Bipagem**, escolha primeiro se a leitura vai ser **Entrada** ou **Saída**, defina a quantidade por leitura (padrão 1) e aponte o leitor de código de barras pro campo de EAN — cada leitura já ajusta o estoque daquela variante na hora, sem precisar confirmar nada mais.\n\nO card **Últimas leituras** mostra um histórico das últimas 30 leituras da sessão, com hora, tipo, EAN e o resultado (referência, cor, tamanho e nova quantidade) — leituras com erro (EAN não encontrado, por exemplo) aparecem destacadas em vermelho. Se uma saída deixar a quantidade negativa, aparece um aviso "Estoque ficou negativo!" junto da leitura, mas ela não é bloqueada por isso.',
    relacionados: ['estoque-movimentar-entrada-saida'],
  },
  {
    id: 'estoque-importar-saldo',
    modulo: 'estoque',
    tela: 'Importar Saldo',
    titulo: 'Importar saldo de estoque em massa',
    rota: '/estoque/importacao',
    perguntas: [
      'como importo saldo de estoque',
      'importar estoque do wiki sistemas',
      'importar relatorio de saldo',
      'importar csv de estoque',
      'importar pdf de saldo de estoque',
      'atualizar quantidade em lote',
      'planilha relest',
      'saldo de estoque em grade pdf',
      'referencia precisa existir pra importar estoque',
    ],
    resposta:
      'A tela **Importar Saldo** aceita o relatório de saldo do Wiki Sistemas em dois formatos: o CSV "relEst" (uma linha por referência + cor + tamanho) ou o PDF "Relatório - Saldo de estoque" (em grade, cor por tamanho). A referência já precisa estar cadastrada em Produtos — a importação atualiza/cria variantes, não produtos.\n\nAssim como na importação de produtos, primeiro clique em **Pré-visualizar** — a tela mostra as variantes que serão criadas, as que serão atualizadas (com a quantidade atual ao lado da nova, em negrito quando muda) e as linhas com erro, que ficam de fora. Só depois de conferir, **Confirmar importação** grava de verdade.',
    relacionados: ['estoque-importar-ean', 'produto-importacao-massa'],
  },
  {
    id: 'estoque-importar-ean',
    modulo: 'estoque',
    tela: 'Importar EAN',
    titulo: 'Importar EAN do sistema real (Wiki Sistemas)',
    rota: '/estoque/ean',
    perguntas: [
      'como importo ean',
      'importar codigo de barras em massa',
      'importar rellistaprod',
      'ean do wiki sistemas',
      'importar varios csv de ean de uma vez',
      'ean fica guardado pra quando a variante existir',
      'atualizar ean de variantes existentes',
      'importacao de ean aplica na hora',
    ],
    resposta:
      'A tela **Importar EAN** aceita um ou mais arquivos "relListaProd" do Wiki Sistemas (colunas REF, COR, TAM, EAN EXTERNO) — dá pra selecionar vários .csv de uma vez. Na prévia, aparecem dois blocos: variantes que **já existem** (o EAN delas será atualizado na hora ao confirmar) e combinações que **ainda não têm variante** cadastrada (o EAN fica guardado e é aplicado sozinho assim que a variante for criada, manual ou por importação de saldo).\n\nEsse é o mecanismo que garante que a bipagem sempre lê o EAN verdadeiro da etiqueta, mesmo quando o EAN chega antes de a variante existir no sistema.',
    relacionados: ['gloss-ean', 'estoque-adicionar-variante'],
  },
  {
    id: 'estoque-ficha-gerar',
    modulo: 'estoque',
    tela: 'Ficha de Estoque',
    titulo: 'Gerar e imprimir fichas de conferência de estoque',
    rota: '/estoque/ficha',
    perguntas: [
      'como gero ficha de estoque',
      'imprimir ficha de conferencia de estoque',
      'ficha de estoque por cor e tamanho',
      'exportar ficha de estoque em pdf',
      'quantas referencias posso gerar de ficha de estoque',
      'ficha de estoque pra contagem',
      'selecionar referencias pra ficha de estoque',
    ],
    resposta:
      'Na tela **Ficha de Estoque**, busque por referência, código ou descrição e clique em **Adicionar** nos resultados pra ir montando a seleção (sem limite fixo de quantidade — só um aviso, a partir de 80 fichas, de que gerar e imprimir pode demorar mais). Clique em **Gerar fichas** pra montar o documento: uma folha por referência, com uma tabela cor × tamanho de cada variante e a quantidade, mais o total de peças, custo total e valor total.\n\nCom as fichas geradas, o botão **Imprimir / Exportar PDF** abre a impressão do navegador. Referências sem custo cadastrado entram como zero nos totais de custo/valor, em vez de travar a geração.',
    relacionados: ['estoque-ficha-marketplace-lote', 'produto-ficha-tecnica-gerar'],
  },
  {
    id: 'estoque-ficha-marketplace-lote',
    modulo: 'estoque',
    tela: 'Ficha de Estoque',
    titulo: 'Gerar fichas de estoque de todo o lote de marketplace de uma vez',
    rota: '/estoque/ficha',
    perguntas: [
      'gerar ficha de todo o marketplace',
      'carregar todas as referencias do marketplace',
      'ficha de estoque do marketplace inteiro',
      'botao fichas do marketplace',
      'imprimir estoque de todos os produtos de marketplace',
      'ficha de estoque em lote grande',
    ],
    resposta:
      'O botão **Carregar todos do Marketplace**, na tela Ficha de Estoque, seleciona de uma vez todas as referências marcadas como produto de marketplace, sem precisar buscar e adicionar uma por uma. É o mesmo destino do link **Fichas do marketplace**, que aparece na lista de Produtos.\n\nEssa seleção especial (identificada como "lote completo do marketplace") é pedida ao servidor numa chamada só, em vez de listar cada referência na URL — é por isso que ela funciona mesmo com centenas de referências marcadas, diferente de montar a seleção manualmente.',
    relacionados: ['estoque-ficha-gerar', 'estoque-filtro-marketplace'],
  },

  // --- Telas novas de decisão (10/09/2026): cobertura e estoque mínimo,
  // -------------------------------------------------------------------
  // Cobertura e Reposição — /estoque/cobertura
  // -------------------------------------------------------------------
  {
    id: 'estoque-cobertura-grupos-de-acao',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'Entender os cartões da tela Cobertura e Reposição (produzir, programar, parado, tranquilo)',
    rota: '/estoque/cobertura',
    perguntas: [
      'o que e a tela de cobertura e reposicao',
      'cartoes da tela cobertura',
      'produzir esta semana o que significa',
      'programar no mes o que significa',
      'parado e sobrando cobertura',
      'grupo tranquilo cobertura de estoque',
      'como a cobertura agrupa as referencias',
      'clicar no cartao troca a lista',
      'onde vejo o que precisa produzir',
      'tela de reposicao de estoque',
    ],
    resposta:
      'A tela **Cobertura e Reposição** abre agrupada em cartões clicáveis no topo, e não numa lista única: **Produzir esta semana** (já faltou, ou vai faltar antes da próxima rodada — ordenado por dinheiro em risco), **Programar no mês** (abaixo do ponto de pedido, mas em cadência quinzenal ou mensal, então entra na próxima ordem), **Parado e sobrando** (estoque muito acima do que o ciclo pede, ou sem nenhuma venda na janela — é dinheiro preso) e **Tranquilo** (acima do ponto de pedido e dentro do esperado para o ciclo). Clicar num cartão troca a lista abaixo; o número de cada cartão já é sobre a lista com os filtros aplicados.\n\nUm quinto grupo, **Sem cálculo possível**, reúne referências que vendem raramente ou em quantidade que pula demais para caber numa fórmula — o sistema não inventa número nesses casos, e cada linha mostra o motivo por escrito.',
    relacionados: ['estoque-cobertura-como-e-calculado', 'estoque-cobertura-pedir-ate-atrasado-sem-calculo'],
  },
  {
    id: 'estoque-cobertura-cadencia-e-prazos',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'Mudar a cadência de reposição e os prazos de produção de cada cadência',
    rota: '/estoque/cobertura',
    perguntas: [
      'como mudo a cadencia de uma referencia',
      'cadencia semanal quinzenal mensal sob demanda',
      'prazo de producao por cadencia',
      'botao prazos de producao',
      'prazo proprio de uma referencia',
      'cadencia escolhida a mao nao e sobrescrita',
      'quanto tempo leva pra repor cada cadencia',
      'segurança da cadencia dias',
      'quem manda no prazo a facção ou o calculo',
      'referencia demora mais pra produzir que as outras',
    ],
    resposta:
      'Dentro do detalhe de cada linha (abra pela seta de expandir), o campo **Cadência** define de quanto em quanto tempo aquela referência é reposta: **Semanal**, **Quinzenal**, **Mensal** ou **Sob demanda** (só quando pedirem). Ela decide o prazo usado no cálculo, e a escolha feita à mão nessa tela sempre vence a sugestão automática baseada na venda — uma peça que demora três semanas na facção não vira "semanal" só por ter vendido bem num mês.\n\nO botão **Prazos de produção**, no topo da tela, abre os prazos padrão de cada cadência (dias de produção + dias de segurança) — vieram da planilha de estoque mínimo da casa e são valores editáveis ali mesmo, porque o prazo real da facção pesa no resultado mais do que qualquer outro número da tela. Há também o campo **Prazo próprio (dias)**, na linha de detalhe, para quando uma referência específica demora diferente das outras da mesma cadência; em branco, vale o prazo padrão da cadência escolhida.',
    relacionados: ['estoque-cobertura-como-e-calculado', 'estoque-cobertura-grupos-de-acao'],
  },
  {
    id: 'estoque-cobertura-como-e-calculado',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'O que significa cada linha do painel "Como cheguei nesse número"',
    rota: '/estoque/cobertura',
    perguntas: [
      'como e calculado o estoque minimo',
      'como e calculado o ponto de pedido',
      'painel como cheguei nesse numero',
      'o que e vende por dia',
      'o que e posicao de estoque',
      'diferenca entre estoque minimo e ponto de pedido',
      'como e calculada a quantidade a produzir',
      'nivel de servico e curva cobertura',
      'botao como isso e calculado',
      'formula do estoque de seguranca',
      'quanto produzir formula',
    ],
    resposta:
      'Dentro do detalhe de cada linha, o bloco **Como cheguei nesse número** mostra por extenso a conta atrás do cálculo: **Vende por dia** (venda média medida na janela escolhida), **Prazo usado** (o prazo de produção que entrou na conta, próprio da referência ou padrão da cadência), **Estoque mínimo** (o colchão contra a variação da venda), **Ponto de pedido** (o nível a partir do qual dispara a decisão de repor — soma o que se espera vender durante o prazo de produção com o estoque mínimo), **Quanto produzir** (o alvo do ciclo inteiro menos a posição de estoque atual), **Posição de estoque** (saldo no galpão mais o que já está na facção) e **Comportamento**/**Curva e proteção** (a classificação da referência e o nível de serviço usado na proteção).\n\nO botão **Como isso é calculado**, no topo da tela, abre a explicação geral de cada conceito — por que estoque mínimo e ponto de pedido são coisas diferentes, por que a proteção muda conforme a curva (A, B ou C) e por que "quanto produzir" cobre o ciclo inteiro em vez de repor só até o mínimo. A tela mostra o raciocínio completo; ela não decide sozinha, e cadência, nível e prazo continuam editáveis à mão em cada linha.',
    relacionados: ['estoque-cobertura-cadencia-e-prazos', 'estoque-cobertura-pedir-ate-atrasado-sem-calculo'],
  },
  {
    id: 'estoque-cobertura-grade-cor-tamanho',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'Ver e copiar a grade cor × tamanho dentro da linha de uma referência',
    rota: '/estoque/cobertura',
    perguntas: [
      'grade cor e tamanho na cobertura',
      'copiar grade para o whatsapp da faccao',
      'ver saldo por cor e tamanho na cobertura',
      'ver venda por cor e tamanho na cobertura',
      'quantas variantes estao zeradas na referencia',
      'faixinha de quadradinhos cobertura',
      'peca vendida em kit na grade',
      'abrir grade dentro da linha',
      'botao copiar grade',
      'combinacao de cor e tamanho que nao existe',
    ],
    resposta:
      'Clicando na coluna **Grade** (ou na seta de expandir a linha), abre embaixo da referência a matriz **cor × tamanho**, no mesmo formato usado pela facção. Um seletor no topo alterna entre **Saldo em estoque** e **Vendeu na janela** — a mesma matriz responde "o que eu tenho" e "o que sai", as duas perguntas que decidem a grade do próximo pedido. Células zeradas (no saldo) ou com venda (na medida "vendeu") ficam destacadas; uma combinação de cor e tamanho que não existe no catálogo aparece como "—", que não é erro.\n\nO botão **Copiar grade** copia a tabela em texto tabulado, pronto para colar direto no WhatsApp da facção. Peça vendida dentro de kit não tem cor nem tamanho — entra no total da referência, mas fica de fora da grade, e a própria grade avisa isso quando é o caso. A faixinha de quadradinhos ao lado da referência (até 24 variantes; acima disso vira barra proporcional) mostra de relance quantas variantes estão zeradas, sem precisar abrir a grade.',
    relacionados: ['estoque-cobertura-grupos-de-acao'],
  },
  {
    id: 'estoque-cobertura-filtros-busca-exportar',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'Filtrar por nível, cadência, categoria ou período e exportar a lista de Cobertura',
    rota: '/estoque/cobertura',
    perguntas: [
      'filtrar cobertura por nivel',
      'filtro essenciais e intermediarias',
      'filtrar cobertura por cadencia',
      'filtrar cobertura por categoria',
      'buscar referencia na cobertura',
      'periodo da cobertura semanas cheias',
      'exportar cobertura de estoque',
      'exportar lista de reposicao',
      'quais colunas vem na exportacao da cobertura',
      'mudar o periodo de venda medida na cobertura',
    ],
    resposta:
      'A barra de comando da tela reúne o **período** (a venda é medida por semana, então as duas pontas do período escolhido são arredondadas para semana inteira — a tela mostra quantas "semanas cheias" entraram na conta), o filtro de **Nível** (com a opção "Essenciais e intermediárias", que junta os dois níveis mais estratégicos de uma vez), **Cadência** (semanal/quinzenal/mensal/sob demanda), **Categoria** e uma busca por referência ou descrição. Esses filtros valem para todos os cartões ao mesmo tempo — o número em cada cartão já é sobre a lista já filtrada.\n\nO botão **Exportar**, dentro do card da lista, gera a planilha só com as referências da seção aberta no momento, com referência, categoria, nível, cadência, venda por dia, cobertura em dias, saldo, estoque na facção, estoque mínimo, ponto de pedido, quanto produzir e a data de "pedir até".',
    relacionados: ['estoque-cobertura-grupos-de-acao', 'estoque-cobertura-cadencia-e-prazos'],
  },
  {
    id: 'estoque-cobertura-pedir-ate-atrasado-sem-calculo',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: '"Pedir até" atrasado e o que faz uma referência cair em "Sem cálculo possível"',
    rota: '/estoque/cobertura',
    perguntas: [
      'pedir ate atrasado o que significa',
      'data limite para mandar produzir',
      'sem calculo possivel motivo',
      'referencia sem venda medida cobertura',
      'ficou sem estoque na janela',
      'censura de demanda cobertura',
      'estoque minimo otimista o que significa',
      'porque essa referencia nao tem numero',
      'falta prazo de producao cobertura',
      'sem cadencia definida',
    ],
    resposta:
      'Na coluna **Pedir até**, cada linha mostra a data-limite para mandar produzir sem furar o estoque — a diferença entre quanto o estoque atual ainda dura e quanto tempo a peça leva para ficar pronta. Quando essa folga já é negativa, a tela usa a palavra **atrasado**, com o selo em vermelho, em vez de mostrar uma data.\n\nUma referência cai no grupo **Sem cálculo possível** quando falta venda medida na janela, falta o prazo de produção, não há posição de estoque ou não há cadência definida — o sistema não inventa número nesses casos, e cada linha traz o motivo por escrito. Vale notar também o selo "**ficou sem estoque**", que aparece quando a referência zerou em alguma semana da janela: a venda medida fica menor que a demanda real, e por isso o estoque mínimo calculado para ela é considerado otimista.',
    relacionados: ['estoque-cobertura-grupos-de-acao', 'estoque-cobertura-como-e-calculado'],
  },

  // -------------------------------------------------------------------
  // Curva de Tamanho — /estoque/curva-tamanho
  // -------------------------------------------------------------------
  {
    id: 'estoque-curva-tamanho-visao-geral',
    modulo: 'estoque',
    tela: 'Curva de Tamanho',
    titulo: 'Para que serve a tela Curva de Tamanho',
    rota: '/estoque/curva-tamanho',
    perguntas: [
      'o que e curva de tamanho',
      'quanto cortar de cada tamanho',
      'como funciona a curva de tamanho',
      'participacao de cada tamanho nas vendas',
      'curva de tamanho por referencia',
      'curva de tamanho de todas as referencias',
      'campo historico em meses curva',
      'campo lote a cortar',
      'campo minimo por tamanho',
      'tela para grade de corte',
    ],
    resposta:
      'A tela **Curva de tamanho** responde "de cada tanto de peças cortadas, quantas de cada tamanho?", usando o histórico de vendas em vez do chute. Escolha uma **Referência** (em branco, a curva é geral, de todas as referências), quantos meses de **Histórico** considerar, o **Lote a cortar** (peças) e um **Mínimo por tamanho** — abaixo desse mínimo, o tamanho sai da grade final de corte.\n\nA tabela **Participação de cada tamanho** mostra, para cada tamanho, quantas peças venderam no histórico e o percentual de participação, com uma barra visual ao lado.',
    relacionados: ['estoque-curva-nivel-hierarquia-volume', 'estoque-curva-grade-para-cortar-lote'],
  },
  {
    id: 'estoque-curva-nivel-hierarquia-volume',
    modulo: 'estoque',
    tela: 'Curva de Tamanho',
    titulo: 'De onde vem a curva usada (referência, categoria ou geral) e o que é "volume curto"',
    rota: '/estoque/curva-tamanho',
    perguntas: [
      'curva usada desta referencia ou da categoria',
      'curva de tamanho sobe para categoria',
      'referencia nova sem historico curva',
      'niveis descartados curva de tamanho',
      'volume suficiente ou curto curva',
      'quantas pecas minimas para a curva',
      'porque a curva usou a categoria e nao a referencia',
      'curva geral de todas as referencias',
      'indicador volume curva de tamanho',
    ],
    resposta:
      'O indicador **Curva usada** mostra de qual nível a curva realmente veio: **desta referência**, **da categoria** ou **de todas as referências**. Quando a referência escolhida tem histórico curto demais, a tela sobe automaticamente para a curva da categoria e depois para a geral — usar a participação de uma referência com poucas peças vendidas seria ruído disfarçado de dado, porque uma venda a mais mudaria o percentual inteiro. Quando isso acontece, a lista **Níveis descartados** explica por que cada nível anterior não foi usado.\n\nO indicador **Volume** mostra **Suficiente** ou **Curto**: abaixo de um número mínimo de peças no histórico (explicado no próprio indicador), a participação de cada tamanho é considerada instável demais para confiar cegamente.',
    relacionados: ['estoque-curva-tamanho-visao-geral', 'estoque-curva-tamanho-esgotou'],
  },
  {
    id: 'estoque-curva-tamanho-esgotou',
    modulo: 'estoque',
    tela: 'Curva de Tamanho',
    titulo: 'O que significa um tamanho aparecer como "esgotou" na Curva de Tamanho',
    rota: '/estoque/curva-tamanho',
    perguntas: [
      'tamanho esgotou na curva',
      'selo esgotou curva de tamanho',
      'tamanho vendeu menos porque faltou',
      'participacao subestimada curva',
      'tamanhos que esgotaram indicador',
      'curva de tamanho tamanho zerado',
      'porque um tamanho tem participacao baixa',
      'corte repete o mesmo erro de tamanho',
    ],
    resposta:
      'O indicador **Tamanhos que esgotaram** e o selo **esgotou** ao lado do tamanho na tabela avisam que aquele tamanho ficou sem estoque durante o período do histórico — ou seja, vendeu menos do que teria vendido se tivesse peça disponível o tempo todo. A participação desse tamanho na curva está, por isso, subestimada: cortar exatamente pela curva como está tende a repetir o mesmo problema, porque ele recebe menos peça ainda e esgota mais cedo de novo.\n\nA tela avisa o fato; ajustar a grade para compensar isso é decisão de quem está cortando, não algo que o sistema faz sozinho.',
    relacionados: ['estoque-curva-nivel-hierarquia-volume', 'estoque-curva-grade-para-cortar-lote'],
  },
  {
    id: 'estoque-curva-grade-para-cortar-lote',
    modulo: 'estoque',
    tela: 'Curva de Tamanho',
    titulo: 'Gerar a grade de corte de um lote pela Curva de Tamanho',
    rota: '/estoque/curva-tamanho',
    perguntas: [
      'gerar grade para cortar lote',
      'grade de corte pela curva',
      'metodo do maior resto',
      'grade nao fecha com o lote',
      'tamanho removido pelo minimo',
      'coluna conta exata curva de tamanho',
      'distribuir lote entre os tamanhos',
      'soma da grade nao confere',
      'quantas pecas cortar de cada tamanho',
    ],
    resposta:
      'Com um **Lote a cortar** definido, a tela monta a **Grade para cortar X peças**, distribuindo o lote entre os tamanhos pela participação de cada um na curva. A distribuição usa o **método do maior resto**: como cada tamanho isolado arredondaria para cima ou para baixo, as sobras do arredondamento vão, uma a uma, para quem mais perdeu na conta — é assim que a soma final fecha exatamente no lote pedido, em vez de sobrar ou faltar peça por causa do arredondamento de cada tamanho em separado.\n\nUm tamanho abaixo do **Mínimo por tamanho** definido no formulário é removido da grade final (a linha aparece destacada como "removido pelo mínimo"), e a quantidade dele é redistribuída para os demais. A coluna **Conta exata** mostra o número antes do arredondamento, para quem quiser conferir. Se por algum motivo a soma da grade não bater com o lote, a tela mostra um aviso explícito de defeito e recomenda não cortar por aquela grade.',
    relacionados: ['estoque-curva-tamanho-visao-geral', 'estoque-curva-tamanho-esgotou'],
  },

  // -------------------------------------------------------------------
  // Depósitos e Transferências — /estoque/depositos
  // -------------------------------------------------------------------
  {
    id: 'estoque-depositos-natureza-cadastro',
    modulo: 'estoque',
    tela: 'Depósitos',
    titulo: 'Cadastrar um depósito e o que significa a natureza (Nosso, Facção, Terceiro)',
    rota: '/estoque/depositos',
    perguntas: [
      'como cadastro um deposito',
      'novo deposito botao',
      'natureza do deposito nosso faccao terceiro',
      'deposito de faccao precisa de fornecedor',
      'canal do deposito mercado livre shopee',
      'canal muda o saldo enviado ao marketplace',
      'deposito padrao o que e',
      'desativar deposito com saldo',
      'nao consigo excluir deposito',
      'codigo e nome do deposito',
    ],
    resposta:
      'Em **Depósitos e transferências**, o botão **Novo depósito** abre o cadastro com Código, Nome e **Natureza**: **Nosso** (aqui dentro — é o único tipo de onde se vende pelo canal normal), **Facção** (costura, lavanderia, bordado — continua sendo nosso e continua valendo dinheiro, mas não dá para vender hoje) e **Terceiro** (consignado, showroom, ML Full, Shopee 3PL — nosso, fora daqui, e não vendável pelo canal normal). Um depósito de natureza **Facção** pede também **De quem é a casa** (o fornecedor dono do lugar).\n\nO campo **Canal** identifica quando o depósito representa uma plataforma (Mercado Livre, Shopee, TikTok Shop, Shein), mas é só informativo por enquanto: marcar um canal **não muda** o saldo que o Hub envia para aquela plataforma — a tela avisa isso explicitamente. Um depósito com saldo dentro não pode ser excluído, só desativado (some das opções normais, mas o histórico continua existindo).',
    relacionados: ['estoque-depositos-nova-transferencia-enviar', 'estoque-depositos-indicadores-panorama'],
  },
  {
    id: 'estoque-depositos-nova-transferencia-enviar',
    modulo: 'estoque',
    tela: 'Depósitos',
    titulo: 'Criar uma transferência entre depósitos e enviar (mandar não entrega)',
    rota: '/estoque/depositos',
    perguntas: [
      'como crio uma transferencia entre depositos',
      'nova transferencia botao',
      'transferencia rascunho o que significa',
      'como envio a transferencia',
      'transferencia em transito',
      'enviar nao tira do estoque na hora',
      'incluir item na remessa',
      'escolher origem e destino transferencia',
      'mandar nao entrega deposito',
      'peca some do saldo enquanto esta em transito',
    ],
    resposta:
      'O botão **Nova transferência** abre um painel para escolher **De** (origem) e **Para** (destino), opcionalmente o **Número** do documento e **Quem leva**. Com a origem escolhida, aparece o saldo dela (peças e insumos) para buscar e incluir item por item na remessa — clicar na linha do item o inclui, com a quantidade editável.\n\nCriar a transferência **não move estoque**: ela nasce como **Rascunho**, que é intenção. O estoque só sai da origem quando alguém clica em **Enviar**, na lista de transferências — a partir daí a carga fica **em trânsito**, some do saldo da origem e ainda não aparece no destino, porque ela realmente não está disponível em lugar nenhum enquanto está na rua.',
    relacionados: ['estoque-depositos-conferir-chegada-divergencia', 'estoque-depositos-natureza-cadastro'],
  },
  {
    id: 'estoque-depositos-conferir-chegada-divergencia',
    modulo: 'estoque',
    tela: 'Depósitos',
    titulo: 'Conferir a chegada de uma transferência (aceite) e o que acontece com a diferença',
    rota: '/estoque/depositos',
    perguntas: [
      'como confiro a chegada da transferencia',
      'botao conferir transferencia',
      'campo chegou vazio no aceite',
      'registrar chegada da carga',
      'chegou menos do que saiu',
      'divergencia na transferencia',
      'zero e diferente de deixar em branco',
      'aceite da transferencia obrigatorio',
      'situacao recebida transferencia',
    ],
    resposta:
      'Uma transferência **em trânsito** tem o botão **Conferir**, que abre o painel de aceite item por item. O campo **Chegou** de cada item nasce **vazio**, de propósito — não vem preenchido com o que foi enviado, porque um aceite que já nasce igual ao envio é um aceite que não está sendo conferido de verdade. Zero também é um número válido ali, diferente de deixar em branco: a tela não deixa **Registrar chegada** enquanto sobrar item sem número.\n\nQuando o que chegou é menor do que o que saiu, a diferença **não vira ajuste de estoque sozinha**: ela volta a ser saldo "sem depósito" e fica marcada na própria transferência, até alguém decidir o que fazer com ela. A transferência muda para a situação **Recebida**, e a coluna **Divergência** mostra quantos itens bateram diferente do enviado.',
    relacionados: ['estoque-depositos-nova-transferencia-enviar', 'estoque-depositos-estornar-baixar-falta'],
  },
  {
    id: 'estoque-depositos-estornar-baixar-falta',
    modulo: 'estoque',
    tela: 'Depósitos',
    titulo: 'Estornar uma transferência em trânsito ou baixar a falta como perda',
    rota: '/estoque/depositos',
    perguntas: [
      'como estorno uma transferencia',
      'transferencia voltou o que fazer',
      'baixar falta como perda',
      'unica acao que muda o total do estoque',
      'divergencia de insumo nao e baixada aqui',
      'motivo obrigatorio ao estornar',
      'desfazer envio de transferencia',
      'perda de peca na transferencia',
    ],
    resposta:
      'Enquanto a transferência está **em trânsito**, o botão **Estornar** pede um motivo (fica gravado na transferência) e devolve as peças para o depósito de origem — é o caminho para desfazer um envio que não deveria ter saído.\n\nDepois que uma transferência **recebida** ficou com divergência, o botão **Baixar falta** pede um motivo e registra a perda de verdade — essa é a **única ação desta tela** que efetivamente muda o total do estoque (as outras só movem peça entre lugares, mantendo o total igual). A confirmação avisa isso explicitamente e não tem como desfazer com um clique. Item de **insumo** com divergência não é baixado por aqui: o total de insumo é controlado por outro módulo, e a tela avisa para ajustar por lá em vez de duplicar o número.',
    relacionados: ['estoque-depositos-conferir-chegada-divergencia'],
  },
  {
    id: 'estoque-depositos-indicadores-panorama',
    modulo: 'estoque',
    tela: 'Depósitos',
    titulo: 'O que significam os indicadores do topo de Depósitos e transferências',
    rota: '/estoque/depositos',
    perguntas: [
      'pecas em transito o que significa',
      'pecas sem deposito o que significa',
      'pecas fora do mapa o que significa',
      'depositos ativos indicador',
      'diferenca entre sem deposito e fora do mapa',
      'panorama de depositos',
      'detalhamento soma mais que o total do estoque',
      'erro de lancamento entre depositos',
    ],
    resposta:
      'No topo de **Depósitos e transferências**, os indicadores resumem o panorama: **Depósitos ativos** (lugares onde o estoque pode estar endereçado), **Peças em trânsito** (já saíram de um depósito e ainda não foram conferidas no outro — não estão disponíveis em lugar nenhum, de propósito), **Peças sem depósito** (estão numa natureza de lugar conhecida, como uma facção, mas ninguém disse ainda em qual depósito específico — é o tamanho do que falta endereçar) e **Peças fora do mapa** (entram no total do estoque mas não aparecem em nenhum detalhamento, nem por depósito nem por natureza — é saldo antigo, de antes de existir esse controle).\n\nSe o detalhamento por depósito somar mais do que o total do estoque, a tela mostra um aviso de erro dizendo que isso é defeito de lançamento (não é possível na operação normal) e recomenda conferir os saldos antes de confiar nos números da tela.',
    relacionados: ['estoque-depositos-natureza-cadastro', 'estoque-locais-visao-geral-disponivel'],
  },

  // -------------------------------------------------------------------
  // Onde está a peça (locais) — /estoque/locais
  // -------------------------------------------------------------------
  {
    id: 'estoque-locais-visao-geral-disponivel',
    modulo: 'estoque',
    tela: 'Onde Está a Peça',
    titulo: 'Para que serve a tela Onde Está a Peça e o que é "Disponível"',
    rota: '/estoque/locais',
    perguntas: [
      'o que e a tela onde esta a peca',
      'endereco da peca no estoque',
      'quanto esta no galpao e quanto na faccao',
      'o que e disponivel no estoque',
      'total no estoque x disponivel para vender',
      'mover peca nao muda o total',
      'pecas fora daqui o que significa',
      'ainda sem lugar indicador',
      'localizacao da peca prateleira',
    ],
    resposta:
      '**Onde está a peça** responde duas perguntas que o resto do sistema não respondia: em que prateleira (endereço) está a referência, e quanto dela está aqui, na facção ou com terceiro. Ela **não muda o total do estoque** — mover peça entre locais é sempre soma zero; o total da variante continua sendo o total do que é nosso, esteja onde estiver. O que ela acrescenta é a repartição desse total, e um número novo: **Disponível** = total menos o que está fora daqui (em facção, trânsito ou terceiro) — é esse número que sustenta o prazo prometido ao cliente, não o total.\n\nOs indicadores do topo são: **Total no estoque**, **Disponível para vender**, **Fora daqui** (em facção, trânsito ou terceiro — continua sendo nosso e continua valendo dinheiro) e **Ainda sem lugar** (saldo que existia antes deste módulo e que ninguém ainda declarou onde está — o sistema não chuta que está tudo no galpão).',
    relacionados: ['estoque-locais-mover-peca-entre-locais', 'estoque-locais-endereco-lote'],
  },
  {
    id: 'estoque-locais-mover-peca-entre-locais',
    modulo: 'estoque',
    tela: 'Onde Está a Peça',
    titulo: 'Registrar que uma peça foi movida entre locais (galpão, facção, terceiro)',
    rota: '/estoque/locais',
    perguntas: [
      'como movo peca para a faccao',
      'botao mover na tela de locais',
      'sai de e vai para',
      'de qual faccao a peca esta indo',
      'motivo do movimento entre locais',
      'peca sai do disponivel ao mover para faccao',
      'mover peca de volta pro galpao',
      'aviso destino nao vendavel',
    ],
    resposta:
      'Na tabela de variantes, o botão **Mover** abre um painel com **Sai de** e **Vai para**, escolhendo entre os locais cadastrados (galpão próprio, facção, terceiro) — quando o local exige, aparece também **De qual facção** / **Para qual facção**, para dizer o fornecedor. Preencha a quantidade e, opcionalmente, um **Motivo** (aparece depois no histórico da variante).\n\nQuando o destino escolhido não é vendável (por exemplo, mandar para a facção), a tela mostra um aviso explícito: essas peças continuam no total do estoque, mas saem do **disponível para venda**. Esse movimento é só de repartição — o total da variante não muda.',
    relacionados: ['estoque-locais-visao-geral-disponivel'],
  },
  {
    id: 'estoque-locais-endereco-lote',
    modulo: 'estoque',
    tela: 'Onde Está a Peça',
    titulo: 'Cadastrar o endereço (prateleira) de uma variante e endereçar tudo em lote',
    rota: '/estoque/locais',
    perguntas: [
      'como cadastro o endereco da peca',
      'editar endereco na tela de locais',
      'endereçar tudo que falta no galpao',
      'botao endereçar em lote',
      'sem endereco na tabela',
      'declarar que o saldo esta no galpao',
      'saldo anterior ao modulo de locais',
      'lancar remessa de faccao antes de endereçar em lote',
    ],
    resposta:
      'Na coluna **Endereço** da tabela, clique no ícone de lápis para digitar o texto livre da localização (por exemplo, "rua B / prat. 3") de cada variante e salvar. Variantes ainda sem endereço aparecem com "sem endereço".\n\nQuando há saldo "ainda sem lugar" (anterior a este módulo), o botão **Endereçar tudo que falta no galpão** aparece na barra de filtros — ele declara de uma vez que **todo** esse saldo pendente está no galpão próprio. A confirmação avisa: se alguma dessas peças estiver de fato numa facção agora, é preciso lançar a remessa dela **antes** de usar o botão, senão o saldo dela passa a constar como se estivesse aqui dentro por engano.',
    relacionados: ['estoque-locais-visao-geral-disponivel'],
  },
  {
    id: 'estoque-locais-faccao-inconsistencias',
    modulo: 'estoque',
    tela: 'Onde Está a Peça',
    titulo: 'Ver quanto está parado em cada facção e os avisos de inconsistência',
    rota: '/estoque/locais',
    perguntas: [
      'peca pronta com a faccao',
      'quanto tempo a peca esta na faccao',
      'variante inconsistente estoque locais',
      'mais peca enderecada do que existe',
      'saldo negativo em algum local',
      'card peca pronta que esta com faccao',
      'remessa mais antiga na faccao',
      'defeito de lancamento nos locais',
    ],
    resposta:
      'Quando há peça pronta com alguma facção, o card **Peça pronta que está com facção** lista, por facção, quantas peças e variantes estão lá e há quanto tempo a mais antiga remessa saiu — um jeito de enxergar, de relance, se alguma facção está segurando peça pronta por tempo demais.\n\nA tela também aponta dois problemas: **variantes inconsistentes**, quando a soma do que foi endereçado é maior do que o saldo real da variante (defeito de lançamento, não arredondamento — o aviso pede para resolver antes de confiar no disponível), e **variantes com saldo negativo em algum local**, quando saiu mais peça de um local do que havia registrado nele (o aviso sugere conferir as remessas de facção daquelas referências).',
    relacionados: ['estoque-locais-visao-geral-disponivel', 'estoque-locais-mover-peca-entre-locais'],
  },

  // -------------------------------------------------------------------
  // Dinheiro Parado — /estoque/parado
  // -------------------------------------------------------------------
  {
    id: 'estoque-parado-visao-geral-janela',
    modulo: 'estoque',
    tela: 'Dinheiro Parado',
    titulo: 'O que a tela Dinheiro Parado mostra e como mudar a janela de dias',
    rota: '/estoque/parado',
    perguntas: [
      'o que e dinheiro parado no estoque',
      'quanto do caixa esta preso em estoque',
      'considerar parado a partir de quantos dias',
      'janela de 90 180 dias parado',
      'idade da peca parada conta de onde',
      'peca que nunca vendeu idade parado',
      'peca que entrou essa semana nao e estoque morto',
      'estoque parado por uma estacao duas estacoes',
    ],
    resposta:
      '**Dinheiro parado no estoque** responde em reais uma pergunta que o resto do sistema só respondia em peças: quanto do caixa está preso em roupa que não vende, e há quanto tempo. O campo **Considerar parado a partir de** define, a partir de quantos dias sem vender, uma peça entra na análise, com três opções prontas: mais de 90 dias (uma estação), mais de 180 dias (duas estações) ou mais de 1 ano.\n\nA idade de cada peça parada conta a partir da **última venda**; quando ela nunca vendeu, conta a partir da entrada no estoque — assim, uma peça que chegou essa semana e ainda não vendeu não é tratada como estoque morto.',
    relacionados: ['estoque-parado-custo-piso-sem-custo', 'estoque-parado-faixas-e-liquidacao'],
  },
  {
    id: 'estoque-parado-custo-piso-sem-custo',
    modulo: 'estoque',
    tela: 'Dinheiro Parado',
    titulo: 'Por que o valor parado é ao custo e o que significa o valor ser um "piso"',
    rota: '/estoque/parado',
    perguntas: [
      'por que o valor parado e ao custo',
      'valor parado nao e ao preco de venda',
      'o que e piso no dinheiro parado',
      'referencia sem ficha de custo dinheiro parado',
      'peca sem custo nao entra como zero',
      'imposto e taxa de marketplace no valor parado',
      'parado em reais no minimo',
      'card paradas mas sem custo para valorizar',
    ],
    resposta:
      'O indicador **Parado em R$** é calculado ao **custo de produção** (material + custo industrial + custo indireto), não ao preço de venda — preço de venda só existiria se a peça estivesse vendendo, e ela não está. Também não entram imposto nem taxa de marketplace, porque esses só existem quando a peça de fato vende.\n\nQuando existe peça parada de uma referência **sem ficha de custo cadastrada**, ela **não entra como R$ 0,00** no total — o rótulo do indicador muda para "**Parado em R$ (no mínimo)**", virando um **piso**: o número real é maior do que o mostrado. Essas peças aparecem à parte, contadas em unidades, na seção **Paradas, mas sem custo para valorizar**.',
    relacionados: ['estoque-parado-visao-geral-janela', 'estoque-parado-referencias-sem-idade'],
  },
  {
    id: 'estoque-parado-faixas-e-liquidacao',
    modulo: 'estoque',
    tela: 'Dinheiro Parado',
    titulo: 'A tabela "Por tempo parado" e a simulação de "quanto volta numa liquidação"',
    rota: '/estoque/parado',
    perguntas: [
      'tabela por tempo parado',
      'faixas de tempo parado',
      'parado ha mais de um ano indicador',
      'quanto volta ao caixa numa liquidacao',
      'simulacao de liquidacao dinheiro parado',
      'vendendo pelo custo quanto entra',
      'perda ja aconteceu quando a peca parou',
      'card recuperacao de valor',
    ],
    resposta:
      'O card **Por tempo parado** agrupa o valor parado em faixas de idade, cada uma com uma leitura do que ela significa. A faixa acima de um ano tem indicador próprio, **Parado há mais de 1 ano**: peça que atravessou a mesma estação duas vezes sem vender — a tela é explícita que, nesse ponto, o dinheiro só volta com liquidação, kit ou desmanche.\n\nO card **Quanto volta ao caixa numa liquidação** simula quanto entraria de caixa vendendo pelo custo ou a um percentual dele — não é uma recomendação de desconto, é a conta que se faz de qualquer forma antes de decidir: a perda já aconteceu quando a peça parou, o desconto só a torna visível.',
    relacionados: ['estoque-parado-visao-geral-janela'],
  },
  {
    id: 'estoque-parado-referencias-sem-idade',
    modulo: 'estoque',
    tela: 'Dinheiro Parado',
    titulo: 'Ver o detalhe por referência ou por variante, e o que é "sem como medir há quanto tempo"',
    rota: '/estoque/parado',
    perguntas: [
      'referencias que prendem mais dinheiro',
      'ver variante por variante dinheiro parado',
      'idade maxima da referencia parada',
      'sem como medir ha quanto tempo estao paradas',
      'peca nunca vendeu e sem movimento de entrada',
      'custo unitario da peca parada',
      'data usada para contar a idade',
      'chutar a idade mudaria o total',
    ],
    resposta:
      'O card **Referências que prendem mais dinheiro** lista, por padrão, uma linha por referência (variantes, peças, valor ao custo, idade máxima e os tamanhos envolvidos); o botão **Ver variante por variante** troca para o detalhe por cor e tamanho, com o custo unitário e a base usada para contar a idade.\n\nA seção **Sem como medir há quanto tempo estão paradas** lista variantes que nunca venderam e também não têm nenhum movimento de entrada registrado — não dá para saber se estão paradas há anos ou entraram ontem, e chutar qualquer uma das duas hipóteses mudaria o total da tela. Por isso elas ficam à parte, sem entrar no valor parado.',
    relacionados: ['estoque-parado-custo-piso-sem-custo'],
  },

  // -------------------------------------------------------------------
  // Reserva de Estoque — /estoque/reserva
  // -------------------------------------------------------------------
  {
    id: 'estoque-reserva-saldo-disponivel-reservado',
    modulo: 'estoque',
    tela: 'Reserva de Estoque',
    titulo: 'A diferença entre saldo, reservado e disponível na tela Reserva de Estoque',
    rota: '/estoque/reserva',
    perguntas: [
      'o que e a tela reserva de estoque',
      'diferenca entre saldo e disponivel',
      'o que e disponivel no estoque',
      'reservar nao move estoque',
      'porque vendi a mesma peca em dois marketplaces',
      'pedido pago e ainda nao separado',
      'card disponivel por variante',
      'filtro so com reserva so negativos',
    ],
    resposta:
      '**Reserva de estoque** existe por causa de um número que hoje sai errado para os marketplaces: o saldo. **Saldo** é o que está fisicamente no galpão; **disponível** é o que ainda pode ser vendido — a diferença entre os dois é a peça de um pedido já pago e ainda não separada, que está no galpão mas **não pode** ser vendida de novo. Sem essa separação, a mesma peça acaba anunciada ao mesmo tempo na Shopee e no Mercado Livre, e um dos dois pedidos é cancelado por falta.\n\nReservar **não move estoque** — a peça continua fisicamente no galpão, só sai do número "disponível". O card **Disponível por variante** lista, por variante, saldo, reservado e disponível, com filtros por referência, busca (referência, descrição, cor, tamanho, EAN ou local) e os toggles **Só com reserva** e **Só negativos**.',
    relacionados: ['estoque-reserva-manual-variante-pedido', 'estoque-reserva-liberar-consumir'],
  },
  {
    id: 'estoque-reserva-manual-variante-pedido',
    modulo: 'estoque',
    tela: 'Reserva de Estoque',
    titulo: 'Reservar uma variante manualmente ou reservar um pedido de venda inteiro',
    rota: '/estoque/reserva',
    perguntas: [
      'como reservo uma variante',
      'botao reservar na tela de reserva',
      'reservar pedido de venda inteiro',
      'campo numero do pedido reservar',
      'item sem variante identificada no pedido',
      'reserva sem motivo',
      'reserva ja existente ajustada',
      'quantidade e motivo da reserva',
    ],
    resposta:
      'No card **Disponível por variante**, o botão **Reservar** de cada linha abre um painel mostrando o saldo, o já reservado e o disponível daquela variante, e pede a **quantidade** e o **motivo** — a tela avisa que reserva sem motivo é reserva que ninguém sabe liberar depois.\n\nJá o campo **Reservar um pedido de venda inteiro**, na seção Reservas, recebe o número de um pedido e reserva todos os itens dele de uma vez; um item do pedido sem variante identificada não trava a operação — ele volta como **aviso**, listado no topo da tela. Se já existir uma reserva daquela mesma origem, a tela ajusta a existente em vez de somar duas vezes.',
    relacionados: ['estoque-reserva-saldo-disponivel-reservado'],
  },
  {
    id: 'estoque-reserva-liberar-consumir',
    modulo: 'estoque',
    tela: 'Reserva de Estoque',
    titulo: 'A diferença entre liberar e consumir uma reserva',
    rota: '/estoque/reserva',
    perguntas: [
      'diferenca entre liberar e consumir reserva',
      'como libero uma reserva',
      'como consumo uma reserva',
      'consumir da baixa no estoque de verdade',
      'liberar devolve ao disponivel',
      'motivo obrigatorio para liberar',
      'abas ativas consumidas liberadas',
      'reserva nao se apaga',
    ],
    resposta:
      'Uma reserva não se apaga — ela só é **liberada** ou **consumida**, e as duas ficam no histórico com data e responsável. **Liberar** (pede motivo obrigatório) devolve a peça ao disponível: usa-se quando o pedido que gerou a reserva caiu ou não vai mais sair. **Consumir** é o único botão desta tela que dá baixa de verdade no estoque — a peça sai do saldo do galpão e não volta; a confirmação avisa isso explicitamente e deve ser usada só quando a peça já foi separada e despachada.\n\nAs abas **Ativas**, **Consumidas** e **Liberadas** filtram as reservas por situação; cada linha mostra a origem (pedido de venda, ordem de produção ou manual), o motivo e há quantos dias a reserva está parada.',
    relacionados: ['estoque-reserva-saldo-disponivel-reservado', 'estoque-reserva-paradas-politica-validade'],
  },
  {
    id: 'estoque-reserva-paradas-politica-validade',
    modulo: 'estoque',
    tela: 'Reserva de Estoque',
    titulo: 'O que é uma reserva "parada" e o campo "Dias de validade da reserva"',
    rota: '/estoque/reserva',
    perguntas: [
      'o que e reserva parada',
      'aba paradas reserva de estoque',
      'dias de validade da reserva',
      'reserva passou do prazo o que fazer',
      'nada e liberado automaticamente',
      'pecas travadas em reserva parada',
      'quem decide se libera a reserva parada',
    ],
    resposta:
      'A aba **Paradas** lista reservas que já passaram do prazo definido em **Dias de validade da reserva** (campo da seção Política) e continuam ativas — saldo que ninguém pode vender e que ninguém separou ainda. **Nada é liberado automaticamente**: a tela só sinaliza (inclusive com um aviso e uma contagem no indicador **Peças travadas em reserva parada**), e cabe a quem opera decidir se o pedido ainda vai andar ou se a reserva deve ser liberada à mão.',
    relacionados: ['estoque-reserva-liberar-consumir', 'estoque-reserva-politica-negativo-automatica'],
  },
  {
    id: 'estoque-reserva-politica-negativo-automatica',
    modulo: 'estoque',
    tela: 'Reserva de Estoque',
    titulo: 'A política de estoque negativo (Livre/Avisar/Bloquear) e a reserva automática ao importar pedido',
    rota: '/estoque/reserva',
    perguntas: [
      'politica de estoque negativo',
      'opcao livre avisar bloquear reserva',
      'reserva automatica ao importar pedido',
      'toggle reserva automatica nasce desligado',
      'o que sobe pro marketplace saldo ou disponivel',
      'bloquear reserva que deixaria negativo',
      'avisar mas nao trava a reserva',
      'deixar disponivel ficar negativo',
    ],
    resposta:
      'Na seção **Política de reserva**, o campo controla o que o sistema faz quando uma reserva deixaria o **disponível** negativo: **Livre** (deixa ficar negativo e não avisa nada — para quem vende peça que ainda vai ser produzida), **Avisar** (deixa a reserva acontecer, mas devolve um aviso escrito dizendo quanto falta — é o padrão do sistema) ou **Bloquear** (recusa a reserva que deixaria o disponível negativo, exigindo que o estoque entre antes).\n\nO toggle **Reserva automática ao importar pedido** nasce **desligado**: enquanto assim, todo pedido importado continua sem segurar saldo, que é o comportamento anterior a esta tela. Ligar essa opção muda o que é enviado aos marketplaces — o número que sobe para Shopee, Mercado Livre e demais canais deixa de ser o saldo do galpão e passa a ser o **disponível**; a própria tela avisa que essa é uma decisão de operação, não um ajuste técnico.',
    relacionados: ['estoque-reserva-saldo-disponivel-reservado', 'estoque-reserva-paradas-politica-validade'],
  },
];
