// Verbetes do módulo Estoque — controle por variante (referência + cor +
// tamanho), com EAN próprio (/estoque), bipagem (/estoque/bipagem),
// importação de saldo (/estoque/importacao), importação de EAN
// (/estoque/ean) e ficha de estoque pra impressão (/estoque/ficha). Cada
// tela foi lida até o fim antes de escrever o verbete.

export const verbetesEstoque = [
  {
    id: 'estoque-ver-variantes-referencia',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ver as variantes (cor/tamanho) de uma referência',
    rota: '/estoque',
    perguntas: [
      'como vejo o estoque de um produto',
      'quantidade em estoque da referencia',
      'ver variantes de uma referencia',
      'estoque por cor e tamanho',
      'selecionar referencia no estoque',
      'onde vejo a grade de estoque',
      'quantidade atual da variante',
      'estoque de uma referencia especifica',
      'tabela de variantes do estoque',
      'nao acho o estoque de um produto',
      'saldo zerado de uma referencia onde vejo',
    ],
    resposta:
      'Na tela **Estoque**, escolha a referência no campo de seleção — abre uma tabela com cada variante dela (cor, tamanho), o EAN, a quantidade atual e um toggle de "ativa". É essa tabela que mostra a grade completa daquela referência, variante por variante.\n\nCada linha também tem controles pra editar o EAN, mover estoque (entrada/saída) e excluir a variante direto ali, sem precisar abrir outra tela (ver os verbetes específicos de cada ação).',
    relacionados: ['estoque-movimentar-entrada-saida', 'estoque-adicionar-variante', 'gloss-grade'],
  },
  {
    id: 'estoque-buscar-em-todo-estoque',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Buscar uma variante em todo o estoque (por referência, descrição ou EAN)',
    rota: '/estoque',
    perguntas: [
      'como busco pelo ean no estoque',
      'buscar variante por ean',
      'achar produto pelo codigo de barras',
      'buscar em todo o estoque',
      'busca geral do estoque',
      'encontrar variante sem saber a referencia',
      'pesquisar estoque por descricao',
      'onde bipa pra buscar em vez de ler',
    ],
    resposta:
      'Além de selecionar uma referência específica, a tela Estoque tem um campo de **busca geral**, que procura por referência, descrição ou **EAN** em todas as variantes do sistema de uma vez — útil quando você tem só o código de barras em mãos e não sabe de qual produto ele é.\n\nO resultado aparece numa tabela com referência, descrição, cor, tamanho, EAN (editável ali mesmo, clicando no lápis) e quantidade — sem precisar selecionar a referência primeiro.',
    relacionados: ['estoque-ver-variantes-referencia', 'gloss-ean'],
  },
  {
    id: 'estoque-adicionar-variante',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Adicionar uma variante nova (cor/tamanho) a uma referência',
    rota: '/estoque',
    perguntas: [
      'como adiciono uma variante',
      'criar cor e tamanho novo no estoque',
      'adicionar variante a referencia',
      'nova cor no produto',
      'novo tamanho na grade',
      'cadastrar variante de estoque',
      'quantidade inicial da variante',
      'aumentar a grade de uma referencia',
    ],
    resposta:
      'Depois de selecionar uma referência na tela Estoque, no fim da tabela de variantes tem o formulário **Adicionar variante**: preencha Cor, Tamanho e a quantidade inicial, e clique em adicionar. A variante nova entra na grade daquela referência, junto das demais.\n\nO EAN da variante nova pode ser gerado depois (ou preenchido na hora, editando o campo EAN na tabela) — e se um EAN pra essa combinação de cor/tamanho já tinha sido importado antes (ver o verbete de importar EAN), ele é aplicado automaticamente nessa variante recém-criada.',
    relacionados: ['estoque-ver-variantes-referencia', 'estoque-importar-ean'],
  },
  {
    id: 'estoque-movimentar-entrada-saida',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Registrar entrada ou saída de estoque de uma variante',
    rota: '/estoque',
    perguntas: [
      'como registro entrada de estoque',
      'como registro saida de estoque',
      'ajustar quantidade da variante',
      'dar entrada manual no estoque',
      'dar baixa no estoque manual',
      'motivo do movimento de estoque',
      'corrigir quantidade de uma variante',
      'aumentar estoque de uma cor e tamanho',
      'diminuir estoque manualmente',
    ],
    resposta:
      'Em cada linha da tabela de variantes, na coluna **Movimentar**, digite a quantidade, opcionalmente um motivo, e clique na seta pra cima (entrada) ou pra baixo (saída) — o ajuste é aplicado na hora, direto naquela variante.\n\nToda movimentação feita por aqui (assim como pela bipagem, importação de saldo etc.) fica registrada no histórico de movimentos da variante, com o tipo, a quantidade e a quantidade resultante — é o que permite auditar depois de onde veio cada mudança de estoque.',
    relacionados: ['estoque-bipagem', 'estoque-ver-variantes-referencia'],
  },
  {
    id: 'estoque-ativar-desativar-excluir-variante',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ativar, desativar ou excluir uma variante',
    rota: '/estoque',
    perguntas: [
      'como desativo uma variante',
      'variante inativa o que significa',
      'ativar variante de novo',
      'como excluo uma variante',
      'remover cor e tamanho do estoque',
      'nao consigo excluir variante',
      'variante ja vendida nao exclui',
      'apagar variante de estoque',
      'desativar cor descontinuada',
    ],
    resposta:
      'Cada variante tem um toggle **Ativa?** — desativar não apaga nada, só marca a variante como fora de uso (por exemplo, uma cor descontinuada); ela some das opções normalmente oferecidas mas o histórico continua existindo. A linha de uma variante inativa fica esmaecida na tabela.\n\nPra excluir de verdade, use o ícone de lixeira na linha — mas o sistema **não deixa excluir uma variante que já teve venda registrada** (ela fica bloqueada, com o histórico de movimentos junto). Se ela nunca foi vendida, a exclusão pede confirmação e também apaga o histórico de movimentos daquela variante.',
    relacionados: ['estoque-selecao-em-massa'],
  },
  {
    id: 'estoque-selecao-em-massa',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ativar, desativar ou excluir várias variantes de uma vez',
    rota: '/estoque',
    perguntas: [
      'ativar varias variantes de uma vez',
      'desativar em lote no estoque',
      'excluir varias variantes juntas',
      'selecionar todas as variantes da referencia',
      'marcar varias linhas no estoque',
      'acao em massa no estoque',
      'checkbox selecionar tudo estoque',
    ],
    resposta:
      'Na tabela de variantes de uma referência, marque as caixinhas das linhas desejadas (ou a do cabeçalho, pra selecionar todas as variantes daquela referência de uma vez) — aparece uma barra com **Ativar selecionadas**, **Desativar selecionadas** e **Excluir selecionadas**.\n\nA exclusão em lote segue a mesma regra da individual: variantes que já tiveram venda registrada não são excluídas, e o sistema avisa quantas foram excluídas e quais ficaram bloqueadas (com cor e tamanho de cada uma).',
    relacionados: ['estoque-ativar-desativar-excluir-variante'],
  },
  {
    id: 'estoque-corrigir-cor-tamanho-em-massa',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Corrigir um valor de cor ou tamanho em várias referências de uma vez',
    rota: '/estoque',
    perguntas: [
      'digitei a cor errada em varias referencias',
      'corrigir cor em massa',
      'corrigir tamanho em massa',
      'trocar azl por azul em tudo',
      'padronizar nome de cor',
      'ferramenta corrigir cor tamanho',
      'renomear cor em varias referencias de uma vez',
      'erro de digitacao na cor repetido',
    ],
    resposta:
      'O card **Corrigir cor/tamanho em massa**, no topo da tela Estoque, resolve o caso de um valor digitado errado (ex.: "Azl" em vez de "Azul") que se repetiu em várias referências diferentes — em vez de corrigir uma por uma.\n\nEscolha o campo (Cor ou Tamanho), digite o valor atual exato e clique em **Buscar** — aparece a lista de todas as variantes com esse valor, em qualquer referência. Digite o valor novo e clique em **Aplicar** pra corrigir todas de uma vez. Se alguma correção esbarrar numa variante que já existe com o valor novo na mesma referência, ela fica de fora e aparece listada como conflito, sem travar as demais.',
    relacionados: ['estoque-ver-variantes-referencia'],
  },
  {
    id: 'estoque-filtro-marketplace',
    modulo: 'estoque',
    tela: 'Estoque',
    titulo: 'Ver só as referências de marketplace no Estoque',
    rota: '/estoque',
    perguntas: [
      'filtrar estoque so marketplace',
      'ver so produtos de marketplace no estoque',
      'toggle marketplace no estoque',
      'estoque so das referencias do marketplace',
      'quantas referencias de marketplace tenho',
    ],
    resposta:
      'O toggle **Somente produtos do marketplace**, na tela Estoque, restringe tanto o seletor de referência quanto a busca geral às referências marcadas como "produto de marketplace" (esse marcador é definido na ficha de cada produto, ou em Configurações › Produtos de Marketplace). Ligado, ele mostra também quantas referências entram nesse filtro.\n\nÉ o mesmo marcador usado nas Fichas de Estoque em lote e no filtro da lista de Produtos — mudar aqui ou lá reflete em todos os lugares, porque é o mesmo campo do produto.',
    relacionados: ['produto-marketplace-selecionar', 'estoque-ficha-marketplace-lote'],
  },
  {
    id: 'estoque-bipagem',
    modulo: 'estoque',
    tela: 'Bipagem',
    titulo: 'Usar a bipagem (leitor de código de barras)',
    rota: '/estoque/bipagem',
    perguntas: [
      'como uso a bipagem',
      'bipar produto',
      'leitor de codigo de barras',
      'dar entrada bipando',
      'dar saida bipando',
      'bipagem nao encontra o ean',
      'estoque ficou negativo na bipagem',
      'quantidade por leitura na bipagem',
      'ultimas leituras da bipagem',
      'bipagem entrada ou saida',
    ],
    resposta:
      'Na tela **Bipagem**, escolha primeiro se a leitura vai ser **Entrada** ou **Saída**, defina a quantidade por leitura (padrão 1) e aponte o leitor de código de barras pro campo de EAN — cada leitura já ajusta o estoque daquela variante na hora, sem precisar confirmar nada mais.\n\nO card **Últimas leituras** mostra um histórico das últimas 30 leituras da sessão, com hora, tipo, EAN e o resultado (referência, cor, tamanho e nova quantidade) — leituras com erro (EAN não encontrado, por exemplo) aparecem destacadas em vermelho. Se uma saída deixar a quantidade negativa, aparece um aviso "Estoque ficou negativo!" junto da leitura, mas ela não é bloqueada por isso.',
    relacionados: ['estoque-movimentar-entrada-saida'],
  },
  {
    id: 'estoque-importar-saldo',
    modulo: 'estoque',
    tela: 'Importar Saldo',
    titulo: 'Importar saldo de estoque em massa',
    rota: '/estoque/importacao',
    perguntas: [
      'como importo saldo de estoque',
      'importar estoque do wiki sistemas',
      'importar relatorio de saldo',
      'importar csv de estoque',
      'importar pdf de saldo de estoque',
      'atualizar quantidade em lote',
      'planilha relest',
      'saldo de estoque em grade pdf',
      'referencia precisa existir pra importar estoque',
    ],
    resposta:
      'A tela **Importar Saldo** aceita o relatório de saldo do Wiki Sistemas em dois formatos: o CSV "relEst" (uma linha por referência + cor + tamanho) ou o PDF "Relatório - Saldo de estoque" (em grade, cor por tamanho). A referência já precisa estar cadastrada em Produtos — a importação atualiza/cria variantes, não produtos.\n\nAssim como na importação de produtos, primeiro clique em **Pré-visualizar** — a tela mostra as variantes que serão criadas, as que serão atualizadas (com a quantidade atual ao lado da nova, em negrito quando muda) e as linhas com erro, que ficam de fora. Só depois de conferir, **Confirmar importação** grava de verdade.',
    relacionados: ['estoque-importar-ean', 'produto-importacao-massa'],
  },
  {
    id: 'estoque-importar-ean',
    modulo: 'estoque',
    tela: 'Importar EAN',
    titulo: 'Importar EAN do sistema real (Wiki Sistemas)',
    rota: '/estoque/ean',
    perguntas: [
      'como importo ean',
      'importar codigo de barras em massa',
      'importar rellistaprod',
      'ean do wiki sistemas',
      'importar varios csv de ean de uma vez',
      'ean fica guardado pra quando a variante existir',
      'atualizar ean de variantes existentes',
      'importacao de ean aplica na hora',
    ],
    resposta:
      'A tela **Importar EAN** aceita um ou mais arquivos "relListaProd" do Wiki Sistemas (colunas REF, COR, TAM, EAN EXTERNO) — dá pra selecionar vários .csv de uma vez. Na prévia, aparecem dois blocos: variantes que **já existem** (o EAN delas será atualizado na hora ao confirmar) e combinações que **ainda não têm variante** cadastrada (o EAN fica guardado e é aplicado sozinho assim que a variante for criada, manual ou por importação de saldo).\n\nEsse é o mecanismo que garante que a bipagem sempre lê o EAN verdadeiro da etiqueta, mesmo quando o EAN chega antes de a variante existir no sistema.',
    relacionados: ['gloss-ean', 'estoque-adicionar-variante'],
  },
  {
    id: 'estoque-ficha-gerar',
    modulo: 'estoque',
    tela: 'Ficha de Estoque',
    titulo: 'Gerar e imprimir fichas de conferência de estoque',
    rota: '/estoque/ficha',
    perguntas: [
      'como gero ficha de estoque',
      'imprimir ficha de conferencia de estoque',
      'ficha de estoque por cor e tamanho',
      'exportar ficha de estoque em pdf',
      'quantas referencias posso gerar de ficha de estoque',
      'ficha de estoque pra contagem',
      'selecionar referencias pra ficha de estoque',
    ],
    resposta:
      'Na tela **Ficha de Estoque**, busque por referência, código ou descrição e clique em **Adicionar** nos resultados pra ir montando a seleção (sem limite fixo de quantidade — só um aviso, a partir de 80 fichas, de que gerar e imprimir pode demorar mais). Clique em **Gerar fichas** pra montar o documento: uma folha por referência, com uma tabela cor × tamanho de cada variante e a quantidade, mais o total de peças, custo total e valor total.\n\nCom as fichas geradas, o botão **Imprimir / Exportar PDF** abre a impressão do navegador. Referências sem custo cadastrado entram como zero nos totais de custo/valor, em vez de travar a geração.',
    relacionados: ['estoque-ficha-marketplace-lote', 'produto-ficha-tecnica-gerar'],
  },
  {
    id: 'estoque-ficha-marketplace-lote',
    modulo: 'estoque',
    tela: 'Ficha de Estoque',
    titulo: 'Gerar fichas de estoque de todo o lote de marketplace de uma vez',
    rota: '/estoque/ficha',
    perguntas: [
      'gerar ficha de todo o marketplace',
      'carregar todas as referencias do marketplace',
      'ficha de estoque do marketplace inteiro',
      'botao fichas do marketplace',
      'imprimir estoque de todos os produtos de marketplace',
      'ficha de estoque em lote grande',
    ],
    resposta:
      'O botão **Carregar todos do Marketplace**, na tela Ficha de Estoque, seleciona de uma vez todas as referências marcadas como produto de marketplace, sem precisar buscar e adicionar uma por uma. É o mesmo destino do link **Fichas do marketplace**, que aparece na lista de Produtos.\n\nEssa seleção especial (identificada como "lote completo do marketplace") é pedida ao servidor numa chamada só, em vez de listar cada referência na URL — é por isso que ela funciona mesmo com centenas de referências marcadas, diferente de montar a seleção manualmente.',
    relacionados: ['estoque-ficha-gerar', 'estoque-filtro-marketplace'],
  },
];
