// Verbetes do módulo Financeiro — as três abas de /financeiro
// (Movimentação, Repasses e Conferência, todas em FinanceiroPage.jsx).
// A linguagem aqui é a de quem cuida do caixa, não a de quem precifica: o
// assunto é dinheiro que entrou e saiu da conta, não margem nem custo.

export const verbetesFinanceiro = [
  {
    id: 'financeiro-movimentacao',
    modulo: 'financeiro',
    tela: 'Movimentação',
    titulo: 'Quanto o marketplace liberou, por data e plataforma',
    rota: '/financeiro/movimentacao',
    perguntas: [
      'quanto o marketplace pagou',
      'quanto foi liberado na conta',
      'quanto entrou de dinheiro',
      'movimentacao bancaria do periodo',
      'quanto a shopee me pagou',
      'quanto o mercado livre liberou',
      'quanto a tiktok repassou',
      'extrato do marketplace',
      'dinheiro liberado por data',
      'quanto caiu na conta em cada dia',
    ],
    resposta:
      'A aba **Movimentação** responde exatamente isso: escolha o período no filtro de data e a tabela **Liberado por data e plataforma** mostra, dia a dia, quanto cada marketplace liberou na conta — uma coluna por plataforma e o total do dia na última.\n\nO número vem do **extrato da própria plataforma**, não da soma dos pedidos. Por isso ele inclui o que não pertence a venda nenhuma: publicidade descontada, multa, ajuste, estorno de um pedido antigo e saque para o banco. O quadro **Para onde o dinheiro foi** separa esses tipos.\n\nO que ainda **não foi liberado** aparece à parte, no indicador "Ainda pendente" — nunca somado ao liberado, porque dinheiro retido ainda não é movimentação bancária.',
    relacionados: ['financeiro-filtros', 'financeiro-repasses', 'financeiro-conferencia'],
  },
  {
    id: 'financeiro-filtros',
    modulo: 'financeiro',
    tela: 'Movimentação',
    titulo: 'Escolher o que aparece na tela (Ads, devolução, taxas…)',
    rota: '/financeiro/movimentacao',
    perguntas: [
      'filtrar tipo de lancamento',
      'quanto gastei de ads',
      'quanto foi descontado de publicidade',
      'quanto voltou de devolucao',
      'quanto paguei de taxa',
      'ver so os estornos',
      'esconder lancamento do relatorio',
      'antecipacao de recebiveis',
    ],
    resposta:
      'O quadro **O que aparece na tela** tem uma caixinha por tipo de lançamento: repasse de venda, devolução/estorno, publicidade (Ads), taxas e multas, antecipação, ajustes, saque para o banco e outros. Desmarcar um tipo tira ele de tudo — tabela de datas, resumo e lista detalhada — então dá pra montar, por exemplo, "só o que a plataforma me cobrou no mês".\n\nOs outros filtros da barra são: **período**, **plataforma**, **loja**, **situação** (liberado, pendente ou os dois) e **com/sem pedido vinculado** — esse último é útil pra achar dinheiro que entrou sem venda por trás.\n\nQualquer combinação de filtro pode ser exportada em CSV ou Excel pelo botão **Exportar**.',
    relacionados: ['financeiro-movimentacao', 'financeiro-tipos'],
  },
  {
    id: 'financeiro-tipos',
    modulo: 'financeiro',
    tela: 'Movimentação',
    titulo: 'O que significa cada tipo de lançamento',
    rota: '/financeiro/movimentacao',
    perguntas: [
      'o que e repasse de venda',
      'o que e ajuste no extrato',
      'o que significa outros no financeiro',
      'tipo de lancamento desconhecido',
      'lancamento sem pedido',
    ],
    resposta:
      '**Repasse de venda** é o dinheiro do pedido, já líquido do que a plataforma cobrou. **Devolução/estorno** é valor que voltou pro cliente. **Publicidade (Ads)** é o que a plataforma descontou de anúncio. **Taxas e multas** são cobranças da plataforma que não são comissão de pedido. **Antecipação** é quando o dinheiro sai antes do prazo mediante taxa. **Saque para o banco** é a transferência do saldo. **Ajustes** são correções lançadas pela plataforma.\n\n**Outros** é proposital: quando a plataforma manda um rótulo que o sistema ainda não conhece, o lançamento entra como "outros" com a descrição original preservada na coluna Descrição — em vez de ser encaixado num tipo parecido e virar número errado com cara de certo.\n\nLançamento **sem pedido vinculado** é normal: multa, Ads e ajuste não têm pedido. Quando o lançamento tem um pedido que ainda não foi importado aqui, a coluna Pedido mostra a marca "externo".',
    relacionados: ['financeiro-filtros', 'financeiro-conferencia'],
  },
  {
    id: 'financeiro-repasses',
    modulo: 'financeiro',
    tela: 'Repasses',
    titulo: 'Conferir com o extrato bancário',
    rota: '/financeiro/repasses',
    perguntas: [
      'conferir com o extrato do banco',
      'quais transferencias o marketplace mandou',
      'repasse ainda nao caiu',
      'quando o dinheiro cai na conta',
      'valor da transferencia do marketplace',
    ],
    resposta:
      'Cada linha da aba **Repasses** é uma transferência da plataforma para a conta da empresa — é o nível que casa **uma pra uma** com o extrato bancário. A coluna Situação diz se o repasse já foi **pago**, está **processando** ou é **previsto**; os dois primeiros indicadores somam pago e não-pago separadamente, porque repasse em processamento ainda não caiu.\n\nA coluna **Lançamentos** mostra quantas linhas do extrato compõem aquele repasse — é o caminho pra abrir e ver de onde saiu o valor.',
    relacionados: ['financeiro-movimentacao', 'financeiro-conferencia'],
  },
  {
    id: 'financeiro-conferencia',
    modulo: 'financeiro',
    tela: 'Conferência',
    titulo: 'Por que o extrato não bate com a soma dos pedidos',
    rota: '/financeiro/conferencia',
    perguntas: [
      'extrato nao bate com os pedidos',
      'diferenca entre o que caiu e o que vendi',
      'conciliacao financeira',
      'sobra sem explicacao',
      'faltou dinheiro do marketplace',
      'conferir repasse com as vendas',
    ],
    resposta:
      'A aba **Conferência** põe lado a lado, por dia e por plataforma, duas leituras independentes: o **extrato** da plataforma e a **soma do valor recebido dos pedidos** liberados naquele dia.\n\nAs duas quase nunca são iguais — e isso normalmente **não é erro**. A diferença é justamente o que o extrato tem e a venda não: publicidade, multa, ajuste, estorno. Por isso a coluna que importa é a última, **Sobra sem explicação**: é o que resta depois de descontar esses lançamentos. Quando ela mostra "bate", o dia fechou.\n\nQuando um dos dois lados não existe, a linha mostra "não lido" ou "sem pedido" em vez de zero — de propósito: um zero passaria a impressão de que está batendo.',
    relacionados: ['financeiro-repasses', 'financeiro-sincronizar'],
  },
  {
    id: 'financeiro-sincronizar',
    modulo: 'financeiro',
    tela: 'Financeiro',
    titulo: 'Atualizar o extrato e por que o Mercado Livre demora',
    rota: '/financeiro/movimentacao',
    perguntas: [
      'atualizar o extrato',
      'puxar extrato agora',
      'extrato vazio',
      'nao aparece nada no financeiro',
      'relatorio de liberacoes do mercado pago',
      'por que o mercado livre demora',
    ],
    resposta:
      'O extrato é atualizado sozinho a cada 30 minutos, e o botão **Puxar extrato agora** força a leitura na hora.\n\nA Shopee e a TikTok Shop respondem na mesma chamada. O **Mercado Livre é diferente**: o extrato de lá é o Relatório de Liberações do Mercado Pago, que é **gerado sob encomenda** — o sistema pede, o Mercado Pago prepara o arquivo em alguns minutos e a leitura acontece na passada seguinte. Por isso a primeira carga do Mercado Livre costuma precisar de dois cliques com alguns minutos de intervalo, e a mensagem "relatório pedido" é o comportamento normal, não erro.\n\nSe alguma linha do extrato vier ilegível (sem data ou sem valor), aparece um aviso amarelo no topo dizendo quantas ficaram de fora — elas **não** entram no relatório como R$ 0,00, porque um zero escondido faz o total fechar errado sem ninguém perceber.',
    relacionados: ['financeiro-movimentacao', 'financeiro-conferencia'],
  },

  // --- Núcleo financeiro da empresa inteira (10/09/2026): pagar, receber,
  // ---------------------------------------------------------------------
  // Contas a Pagar (/financeiro/pagar)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-pagar-visao-geral',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'O que é a tela Contas a Pagar e o que significam bruto, retido e líquido',
    rota: '/financeiro/pagar',
    perguntas: [
      'contas a pagar',
      'o que e a tela de contas a pagar',
      'quanto eu devo',
      'total a pagar em aberto',
      'o que e valor bruto retido e liquido',
      'diferenca entre bruto e liquido do titulo',
      'quanto ainda falta pagar de um titulo',
      'saldo em aberto do titulo',
      'o que e o saldo do titulo a pagar',
      'onde ficam as contas da facção e do aluguel',
    ],
    resposta:
      'A tela **Contas a Pagar** reúne tudo que a empresa deve: facção, insumo, aluguel, guia de imposto. O título é a unidade básica, e ele guarda o valor **bruto** — a retenção e a baixa são registros à parte, exatamente para o líquido calculado e o razão do contador nunca discordarem.\n\nQuatro valores aparecem lado a lado em cada título: **bruto** é o valor do documento; **retido** é o que fica retido para o fisco; **líquido** é bruto menos retido — é sobre o líquido que a baixa acontece; **baixado** é quanto já foi pago; **saldo em aberto** é líquido menos baixado. Juros, multa e desconto lançados numa baixa não mexem em nenhum desses quatro: eles só mudam quanto saiu da conta naquela baixa.\n\nQuando um título não tem retenção, ou ainda não teve nenhuma baixa, o campo correspondente aparece como travessão — não como R$ 0,00 — porque a ausência de retenção e a ausência de baixa são informações diferentes de um valor zerado.',
    relacionados: ['financeiro-pagar-novo-titulo', 'financeiro-pagar-baixar', 'financeiro-pagar-indicadores-filtros'],
  },
  {
    id: 'financeiro-pagar-novo-titulo',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Como lançar um novo título a pagar',
    rota: '/financeiro/pagar',
    perguntas: [
      'como criar um titulo a pagar',
      'lancar uma conta a pagar nova',
      'novo titulo a pagar',
      'fornecedor sem cadastro no financeiro',
      'qual empresa escolher no titulo',
      'diferenca entre competencia e vencimento',
      'pra que serve a categoria do plano financeiro no titulo',
      'centro de custo no titulo a pagar',
      'documento do titulo pra que serve',
      'cadastrar guia de imposto como titulo',
    ],
    resposta:
      'O botão **Novo título a pagar** abre um formulário onde a **empresa (CNPJ)** é obrigatória — ela decide a retenção e a guia do título, então é a primeira dimensão que precisa ser escolhida. O **fornecedor** vem de um cadastro, mas quando o acesso do usuário não alcança o módulo Compras (fornecedor mora lá) o campo de nome livre assume: serve para lançar guia de imposto, tarifa bancária ou qualquer contraparte sem cadastro.\n\nA **categoria do plano financeiro** é o que leva o título até o **DRE** — sem categoria, o título simplesmente não aparece no resultado, nem como zero. O **centro de custo** é opcional. Duas datas têm papéis diferentes: **competência** é quando o fato aconteceu e é a data que o **DRE** usa; **vencimento** é quando o dinheiro deve andar e é a data que o **fluxo de caixa** usa — lançar as duas iguais por hábito pode fazer um relatório enxergar o título num mês em que o outro não enxerga.\n\nO valor lançado é sempre o **bruto**. Se o título tiver retenção ou precisar ser dividido entre categorias, isso é feito nos blocos de **Retenções** e **Rateio** do mesmo formulário, antes de gravar.',
    relacionados: ['financeiro-pagar-retencao', 'financeiro-pagar-rateio', 'financeiro-pagar-visao-geral', 'financeiro-dre-periodo-competencia'],
  },
  {
    id: 'financeiro-pagar-retencao',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Como funciona a retenção de tributo num título a pagar',
    rota: '/financeiro/pagar',
    perguntas: [
      'retencao de inss no titulo',
      'retencao de irrf',
      'iss retido no titulo',
      'o que e csrf',
      'retencao na facção com cessao de mao de obra',
      'aliquota da retencao',
      'titulo com imposto retido',
      'quanto e o inss de 11%',
      'informar o valor da retencao direto',
      'toda retencao precisa de tributo',
    ],
    resposta:
      'No formulário de novo título, o bloco **Retenções** permite acrescentar uma ou mais linhas, cada uma com um tributo: **INSS** (11% sobre facção com cessão de mão de obra), **IRRF**, **ISS**, **CSRF** (PIS/COFINS/CSLL) ou **outra retenção**. Cada linha diminui o líquido do título e vira uma obrigação com o fisco.\n\nO valor de cada retenção pode ser informado de duas formas: preenchendo a **alíquota** (em %, com o valor em branco — o sistema calcula alíquota × bruto), ou preenchendo o **valor** diretamente. O card "O que vai ser gravado", no fim do formulário, mostra o bruto, o retido somado e o líquido resultante antes de confirmar — é a mesma conta que o servidor faz, mostrada ali só para ninguém assinar um líquido que não esperava.\n\nSe nenhuma retenção for acrescentada, o líquido é igual ao bruto. E toda retenção lançada precisa ter um tributo escolhido — o formulário recusa gravar sem isso.',
    relacionados: ['financeiro-pagar-novo-titulo', 'financeiro-pagar-rateio'],
  },
  {
    id: 'financeiro-pagar-rateio',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Como dividir um título entre categorias ou centros de custo (rateio)',
    rota: '/financeiro/pagar',
    perguntas: [
      'dividir titulo entre categorias',
      'ratear conta de energia',
      'titulo com mais de uma categoria',
      'rateio de aluguel entre centros de custo',
      'dividir um titulo em varios centros de custo',
      'o percentual do rateio nao fecha',
      'pra onde vai a sobra do rateio',
      'titulo sem rateio fica em qual categoria',
    ],
    resposta:
      'O bloco **Rateio**, no formulário de novo título, serve para um título só (energia, aluguel, contador) ser dividido entre mais de uma categoria do plano financeiro ou mais de um centro de custo. Cada linha de rateio tem categoria, centro de custo e um **percentual**; a coluna "Dá em" mostra, em tempo real, quanto daquele percentual representa em reais sobre o valor bruto.\n\nA soma dos percentuais precisa fechar em 100% — quando não fecha, um aviso mostra a soma atual e explica que **a diferença cai inteira na última linha do rateio**, para a soma sempre bater com o bruto. Vale ajustar os percentuais manualmente se esse comportamento automático não for o que se quer.\n\nSem nenhuma linha de rateio, o título inteiro fica na categoria e no centro de custo escolhidos no cabeçalho do formulário — não é preciso ratear títulos que pertencem a uma categoria só.',
    relacionados: ['financeiro-pagar-novo-titulo', 'financeiro-pagar-retencao'],
  },
  {
    id: 'financeiro-pagar-baixar',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Como baixar (pagar) um título e a simulação de juros e multa',
    rota: '/financeiro/pagar',
    perguntas: [
      'como pagar um titulo',
      'baixar uma conta a pagar',
      'simular juros e multa do atraso',
      'calcular encargos de um titulo vencido',
      'quanto fica um titulo com multa e juros',
      'juros pro rata die',
      'tarifa bancaria na baixa',
      'desconto na baixa de um titulo',
      'de onde sai o dinheiro quando pago um titulo',
      'a baixa muda o saldo do titulo',
    ],
    resposta:
      'O botão **Pagar**, disponível em qualquer título com saldo em aberto, abre o formulário de baixa. Só o campo **Principal** abate o saldo do título — os campos **Juros**, **Multa**, **Desconto** e **Tarifa** mudam apenas quanto sai da conta bancária escolhida naquela baixa, não quanto o título devia.\n\nO card "Quanto ficaria com os encargos" traz uma **simulação calculada pelo servidor**, de propósito: multa incide uma vez sobre o saldo e juros correm pro rata die (por dia corrido), contados do vencimento até a data da baixa escolhida — repetir essa conta na tela seria o caminho mais curto para a tela e o banco discordarem em um centavo. As alíquotas de multa e juros ao mês são ajustáveis antes de simular, e o botão "Usar multa e juros da simulação" preenche os campos automaticamente; nada é gravado até a baixa ser confirmada. Quando não há atraso na data escolhida, a simulação devolve o próprio saldo, sem multa nem juros.\n\nA baixa também pede a **conta** de onde o dinheiro sai e a **data da baixa** — essa é a data de caixa, a mesma que o extrato e o fluxo de caixa usam.',
    relacionados: ['financeiro-pagar-visao-geral', 'financeiro-pagar-cancelar-estornar', 'financeiro-conciliacao-titulo'],
  },
  {
    id: 'financeiro-pagar-cancelar-estornar',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Cancelar um título ou estornar uma baixa já feita',
    rota: '/financeiro/pagar',
    perguntas: [
      'cancelar um titulo a pagar',
      'titulo lancado errado como cancelar',
      'estornar um pagamento',
      'desfazer uma baixa',
      'pagamento devolvido pelo banco',
      'motivo do cancelamento do titulo',
      'titulo cancelado ainda aparece na lista',
      'estorno de baixa o que acontece',
      'apagar um titulo',
    ],
    resposta:
      'Cancelar um título (ícone de proibido, na lista) exige escrever o **motivo** — o formulário não deixa cancelar sem isso. Um título cancelado sai do fluxo de caixa e do DRE e não recebe mais baixa, mas continua aparecendo na lista, com o motivo registrado: nada é apagado, para o histórico continuar explicando o que houve.\n\nJá o **estorno** é de uma baixa específica, feita dentro do detalhe do título, na lista "Histórico de baixas". Também exige motivo. Estornar não apaga a baixa original: grava um **lançamento novo com os valores negativos** — e, se aquela baixa tinha um lançamento do extrato bancário conciliado com ela, esse lançamento **volta a ficar pendente** na Conciliação Bancária.\n\nUma baixa que já é ela mesma um estorno, ou que já foi estornada, não pode ser estornada de novo — a lista mostra a marca "estorno" ou "estornada" em vez do botão.',
    relacionados: ['financeiro-pagar-baixar', 'financeiro-conciliacao-titulo'],
  },
  {
    id: 'financeiro-pagar-indicadores-filtros',
    modulo: 'financeiro',
    tela: 'Contas a Pagar',
    titulo: 'Os quatro indicadores e os filtros de situação de Contas a Pagar',
    rota: '/financeiro/pagar',
    perguntas: [
      'total em aberto a pagar',
      'o que vence essa semana no financeiro',
      'maior atraso de pagamento',
      'titulos vencidos a pagar',
      'filtrar so os vencidos',
      'situacao do titulo previsto aberto parcial liquidado cancelado',
      'buscar titulo por documento ou contraparte',
      'exportar contas a pagar',
    ],
    resposta:
      'A faixa no topo mostra quatro números, sempre calculados sobre o que está na tela naquele momento — mudar um filtro muda os quatro juntos: **total em aberto** (soma do saldo ainda não baixado, exclui cancelado e liquidado), **já vencido** (títulos com saldo que passaram do vencimento — é a fila que gera juros e multa), **vence nos próximos 7 dias** (o dinheiro que precisa estar em conta nesta semana) e **maior atraso** (o título mais antigo ainda em aberto, com sua contraparte e valor). Quando um indicador não tem nada para mostrar, aparece travessão — não é o mesmo que zero.\n\nO filtro de **situação** tem seis opções: previsto, em aberto, baixado em parte, liquidado, cancelado, ou todas juntas; o padrão da tela é "ainda em aberto" (previsto + aberto + parcial), porque é a pergunta de todo dia. Há também filtro de **empresa**, **período de vencimento** e a caixa **só vencidos**.\n\nA busca livre procura por **descrição, documento ou nome da contraparte**, e qualquer recorte de filtros pode ser exportado pelo botão **Exportar**.',
    relacionados: ['financeiro-pagar-visao-geral'],
  },

  // ---------------------------------------------------------------------
  // Contas a Receber (/financeiro/receber)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-receber-visao-geral',
    modulo: 'financeiro',
    tela: 'Contas a Receber',
    titulo: 'O que é a tela Contas a Receber',
    rota: '/financeiro/receber',
    perguntas: [
      'contas a receber',
      'quanto tenho a receber',
      'total a receber em aberto',
      'o que a empresa vai receber',
      'titulo a receber vencido',
      'diferenca entre a tela de pagar e a de receber',
      'maior atraso de recebimento',
      'venceu essa semana a receber',
    ],
    resposta:
      'A tela **Contas a Receber** é, na prática, a mesma mecânica de **Contas a Pagar** — mesmo formulário, mesma tabela, mesmos quatro indicadores — só que para o dinheiro que a empresa tem a receber. A contraparte de cada título é o **cliente** em vez do fornecedor, mas bruto, retido, líquido, baixado e saldo em aberto significam exatamente a mesma coisa, e a baixa continua acontecendo sobre o líquido.\n\nOs quatro indicadores da faixa superior mudam só de rótulo: **total em aberto a receber**, **já vencido**, **vence nos próximos 7 dias** e **maior atraso** — cada um somado sobre o recorte de filtros ativo na tela, nunca sobre a base inteira.\n\nO filtro de situação, a busca e a exportação funcionam do mesmo jeito descrito para Contas a Pagar.',
    relacionados: ['financeiro-pagar-visao-geral', 'financeiro-receber-novo-titulo', 'financeiro-receber-baixar'],
  },
  {
    id: 'financeiro-receber-novo-titulo',
    modulo: 'financeiro',
    tela: 'Contas a Receber',
    titulo: 'Como lançar um novo título a receber',
    rota: '/financeiro/receber',
    perguntas: [
      'criar um titulo a receber',
      'lancar uma venda no financeiro',
      'cliente sem cadastro no financeiro',
      'novo titulo pra um cliente',
      'titulo de uma venda propria fora do marketplace',
      'empresa do titulo a receber',
      'categoria do plano financeiro num titulo a receber',
      'competencia e vencimento no titulo a receber',
    ],
    resposta:
      'O botão **Novo título a receber** abre o mesmo formulário de Contas a Pagar, com a contraparte sendo o **cliente**. O cadastro de clientes mora no módulo Vendas — quem tem acesso só ao Financeiro recebe 403 ao tentar carregar essa lista, e a tela reage caindo no campo de **nome livre** da contraparte, com aviso explicando isso no próprio formulário.\n\nAssim como em Contas a Pagar, a **empresa (CNPJ)** é obrigatória, a **categoria do plano financeiro** é o que leva o título ao DRE, e **competência** (usada pelo DRE) e **vencimento** (usado pelo fluxo de caixa) são datas distintas. Retenção e rateio funcionam com a mesma mecânica — um cliente pode reter imposto sobre a nota, por exemplo, e isso se lança do mesmo jeito que uma retenção de fornecedor.',
    relacionados: ['financeiro-pagar-novo-titulo', 'financeiro-pagar-retencao', 'financeiro-pagar-rateio'],
  },
  {
    id: 'financeiro-receber-baixar',
    modulo: 'financeiro',
    tela: 'Contas a Receber',
    titulo: 'Como baixar (receber) um título a receber',
    rota: '/financeiro/receber',
    perguntas: [
      'como receber um titulo',
      'dar baixa numa conta a receber',
      'o cliente pagou como registro',
      'registrar um recebimento',
      'em qual conta o dinheiro entrou',
      'juros por atraso do cliente',
      'simular multa de um cliente atrasado',
      'cancelar um titulo a receber',
    ],
    resposta:
      'Em Contas a Receber o mesmo botão de baixa aparece com o rótulo **Receber**, e o formulário é idêntico ao de Contas a Pagar: só o campo **Principal** abate o saldo do título; **Juros**, **Multa**, **Desconto** e **Tarifa** só mudam quanto entra na conta escolhida, não o saldo do título. A simulação de encargos do servidor (multa uma vez, juros pro rata die desde o vencimento) também está disponível aqui — útil quando um cliente paga com atraso.\n\nA **conta** escolhida é a conta bancária onde o dinheiro entra, e a **data da baixa** é a data de caixa usada pelo extrato e pelo fluxo de caixa. Os detalhes de cancelamento e estorno funcionam do mesmo jeito descritos para Contas a Pagar.',
    relacionados: ['financeiro-pagar-baixar', 'financeiro-pagar-cancelar-estornar'],
  },

  // ---------------------------------------------------------------------
  // Conciliação Bancária (/financeiro/conciliacao-bancaria)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-conciliacao-o-que-e',
    modulo: 'financeiro',
    tela: 'Conciliação Bancária',
    titulo: 'Para que serve a Conciliação Bancária e os três destinos de cada lançamento',
    rota: '/financeiro/conciliacao-bancaria',
    perguntas: [
      'o que e conciliacao bancaria',
      'conciliar o extrato do banco',
      'casar o extrato com os titulos',
      'lancamento pendente no banco',
      'o extrato nao bate com o sistema',
      'o que fazer com um lancamento do extrato',
      'pra que serve essa tela de conciliacao',
      'lancamento do ofx que nao virou nada',
      'linha do extrato que sumiu',
    ],
    resposta:
      'A **Conciliação Bancária** existe para casar o que o **banco** diz que aconteceu (o extrato) com o que o sistema já tinha registrado. O extrato fica separado das baixas de propósito — um extrato que já nascesse casado com elas não conciliaria nada.\n\nCada linha do extrato que ainda está **pendente** tem exatamente três destinos possíveis, e nenhum outro: **é um título** (conciliar gera a baixa, com a data e a conta do próprio banco), **não é título nenhum** — como tarifa ou rendimento (classifica numa categoria do plano financeiro) ou **é dinheiro próprio mudando de conta** (marca como transferência, ligando os dois lados).\n\nQuando uma linha do arquivo OFX não dá para interpretar, ela **não vira zero e não some** — volta na lista de avisos da importação, para ser conferida uma a uma.',
    relacionados: ['financeiro-conciliacao-importar-ofx', 'financeiro-conciliacao-titulo', 'financeiro-conciliacao-classificar', 'financeiro-conciliacao-transferencia'],
  },
  {
    id: 'financeiro-conciliacao-importar-ofx',
    modulo: 'financeiro',
    tela: 'Conciliação Bancária',
    titulo: 'Como importar o extrato OFX do banco',
    rota: '/financeiro/conciliacao-bancaria',
    perguntas: [
      'importar extrato ofx',
      'mandar o arquivo do banco',
      'importar o extrato duas vezes',
      'arquivo ofx duplicado',
      'quantos lancamentos vieram no arquivo',
      'avisos da importacao do extrato',
      'saldo final informado pelo banco',
      'reimportar o mesmo mes',
    ],
    resposta:
      'A importação exige escolher a **conta bancária** primeiro; o botão fica desabilitado até isso. O arquivo aceito é o **OFX** que o próprio banco exporta — ele é lido no navegador e enviado ao servidor.\n\n**Reimportar o mesmo mês é normal e esperado**: um lançamento repetido é reconhecido e ignorado, não duplicado. Depois de importar, um card mostra quatro números — lançamentos **lidos**, **novos** (os que ficam pendentes na lista logo abaixo), **repetidos** (já existiam, não geraram nada novo) e **avisos** — mais o período do arquivo e, quando o banco informa, o **saldo final**.\n\nCada aviso é dinheiro que existe no arquivo e ficou de fora da lista, ou uma repetição que pode ser duplicidade de verdade — nada disso vira zero em silêncio, porque um extrato que parece ter fechado sem ter fechado é pior do que um aviso visível.',
    relacionados: ['financeiro-conciliacao-o-que-e'],
  },
  {
    id: 'financeiro-conciliacao-titulo',
    modulo: 'financeiro',
    tela: 'Conciliação Bancária',
    titulo: 'Conciliar um lançamento do extrato com um título em aberto',
    rota: '/financeiro/conciliacao-bancaria',
    perguntas: [
      'ligar um lancamento a um titulo',
      'sugestao de titulo pro pagamento do extrato',
      'titulo parecido com o valor do banco',
      'conciliar automaticamente um lancamento',
      'diferenca de valor na conciliacao',
      'lancamento maior que o saldo do titulo',
      'a conciliacao gera a baixa',
      'nenhum titulo parecido no extrato',
    ],
    resposta:
      'Ao clicar em **Conciliar** numa linha pendente, a primeira seção do painel mostra **sugestões de títulos em aberto** que podem ser aquele lançamento — títulos a pagar quando o lançamento é uma saída, a receber quando é entrada, ordenados do valor mais próximo para o mais distante e depois pela data, dentro de uma janela de até 30 dias de vencimento a partir da data do lançamento.\n\nCada sugestão mostra o saldo em aberto do título e a diferença de valor e de dias em relação ao lançamento. Conciliar **gera a baixa do título com a data e a conta do próprio lançamento bancário**. Quando o valor do lançamento é maior que o saldo do título sugerido, o botão de conciliar some e aparece "maior que o saldo" — porque o servidor recusaria uma baixa maior que o que o título ainda deve.\n\nSe nenhum título em aberto aparecer, o título ainda não foi lançado ou aquele dinheiro não é título nenhum — nesse segundo caso, o caminho é a classificação por categoria, na seção seguinte do mesmo painel.',
    relacionados: ['financeiro-conciliacao-o-que-e', 'financeiro-pagar-baixar'],
  },
  {
    id: 'financeiro-conciliacao-classificar',
    modulo: 'financeiro',
    tela: 'Conciliação Bancária',
    titulo: 'Classificar um lançamento do extrato que não é título (tarifa, rendimento)',
    rota: '/financeiro/conciliacao-bancaria',
    perguntas: [
      'tarifa bancaria no extrato',
      'rendimento de aplicacao financeira',
      'iof no extrato',
      'lancamento sem titulo no banco',
      'categoria de um lancamento bancario',
      'classificar lancamento direto no dre',
      'lancamento que nao e titulo nenhum',
      'segunda opcao da tela de conciliar',
    ],
    resposta:
      'Quando um lançamento do extrato não corresponde a nenhum título — caso típico de tarifa bancária, rendimento de aplicação ou IOF —, a segunda seção do painel de conciliação permite **classificá-lo numa categoria do plano financeiro** diretamente, sem passar por um título.\n\nA categoria escolhida é o que leva esse valor até o lugar certo do **DRE**. Depois de classificado, o lançamento passa a mostrar o rótulo "Classificado" na lista do extrato, junto do nome da categoria.',
    relacionados: ['financeiro-conciliacao-o-que-e', 'financeiro-conciliacao-titulo'],
  },
  {
    id: 'financeiro-conciliacao-transferencia',
    modulo: 'financeiro',
    tela: 'Conciliação Bancária',
    titulo: 'Marcar um lançamento como transferência entre contas próprias',
    rota: '/financeiro/conciliacao-bancaria',
    perguntas: [
      'transferencia entre contas proprias',
      'dinheiro que sai de uma conta e entra em outra',
      'ligar o par da transferencia',
      'evitar contar a mesma transferencia duas vezes',
      'transferencia nao aparece nos candidatos',
      'saque para outro banco no extrato',
      'janela de sete dias da transferencia',
      'terceira opcao da tela de conciliar',
    ],
    resposta:
      'A terceira seção do painel de conciliação serve para quando o mesmo dinheiro só mudou de conta — uma transferência entre contas da própria empresa aparece **duas vezes** no extrato, débito numa conta e crédito noutra. Ligar o par é o que impede esse dinheiro de ser contado duas vezes no resultado.\n\nOs candidatos mostrados são lançamentos de **outra conta**, com **sinal contrário**, **mesmo valor** e dentro de uma janela de **sete dias** ao redor da data — a janela existe porque uma transferência entre bancos diferentes pode levar até isso para aparecer nos dois extratos. Se os dois lados ainda não foram importados, nenhum candidato aparece.\n\nUm lançamento marcado como transferência continua listado com o filtro "só pendentes" desligado, mas não gera baixa nem categoria — ele só liga os dois lados um ao outro.',
    relacionados: ['financeiro-conciliacao-o-que-e', 'financeiro-conciliacao-importar-ofx'],
  },

  // ---------------------------------------------------------------------
  // DRE Gerencial (/financeiro/dre)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-dre-o-que-e',
    modulo: 'financeiro',
    tela: 'DRE Gerencial',
    titulo: 'O que é o DRE Gerencial e em que ele difere da contabilidade',
    rota: '/financeiro/dre',
    perguntas: [
      'o que e o dre gerencial',
      'dre nao e contabil',
      'pra que serve o dre',
      'resultado do periodo',
      'margem de contribuicao o que e',
      'demonstrativo de resultado do exercicio',
      'diferenca entre dre gerencial e contabil',
      'so entra titulo firme no dre',
      'transferencia entra no dre',
    ],
    resposta:
      'O **DRE Gerencial** não é um demonstrativo contábil — é um plano **gerencial**, pensado para responder três perguntas que a contabilidade formal só responde tarde demais: quanto sobra de cada real vendido depois do custo que varia com a venda (**margem de contribuição**), quanto a estrutura custa por mês, venda-se muito ou pouco (**despesas fixas**), e quanto seria preciso faturar para o resultado zerar (**ponto de equilíbrio**).\n\nO cálculo é por **competência** — quando o fato aconteceu, não quando o dinheiro andou. Só título **firme** entra no resultado: título em situação **previsto** e **cancelado** ficam de fora, e uma transferência entre contas próprias nunca entra, porque mover dinheiro de bolso não é receita nem despesa.',
    relacionados: ['financeiro-dre-estrutura-linhas', 'financeiro-dre-variavel-fixo', 'financeiro-dre-ponto-equilibrio', 'financeiro-dre-periodo-competencia'],
  },
  {
    id: 'financeiro-dre-estrutura-linhas',
    modulo: 'financeiro',
    tela: 'DRE Gerencial',
    titulo: 'Como está organizada a estrutura de linhas do DRE (receita, variáveis, margem, fixas, resultado)',
    rota: '/financeiro/dre',
    perguntas: [
      'estrutura de linhas do dre',
      'como e organizado o relatorio de resultado',
      'grupos do dre',
      'codigo do plano financeiro no dre',
      'como as categorias sao agrupadas no dre',
      'peso da categoria sobre a receita',
      'porcentagem sobre a receita no dre',
      'o que e o codigo raiz do plano',
    ],
    resposta:
      'O DRE agrupa as categorias analíticas do plano financeiro pelo **código-raiz** — por exemplo, o código 2.3 entra no grupo 2 — porque é assim que o plano foi desenhado para ser lido no relatório. A demonstração aparece na ordem: **Receita** (por grupo, com o total geral logo abaixo), **Custos e despesas variáveis**, a linha calculada **= Margem de Contribuição**, **Despesas fixas**, a linha calculada **= Resultado do período** e, por fim, o **Ponto de equilíbrio**.\n\nCada linha mostra o valor no período e o **peso sobre a receita** — o percentual daquela linha em relação à receita total. Quando não há receita lançada no período, esse peso aparece como travessão, não como 0%: é uma conta sem denominador, não um percentual nulo.',
    relacionados: ['financeiro-dre-o-que-e', 'financeiro-dre-variavel-fixo'],
  },
  {
    id: 'financeiro-dre-variavel-fixo',
    modulo: 'financeiro',
    tela: 'DRE Gerencial',
    titulo: 'Como o sistema decide se uma categoria é custo variável ou despesa fixa',
    rota: '/financeiro/dre',
    perguntas: [
      'o que e custo variavel no dre',
      'o que e despesa fixa no dre',
      'diferenca entre variavel e fixo',
      'categoria marcada errada no plano financeiro',
      'de onde vem a margem de contribuicao',
      'onde marca se uma categoria e variavel',
      'facção entra como custo variavel',
      'aluguel entra como despesa fixa',
    ],
    resposta:
      'A separação entre **variável** e **fixo** vem de uma marcação feita em cada categoria do **plano financeiro**, não de uma regra calculada dentro do DRE — e é essa marcação que sustenta tanto a margem de contribuição quanto o ponto de equilíbrio.\n\n**Variável** é o que só existe porque houve venda: comissão de marketplace, frete, imposto sobre venda, matéria-prima, facção. **Fixo** é o que a estrutura custa venda-se muito ou pouco: aluguel, salário, contador, software, tarifa.\n\nUma categoria marcada no grupo errado muda a margem de contribuição e o ponto de equilíbrio **sem mudar nenhum lançamento** — o número que aparece na tela depende de onde essa categoria está classificada no cadastro do plano, não só de quanto foi lançado nela.',
    relacionados: ['financeiro-dre-estrutura-linhas', 'financeiro-dre-ponto-equilibrio'],
  },
  {
    id: 'financeiro-dre-ponto-equilibrio',
    modulo: 'financeiro',
    tela: 'DRE Gerencial',
    titulo: 'O que é o ponto de equilíbrio do DRE e quando ele não existe',
    rota: '/financeiro/dre',
    perguntas: [
      'o que e ponto de equilibrio',
      'quanto preciso faturar pra nao ter prejuizo',
      'ponto de equilibrio nao aparece',
      'por que nao tem ponto de equilibrio no periodo',
      'margem de contribuicao negativa no dre',
      'ponto de equilibrio zerado',
      'sem receita no periodo o ponto de equilibrio existe',
      'quanto preciso vender pra empatar',
    ],
    resposta:
      'O **ponto de equilíbrio** é o faturamento que, no mesmo mix de produtos vendido no período, faria o resultado ser **exatamente zero**. Acima desse valor, cada real vendido passa a virar resultado positivo na proporção da margem de contribuição; a tela não diz se esse ponto está perto ou longe do que a empresa faturou — só mostra o número.\n\nQuando a margem de contribuição do período está **zerada ou negativa**, ou quando não há receita lançada, o ponto de equilíbrio **não existe** matematicamente, e a tela escreve isso por extenso em vez de mostrar um zero — um zero ali passaria a falsa impressão de que bastaria faturar nada para empatar. O aviso que aparece nesse caso explica que, sem denominador (sem receita) ou com margem que não sobra nada por real vendido, o cálculo simplesmente não tem resultado a mostrar.',
    relacionados: ['financeiro-dre-variavel-fixo', 'financeiro-dre-estrutura-linhas'],
  },
  {
    id: 'financeiro-dre-periodo-competencia',
    modulo: 'financeiro',
    tela: 'DRE Gerencial',
    titulo: 'Por que o DRE trabalha por mês de competência inteiro',
    rota: '/financeiro/dre',
    perguntas: [
      'dre com periodo no meio do mes',
      'o faturamento sumiu no dre',
      'por que o mes esta incompleto no dre',
      'o periodo do dre nao bate com o esperado',
      'preciso comecar o dre no dia 1',
      'titulo sem categoria nao aparece no dre',
      'periodo do dre corta o mes',
      'aviso amarelo no dre sobre o periodo',
    ],
    resposta:
      'O DRE agrupa cada título pelo **mês de competência inteiro** — a view por trás do relatório usa sempre o dia 1º do mês da competência de cada título. Por isso, quando o período do filtro começa no meio de um mês, esse mês inteiro fica de fora do relatório: um aviso amarelo aparece explicando que não é o faturamento que sumiu, e que começar o período no dia 1º traz o mês completo de volta.\n\nOutro ponto que muda o que aparece: um título **sem categoria** do plano financeiro preenchida não entra no DRE — nem como zero, nem como linha vazia. Ele simplesmente não tem lugar no resultado até ganhar uma categoria.',
    relacionados: ['financeiro-dre-o-que-e', 'financeiro-pagar-novo-titulo'],
  },

  // ---------------------------------------------------------------------
  // Fluxo de Caixa (/financeiro/fluxo-caixa)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-fluxo-o-que-e',
    modulo: 'financeiro',
    tela: 'Fluxo de Caixa',
    titulo: 'O que é o Fluxo de Caixa e a pergunta que ele responde',
    rota: '/financeiro/fluxo-caixa',
    perguntas: [
      'o que e o fluxo de caixa',
      'previsto e realizado no fluxo de caixa',
      'quando o caixa fica negativo',
      'projecao de caixa',
      'fluxo de caixa dia a dia',
      'ate quando o caixa aguenta',
      'previsto e realizado somados',
      'qual periodo o fluxo de caixa mostra',
    ],
    resposta:
      'O **Fluxo de Caixa** existe para responder uma única pergunta: **quando o caixa fica negativo**. Tudo o mais na tela — as duas linhas do gráfico, a tabela dia a dia — está ali para explicar por que a resposta é aquela.\n\nDuas ideias sustentam a tela e nunca se misturam: **previsto** é título em aberto pela data de **vencimento**; **realizado** é baixa pela data em que o dinheiro **andou**. Os dois nunca são somados — somados, o mesmo título entraria duas vezes no resultado.\n\nO período padrão vai de hoje até 90 dias à frente, mas pode ser ajustado livremente (inclusive para o futuro, já que é uma projeção) e filtrado por empresa.',
    relacionados: ['financeiro-fluxo-saldo-acumulado', 'financeiro-fluxo-tabela-dia-a-dia', 'financeiro-fluxo-indicadores'],
  },
  {
    id: 'financeiro-fluxo-saldo-acumulado',
    modulo: 'financeiro',
    tela: 'Fluxo de Caixa',
    titulo: 'Como o saldo acumulado projetado é calculado',
    rota: '/financeiro/fluxo-caixa',
    perguntas: [
      'como e calculado o saldo acumulado',
      'de onde parte a projecao do fluxo de caixa',
      'saldo atual das contas no fluxo',
      'por que o realizado nao entra no acumulado',
      'grafico de barras vermelhas do fluxo',
      'o acumulado conta duas vezes o dinheiro',
      'por que a barra do fluxo fica vermelha',
      'saldo inicial das contas no fluxo',
    ],
    resposta:
      'O saldo acumulado projetado parte do **saldo atual das contas** — o saldo inicial de cada conta mais tudo que já entrou e saiu segundo o extrato bancário importado — e soma, dia após dia, **só o previsto** (títulos em aberto pelo vencimento).\n\nO **realizado não é somado de novo** porque ele já está dentro do saldo atual das contas: somá-lo outra vez contaria o mesmo dinheiro duas vezes e adiantaria artificialmente o dia em que o acumulado apareceria negativo.\n\nNo gráfico de barras do saldo acumulado, cada barra representa o saldo projetado ao fim daquele dia; a barra fica vermelha quando esse saldo é negativo — a cor vem direto do sinal do número, sem depender de legenda.',
    relacionados: ['financeiro-fluxo-o-que-e', 'financeiro-fluxo-tabela-dia-a-dia'],
  },
  {
    id: 'financeiro-fluxo-tabela-dia-a-dia',
    modulo: 'financeiro',
    tela: 'Fluxo de Caixa',
    titulo: 'Como ler a tabela dia a dia do fluxo de caixa',
    rota: '/financeiro/fluxo-caixa',
    perguntas: [
      'tabela do fluxo de caixa',
      'dia sem movimento nao aparece no fluxo',
      'previsto a receber e a pagar no dia',
      'recebido e pago no fluxo de caixa',
      'primeiro dia negativo do fluxo',
      'linhas vazias no fluxo de caixa',
      'travessao na tabela do fluxo de caixa',
      'o que significa cada coluna da tabela do fluxo',
    ],
    resposta:
      'A tabela "Dia a dia" só lista datas que **tiveram movimento** — dia sem título vencendo e sem baixa acontecendo não entra como linha vazia, porque uma tabela de 90 linhas em branco esconderia justamente os dias que importam.\n\nCada linha traz **previsto a receber** e **previsto a pagar** (soma do saldo dos títulos que vencem naquele dia), o **previsto no dia** (a diferença líquida), **recebido** e **pago** (baixas ocorridas naquele dia, o realizado), o **realizado no dia** e o **saldo acumulado**. Um travessão numa célula significa que não houve nada daquele tipo no dia — não que o valor foi zero.\n\nA linha correspondente ao **primeiro dia em que o acumulado fica negativo** recebe um destaque visual e a marcação "primeiro dia negativo" ao lado do valor.',
    relacionados: ['financeiro-fluxo-saldo-acumulado', 'financeiro-fluxo-o-que-e'],
  },
  {
    id: 'financeiro-fluxo-indicadores',
    modulo: 'financeiro',
    tela: 'Fluxo de Caixa',
    titulo: 'Os indicadores da faixa superior do Fluxo de Caixa',
    rota: '/financeiro/fluxo-caixa',
    perguntas: [
      'saldo de onde a projecao parte',
      'previsto a receber no fluxo de caixa',
      'previsto a pagar no fluxo de caixa',
      'saldo projetado no fim do periodo',
      'indicador quando o caixa fica negativo',
      'nenhum dia negativo no periodo',
      'de onde vem o saldo de partida do fluxo',
      'filtrar o fluxo de caixa por empresa',
    ],
    resposta:
      'A faixa de indicadores traz cinco números: **saldo de onde a projeção parte** (a soma do saldo atual de todas as contas, ou só da empresa filtrada); **previsto a receber** e **previsto a pagar** (soma do saldo em aberto dos títulos que vencem dentro do período escolhido — não é o que já entrou ou saiu, é o que está programado); **saldo projetado no fim do período** (o saldo de partida mais tudo o que está previsto até o último dia); e **quando o caixa fica negativo**, que mostra a primeira data em que o acumulado projetado é negativo.\n\nQuando o acumulado não fica negativo em nenhum dia do período, esse último indicador mostra travessão — de propósito: não é que o valor seja zero, é que não existe dia negativo a apontar dentro do recorte escolhido.',
    relacionados: ['financeiro-fluxo-o-que-e', 'financeiro-fluxo-saldo-acumulado'],
  },

  // ---------------------------------------------------------------------
  // Caixa de Entrada (/financeiro/entradas)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-entradas-o-que-e',
    modulo: 'financeiro',
    tela: 'Caixa de Entrada',
    titulo: 'O que é a Caixa de Entrada do Financeiro e por que ela não tem filtro de data',
    rota: '/financeiro/entradas',
    perguntas: [
      'o que e a caixa de entrada do financeiro',
      'fila de pendencias financeiras',
      'compromisso que a operacao gerou',
      'pendencia sem titulo ainda',
      'por que nao tem filtro de periodo na caixa de entrada',
      'o que a operacao comprometeu',
      'pendencia de facção sem valor',
      'a caixa de entrada mostra pendencia antiga',
    ],
    resposta:
      'A **Caixa de Entrada** é a fila de trabalho do Financeiro: o que a operação já comprometeu — numa facção, numa compra, numa devolução — e que ainda não virou **título** em Contas a Pagar ou a Receber. Ela existe porque a resposta certa (quanto vai custar, por exemplo) nem sempre está disponível no momento em que a mercadoria sai; o que não podia continuar era a pergunta não ser feita a ninguém.\n\nA lista **nasce sem recorte de data de propósito**: "o que a operação comprometeu e ninguém resolveu" é uma pergunta sem período, e um filtro de mês corrente esconderia justamente a pendência mais velha, que é a que mais dói.\n\nQuando uma pendência ainda não tem valor apurado, a coluna de valor mostra travessão, nunca R$ 0,00 — "não sei quanto vai custar" e "vai custar nada" são coisas diferentes, e um zero ali faria a faixa de indicadores somar errado e todo mundo parecer tranquilo sem motivo.',
    relacionados: ['financeiro-entradas-atender', 'financeiro-entradas-dispensar', 'financeiro-entradas-indicadores-origem', 'financeiro-cobertura-o-que-e'],
  },
  {
    id: 'financeiro-entradas-atender',
    modulo: 'financeiro',
    tela: 'Caixa de Entrada',
    titulo: 'Como atender uma pendência e gerar o título (ou vários, em parcelas)',
    rota: '/financeiro/entradas',
    perguntas: [
      'gerar titulo a partir da pendencia',
      'atender uma pendencia na caixa de entrada',
      'dividir uma pendencia em parcelas',
      'a competencia e a mesma em todas as parcelas',
      'reter inss na pendencia',
      'de onde saiu o valor estimado da pendencia',
      'a soma das parcelas nao bate com o estimado',
      'quantos titulos gera uma pendencia com varias parcelas',
    ],
    resposta:
      'O botão **Gerar título**, em cada pendência aberta, abre o formulário "Atender". Nele são obrigatórios a **empresa (CNPJ)** e a **categoria do DRE** — sem categoria, o valor cairia numa linha "sem classificação" do relatório. Centro de custo é opcional.\n\nA **competência** é uma só e vale para todas as parcelas geradas, de propósito: propagar a competência junto com o vencimento de cada parcela transformaria o DRE num fluxo de caixa disfarçado. Já o **vencimento** é por parcela — cada linha da tabela de parcelas vira um **título irmão**, com vencimento e baixa próprios. Se a soma das parcelas não bater com o valor que a operação estimou, um aviso mostra a diferença, mas o sistema deixa gravar assim mesmo — a decisão final é de quem está atendendo.\n\nQuando a pendência é de natureza **a pagar**, o formulário oferece a opção de **reter INSS** com alíquota ajustável (o caso recorrente é 11% sobre facção com cessão de mão de obra) — mas nenhuma retenção é assumida automaticamente, porque a regra depende da empresa tomadora, do tipo de serviço e do regime do prestador. Quando a pendência traz um "detalhe", um card mostra exatamente o que o módulo de origem calculou, para conferir sem precisar abrir o documento original.',
    relacionados: ['financeiro-entradas-o-que-e', 'financeiro-entradas-dispensar', 'financeiro-pagar-retencao'],
  },
  {
    id: 'financeiro-entradas-dispensar',
    modulo: 'financeiro',
    tela: 'Caixa de Entrada',
    titulo: 'Como dispensar uma pendência (e quando reabrir)',
    rota: '/financeiro/entradas',
    perguntas: [
      'dispensar uma pendencia',
      'pendencia que nao deve virar titulo',
      'devolucao ja descontada do repasse',
      'motivo da dispensa',
      'reabrir uma pendencia dispensada',
      'pendencia cancelada volta pra fila',
      'pendencia sem gerar titulo',
      'documento morto na caixa de entrada',
    ],
    resposta:
      '**Dispensar** é decidir que aquele compromisso **não** vai gerar título. O caso legítimo mais comum é a devolução que a plataforma já descontou do repasse: gerar um título ali contaria o mesmo dinheiro duas vezes. O formulário exige um **motivo** escrito, com pelo menos alguns caracteres — a dispensa é a válvula legítima do fluxo, e uma válvula sem registro seria o buraco por onde todo controle vaza.\n\nA pendência dispensada continua aparecendo na lista (basta trocar o filtro de situação para "Dispensadas") com o motivo visível, e pode ser **reaberta** a qualquer momento pelo botão correspondente, voltando ao estado "aberta" na fila.',
    relacionados: ['financeiro-entradas-o-que-e', 'financeiro-entradas-atender'],
  },
  {
    id: 'financeiro-entradas-indicadores-origem',
    modulo: 'financeiro',
    tela: 'Caixa de Entrada',
    titulo: 'Os indicadores e a tabela "De onde vem a fila" da Caixa de Entrada',
    rota: '/financeiro/entradas',
    perguntas: [
      'quantos compromissos estao na fila',
      'valor ja estimado na caixa de entrada',
      'pendencia travando documento',
      'pendencia mais antiga na fila',
      'de onde vem a fila de pendencias',
      'clicar na origem pra filtrar a lista',
      'qual modulo mais gera pendencia',
      'quanto tempo uma pendencia fica esperando',
    ],
    resposta:
      'A faixa de indicadores mostra **compromissos na fila** (todas as pendências abertas, de todas as origens, sem recorte de data), **valor já estimado** (soma só das que têm valor apurado — quando há pendência sem valor, um aviso diz quantas ficam de fora dessa soma, porque o número real é maior), **travando documento** (pendências que impedem o fechamento do documento de origem — a ordem de produção não conclui, a venda não fatura, enquanto estiverem ali) e **mais antiga** (há quanto tempo a pendência mais velha da fila está esperando).\n\nO card "De onde vem a fila" lista, por módulo e origem, quantas pendências estão abertas, quantas travam, o valor somado e a mais antiga de cada uma — clicar numa linha filtra a lista de pendências abaixo para mostrar só aquela origem.',
    relacionados: ['financeiro-entradas-o-que-e', 'financeiro-cobertura-catalogo-origens'],
  },

  // ---------------------------------------------------------------------
  // Cobertura (/financeiro/cobertura)
  // ---------------------------------------------------------------------
  {
    id: 'financeiro-cobertura-o-que-e',
    modulo: 'financeiro',
    tela: 'Cobertura',
    titulo: 'O que é a tela Cobertura do Financeiro (e por que não é a Cobertura de Estoque)',
    rota: '/financeiro/cobertura',
    perguntas: [
      'o que e a tela cobertura do financeiro',
      'cobertura financeira nao e cobertura de estoque',
      'o que gerou dinheiro e nao chegou ao financeiro',
      'rede de seguranca do financeiro',
      'documento sem titulo nem pendencia',
      'diferenca entre cobertura de estoque e cobertura financeira',
      'a cobertura varre a caixa de entrada ou as tabelas de origem',
      'documento anterior a ponte financeira',
    ],
    resposta:
      'A **Cobertura** do módulo Financeiro não tem relação com a Cobertura de Estoque (dias de estoque) — é a **rede de segurança** da ponte entre operação e financeiro. Ela existe para responder uma pergunta só: **o que gerou dinheiro no sistema e não chegou ao financeiro** — nem como título, nem como pendência na Caixa de Entrada.\n\nA diferença para a Caixa de Entrada é onde cada uma olha: a Caixa de Entrada mostra o que a ponte já registrou; a Cobertura **varre as tabelas de origem** — ordens de serviço, pedidos de compra, notas, devoluções, vendas próprias, repasses e custos fixos — em vez dos registros da própria ponte. Varrer só a ponte só confirmaria o que ela já sabe; o que se procura aqui é justamente o que passou por fora dela.\n\nÉ também a rede que pega o **passado**: todo documento anterior à existência da ponte aparece como descoberto, porque nenhum deles passou por ela.',
    relacionados: ['financeiro-cobertura-indicadores', 'financeiro-cobertura-trazer-para-caixa-entrada', 'financeiro-cobertura-catalogo-origens', 'financeiro-entradas-o-que-e'],
  },
  {
    id: 'financeiro-cobertura-indicadores',
    modulo: 'financeiro',
    tela: 'Cobertura',
    titulo: 'Os indicadores de Cobertura: documentos, descobertos, valor descoberto e percentual',
    rota: '/financeiro/cobertura',
    perguntas: [
      'quantos documentos descobertos',
      'valor descoberto no financeiro',
      'percentual de cobertura',
      'documento sem valor apurado na cobertura',
      'o que significa 100% de cobertura',
      'documentos que movem dinheiro',
      'quantos documentos nao chegaram ao financeiro',
      'documento sem valor apurado na cobertura conta no total',
    ],
    resposta:
      'A faixa de indicadores mostra **documentos que movem dinheiro** (o total de todos os documentos das origens varridas: O.S. remetidas, pedidos aprovados, notas lançadas, compras, devoluções com dinheiro, vendas próprias faturadas, repasses pagos e custos fixos), **sem chegar ao financeiro** (quantos desses documentos não têm título nem pendência — todo documento anterior à ponte entra aqui por definição), **valor descoberto** (soma só do que tem valor apurado; quando há documento sem valor, um aviso diz quantos ficam de fora dessa soma) e **cobertura**, o percentual de documentos que já têm alguma contrapartida no financeiro.\n\nA tela chama 100% de "meta" porque é o ponto em que nenhum documento fica de fora; abaixo disso, a diferença é dinheiro que o DRE e o fluxo de caixa ainda não enxergam — a tela mostra esse fato, sem indicar o que fazer a respeito.',
    relacionados: ['financeiro-cobertura-o-que-e', 'financeiro-cobertura-trazer-para-caixa-entrada'],
  },
  {
    id: 'financeiro-cobertura-trazer-para-caixa-entrada',
    modulo: 'financeiro',
    tela: 'Cobertura',
    titulo: 'Como trazer documentos descobertos para a Caixa de Entrada',
    rota: '/financeiro/cobertura',
    perguntas: [
      'trazer documento pra caixa de entrada',
      'importar pendencia descoberta',
      'botao trazer tudo para a caixa de entrada',
      'lote de documentos descobertos',
      'documentos descobertos viram pendencia',
      'filtrar cobertura por origem',
      'abrir o documento original da cobertura',
      'limite de documentos mostrados na cobertura',
    ],
    resposta:
      'O botão **Trazer [origem / tudo] para a Caixa de Entrada**, no topo da tela, importa os documentos descobertos em **lotes de até 200 por vez** — quando ainda restam mais depois de um lote, a mensagem avisa e basta rodar de novo para trazer o próximo. Cada documento trazido vira uma pendência nova na **Caixa de Entrada**, pronta para ser atendida ou dispensada.\n\nA tabela "Por origem" mostra quantos documentos e quantos descobertos existem em cada módulo; clicar numa linha filtra tanto essa contagem quanto o botão de importar para só aquela origem. A tabela de documentos descobertos fica limitada a 500 linhas exibidas (os indicadores acima contam todos, mesmo além desse limite), e cada linha tem um link **Abrir** que leva direto ao documento de origem, quando a rota é conhecida.',
    relacionados: ['financeiro-cobertura-o-que-e', 'financeiro-cobertura-indicadores', 'financeiro-entradas-atender'],
  },
  {
    id: 'financeiro-cobertura-catalogo-origens',
    modulo: 'financeiro',
    tela: 'Cobertura',
    titulo: 'O catálogo de origens: categoria padrão, prazo e trava por tipo de evento',
    rota: '/financeiro/cobertura',
    perguntas: [
      'catalogo de origens do financeiro',
      'categoria padrao de uma pendencia',
      'prazo padrao de vencimento da pendencia',
      'o que trava a conclusao do documento',
      'por que estoque nao esta no catalogo de origens',
      'editar a origem sem precisar de deploy',
      'momento na abertura ou na conclusao',
      'origem sem varredura automatica de cobertura',
    ],
    resposta:
      'No fim da tela, o card "Os pontos do sistema que movem dinheiro" lista cada **evento** que cria ou extingue um compromisso de caixa — módulo, origem, se é natureza a pagar ou a receber, e o **momento** em que ele gera pendência: na abertura do documento (previsto) ou só na conclusão. Cada linha é editável sem precisar de deploy: **categoria padrão** do plano financeiro, **prazo padrão** em dias (sugestões que quem lança pode trocar) e se aquela origem **trava a conclusão** do documento até a pendência ser resolvida.\n\n**Estoque, produção, qualidade e promoções não aparecem no catálogo de propósito**: esses módulos movem **custo do produto**, não caixa — e esse custo já foi pago quando a nota de compra entrou. Criar título para eles contaria o mesmo dinheiro duas vezes.\n\nDuas origens não têm varredura automática de Cobertura, e a própria tela lista quais são e por quê, em vez de deixar por baixo do tapete a impressão de que está tudo coberto.',
    relacionados: ['financeiro-cobertura-o-que-e', 'financeiro-entradas-indicadores-origem'],
  },
];
