// Verbetes "gerais" — tudo que não é de um módulo específico (login, a
// casca do sistema — barra lateral, tema, densidade, busca ⌘K, celular,
// tabela) e o Glossário (os termos de precificação que aparecem em várias
// telas diferentes, explicados uma vez só aqui). Cada resposta só explica
// o que a palavra/tela significa e como usar — nunca sugere um valor de
// referência pra nenhum campo (Regra 1: cálculo é intocável, e sugerir
// "seu markup devia ser X" seria opinar sobre cálculo por outra porta).
//
// `rota` é sempre uma tela que existe de verdade e que qualquer usuário
// autenticado alcança (sem precisar de um :id que a Manu não tem como
// adivinhar) — ver relatório da tarefa pra decisão de rota por verbete.

export const verbetesGeral = [
  {
    id: 'geral-login',
    modulo: 'geral',
    tela: 'Login',
    titulo: 'Entrar no sistema',
    rota: '/login',
    perguntas: [
      'como faço login',
      'como entro no sistema',
      'como acesso o hbn hub',
      'tela de login',
      'cade o login',
      'nao consigo entrar',
      'nao to conseguindo entrar',
      'login nao funciona',
      'como logar',
      'logar no hbn',
      'entrar no hub',
      'usuario e senha pra entrar',
      'onde boto meu usuario',
      'tela de acesso do sistema',
      'como abro o sistema',
      'primeiro acesso como faz',
      'preciso de email pra entrar',
      'entra com email ou usuario',
      'diz que usuario ou senha errados',
      'nome de usuario nao existe',
    ],
    resposta:
      'A tela de login pede **Usuário** e **Senha** — é o nome de usuário cadastrado, não o e-mail (o e-mail só entra na conta pra receber o link de redefinição, se um dia precisar). Digite os dois e clique em **Entrar**.\n\nSe aparecer que o usuário ou a senha estão errados, confira letra por letra (o campo de senha tem um ícone de olho pra você ver o que digitou) e o Caps Lock. Se não lembra a senha, use o link **Esqueci minha senha** logo abaixo do botão de entrar.\n\nDepois de logado, o sistema te leva direto pra primeira tela que seu usuário pode acessar — se seu perfil só tem um módulo liberado, é nele que você cai.',
    relacionados: ['geral-esqueci-senha', 'geral-trocar-senha', 'geral-tela-nao-aparece'],
  },
  {
    id: 'geral-esqueci-senha',
    modulo: 'geral',
    tela: 'Esqueci minha senha',
    titulo: 'Esqueci minha senha',
    rota: '/esqueci-senha',
    perguntas: [
      'esqueci minha senha',
      'esqueci a senha',
      'perdi a senha',
      'nao lembro minha senha',
      'como recupero a senha',
      'como redefino a senha',
      'redefinir senha',
      'resetar senha',
      'link de redefinicao de senha',
      'nao chegou o email de redefinir senha',
      'nao recebi o email da senha',
      'pedi nova senha e nao veio nada',
      'como troco a senha esquecida',
      'senha bloqueada esqueci',
      'perdi acesso a minha conta',
      'travei a senha',
      'quero uma senha nova',
      'cade o email de redefinicao',
    ],
    resposta:
      'Na tela de login, clique em **Esqueci minha senha**. Digite seu nome de usuário (não o e-mail) e confirme — se existir uma conta ativa com esse nome, chega um e-mail com um link de redefinição no endereço cadastrado pra essa conta.\n\nAbra o link do e-mail e escolha a senha nova. O sistema não confirma nem nega se o nome existe, de propósito (é uma proteção padrão) — então se o e-mail não chegar em alguns minutos, confira a caixa de spam antes de tentar de novo, e se mesmo assim nada chegar, o e-mail cadastrado pode estar desatualizado: um administrador consegue conferir e corrigir isso na tela de Acessos.',
    relacionados: ['geral-login', 'geral-trocar-senha'],
  },
  {
    id: 'geral-trocar-senha',
    modulo: 'geral',
    tela: 'Conta',
    titulo: 'Trocar a própria senha',
    rota: '/esqueci-senha',
    perguntas: [
      'como troco minha senha',
      'trocar minha senha',
      'mudar senha',
      'alterar minha senha',
      'onde troco a senha',
      'quero mudar de senha',
      'trocar senha atual por outra',
      'mudar minha senha de acesso',
      'tem como trocar a senha sem esquecer ela',
      'trocar senha estando logado',
      'atualizar senha',
      'configuracao de conta senha',
      'perfil trocar senha',
      'redefinir minha propria senha',
    ],
    resposta:
      'Hoje o sistema não tem uma tela de "minha conta" onde você troca a própria senha só digitando a atual e a nova — o único caminho pra trocar de senha, mesmo lembrando da atual, é o mesmo da tela de login: clique em **Esqueci minha senha**, informe seu usuário e siga o link que chega por e-mail pra escolher a senha nova.\n\nSe você quer trocar a senha de **outra pessoa** (por exemplo, um funcionário que saiu ou esqueceu de novo), isso é diferente: um administrador faz isso pela tela de **Acessos**, editando o cadastro daquele usuário.',
    relacionados: ['geral-esqueci-senha', 'geral-login'],
  },
  {
    id: 'geral-modulos-barra',
    modulo: 'geral',
    tela: 'Barra lateral',
    titulo: 'O que é cada módulo da barra lateral',
    rota: '/produtos',
    perguntas: [
      'o que e cada modulo',
      'pra que serve cada menu',
      'o que significa cada icone da barra lateral',
      'o que tem em cada modulo',
      'nao sei o que cada modulo faz',
      'o que e o modulo produto',
      'o que e o modulo estoque',
      'o que e o modulo vendas',
      'o que e o modulo marketplace',
      'o que e o modulo viagens',
      'o que e o modulo compras',
      'o que e o modulo analises',
      'o que e o modulo configuracoes',
      'o que e o modulo calendario',
      'pra que serve cada aba do menu lateral',
      'nao entendo os icones do menu',
      'diferenca entre os modulos',
      'quantos modulos tem o sistema',
    ],
    resposta:
      'A barra lateral tem um botão por módulo, cada um com seu ícone e sua cor (só quem você tem acesso aparece):\n\n**Produto** — cadastro de referências, ficha técnica, kits e importação em lote.\n**Estoque** — quantidade por variante (cor/tamanho), bipagem, importação de saldo e de EAN.\n**Vendas** — pedidos feitos direto pelo balcão/site próprio, clientes e a lucratividade dessas vendas.\n**Marketplace** — pedidos vindos de canal externo (Mercado Livre, Shopee etc.), métricas, taxas cobradas e importação.\n**Viagens** — controle de viagens de compra/produção.\n**Compras** — pedidos de compra e fornecedores.\n**Análises** — dashboard, ficha de precificação, alertas e simulador.\n**Configurações** — parâmetros gerais, empresas, custos indiretos, taxas, listas, acessos e integrações (a maior parte só pra administrador).\n**Calendário** — agenda de eventos e prazos.\n\nClicar no módulo abre a primeira página dele; se ele tem mais de uma tela, elas aparecem como abas logo abaixo do cabeçalho.',
    relacionados: ['geral-tela-nao-aparece', 'geral-recolher-sidebar'],
  },
  {
    id: 'geral-recolher-sidebar',
    modulo: 'geral',
    tela: 'Barra lateral',
    titulo: 'Recolher ou expandir a barra lateral',
    rota: '/produtos',
    perguntas: [
      'como recolho o menu lateral',
      'como escondo a barra lateral',
      'minimizar o menu',
      'menu lateral ta grande demais',
      'como fecho o menu do lado',
      'esconder os nomes dos modulos',
      'deixar o menu so com os icones',
      'expandir o menu de novo',
      'menu lateral sumiu como volto',
      'barra lateral ocupando espaco',
      'diminuir a barra do lado',
      'colapsar sidebar',
      'como aumento o espaco da tela',
    ],
    resposta:
      'No fim da barra lateral tem o botão **Recolher** (a seta dupla). Clicando nele, o menu encolhe pra mostrar só os ícones dos módulos, sem o nome — sobra mais espaço pra tabela e formulário. Pra voltar ao tamanho normal, clique de novo no mesmo botão (agora com a seta apontando pro outro lado).\n\nO sistema lembra sua escolha: se você recolher, ele continua recolhido da próxima vez que você abrir o sistema nesse mesmo navegador, até você expandir de novo.\n\nNo celular a barra lateral já funciona diferente — vira uma gaveta que abre por cima da tela pelo botão de menu no canto (ver o verbete sobre usar no celular).',
    relacionados: ['geral-mobile', 'geral-modulos-barra'],
  },
  {
    id: 'geral-tema',
    modulo: 'geral',
    tela: 'Barra superior',
    titulo: 'Alternar entre tema claro e escuro',
    rota: '/produtos',
    perguntas: [
      'como mudo pro modo escuro',
      'tem modo escuro',
      'ativar tema escuro',
      'trocar tema claro escuro',
      'deixar a tela escura',
      'modo noturno',
      'dark mode',
      'onde fica o botao do tema',
      'como volto pro tema claro',
      'tela muito clara a noite',
      'mudar cor de fundo do sistema',
      'alternar aparencia do sistema',
      'icone de sol e lua',
    ],
    resposta:
      'No cabeçalho, perto do seu nome, tem um botão com um ícone de sol ou lua. Clicar nele alterna entre tema claro e tema escuro na hora, na tela inteira — sem precisar recarregar a página.\n\nO ícone mostra o que você **vai** ativar ao clicar: lua parada significa que o tema atual é claro (clique pra ir pro escuro); sol significa que já está no escuro (clique pra voltar ao claro). O sistema guarda sua preferência nesse navegador, então da próxima vez que você entrar ele já abre no tema que você escolheu por último.',
    relacionados: ['geral-densidade'],
  },
  {
    id: 'geral-densidade',
    modulo: 'geral',
    tela: 'Barra superior',
    titulo: 'Alternar densidade da tabela (compacta ou confortável)',
    rota: '/produtos',
    perguntas: [
      'como deixo a tabela mais compacta',
      'tabela com linhas mais juntas',
      'diminuir espaco entre linhas da tabela',
      'tabela densa',
      'ver mais linhas na tela',
      'tabela ta com muito espaco',
      'aumentar espacamento da tabela',
      'densidade da tabela',
      'deixar a tabela confortavel',
      'linhas da tabela muito coladas',
      'quero ver mais produtos na tela de uma vez',
      'icone de linhas no cabecalho',
      'mudar tamanho das linhas',
    ],
    resposta:
      'No cabeçalho tem um botão que alterna a densidade de todas as tabelas do sistema entre duas opções: **compacta** (linhas mais juntas, cabe mais informação na tela de uma vez) e **confortável** (mais espaço entre linhas, mais fácil de ler).\n\nA mudança vale pra tela toda, em qualquer tabela do sistema — não dá pra escolher uma densidade diferente por tela. O sistema guarda a escolha nesse navegador, então continua do jeito que você deixou da próxima vez.',
    relacionados: ['geral-tema', 'geral-tabela-navegar'],
  },
  {
    id: 'geral-busca-cmdk',
    modulo: 'geral',
    tela: 'Busca global',
    titulo: 'Usar a busca rápida (⌘K / Ctrl+K)',
    rota: '/produtos',
    perguntas: [
      'como uso a busca rapida',
      'atalho de busca',
      'ctrl k nao funciona',
      'command k',
      'busca global',
      'como busco um produto rapido',
      'atalho pra achar pedido',
      'buscar por ean rapido',
      'pesquisa rapida do sistema',
      'onde fica a lupa de busca',
      'nao acho o botao de busca',
      'busca por atalho de teclado',
      'como abro a busca',
      'pesquisar cliente rapido',
      'buscar uma pagina do sistema',
      'atalho pra pular de tela',
      'busca universal',
    ],
    resposta:
      'A busca rápida abre com o atalho de teclado **Ctrl+K** (Windows/Linux) ou **⌘K** (Mac) em qualquer tela do sistema — ela não tem um botão clicável na barra, é só pelo atalho mesmo. Digite produto, pedido, cliente, fornecedor, EAN ou o nome de uma página, e ela mostra os resultados junto com um jeito de pular direto pra tela certa.\n\nEla também mostra um grupo **"Ajuda da Manu"** dentro dos resultados — se o que você digitou parecer uma dúvida (por exemplo, começar com "como" ou "onde"), esse grupo aparece primeiro; senão, os resultados de produto/pedido/cliente vêm primeiro e a ajuda entra depois. Pra fechar, aperte **Esc**.',
    relacionados: [],
  },
  {
    id: 'geral-tela-nao-aparece',
    modulo: 'geral',
    tela: 'Permissões',
    titulo: 'Por que uma tela não aparece pra mim',
    rota: '/produtos',
    perguntas: [
      'nao acho uma tela',
      'sumiu um menu pra mim',
      'nao vejo o modulo de configuracoes',
      'nao tenho acesso a essa tela',
      'por que nao consigo abrir essa pagina',
      'tela some quando eu clico',
      'diz que nao tenho permissao',
      'nao aparece marketplace pra mim',
      'meu usuario nao tem acesso a nada',
      'sem acesso liberado',
      'nao vejo nenhum modulo',
      'colega ve uma tela que eu nao vejo',
      'quem libera acesso a modulo',
      'como peco acesso a um modulo',
      'so administrador ve essa tela',
      'tela some do menu lateral',
    ],
    resposta:
      'Cada usuário só vê, na barra lateral e nos resultados de busca, os módulos que foram liberados pra ele — quem decide isso é um administrador, na tela de **Acessos**. Se um módulo inteiro não aparece pra você, é porque seu usuário ainda não tem acesso a ele; peça pra um administrador liberar.\n\nAlgumas telas dentro de um módulo (por exemplo, Integrações e Saúde dos Dados, dentro de Configurações) são reservadas só pra administrador mesmo com o módulo liberado — nesse caso o resto do módulo aparece normalmente, só essas telas específicas ficam de fora.\n\nSe você digitar o endereço de uma tela direto no navegador sem ter acesso a ela, o sistema te manda de volta pra primeira tela que seu usuário realmente pode ver, em vez de mostrar um erro.',
    relacionados: ['geral-modulos-barra'],
  },
  {
    id: 'geral-mobile',
    modulo: 'geral',
    tela: 'Barra lateral',
    titulo: 'Usar o sistema no celular',
    rota: '/produtos',
    perguntas: [
      'da pra usar no celular',
      'sistema funciona no celular',
      'usar pelo cel',
      'acessar do celular',
      'versao mobile do sistema',
      'menu no celular',
      'como abro o menu no celular',
      'tabela fica ruim no celular',
      'app pro celular tem',
      'sistema no tablet',
      'usar no celular funciona',
      'nao acho o menu no celular',
      'onde fica o menu no celular',
      'tres tracinhos no celular',
    ],
    resposta:
      'Não existe um aplicativo separado — o sistema funciona pelo navegador do celular mesmo, e a tela se adapta ao espaço menor. No celular a barra lateral fica escondida por padrão: toque no ícone de menu (as três linhas) no canto superior esquerdo do cabeçalho pra abrir a gaveta com os módulos, e toque fora dela (ou em Esc, se tiver teclado) pra fechar. Ela também fecha sozinha assim que você escolhe uma página.\n\nTabelas longas ganham rolagem horizontal quando não cabem na largura da tela, e alguns painéis (como o carrinho de compra de viagem) viram uma folha que sobe do rodapé em vez de um card fixo. As funções são as mesmas do computador — só a moldura muda pra caber na tela menor.',
    relacionados: ['geral-recolher-sidebar'],
  },
  {
    id: 'geral-tabela-navegar',
    modulo: 'geral',
    tela: 'Tabelas',
    titulo: 'Ordenar e paginar uma tabela',
    rota: '/produtos',
    perguntas: [
      'como ordeno a tabela',
      'como classifico a tabela por coluna',
      'clicar no titulo da coluna nao ordena',
      'como mudo a ordem da tabela',
      'ordenar por nome',
      'ordenar do maior pro menor',
      'quantos itens por pagina',
      'mudar itens por pagina',
      'como pulo pra outra pagina da tabela',
      'ir pra ultima pagina',
      'tabela tem muitas paginas',
      'onde troco o tamanho da pagina',
      'nao acho a paginacao',
      'ver todos os itens de uma vez',
      'tabela mostra so 50 por vez',
    ],
    resposta:
      'Clique no título de uma coluna pra ordenar a tabela por ela — clicando de novo no mesmo título, a ordem inverte (crescente/decrescente). Nem toda coluna é clicável; as que ordenam normalmente mudam a aparência do cursor ao passar por cima.\n\nA barra de paginação, no rodapé da tabela (e às vezes repetida no topo), mostra quantos itens estão sendo exibidos do total e tem: um seletor de quantos itens mostrar por página, os botões de primeira/anterior/próxima/última página, e um seletor pra pular direto pra um número de página específico.\n\nA ordenação e a página atual não ficam salvas — voltando pra tela depois, ela abre do jeito padrão de novo.',
    relacionados: ['geral-tabela-exportar', 'geral-densidade'],
  },
  {
    id: 'geral-tabela-exportar',
    modulo: 'geral',
    tela: 'Tabelas',
    titulo: 'Exportar uma tabela (CSV ou XLSX)',
    rota: '/produtos',
    perguntas: [
      'como exporto a tabela',
      'exportar para excel',
      'exportar para csv',
      'exportar para xlsx',
      'baixar a tabela',
      'tirar relatorio da tabela',
      'salvar a lista em excel',
      'gerar planilha da tabela',
      'download da tabela',
      'onde fica o botao exportar',
      'exportar lista de produtos',
      'exportar pedidos pra planilha',
      'como tiro os dados pra excel',
      'baixar csv',
      'baixar xlsx',
      'exportar so os itens filtrados',
      'a exportacao pega tudo ou so a pagina',
    ],
    resposta:
      'A maioria das tabelas de listagem tem um botão **Exportar** (ícone de seta pra baixo). Clicando nele, abre um menu com duas opções: **Exportar como CSV** e **Exportar como XLSX** — o arquivo baixa direto no navegador, com o nome da lista e a data de hoje.\n\nO arquivo sai com as colunas formatadas do jeito que aparecem na tela (valor em R$, percentual, data em dd/mm/aaaa) — não em número cru. A exportação considera o que está filtrado/buscado na tela naquele momento, não fica limitada só à página atual da paginação.\n\nSe a tabela que você está olhando não tem o botão Exportar, é porque essa lista específica ainda não tem essa opção — nem toda tela do sistema tem exportação.',
    relacionados: ['geral-tabela-navegar'],
  },

  // -----------------------------------------------------------------
  // Glossário — termos de precificação/estoque que aparecem em mais de
  // uma tela. Cada verbete explica o SIGNIFICADO do termo; nenhum deles
  // sugere um valor, faixa ou "número bom" pra ele (Regra 1) — quem quer
  // mudar o número vai na tela de configuração correspondente.
  // -----------------------------------------------------------------
  {
    id: 'gloss-referencia',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é a referência de um produto',
    rota: '/produtos',
    perguntas: [
      'o que e referencia',
      'o que significa referencia',
      'referencia do produto e o que',
      'codigo de referencia',
      'diferenca entre referencia e codigo',
      'referencia e o mesmo que sku',
      'referencia unica',
      'como funciona a referencia',
      'referencia repetida da erro',
      'posso repetir referencia',
      'referencia obrigatoria',
      'pra que serve a referencia',
      'referencia identifica o que',
    ],
    resposta:
      'A **referência** é o código que identifica um produto de forma única no sistema — cada referência só pode existir uma vez no cadastro (o sistema não deixa salvar duas iguais). Ela representa o produto "em geral" (o modelo), não uma cor ou tamanho específico: as variações de cor e tamanho de uma mesma referência ficam dentro da grade dela, no Estoque.\n\nÉ a referência que aparece na maioria das listas e buscas do sistema (produtos, pedidos, ficha técnica, ficha de precificação) como o jeito principal de identificar um item — inclusive é por ela que a busca ⌘K encontra um produto.',
    relacionados: ['gloss-grade', 'gloss-ean', 'gloss-sku'],
  },
  {
    id: 'gloss-grade',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é a grade (cor e tamanho)',
    rota: '/estoque',
    perguntas: [
      'o que e grade',
      'o que significa grade',
      'grade de cor e tamanho',
      'grade do produto',
      'o que e uma variante',
      'variante do produto e o que',
      'diferenca entre produto e variante',
      'grade completa o que e',
      'como funciona a grade no estoque',
      'cada cor e tamanho e uma linha',
      'grade e o mesmo que estoque',
      'montar grade de um produto',
    ],
    resposta:
      'A **grade** é o conjunto de variações de cor e tamanho de uma mesma referência — cada combinação de cor + tamanho é uma **variante**, com seu próprio saldo em estoque e seu próprio EAN. Uma referência pode ter uma grade grande (várias cores, vários tamanhos) ou nenhuma variação além do padrão, dependendo do produto.\n\nÉ na tela de **Estoque** que a grade de uma referência aparece detalhada, variante por variante, com a quantidade de cada uma. Todo movimento de estoque (entrada, saída, ajuste, bipagem, importação) é sempre registrado numa variante específica da grade, nunca na referência "como um todo".',
    relacionados: ['gloss-referencia', 'gloss-ean'],
  },
  {
    id: 'gloss-ean',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é o EAN',
    rota: '/estoque/ean',
    perguntas: [
      'o que e ean',
      'o que significa ean',
      'ean e o codigo de barras',
      'pra que serve o ean',
      'cada variante tem um ean',
      'ean obrigatorio',
      'como gero um ean',
      'ean repetido da erro',
      'importar ean',
      'ean nao bate na bipagem',
      'codigo de barras do produto',
      'ean automatico',
    ],
    resposta:
      'O **EAN** é o código de barras de uma variante específica (uma cor + tamanho de uma referência) — cada variante tem o seu próprio, e o sistema não deixa dois EANs iguais cadastrados. É esse código que a **bipagem** lê pra identificar exatamente qual variante está entrando ou saindo do estoque.\n\nSe uma variante ainda não tem EAN definido, o sistema pode gerar um automaticamente; ele também aceita EANs vindos de outro sistema (ex.: Wiki Sistemas), que dá pra importar antes mesmo de a variante existir aqui — quando ela for criada depois, o EAN certo já é aplicado sozinho em vez de gerar um novo à toa.',
    relacionados: ['gloss-grade', 'gloss-sku'],
  },
  {
    id: 'gloss-sku',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é SKU',
    rota: '/marketplace/importar-pedidos',
    perguntas: [
      'o que e sku',
      'o que significa sku',
      'sku e o mesmo que referencia',
      'sku e o mesmo que ean',
      'diferenca entre sku e referencia',
      'sku do anuncio',
      'sku externo',
      'sku do mercado livre',
      'sku da shopee',
      'como o sistema casa o sku',
      'sku nao bate com a referencia',
      'sku sem correspondencia',
    ],
    resposta:
      '"SKU" aparece de dois jeitos no sistema. Na ficha do produto, o campo **Referência** vem rotulado como "Referência (SKU)" — ali é só um apelido pro mesmo campo, não existe um campo separado chamado SKU no cadastro.\n\nJá na importação de pedidos de marketplace, **SKU** é o código que o anúncio (Mercado Livre, Shopee etc.) usa lá fora pra identificar o item vendido — diferente da referência interna. Quando um pedido é importado, o sistema tenta casar esse SKU externo com a referência + cor + tamanho cadastrados aqui. Quando esse casamento não é possível (o SKU do anúncio não bate com nada do cadastro), o pedido fica sinalizado — normalmente aparece como item "sem correspondência" ou agrupado à parte nas métricas de marketplace, até alguém ajustar o cadastro ou o próprio anúncio.',
    relacionados: ['gloss-referencia', 'gloss-ean'],
  },
  {
    id: 'gloss-ficha-tecnica',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é a ficha técnica',
    rota: '/ficha-tecnica',
    perguntas: [
      'o que e ficha tecnica',
      'pra que serve a ficha tecnica',
      'ficha tecnica do produto',
      'ficha tecnica e a mesma coisa que ficha de precificacao',
      'ficha tecnica mostra o que',
      'onde vejo a ficha tecnica',
      'imprimir ficha tecnica',
      'ficha tecnica de producao',
    ],
    resposta:
      'A **ficha técnica** reúne, numa página só, os materiais e a montagem de uma referência — é o documento pensado pra quem está produzindo a peça consultar, diferente da **ficha de precificação**, que é focada no preço e na margem. Ela fica disponível na tela de Ficha Técnica, dentro do módulo Produto.\n\nCada material do produto (com quantidade e unidade) e as etapas de custo industrial cadastradas aparecem ali organizados pra consulta e impressão — é o mesmo cadastro de materiais que alimenta o cálculo de preço, só que apresentado do jeito que ajuda quem está montando a peça, não quem está precificando.',
    relacionados: ['gloss-custo-industrial'],
  },
  {
    id: 'gloss-custo-industrial',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é custo industrial',
    rota: '/ficha-precificacao',
    perguntas: [
      'o que e custo industrial',
      'custo industrial e o que',
      'mao de obra industrial',
      'diferenca entre custo industrial e material',
      'custo industrial entra em que',
      'custo de producao e custo industrial e a mesma coisa',
      'o que compoe o custo industrial',
      'custo industrial e etapa de producao',
    ],
    resposta:
      'O **custo industrial** é o custo de transformar o material em peça pronta — mão de obra e etapas de produção (corte, costura, acabamento etc.), cadastradas por referência. Ele é separado do custo de **material** (o tecido, aviamento e afins, com quantidade e valor unitário próprios) mesmo entrando junto na composição final do preço.\n\nNa composição do preço de venda, o custo industrial aparece como uma fatia própria, ao lado de materiais, custo indireto, impostos, taxas e lucro — dá pra ver essa composição na Ficha de Precificação, no gráfico de composição do preço de uma referência.',
    relacionados: ['gloss-custo-indireto', 'gloss-ficha-tecnica'],
  },
  {
    id: 'gloss-custo-indireto',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é custo indireto',
    rota: '/custos-indiretos',
    perguntas: [
      'o que e custo indireto',
      'custo indireto e o que',
      'despesas indiretas o que sao',
      'custo indireto por peca',
      'diferenca entre custo direto e indireto',
      'o que entra no custo indireto',
      'custo fixo mensal o que e',
      'custo indireto vem de onde',
      'aluguel entra no custo do produto como',
      'custo indireto e o mesmo que rateio',
    ],
    resposta:
      'O **custo indireto** é o custo fixo do negócio que não é de nenhuma peça em particular — aluguel, contas, salário administrativo e afins — cadastrado como uma lista de itens mensais na tela de **Custos Indiretos**, dentro de Configurações. Ele não tem como ser ligado direto a um produto específico, então precisa ser **rateado** entre a produção (ver o verbete "rateio").\n\nNa composição do preço de uma referência, o custo indireto aparece como uma fatia própria — o valor por peça já vem calculado, não é digitado produto a produto.',
    relacionados: ['gloss-rateio', 'gloss-custo-industrial'],
  },
  {
    id: 'gloss-rateio',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é rateio (dos custos indiretos)',
    rota: '/custos-indiretos',
    perguntas: [
      'o que e rateio',
      'como funciona o rateio',
      'rateio dos custos indiretos',
      'rateio e o que',
      'rateio muda quando',
      'rateio por peca o que e',
      'producao mensal afeta o rateio',
      'diminuir o rateio como',
      'rateio sobe se produz menos',
      'rateio e dividido como',
    ],
    resposta:
      'O **rateio** é a divisão do total dos custos indiretos (o somatório de tudo cadastrado em Custos Indiretos) pela quantidade de peças que a produção do mês deve gerar — o resultado é o custo indireto que cada peça individual carrega, usado no cálculo de preço de todas as referências.\n\nA quantidade de produção mensal usada no rateio é um número configurável na mesma tela de Custos Indiretos, editável separado dos itens de custo. Mudar qualquer um dos dois lados dessa conta — o total de custos indiretos ou a produção mensal considerada — muda o custo indireto por peça de **todas** as referências ao mesmo tempo, não só de uma.',
    relacionados: ['gloss-custo-indireto'],
  },
  {
    id: 'gloss-markup',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é markup',
    rota: '/ficha-precificacao',
    perguntas: [
      'o que e markup',
      'markup e o que',
      'como calcula o markup',
      'markup e a mesma coisa que margem',
      'diferenca entre markup e margem',
      'markup do produto',
      'markup baixo o que significa',
      'markup alto o que significa',
      'markup multiplicador',
      'o que o markup mostra',
      'pra que serve o markup',
      'markup em vezes',
    ],
    resposta:
      'O **markup** é o preço de venda expresso como um múltiplo do custo total do produto — por isso ele aparece na tela como um número seguido de "x" (por exemplo, algo como "2,5x"). Ele mostra, de um jeito rápido, quantas vezes o custo o preço de venda representa; markup e margem respondem perguntas parecidas mas não são a mesma conta — margem é sobre o preço de venda, markup é sobre o custo.\n\nEle é calculado automaticamente a partir do custo e do preço de cada referência, e aparece junto com o preço sugerido e o lucro na Ficha de Precificação. Este verbete não recomenda nenhum markup "certo" — isso é decisão de precificação de cada referência, não algo que a Manu opina.',
    relacionados: ['gloss-margem-contribuicao', 'gloss-precos-referencia'],
  },
  {
    id: 'gloss-margem-contribuicao',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é margem de contribuição',
    rota: '/ficha-precificacao',
    perguntas: [
      'o que e margem de contribuicao',
      'margem de contribuicao e o que',
      'diferenca entre margem de contribuicao e lucro',
      'margem de contribuicao e a mesma coisa que markup',
      'como calcula a margem de contribuicao',
      'margem de contribuicao negativa o que significa',
      'onde vejo a margem de contribuicao',
      'margem de contribuicao por produto',
    ],
    resposta:
      'A **margem de contribuição** é quanto sobra do preço de venda depois de descontar os custos que variam com a venda daquela peça (material, industrial, indireto, impostos e taxas) — é o valor que "contribui" pra cobrir o restante do negócio e formar o lucro, por isso o nome. Ela aparece na Ficha do Produto, junto com os outros indicadores da referência.\n\nÉ diferente do markup (que é o preço como múltiplo do custo) e diferente do lucro final mostrado na composição de preço — são três jeitos distintos de olhar pra mesma composição de custo e preço, cada um respondendo uma pergunta diferente.',
    relacionados: ['gloss-markup', 'gloss-custo-indireto'],
  },
  {
    id: 'gloss-precos-referencia',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que são preço mínimo, ideal, premium e máximo',
    rota: '/ficha-precificacao',
    perguntas: [
      'o que e preco minimo',
      'o que e preco ideal',
      'o que e preco premium',
      'o que e preco maximo recomendado',
      'diferenca entre preco minimo e ideal',
      'qual a diferenca entre esses precos',
      'faixa de preco da referencia',
      'preco sugerido e o mesmo que preco ideal',
      'preco ativo o que e',
      'preco praticado e o que',
      'onde vejo a faixa de preco',
      'quatro precos diferentes o que significam',
      'preco minimo ideal premium maximo pra que servem',
    ],
    resposta:
      'A Ficha de Precificação mostra uma faixa com quatro pontos de referência pra cada produto, todos calculados a partir do custo:\n\n**Mínimo** — o menor preço que ainda cobre o custo dentro do critério do sistema.\n**Ideal** — o preço-alvo padrão pra aquela referência.\n**Premium** — um preço mais alto, acima do ideal.\n**Máximo recomendado** — o teto sugerido, visível na Ficha do Produto.\n\nAlém desses quatro, o painel também mostra o **preço ativo**: o que está realmente em uso pra referência — que pode ser um preço informado manualmente no cadastro do produto, ou, na ausência dele, o preço sugerido pelo cálculo.\n\nEsses quatro pontos são resultado do cálculo, não campos que se digita — mudar qualquer um deles é mudar o custo ou os parâmetros de cálculo em Configurações, algo que a Manu não orienta a fazer.',
    relacionados: ['gloss-markup', 'gloss-margem-contribuicao'],
  },
  {
    id: 'gloss-taxa-venda',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é taxa de venda',
    rota: '/taxas',
    perguntas: [
      'o que e taxa de venda',
      'taxa de venda e o que',
      'onde cadastro taxa de venda',
      'taxa de cartao e taxa de venda',
      'taxa de antecipacao o que e',
      'diferenca entre taxa de venda e taxa de marketplace',
      'quais taxas de venda existem',
      'taxa de venda entra no calculo como',
      'ativar taxa de venda',
    ],
    resposta:
      'As **taxas de venda** são os percentuais cobrados sobre uma venda por fora do custo do produto em si — cartão, antecipação e afins — cadastradas na tela **Taxas**, aba "Venda". Cada taxa tem nome, um percentual e pode estar ativa ou não; só as ativas entram no cálculo de preço.\n\nElas são diferentes das taxas de marketplace (a outra aba da mesma tela), que são específicas de cada canal de venda externo (comissão do Mercado Livre, da Shopee etc.) e podem ter faixas em vez de um percentual único — taxa de venda vale pra venda direta (balcão/site próprio).',
    relacionados: ['gloss-conciliacao'],
  },
  {
    id: 'gloss-regime-tributario',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é regime tributário',
    rota: '/empresas',
    perguntas: [
      'o que e regime tributario',
      'regime tributario e o que',
      'quais regimes tributarios tem',
      'simples nacional lucro presumido lucro real',
      'como troco o regime tributario',
      'cada empresa tem um regime diferente',
      'regime tributario afeta o preco como',
      'onde configuro o regime tributario',
    ],
    resposta:
      'O **regime tributário** é o enquadramento fiscal de cada empresa/CNPJ cadastrado no sistema — Simples Nacional, Lucro Presumido ou Lucro Real — configurado na tela **Empresas**. Como o negócio tem mais de uma pessoa jurídica, cada uma pode estar num regime diferente, com suas próprias alíquotas (ICMS, PIS, COFINS, IPI, ISS e outras).\n\nCada produto fica associado a uma empresa, e é o regime dela que entra no cálculo de impostos daquele produto — por isso o mesmo produto pode ter um resultado de imposto diferente dependendo de qual empresa está vendendo.',
    relacionados: [],
  },
  {
    id: 'gloss-escrow',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é escrow',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'o que e escrow',
      'escrow e o que',
      'escrow da shopee',
      'conciliacao escrow',
      'valor recebido shopee escrow',
      'shopee nao tem pagamento separado',
      'escrow amount o que e',
      'liberacao de escrow',
    ],
    resposta:
      'O **escrow** é o jeito que a Shopee usa pra repassar o valor de uma venda: em vez de gerar um "pagamento" separado (como faz o Mercado Livre), ela concilia o valor pelo próprio número do pedido, e esse repasse é liberado com um prazo. É esse valor de conciliação — não um pagamento à parte — que o sistema usa como o valor de verdade recebido de um pedido Shopee.\n\nEnquanto a conciliação ainda não aconteceu, o pedido fica sem esse valor confirmado, e o cálculo de lucratividade usa uma estimativa no lugar (marcada como estimativa) até o valor real da Shopee ficar disponível.',
    relacionados: ['gloss-conciliacao'],
  },
  {
    id: 'gloss-conciliacao',
    modulo: 'geral',
    tela: 'Glossário',
    titulo: 'O que é conciliação (valor recebido)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'o que e conciliacao',
      'conciliacao e o que',
      'valor recebido ainda sem conciliacao',
      'pedido sem conciliacao o que significa',
      'conciliacao financeira o que e',
      'como sei se um pedido foi conciliado',
      'valor recebido nao bate',
      'diferenca entre valor do pedido e valor recebido',
      'conciliacao demora quanto',
    ],
    resposta:
      'A **conciliação** é o processo de confirmar, com o marketplace, quanto de dinheiro de verdade chegou por um pedido — nem sempre é igual ao valor do pedido em si, porque taxas, frete e eventuais ajustes do canal entram na conta. Enquanto um pedido não foi conciliado, ele aparece como "ainda sem conciliação" e o valor recebido usado na lucratividade é uma estimativa.\n\nCada marketplace concilia de um jeito: o Mercado Livre gera um pagamento vinculado ao pedido; a Shopee usa o escrow (ver o verbete "escrow"). O relatório de Lucratividade do Marketplace mostra, pedido a pedido, se o valor já está confirmado ou ainda é estimativa.',
    relacionados: ['gloss-escrow', 'gloss-taxa-venda'],
  },
];
