// Verbetes do módulo Marketplace — pedidos de marketplace (/marketplace/pedidos,
// origemFiltro="marketplace" de PedidosListPage), Lucratividade de Marketplace
// (/marketplace/lucratividade, origemFiltro="marketplace" de
// RelatorioLucratividadePage — mesmo componente do módulo Vendas, mas aqui
// documento só o que aparece quando a origem é "marketplace": Ads/TACOS/MPA,
// valor recebido/escrow, vincular produto, duplicatas suspeitas, buscar
// pedido por origem, sub-abas Resumo por Produto/Vendas/Não Avaliáveis),
// Métricas de Marketplace (/marketplace/metricas, 11 sub-abas de
// MetricasMarketplacePage), Taxas de Marketplace (/marketplace/taxas,
// RelatorioTaxasPage) e Importar Pedidos (/marketplace/importar-pedidos,
// ImportarPedidosPage — planilha do Mercado Livre, Shopee ou UpSeller).

export const verbetesMarketplace = [
  {
    id: 'mkt-pedidos-listar-filtrar',
    modulo: 'marketplace',
    tela: 'Pedidos de Marketplace',
    titulo: 'Ver e filtrar os pedidos de marketplace',
    rota: '/marketplace/pedidos',
    perguntas: [
      'onde vejo os pedidos de marketplace',
      'pedidos do mercado livre',
      'pedidos da shopee',
      'lista de pedidos de marketplace',
      'filtrar pedidos por plataforma',
      'filtrar pedidos por loja',
      'de quanto em quanto tempo os pedidos chegam',
      'sincronizacao automatica de pedidos',
      'nao tem botao de novo pedido no marketplace',
      'pedidos chegam sozinhos',
      'buscar pedido de marketplace por numero',
    ],
    resposta:
      'A tela **Pedidos de Marketplace** lista os pedidos importados do Mercado Livre, Shopee, TikTok Shop e demais marketplaces conectados. Diferente da tela de Vendas, aqui não tem botão de "Novo pedido": pedidos chegam sozinhos, sincronizados a cada 5 minutos pelas integrações conectadas em **Integrações**, ou por importação de planilha (tela **Importar Pedidos**).\n\nDá pra filtrar por período, plataforma (Mercado Livre, Shopee, TikTok Shop...), loja/integração específica, situação e por texto (número do pedido, cliente etc.). Se a lista estiver vazia, o próprio sistema sugere ir em Integrações pra conectar uma loja.',
    relacionados: ['mkt-importar-pedidos', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-kpis',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Indicadores da Lucratividade de Marketplace (Faturamento, Lucro, Margem...)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'lucratividade de marketplace',
      'lucro dos pedidos de marketplace',
      'faturamento do marketplace',
      'quanto ganhei no mercado livre',
      'quanto ganhei na shopee',
      'margem dos pedidos de marketplace',
      'ticket medio marketplace',
      'roi do marketplace',
      'numero de vendas marketplace',
      'unidades vendidas marketplace',
      'liquido do marketplace',
      'selo de confianca da lucratividade',
      'pedido marcado como estimativa',
      'frete nao entra no faturamento',
    ],
    resposta:
      'A tela **Lucratividade de Marketplace** calcula o lucro real de cada pedido de marketplace: valor de verdade recebido do marketplace (o pagamento no Mercado Livre, a conciliação/escrow na Shopee) menos custo de produção, embalagem e imposto — quando esse valor já está confirmado. Pedido ainda sem confirmação usa uma estimativa baseada no preço de venda, e fica marcado com o selo **estimativa**.\n\n**Indicadores do topo**\n\nFaturamento, Líq. do Marketplace, Lucro Bruto e Margem vêm primeiro; embaixo, Número de Vendas, Unidades Vendidas, Ticket Médio e Retorno Sobre Investimento (ROI). O Frete aparece à parte (não entra no Faturamento — é dinheiro do comprador/transportadora, não da loja).\n\nNo rodapé, o **selo de confiança** mostra sobre quantos pedidos o cálculo foi feito, de quantos existem no período, e quantos ficaram de fora por falta de custo de material cadastrado — com link pra auditoria em Saúde dos Dados.',
    relacionados: ['mkt-lucratividade-ads', 'mkt-lucratividade-recebido-escrow', 'mkt-lucratividade-nao-avaliaveis'],
  },
  {
    id: 'mkt-lucratividade-ads',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Custo de Ads, TACOS, Lucro Pós Ads e MPA',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'tacos',
      'o que e tacos',
      'mpa',
      'o que e mpa',
      'lucro pos ads',
      'valor gasto em ads',
      'custo de publicidade no lucro',
      'como o ads e rateado no lucro',
      'gasto de anuncio nao atribuido',
      'ads sem venda no dia',
    ],
    resposta:
      'Quando existe gasto de Ads sincronizado no período, a Lucratividade de Marketplace mostra mais quatro indicadores: **Valor em Ads** (gasto total, dividido em "atribuído" a alguma venda do dia e "sem venda no dia"), **TACOS** (o gasto de Ads como % do faturamento), **Lucro Pós Ads** (o lucro depois de descontar o Ads) e **MPA** — a margem sobre esse lucro pós Ads.\n\nO rateio do Ads por pedido é o gasto do dia daquele anúncio dividido por todas as unidades vendidas do anúncio naquele dia — pode mudar se a tela for recalculada depois, porque uma venda cancelada altera esse divisor. Quem sincroniza o histórico de gasto por anúncio é a aba **Publicidade** da tela Métricas.',
    relacionados: ['mkt-lucratividade-kpis', 'mkt-metricas-publicidade', 'mkt-lucratividade-resumo-produto'],
  },
  {
    id: 'mkt-lucratividade-recebido-escrow',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Valor recebido, liberado, confirmado e conciliação (escrow)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'valor recebido do marketplace',
      'o que e escrow',
      'conciliacao da shopee',
      'valor liberado no saldo',
      'valor confirmado ainda retido',
      'sem confirmacao ainda',
      'quando o dinheiro do mercado livre cai',
      'quando a shopee libera o pagamento',
      'coluna recebido da tabela de pedidos',
    ],
    resposta:
      '**Valor Liberado no Saldo** é o dinheiro que o marketplace já colocou de fato disponível pra saque/uso; **Valor Confirmado, Ainda Retido** é o que já está confirmado mas ainda preso (prazo de liberação); e **Sem Confirmação Ainda** conta os pedidos que ainda não têm nenhum valor recebido confirmado.\n\nNa coluna **Recebido** da tabela de pedidos, cada linha mostra o valor com o selo **liberado** ou **confirmado** (com a data em que libera, quando ainda está retido) — passando o mouse no cabeçalho da coluna aparece a explicação: é o valor que o marketplace pagou de verdade, o pagamento no Mercado Livre ou a conciliação (escrow) na Shopee. Pedido de plataforma sem repasse rastreado mostra um traço nessa coluna.',
    relacionados: ['mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-vincular-produto',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Vincular ou trocar o produto de um item de pedido',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'vincular produto no pedido de marketplace',
      'item sem vinculo',
      'trocar produto vinculado ao pedido',
      'sku do anuncio nao bate',
      'alterar produto do item',
      'botao vincular na tabela de pedidos',
      'revincular custos e impostos',
      'item fantasma',
    ],
    resposta:
      'Na tabela de pedidos, cada linha tem um botão **Vincular** (quando o item ainda não tem produto associado) ou **Alterar** (quando já tem, mas quer trocar). Ele abre uma janela com todos os itens do pedido: pra cada um, é possível buscar por referência, descrição ou EAN e clicar em **Selecionar** pra ligar aquele item a uma variante do estoque.\n\nO botão **Revincular custos e impostos** (na barra de ações do topo, e também na tela Taxas de Marketplace) tenta vincular em lote todos os itens sem correspondência automática, além de atualizar empresa/% de nota fiscal, corrigir pagamento vinculado errado, preencher ID de anúncio e dado de pacote faltando, e remover item "fantasma" (mesmo SKU duplicado com valor zerado cobrando custo sem receita). Ele mostra um resumo do que foi corrigido ao terminar — se ainda sobrar algo, é só clicar de novo (corrige em lotes).',
    relacionados: ['mkt-lucratividade-nao-avaliaveis', 'mkt-taxas-cobradas'],
  },
  {
    id: 'mkt-lucratividade-nao-avaliaveis',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Não Avaliáveis" — pedidos sem custo cadastrado',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'pedidos nao avaliaveis',
      'pedido sem custo cadastrado',
      'por que um pedido nao entra no total',
      'aba nao avaliaveis',
      'referencia nao cadastrada no pedido de marketplace',
      'sku do anuncio em formato desconhecido',
    ],
    resposta:
      'A sub-aba **Não Avaliáveis** só aparece quando existe pelo menos um pedido com item sem produto vinculado — referência não cadastrada, ou SKU do anúncio num formato que o sistema não reconhece. Sem custo de verdade pra calcular, esses pedidos ficam de fora do total agregado do topo (custo zero não é a mesma coisa que custo baixo).\n\nA lista mostra pedido, data, cliente, receita e o(s) item(ns) sem vínculo. Pra fazer esses pedidos voltarem a entrar na conta, vincule o produto certo na aba Pedidos (botão **Vincular**), ou cadastre a referência que está faltando.',
    relacionados: ['mkt-lucratividade-vincular-produto', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-duplicatas-suspeitas',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Avisos de possível receita duplicada (pacote e troca)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'receita duplicada',
      'venda contada duas vezes',
      'pedido de pacote duplicado',
      'possivel troca suspeita',
      'mesmo comprador mesmo valor dias diferentes',
      'aviso de duplicata no marketplace',
      'excesso de receita possivel',
    ],
    resposta:
      'Quando existe algum caso, dois avisos amarelos podem aparecer no topo da Lucratividade de Marketplace:\n\n**Possível receita duplicada entre pedidos de pacote** — mesmo SKU, preço e quantidade aparecendo em mais de um pedido dentro do mesmo pacote do Mercado Livre; pode ser a mesma venda contada duas vezes.\n\n**Possível receita duplicada por troca** — mesmo comprador, mesmo valor, em dias diferentes; assinatura de uma troca do Mercado Livre que virou pedido novo em vez de ficar vinculada ao original.\n\nOs dois são só informativos: o sistema não tem confiança suficiente pra corrigir sozinho (não confirma o vínculo direto pela API), então nunca desconta nada do total agregado automaticamente. A recomendação é conferir cada caso no painel do Mercado Livre antes de decidir o que fazer.',
    relacionados: ['mkt-lucratividade-buscar-pedido-origem'],
  },
  {
    id: 'mkt-lucratividade-buscar-pedido-origem',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Buscar um pedido do Mercado Livre por número (investigação)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'buscar pedido do mercado livre por numero',
      'conferir pedido direto no mercado livre',
      'pedido nao apareceu no sistema',
      'item de pacote sumiu',
      'ferramenta de investigacao de pedido',
      'colar numero do pedido do mercado livre',
    ],
    resposta:
      'O link **Buscar pedido do Mercado Livre por número** (acima da tabela de pedidos) abre uma ferramenta de investigação: cole o número de um pedido ou pacote visto direto no painel do Mercado Livre, e ela busca ao vivo na API — mesmo que esse pedido nunca tenha sido importado pra cá — pra conferir se ele existe no sistema, quais itens o Mercado Livre diz que ele tem, e quais outros pedidos do mesmo pacote já estão gravados aqui.\n\nServe principalmente pra achar item de pacote que sumiu: existe no Mercado Livre mas nunca virou pedido/item no sistema. O número também pode ser reconhecido como número de envio ou de pacote, não só de pedido — a ferramenta avisa qual dos três tipos encontrou.',
    relacionados: ['mkt-lucratividade-duplicatas-suspeitas'],
  },
  {
    id: 'mkt-lucratividade-resumo-produto',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Resumo por Produto" — histórico e lucro por produto',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'resumo por produto marketplace',
      'lucro por produto no marketplace',
      'grafico de lucratividade',
      'historico de lucratividade',
      'qual produto mais vendeu no marketplace',
      'representatividade do produto no faturamento',
      'custo de ads por produto',
    ],
    resposta:
      'A sub-aba **Resumo por Produto** mostra um gráfico de área (Faturamento, Líq. do Marketplace e Lucro Bruto ao longo dos dias do período) e, embaixo, uma tabela por produto: preço médio, custo unitário médio, unidades vendidas, total faturado, representatividade no faturamento, lucro bruto, margem bruta e — quando há Ads no período — custo de Ads (rateado por unidade do dia) e lucro/margem pós Ads.\n\nO gráfico e os indicadores de cima (Número de Vendas, Unidades Vendidas, Ticket Médio, ROI, Ads/TACOS/MPA quando houver) podem ser recolhidos clicando na seta, deixando só a tabela por produto visível.',
    relacionados: ['mkt-lucratividade-ads', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-aba-vendas',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Vendas" — detalhe de cada venda em cartão',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'aba vendas da lucratividade de marketplace',
      'cartao de venda individual',
      'ver detalhe de uma venda de marketplace',
      'diferenca entre aba pedidos e aba vendas',
    ],
    resposta:
      'A sub-aba **Vendas** mostra os mesmos pedidos do período, só que em formato de cartão (um por pedido) em vez de linha de tabela — útil pra olhar o detalhe de uma venda sem precisar rolar a tabela pro lado. Usa o mesmo filtro de busca por texto e o mesmo período da aba Pedidos, só muda a apresentação.',
    relacionados: ['mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-metricas-visao-geral',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Painel de Métricas de Marketplace — visão geral e por loja',
    rota: '/marketplace/metricas',
    perguntas: [
      'metricas de marketplace',
      'diferenca entre metricas e lucratividade',
      'visao geral de vendas do marketplace',
      'valor total de vendas vs vendas validas',
      'pedidos validos',
      'clientes do marketplace',
      'vendas por cliente',
      'variacao em relacao ao periodo anterior',
      'comparar loja com loja',
    ],
    resposta:
      'A tela **Métricas de Marketplace** é um painel de acompanhamento de vendas — volume, pedidos, clientes, produtos e estoque — separado da Lucratividade (que foca em custo/lucro). Tem 11 sub-abas: as 6 primeiras aparecem direto (Visão Geral, Por Loja, Vendas por Anúncio, Análise ABC, Entrada e Saída, Reputação), e o resto fica agrupado num menu "Mais" (Opiniões, Concorrentes, Publicidade, Categorias, Shopee).\n\nOs indicadores de resumo (Visão Geral e Por Loja) são: **Valor Total de Vendas** e **Total de Pedidos** (todo pedido importado, sem filtrar cancelado), e **Valor de Vendas Válidas** e **Pedidos Válidos** (só pedidos não cancelados — a mesma contagem que aparece no painel do Mercado Livre, agrupada por pacote/carrinho), além de Clientes e Vendas por Cliente. Cada número tem uma variação (%) comparando com o período anterior equivalente. A aba **Por Loja** quebra os mesmos indicadores por loja/canal conectado.',
    relacionados: ['mkt-metricas-vendas-anuncio-abc', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-metricas-vendas-anuncio-abc',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Abas "Vendas por Anúncio" e "Análise ABC"',
    rota: '/marketplace/metricas',
    perguntas: [
      'vendas por anuncio',
      'quanto cada anuncio vendeu',
      'curva abc de produtos',
      'classificacao abc marketplace',
      'produto classe a b c',
      'anuncio sem id gravado',
      'representatividade acumulada',
    ],
    resposta:
      'A aba **Vendas por Anúncio** mostra, por ID de anúncio do marketplace, quantos pedidos válidos, unidades vendidas, preço médio e total faturado ele teve — item importado antes de o sistema guardar o ID do anúncio aparece marcado "sem ID gravado" e entra agrupado por SKU nesse caso.\n\nA aba **Análise ABC** classifica os produtos pela curva de Pareto sobre o faturamento: classe **A** = produtos que somam até 80% do faturamento acumulado, **B** = até 95%, **C** = o restante — ordenado do que mais fatura pro que menos fatura. Ajuda a enxergar quais produtos merecem mais atenção em estoque, reposição ou campanha.',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-entrada-saida',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Entrada e Saída" — saídas de estoque pelas vendas',
    rota: '/marketplace/metricas',
    perguntas: [
      'entrada e saida de estoque no marketplace',
      'saida de estoque pela venda',
      'quanto saiu de estoque no marketplace',
      'estoque baixado pela venda de marketplace',
    ],
    resposta:
      'A aba **Entrada e Saída** mostra as saídas de estoque geradas pelas vendas de marketplace no período, calculadas direto pela quantidade de itens vendidos — não depende de nenhuma ação manual tipo "Faturar" (que existe só nos pedidos manuais de Vendas). A baixa de estoque de um pedido de marketplace já acontece pela venda em si.',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-reputacao',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Reputação" — nível da conta no Mercado Livre',
    rota: '/marketplace/metricas',
    perguntas: [
      'reputacao da loja no mercado livre',
      'nivel da conta mercado livre',
      'reclamacoes cancelamento atraso',
      'meta de reclamacoes',
      'termometro do mercado livre',
    ],
    resposta:
      'A aba **Reputação** busca, pra cada loja do Mercado Livre conectada, o nível de reputação da conta (de "Crítica" a "Excelente", a mesma escala que aparece no painel do Mercado Livre), o total de vendas, e os percentuais de reclamações, cancelamentos feitos pelo vendedor e despacho com atraso.\n\nAs metas mostradas ao lado de cada percentual (reclamações até 2%, cancelados até 1,5%, despacho atrasado até 10%) são só uma referência visual pra contexto — não vêm da API do Mercado Livre, são um parâmetro fixo do sistema. Exige integração do Mercado Livre conectada e autorizada; sem isso, a aba pede pra conectar em Integrações.',
    relacionados: ['mkt-metricas-opinioes-concorrentes'],
  },
  {
    id: 'mkt-metricas-opinioes-concorrentes',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Abas "Opiniões" e "Concorrentes" (nos mais vendidos do Mercado Livre)',
    rota: '/marketplace/metricas',
    perguntas: [
      'opinioes dos anuncios',
      'avaliacoes dos anuncios mais vendidos',
      'concorrencia dos anuncios',
      'estou ganhando ou perdendo a disputa',
      'modo catalogo mercado livre',
      'preco pra ganhar a disputa',
      'estrelas dos anuncios',
    ],
    resposta:
      'As abas **Opiniões** e **Concorrentes** (dentro do menu "Mais") consultam, item por item, os até 25 anúncios com mais unidades vendidas de uma loja do Mercado Livre — por isso a busca pode demorar um pouco.\n\n**Opiniões** traz a nota média e a distribuição de 1 a 5 estrelas de cada anúncio. **Concorrentes** só funciona pra anúncio que participa do modo catálogo do Mercado Livre (a maioria dos anúncios normais não participa): mostra se está "Ganhando" ou "Perdendo" a disputa de catálogo, o preço atual e o preço que seria preciso pra ganhar.',
    relacionados: ['mkt-metricas-reputacao'],
  },
  {
    id: 'mkt-metricas-publicidade',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Publicidade" (Ads) — campanhas, ROAS e gasto por anúncio',
    rota: '/marketplace/metricas',
    perguntas: [
      'publicidade do marketplace',
      'campanhas de ads',
      'roas',
      'o que e roas',
      'sincronizar historico de ads',
      'gasto por anuncio de publicidade',
      'product ads mercado livre',
      'ads da shopee',
    ],
    resposta:
      'A aba **Publicidade** mostra campanhas de anúncio patrocinado (Mercado Ads/Product Ads e, quando aplicável, Shopee Ads) num período escolhido: custo, cliques, impressões, CPC e **ROAS** (retorno sobre o investimento — receita atribuída dividida pelo gasto; é o indicador que o próprio Mercado Livre passou a priorizar no lugar do ACOS). Uma segunda tabela mostra o gasto detalhado por anúncio — o mesmo dado usado pra ratear o custo de Ads na Lucratividade de Marketplace, pra bater certinho com o que aparece lá.\n\nO botão **Sincronizar histórico (90 dias)** busca até 90 dias pra trás direto na API de publicidade da loja escolhida. Campanha da Shopee sem anúncio identificável entra como "gasto de Ads não atribuído" — some no total do período, nunca é chutado em cima de um pedido específico. Exige Product Ads habilitado na conta do Mercado Livre (com o produto "Publicidade" adicionado no painel de desenvolvedores); sem isso, a busca volta com aviso explicando o que falta.',
    relacionados: ['mkt-lucratividade-ads'],
  },
  {
    id: 'mkt-metricas-categorias',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Categorias" — tendências e distribuição de anúncios',
    rota: '/marketplace/metricas',
    perguntas: [
      'tendencias do mercado livre',
      'termos mais buscados',
      'distribuicao de anuncios por categoria',
      'navegar categorias do mercado livre',
      'popular da semana maior crescimento',
    ],
    resposta:
      'A aba **Categorias** traz dados da plataforma inteira do Mercado Livre (não só da sua loja), atualizados semanalmente pelo próprio Mercado Livre. Tem duas sub-visões:\n\n**Tendência** lista os termos mais buscados — pro Brasil inteiro, ou dentro de uma categoria específica escolhida navegando na árvore de categorias — classificados em "Maior crescimento" (10 primeiros), "Mais buscado" (próximos 20) e "Popular da semana" (últimos 20).\n\n**Distribuição de Anúncios** mostra o % do total de anúncios ativos em cada categoria, com navegação por aprofundamento (clica numa categoria pra ver as subcategorias dela, e assim por diante).',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-shopee',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Shopee" — desempenho, avaliações e devoluções',
    rota: '/marketplace/metricas',
    perguntas: [
      'aba shopee das metricas',
      'saude da conta shopee',
      'avaliacoes dos compradores shopee',
      'devolucoes da shopee',
      'nota geral shopee',
      'falhas de cumprimento shopee',
      'abas da loja shopee dentro de metricas',
    ],
    resposta:
      'A aba **Shopee** mostra o desempenho da loja Shopee a partir dos pedidos já sincronizados (vendas válidas por dia), e três blocos que só existem na API da Shopee — carregados sob demanda porque cada um é uma chamada externa separada:\n\n**Saúde da Conta** — nota geral e falhas de cumprimento, anúncio e atendimento, com métricas comparando período atual, anterior e meta. **Avaliações dos Compradores** — nota média (calculada só sobre as avaliações mais recentes que a API devolve, não o histórico completo da loja) e os comentários recentes. **Devoluções** (últimos 30 dias) — lista só informativa: nenhuma situação de pedido muda por causa dela. Uma devolução aceita já chega ao lucro pelo caminho certo, porque o valor da conciliação (escrow) fica menor.',
    relacionados: ['mkt-lucratividade-recebido-escrow'],
  },
  {
    id: 'mkt-taxas-cobradas',
    modulo: 'marketplace',
    tela: 'Taxas de Marketplace',
    titulo: 'Conferir se a taxa cobrada bate com o esperado',
    rota: '/marketplace/taxas',
    perguntas: [
      'taxas de marketplace',
      'taxa cobrada diferente do esperado',
      'pedido divergente de taxa',
      'comissao errada mercado livre',
      'comparar taxa cobrada com tabela',
      'pedido sem tabela cadastrada',
      'so comissao sem frete',
      'peso do produto nao cadastrado',
    ],
    resposta:
      'A tela **Taxas de Marketplace** compara, pedido a pedido, a taxa que o Mercado Livre/Shopee/TikTok Shop realmente cobrou com o que era esperado pelas tabelas de comissão + frete cadastradas em Configurações → Taxas. Só considera pedidos importados automaticamente das integrações (planilha manual não entra nessa checagem).\n\nCada linha mostra receita, taxa cobrada, taxa esperada, a diferença entre as duas e a situação: **OK**, **Divergente** ou **Sem referência** (quando não existe tabela de comissão cadastrada pra comparar — nesse caso não conta como divergente, pra não acusar diferença falsa contra taxa zero). Pedido sem peso de produto cadastrado mostra "só comissão" na taxa esperada, porque o frete não entrou na conta. Se mais de 80% dos pedidos do período estiverem divergentes, o sistema avisa que provavelmente é a tabela de comissão desatualizada, não cobrança errada pedido a pedido. O botão **Revincular custos e impostos** (o mesmo da Lucratividade de Marketplace) também está disponível aqui.',
    relacionados: ['mkt-lucratividade-vincular-produto'],
  },
  {
    id: 'mkt-importar-pedidos',
    modulo: 'marketplace',
    tela: 'Importar Pedidos',
    titulo: 'Importar pedidos de marketplace por planilha',
    rota: '/marketplace/importar-pedidos',
    perguntas: [
      'importar pedidos de marketplace',
      'importar planilha de vendas',
      'importar pedido do mercado livre por planilha',
      'importar pedido da shopee por planilha',
      'importar upseller',
      'importar tiktok shop',
      'importar shein',
      'pre-visualizar pedidos antes de importar',
      'item sem correspondencia na importacao de pedidos',
    ],
    resposta:
      'A tela **Importar Pedidos** recebe uma planilha .xlsx exportada do Mercado Livre (Vendas → Relatórios → Vendas), da Shopee (Meus Pedidos → Exportar) ou do UpSeller (Pedidos → Exportar — que também cobre TikTok Shop e Shein, sem precisar de API própria pra essas duas).\n\nEscolha a origem da planilha, envie o arquivo e clique em **Pré-visualizar**: nada é gravado ainda nessa etapa. A prévia lista os pedidos encontrados, marca os que já foram importados antes (ficam desmarcados e esmaecidos) e avisa quando algum item não bateu com nenhuma referência/EAN do estoque — esse item entra só com a descrição, sem baixar estoque ao faturar. Marque os pedidos desejados e clique em **Importar N pedido(s) selecionado(s)**: cada um vira um pedido de venda em aberto, igual à sincronização automática.',
    relacionados: ['mkt-pedidos-listar-filtrar'],
  },
  {
    id: 'mkt-anuncios-publicacao-variacao',
    modulo: 'marketplace',
    tela: 'Anúncios',
    titulo: 'Por que o número de anúncios daqui bate (agora) com o do painel da plataforma',
    rota: '/marketplace/anuncios',
    perguntas: [
      'por que tem mais anuncios aqui do que no mercado livre',
      'numero de anuncios diferente do painel',
      'anuncio repetido na tela de anuncios',
      'o que e publicacao e o que e variacao',
      'por anuncio ou por variacao',
      'aparecem 800 anuncios e no mercado livre sao 82',
      'contagem de anuncios errada',
    ],
    resposta:
      'A tela abre em **Por anúncio**, que conta do mesmo jeito que o painel da plataforma conta — se lá diz 82 anúncios, aqui também diz 82.\n\nO motivo de um dia ter dito quase 800: no Mercado Livre, **um anúncio criado com variações vira vários itens na API**, um por variação, todos amarrados pelo mesmo código de família. O painel mostra a *publicação* (o anúncio que você criou); a API devolve os *itens*. Os dois números estão certos, só contam coisas diferentes — e a tela mostrava o da API com o nome do outro.\n\nNada foi escondido. Clicando num cartão com o selo "N variações" você entra na lista delas, e o modo **Por variação** mostra a lista crua, um cartão por item, como era antes. A faixa de lojas no topo diz os dois números quando eles diferem ("82 anúncios · 794 variações").\n\nO agrupamento é por **código exato de família da própria plataforma** — nunca por título parecido. Na Shopee e na TikTok Shop esse conceito não existe: lá cada anúncio já vale por si, e a contagem não muda.',
    relacionados: ['mkt-anuncios-filtros', 'mkt-metricas-vendas-anuncio-abc'],
  },
  {
    id: 'mkt-anuncios-filtros',
    modulo: 'marketplace',
    tela: 'Anúncios',
    titulo: 'Filtros: várias lojas de uma vez, situação e período do Ads',
    rota: '/marketplace/anuncios',
    perguntas: [
      'filtrar por mais de uma loja',
      'selecionar duas lojas ao mesmo tempo',
      'filtrar por varias lojas como no upseller',
      'por que so aparecem anuncios ativos',
      'ver anuncios pausados e encerrados',
      'mudar o periodo do ads',
      'calendario do ads',
      'ads de um periodo especifico',
    ],
    resposta:
      'Todo filtro de **loja** e de **plataforma** do módulo Marketplace aceita mais de uma escolha ao mesmo tempo, no mesmo formato do UpSeller: clique no filtro, use a busca ou o "Tudo", marque as que quiser e clique em **Salvar** (a lista só recarrega no Salvar — Cancelar desfaz). Vale em Anúncios, Pedidos, Promoções, Métricas, Publicidade, Taxas Cobradas, Lucratividade e Financeiro.\n\nA tela de Anúncios **abre filtrada em Ativos**, que é o padrão do painel de qualquer plataforma. Isso aparece como um chip de filtro logo abaixo da busca — clique no "x" dele para ver também pausados, encerrados e em análise. Nada é apagado: anúncio que saiu do ar continua gravado, com a data em que sumiu.\n\nO **período do Ads** é o mesmo filtro de calendário das outras telas do módulo: atalhos (hoje, 7 dias, 30 dias, este mês, mês passado) e um período personalizado com calendário nas duas pontas. Sem escolher nada, continuam valendo os últimos 30 dias.',
    relacionados: ['mkt-anuncios-publicacao-variacao', 'mkt-metricas-publicidade'],
  },
  {
    id: 'mkt-anuncios-sem-foto',
    modulo: 'marketplace',
    tela: 'Anúncios',
    titulo: 'A foto do anúncio não aparece',
    rota: '/marketplace/anuncios',
    perguntas: [
      'nao aparece foto do anuncio',
      'foto do anuncio em branco',
      'cartao de anuncio sem imagem',
      'imagem quebrada no anuncio',
    ],
    resposta:
      'Isso era um defeito do sistema, corrigido em 10/09/2026: as fotos vêm da CDN da plataforma, e duas coisas as barravam ao mesmo tempo — o Mercado Livre entrega o endereço em `http://`, que o navegador bloqueia dentro de uma página segura, e a política de segurança do próprio HBN Hub não liberava nenhuma imagem de fora do domínio. As duas foram corrigidas, e vale para as fotos já gravadas: não é preciso rodar "Atualizar das lojas" antes.\n\nSe ainda houver cartão sem imagem, o quadro diz o motivo: **"sem foto"** significa que a plataforma não mandou endereço nenhum; **"foto não abriu"** significa que o endereço existe mas não respondeu (foto apagada na plataforma, por exemplo). Nesses casos o sistema tenta antes a foto do produto no cadastro, e só depois mostra a referência escrita.',
    relacionados: ['mkt-anuncios-publicacao-variacao'],
  },

  // --- Telas novas (10/09/2026): conferência, etiquetas, romaneio,
  // ---------------------------------------------------------------------
  // Conferência de Pedidos — /marketplace/conferencia
  // ---------------------------------------------------------------------
  {
    id: 'mkt-conferencia-visao-geral',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'O que é a Conferência de Pedidos e como ela funciona',
    rota: '/marketplace/conferencia',
    perguntas: [
      'o que e a conferencia de pedidos',
      'pra que serve a tela de conferencia',
      'como bipar pedido antes de despachar',
      'conferencia de pedidos do marketplace',
      'abas da conferencia',
      'bipagem fila relatorio',
      'como evitar caixa errada',
      'como confirmar as pecas antes de fechar a caixa',
      'onde confiro os pedidos antes de enviar',
    ],
    resposta:
      'A tela **Conferência de Pedidos** (`/marketplace/conferencia`) serve para bipar cada peça de um pedido antes de fechar a caixa, comparando contra o que foi realmente vendido — é a etapa que existe pra pegar a peça errada antes que ela saia da casa. Tem três abas: **Bipagem** (onde a conferência acontece, peça por peça), **Fila do dia** (a lista de pedidos do período, o que já foi conferido e o que falta) e **Relatório** (indicadores e histórico de divergências por período).\n\nA aba de Bipagem fica sempre montada por trás das outras — trocar de aba no meio de uma caixa não perde a sessão nem obriga a bipar a etiqueta de novo.',
    relacionados: ['mkt-conferencia-bipagem-fluxo', 'mkt-conferencia-fila-do-dia', 'mkt-conferencia-relatorio'],
  },
  {
    id: 'mkt-conferencia-bipagem-fluxo',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'Como bipar um pedido: abrir pela etiqueta, bipar as peças e fechar a caixa',
    rota: '/marketplace/conferencia',
    perguntas: [
      'como bipar a etiqueta de envio',
      'como abrir um pedido para conferir',
      'bipar cada peca da caixa',
      'posso digitar o numero do pedido em vez de bipar',
      'numero do pacote do mercado livre na conferencia',
      'fechar caixa antes de bipar tudo',
      'fechar mesmo faltando peca',
      'motivo do fechamento incompleto',
      'desfazer ultima leitura',
      'largar a conferencia no meio',
    ],
    resposta:
      'No campo do topo, bipe a etiqueta de envio (ou digite o número do pedido na plataforma, o número do pacote do Mercado Livre ou o número interno) para abrir o pedido. Depois disso o mesmo campo passa a aceitar o código de barras de cada peça: cada bipagem certa soma no contador "X de Y peças" e toca um som de acerto; peça de outro pedido, código desconhecido ou peça que já completou a quantidade esperada tocam som de erro e ficam registradas como recusadas.\n\nAo bipar a última peça esperada, aparece um aviso de tela cheia "Pedido completo" e a caixa pode ser fechada no botão **Fechar caixa**. O botão **Fechar mesmo faltando peça** só liga depois de pelo menos uma peça bipada, e fechar assim exige escrever um motivo (fica registrado no relatório) — de propósito: oferecer esse fechamento como ação natural antes de bipar nada é convidar justamente o erro que a conferência existe pra evitar.\n\n**Desfazer última** desfaz a última leitura (útil pra corrigir uma bipagem errada) e **Largar** devolve o pedido pra fila pra outra pessoa conferir do zero, mantendo o que já foi bipado registrado.',
    relacionados: ['mkt-conferencia-confirmar-no-olho', 'mkt-conferencia-vincular-etiqueta', 'mkt-conferencia-relatorio'],
  },
  {
    id: 'mkt-conferencia-confirmar-no-olho',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'Peça sem código de barras cadastrado — "Confirmar no olho"',
    rota: '/marketplace/conferencia',
    perguntas: [
      'peca sem codigo de barras',
      'nao da para bipar essa peca',
      'confirmar no olho',
      'o que e confirmado no olho',
      'por que o pedido fica com divergencia',
      'item sem ean na conferencia',
      'como registrar peca sem ean',
      'codigo que o sistema nao conhece',
    ],
    resposta:
      'Quando um item do pedido não tem código de barras (EAN) cadastrado, ele aparece marcado "Sem código de barras cadastrado — não dá pra bipar" e, no lugar da contagem, tem um botão **Confirmar no olho**. Antes de confirmar, o sistema pergunta se a peça está mesmo na caixa e avisa que confirmar assim marca o pedido como **divergente** no relatório — é uma garantia mais fraca do que bipar de verdade, então fica registrada como tal.\n\nCada código bipado que o sistema não reconhece entra na lista **Códigos que o sistema não conhece**, na aba Relatório — que é, na prática, a fila de trabalho de **Estoque › Importar EAN**: cadastrar o código lá tira a peça dessa situação nas próximas conferências.',
    relacionados: ['mkt-conferencia-bipagem-fluxo', 'mkt-conferencia-relatorio'],
  },
  {
    id: 'mkt-conferencia-vincular-etiqueta',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'Pedido sem etiqueta cadastrada — vincular pelo número',
    rota: '/marketplace/conferencia',
    perguntas: [
      'pedido sem etiqueta',
      'vincular etiqueta na conferencia',
      'abri o pedido pelo numero e agora',
      'como vincular o rastreio ao pedido',
      'etiqueta ainda nao esta no sistema',
      'bipar a etiqueta depois de abrir pelo numero',
      'por que aparece aviso de sem etiqueta',
      'cadastrar codigo de rastreio na conferencia',
      'proxima vez o pedido abre pela etiqueta',
    ],
    resposta:
      'Se o pedido ainda não tem etiqueta cadastrada, ele só pode ser aberto pelo número (do pedido, do pacote ou o interno) — nesse caso aparece o aviso "Este pedido ainda não tem etiqueta cadastrada" com o botão **Vincular esta etiqueta**. Clicando nele, abre um campo próprio na tela (não um pop-up do navegador) pra bipar ou digitar o código da etiqueta de envio; da próxima vez, essa etiqueta abre o pedido direto.\n\nNa aba **Fila do dia**, o filtro "Só os sem etiqueta cadastrada" e o indicador "Sem etiqueta cadastrada" mostram quantos pedidos do período ainda dependem de abrir pelo número.',
    relacionados: ['mkt-conferencia-bipagem-fluxo', 'mkt-conferencia-fila-do-dia'],
  },
  {
    id: 'mkt-conferencia-fila-do-dia',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'Aba "Fila do dia" — o que falta conferir e o que já foi',
    rota: '/marketplace/conferencia',
    perguntas: [
      'fila do dia da conferencia',
      'quais pedidos faltam conferir',
      'filtrar pedidos conferidos',
      'filtrar pedidos com divergencia',
      'filtrar pedidos sem etiqueta',
      'abrir pedido direto da fila',
      'quem esta conferindo agora',
      'periodo de datas na fila do dia',
      'quantos pedidos faltam expedir hoje',
    ],
    resposta:
      'A aba **Fila do dia** lista os pedidos do período escolhido com a situação da conferência de cada um: **não conferido**, **conferindo agora** (com o nome de quem está bipando, quando duas pessoas entram na tela ao mesmo tempo), **conferido** ou **conferido com divergência**. Os filtros rápidos são: só os que faltam conferir, só os já conferidos, só os com divergência e só os sem etiqueta cadastrada.\n\nClicar numa linha abre a conferência daquele pedido direto na aba Bipagem — sem precisar decorar o número nem trocar de aba manualmente.',
    relacionados: ['mkt-conferencia-bipagem-fluxo', 'mkt-conferencia-vincular-etiqueta'],
  },
  {
    id: 'mkt-conferencia-relatorio',
    modulo: 'marketplace',
    tela: 'Conferência de Pedidos',
    titulo: 'Aba "Relatório" — indicadores, divergências e por pessoa',
    rota: '/marketplace/conferencia',
    perguntas: [
      'relatorio da conferencia',
      'sairam de primeira o que significa',
      'pedidos com divergencia na conferencia',
      'por que um pedido fechado conta como divergencia mesmo completo',
      'codigos que o sistema nao conhece',
      'conferencia por pessoa',
      'quantas pecas foram conferidas no periodo',
      'motivo registrado da divergencia',
      'o que foi recusado na conferencia',
    ],
    resposta:
      'A aba **Relatório** mostra, para o período escolhido: pedidos conferidos, o percentual que "saíram de primeira" (fechados sem nenhuma peça confirmada no olho e sem nada faltando), pedidos com divergência e total de peças conferidas. Um pedido fechado com pelo menos uma peça confirmada no olho conta como divergência mesmo estando completo — a garantia de "confirmado no olho" não é a mesma de bipado de verdade.\n\nTambém traz o que foi recusado (peça de outro pedido é o erro que a conferência existe pra pegar), os **códigos que o sistema não conhece** (a fila de cadastro de EAN), um resumo **por pessoa** (quantos pedidos cada uma conferiu e com quantas divergências) e a lista de pedidos com divergência, com o motivo registrado por quem fechou.',
    relacionados: ['mkt-conferencia-confirmar-no-olho', 'mkt-conferencia-bipagem-fluxo'],
  },

  // ---------------------------------------------------------------------
  // Etiquetas — /marketplace/etiquetas
  // ---------------------------------------------------------------------
  {
    id: 'mkt-etiquetas-converter-zpl',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Converter uma etiqueta ZPL em PDF pra imprimir',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'converter etiqueta zpl',
      'etiqueta do mercado livre full nao imprime',
      'transformar zpl em pdf',
      'colar codigo zpl',
      'imprimir etiqueta na impressora comum',
      'por que a etiqueta nao abre na impressora de casa',
      'analisar zpl antes de converter',
      'quantas etiquetas tem no arquivo',
    ],
    resposta:
      'A tela **Etiquetas de Envio** resolve um problema concreto: a etiqueta do Mercado Livre Full sai em **ZPL** (a linguagem das impressoras térmicas Zebra), e a impressora comum da casa só entende PDF. Na aba **Converter etiqueta**, cole o conteúdo ZPL (ou solte o arquivo .zpl/.txt) e o sistema analisa sozinho, mostrando quantas etiquetas existem naquele conteúdo (cada trecho entre `^XA` e `^XZ` vira uma página do PDF) e se dá pra converter tudo aqui dentro ou não.\n\nClicando em **Gerar PDF**, o arquivo abre numa aba nova, pronto pra mandar na impressora. O arquivo é lido no navegador e só sobe pro servidor quando a pessoa decide converter de fato.',
    relacionados: ['mkt-etiquetas-labelary-privacidade', 'mkt-etiquetas-tamanho-etiqueta', 'mkt-etiquetas-lote-expedicao'],
  },
  {
    id: 'mkt-etiquetas-labelary-privacidade',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Por que a opção da Labelary vem sempre desmarcada',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'o que e labelary',
      'comando nao desenhado na etiqueta',
      'por que preciso marcar uma caixinha para converter',
      'dados do comprador saindo da empresa',
      'etiqueta incompleta sem a labelary',
      'aviso de conversor local nao desenha',
      'reserva de conversao de etiqueta',
      'checkbox desmarcada de proposito',
      'endereco do comprador saindo da empresa',
    ],
    resposta:
      'O conversor **local** (dentro do próprio HBN Hub) não desenha todos os comandos ZPL que existem — quando uma etiqueta usa algum que ele não entende, esses trechos sairiam em branco. Nesse caso a tela mostra quais comandos são e oferece a opção de usar a **Labelary**, um serviço de conversão externo, como reserva.\n\nEssa opção nunca vem marcada de fábrica: usar a Labelary manda o conteúdo da etiqueta — nome e endereço do comprador incluídos — pra fora da empresa, e essa é uma decisão que precisa ser tomada conscientemente a cada etiqueta, não herdada de uma anterior. Trocar o conteúdo do campo ZPL zera a marcação de novo, pelo mesmo motivo: quem autorizou a etiqueta anterior não autorizou a próxima.',
    relacionados: ['mkt-etiquetas-converter-zpl', 'mkt-etiquetas-lote-expedicao'],
  },
  {
    id: 'mkt-etiquetas-tamanho-etiqueta',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Tamanho e densidade da etiqueta (dpmm, largura e altura)',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'tamanho da etiqueta errado',
      'etiqueta saiu cortada',
      'etiqueta saiu encolhida',
      'densidade da impressora dpmm',
      '8 dpmm ou 12 dpmm',
      'mudar largura e altura da etiqueta',
      'qual o tamanho padrao da etiqueta de envio',
      'etiqueta 10x15 centimetros',
      'campo de tamanho compartilhado entre converter e lote',
    ],
    resposta:
      'Os campos **Densidade da impressora**, **Largura da etiqueta** e **Altura da etiqueta** (em milímetros) definem o tamanho físico do PDF gerado — compartilhados entre a aba Converter e a aba Lote. O padrão é 8 dpmm (203 dpi) e 101,6 × 152,4 mm (10 × 15 cm), o tamanho de etiqueta de envio usado pelos marketplaces.\n\nSó vale mudar esses campos se a bobina da impressora for de fato outra: o PDF sai exatamente no tamanho escrito aqui, e uma medida que não bate com o papel de verdade imprime a etiqueta cortada ou encolhida no meio da folha.',
    relacionados: ['mkt-etiquetas-converter-zpl', 'mkt-etiquetas-lote-expedicao'],
  },
  {
    id: 'mkt-etiquetas-lote-expedicao',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Aba "Lote da expedição" — juntar várias etiquetas num PDF só',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'lote de etiquetas',
      'imprimir todas as etiquetas do dia de uma vez',
      'juntar etiquetas num pdf',
      'limite de etiquetas por lote',
      'ordem das etiquetas no pdf do lote',
      'adicionar varios arquivos zpl de uma vez',
      'tirar uma etiqueta do lote',
      'quantas etiquetas entraram no pdf do lote',
      'nome do arquivo baixado do lote',
    ],
    resposta:
      'A aba **Lote da expedição** junta as etiquetas do dia num único PDF, pra imprimir de uma vez em vez de abrir o painel de cada marketplace etiqueta por etiqueta. Dá pra soltar vários arquivos .zpl/.txt de uma vez ou colar o ZPL de uma etiqueta por vez; cada item entra numa linha da lista, com botão **Tirar** pra remover. A ordem do PDF final é a ordem da lista.\n\nO limite do servidor é de 500 etiquetas por lote. Se algum comando não for desenhado pelo conversor local, o mesmo aviso da Labelary aparece aqui (depois de a primeira tentativa voltar com erro), com a mesma escolha explícita de mandar ou não o conteúdo pra fora. Ao gerar, o PDF é baixado automaticamente com o nome "lote-etiquetas.pdf".',
    relacionados: ['mkt-etiquetas-converter-zpl', 'mkt-etiquetas-labelary-privacidade', 'mkt-etiquetas-tamanho-etiqueta'],
  },
  {
    id: 'mkt-etiquetas-lista-separacao-picking',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Aba "Lista de separação" — picking agregado por SKU',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'lista de separacao',
      'picking de pedidos',
      'separar varios pedidos de uma vez',
      'por que a lista soma por referencia e nao por pedido',
      'montar lista de separacao por numeros de pedido',
      'imprimir lista de separacao',
      'local da peca no galpao nao aparece',
      'colar lista de pedidos de uma vez so',
      'numero repetido na lista de separacao',
    ],
    resposta:
      'A aba **Lista de separação** recebe uma lista de números internos de pedido (colados de qualquer jeito — vírgula, ponto e vírgula, espaço ou quebra de linha; número repetido conta uma vez só) e monta uma lista de coleta pro galpão. Ela mostra quantos pedidos, quantas linhas pra separar e quantas peças no total; o botão **Imprimir lista** gera o PDF pra levar na bancada.\n\nA lista não é uma folha por pedido: ela soma a mesma referência, cor e tamanho de todos os pedidos numa linha só, ordenada pelo endereço no galpão — quem separa anda o corredor uma vez por referência, pegando de uma vez as peças de todos os pedidos daquela grade, em vez de repetir o mesmo caminho pedido por pedido. A divisão de qual peça vai em qual caixa acontece depois, na bipagem da Conferência de Pedidos.',
    relacionados: ['mkt-etiquetas-localizacao-galpao', 'mkt-conferencia-bipagem-fluxo'],
  },
  {
    id: 'mkt-etiquetas-localizacao-galpao',
    modulo: 'marketplace',
    tela: 'Etiquetas de Envio',
    titulo: 'Peça sem local cadastrado aparece por último na separação',
    rota: '/marketplace/etiquetas',
    perguntas: [
      'local da peca aparece vazio na lista de separacao',
      'peca sem localizacao na lista de separacao',
      'por que a linha foi para o fim da lista de separacao',
      'local vazio travessao na lista de separacao',
      'separacao no galpao fora de ordem',
      'picking sem endereco vai pro final',
    ],
    resposta:
      'Na Lista de separação, quando uma peça não tem endereço cadastrado no galpão, a coluna **Local** sai com travessão e a linha vai pro fim da lista — são justamente essas peças que fazem quem separa ficar procurando. Cadastrar o endereço em **Estoque › Onde Está a Peça** (ver verbete específico) tira a peça dessa situação nas próximas listas.',
    relacionados: ['mkt-etiquetas-lista-separacao-picking', 'estoque-locais-visao-geral-disponivel'],
  },

  // ---------------------------------------------------------------------
  // Romaneio — /marketplace/romaneio
  // ---------------------------------------------------------------------
  {
    id: 'mkt-romaneio-o-que-e',
    modulo: 'marketplace',
    tela: 'Romaneio de expedição',
    titulo: 'O que é o Romaneio e o que ele resolve',
    rota: '/marketplace/romaneio',
    perguntas: [
      'o que e romaneio de expedicao',
      'pra que serve o romaneio',
      'papel que o motorista assina',
      'prova que o pedido saiu da empresa',
      'coleta atrasada no mercado livre',
      'caixa entrando duas vezes na remessa',
      'diferenca entre romaneio e conferencia',
      'romaneio de coleta',
      'lista de pedidos para o transportador',
    ],
    resposta:
      'O **Romaneio de expedição** (`/marketplace/romaneio`) é o papel que o motorista assina ao levar os pedidos embora — e resolve três faltas que a etiqueta sozinha não cobria: não havia como provar que um pedido saiu da casa quando ele sumia depois; não havia como enxergar o que já devia ter sido coletado e não foi (o que custa reputação no Mercado Livre e na Shopee antes de custar dinheiro); e não havia trava contra a mesma caixa entrar em duas remessas ao mesmo tempo.\n\nÉ uma etapa depois da etiqueta e independente da Conferência de Pedidos: o romaneio junta pedidos **faturados** que ainda não foram coletados, sejam eles já conferidos na bipagem ou não.',
    relacionados: ['mkt-romaneio-criar-fechar-coletar', 'mkt-romaneio-prazos-situacao-coleta', 'mkt-romaneio-rastreio-congelado'],
  },
  {
    id: 'mkt-romaneio-criar-fechar-coletar',
    modulo: 'marketplace',
    tela: 'Romaneio de expedição',
    titulo: 'Criar, acrescentar pedidos, fechar e registrar a coleta de um romaneio',
    rota: '/marketplace/romaneio',
    perguntas: [
      'como criar um romaneio',
      'acrescentar pedidos ao romaneio',
      'fechar o romaneio para imprimir',
      'reabrir romaneio fechado',
      'registrar coleta motorista',
      'imprimir o papel do romaneio',
      'cancelar romaneio',
      'por que o romaneio fechado nao recebe mais pedido',
    ],
    resposta:
      '**Novo romaneio** cria um romaneio vazio e o abre na tela. Na lista **Esperando coleta**, marque os pedidos desejados e clique em **Mandar N para o romaneio** — o servidor pode recusar algum pedido (mostra o motivo, um por um, sem esconder nenhum), e o que entrou some da lista de pendentes.\n\n**Fechar** trava o romaneio: depois disso ele não recebe mais pedido, porque o papel na mão do motorista não pode discordar do sistema — mas ainda dá pra **Reabrir** enquanto ninguém coletou. Fechado, aparecem os botões **Imprimir** (abre o PDF do papel) e **Registrar coleta**, que pede o nome de quem está levando e, opcionalmente, a placa do veículo; a partir daí o romaneio vira **Coletado** e o relógio de prazo para para aqueles pedidos. **Cancelar** (disponível em Aberto ou Fechado) devolve os pedidos pra poderem entrar em outro romaneio.',
    relacionados: ['mkt-romaneio-o-que-e', 'mkt-romaneio-rastreio-congelado', 'mkt-romaneio-tirar-cancelar'],
  },
  {
    id: 'mkt-romaneio-rastreio-congelado',
    modulo: 'marketplace',
    tela: 'Romaneio de expedição',
    titulo: 'Por que o código de rastreio fica congelado no romaneio',
    rota: '/marketplace/romaneio',
    perguntas: [
      'rastreio congelado no romaneio',
      'reetiquetar pedido depois do romaneio',
      'codigo de rastreio mudou mas o papel nao',
      'pedido sem rastreio no romaneio',
      'sem rastreio no papel impresso',
      'reetiquetar pedido que ja esta no romaneio',
      'papel assinado com rastreio diferente do atual',
      'indicador de sem rastreio na lista de romaneios',
    ],
    resposta:
      'O código de rastreio de um pedido fica **congelado** no momento em que ele entra no romaneio: o pedido pode até ser reetiquetado depois, mas o papel já assinado pelo motorista continua dizendo o que dizia na hora da coleta — trocar o rastreio depois não reescreve um documento já assinado.\n\nPedido sem nenhum código de rastreio cadastrado entra do mesmo jeito, mas aparece na tabela do romaneio marcado como **SEM RASTREIO** — é um alerta pra conferir antes de o motorista sair, não depois. O indicador "Sem rastreio" na lista de romaneios mostra quantos pedidos de cada romaneio estão nessa situação.',
    relacionados: ['mkt-romaneio-criar-fechar-coletar', 'mkt-romaneio-o-que-e'],
  },
  {
    id: 'mkt-romaneio-prazos-situacao-coleta',
    modulo: 'marketplace',
    tela: 'Romaneio de expedição',
    titulo: 'Situação de coleta (atrasado, apertado, no prazo) e prazo por canal',
    rota: '/marketplace/romaneio',
    perguntas: [
      'pedido atrasado para coleta',
      'o que e apertado na coleta',
      'sem prazo conhecido o que significa',
      'prazo de coleta por canal',
      'de onde vem o prazo de cada plataforma',
      'mudar horas para coleta de um canal',
      'quando o relogio de coleta comeca',
      'horas para coletar por canal',
      'dois tercos do prazo de coleta',
    ],
    resposta:
      'Cada pedido esperando coleta recebe uma situação: **Atrasado** (passou do prazo do canal — reputação em risco), **Apertado** (já passou de dois terços do prazo), **No prazo**, **Sem prazo conhecido** (o canal não tem prazo cadastrado — não é "em dia", é "ninguém sabe": esses pedidos não entram na conta de atraso até o prazo ser cadastrado) e **Não faturado** (o relógio só começa a contar no faturamento).\n\nA tabela **Prazo de coleta por canal**, no fim da página, mostra as horas cadastradas para cada canal, editáveis diretamente no campo numérico. Os números de partida vieram do padrão divulgado por cada plataforma e servem só como ponto de partida: o prazo real muda com o plano da loja, a modalidade de envio e a região, então vale conferir no painel de cada canal.',
    relacionados: ['mkt-romaneio-o-que-e', 'mkt-romaneio-criar-fechar-coletar'],
  },
  {
    id: 'mkt-romaneio-tirar-cancelar',
    modulo: 'marketplace',
    tela: 'Romaneio de expedição',
    titulo: 'Tirar um pedido do romaneio e histórico de saídas',
    rota: '/marketplace/romaneio',
    perguntas: [
      'tirar pedido do romaneio',
      'liberar pedido do romaneio',
      'por que preciso escrever motivo para tirar pedido',
      'pedido saiu do romaneio fica registrado',
      'historico de pedidos liberados do romaneio',
      'tirei o pedido errado do romaneio',
      'pedido some do romaneio depois de tirado',
      'lista de saidas do romaneio',
    ],
    resposta:
      'Com o romaneio ainda **Aberto**, cada linha da lista de pedidos tem um botão **Tirar**, que pede o motivo antes de liberar o pedido — ele volta a poder entrar em outro romaneio. Pedidos liberados não desaparecem: ficam numa lista separada, "Saíram deste romaneio", com o motivo registrado, de propósito, pra manter o histórico completo do que passou por ali.',
    relacionados: ['mkt-romaneio-criar-fechar-coletar'],
  },

  // ---------------------------------------------------------------------
  // Promoções — /marketplace/promocoes
  // ---------------------------------------------------------------------
  {
    id: 'mkt-promocoes-o-que-e',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'O que é a tela de Promoções e por que ela mostra margem',
    rota: '/marketplace/promocoes',
    perguntas: [
      'o que e a tela de promocoes',
      'pra que serve promocoes do marketplace',
      'ver todas as promocoes das lojas',
      'sincronizar promocoes',
      'promocao nao aparece na lista',
      'margem no preco promocional',
      'o hub decide o preco da promocao',
      'quais lojas entram nas promocoes',
      'andamento da sincronizacao de promocoes',
    ],
    resposta:
      'A tela **Promoções** reúne as promoções de todas as lojas conectadas (Shopee, TikTok Shop, Mercado Livre) num só lugar, mostrando — pra cada item em promoção — a margem que sobra naquele preço promocional. Antes dela, a única forma de acompanhar promoção era o painel de cada plataforma, sem visibilidade nenhuma de quanto de margem estava sendo dado.\n\nO botão **Sincronizar** busca o que existe nas plataformas; enquanto roda, a faixa de andamento mostra loja por loja o que já foi lido. O sistema **não decide** se um preço promocional ou um desconto está certo — ele mostra o número calculado (lucro, margem, prejuízo) e quem decide é sempre a pessoa, item por item, na prévia antes de qualquer coisa ser enviada à plataforma.',
    relacionados: ['mkt-promocoes-margem-ao-vivo', 'mkt-promocoes-criar-nova', 'mkt-promocoes-tipos-por-plataforma'],
  },
  {
    id: 'mkt-promocoes-margem-ao-vivo',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'O selo de margem — como ele funciona e o que cada cor mostra',
    rota: '/marketplace/promocoes',
    perguntas: [
      'selo de margem na promocao',
      'margem recalculando',
      'prejuizo em vermelho na promocao',
      'abaixo da margem minima',
      'por que a margem demora para atualizar',
      'margem indisponivel o que significa',
      'sem produto vinculado sem margem',
      'cor do selo de margem na promocao',
      'margem recalculada apos editar preco',
    ],
    resposta:
      'Toda vez que um preço promocional é editado num campo da tela, a margem daquela linha é recalculada perguntando de novo ao motor de precificação — que é quem conhece o custo do produto, os impostos da empresa e as taxas do marketplace; a tela nunca calcula margem sozinha. Enquanto a resposta não chega, o selo mostra "…" (recalculando), pra nunca exibir o número antigo como se já valesse para o preço novo.\n\nO selo tem três tons: verde (margem saudável), laranja (abaixo da margem mínima — continua sendo uma decisão de quem está editando, o sistema só avisa) e vermelho com ícone de alerta (prejuízo — o preço fica abaixo do custo total da peça). Quando não dá pra calcular (anúncio sem produto vinculado, ou produto sem custo cadastrado), o selo mostra travessão em vez de inventar um número.',
    relacionados: ['mkt-promocoes-criar-nova', 'mkt-promocoes-editar-item-painel'],
  },
  {
    id: 'mkt-promocoes-criar-nova',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'Criar uma promoção nova — os 4 passos e a prévia obrigatória',
    rota: '/marketplace/promocoes',
    perguntas: [
      'como criar uma promocao',
      'nova promocao passo a passo',
      'escolher loja para criar promocao',
      'selecionar anuncios para promocao',
      'previa antes de enviar promocao',
      'desconto percentual preco fixo margem alvo',
      'itens recusados pela plataforma na promocao',
      'passo a passo para criar promocao',
      'nada e enviado antes da previa',
    ],
    resposta:
      'O botão **Nova promoção** abre um fluxo em 4 passos: 1) escolher a **Loja** e o **Tipo** de promoção (o que a plataforma permite criar varia — veja o verbete específico sobre isso); 2) escolher **Quais anúncios** entram, com um seletor que por padrão só mostra os que ainda não estão em nenhuma promoção (evita empilhar dois descontos no mesmo anúncio); 3) escolher **Por qual preço**, com três formas de calcular — desconto percentual sobre o preço de hoje, preço fixo igual para todos, ou uma margem-alvo que o motor de precificação resolve item a item; 4) a **prévia**, que mostra linha por linha o preço final e a margem antes de qualquer coisa sair daqui.\n\nNenhuma ação em massa sai sem passar pela prévia — é uma das travas decididas de propósito nessa tela. Ao confirmar, se a plataforma recusar algum item, a tela mostra quantos entraram e o motivo de cada recusa, nunca só "N de M entraram" em silêncio.',
    relacionados: ['mkt-promocoes-margem-ao-vivo', 'mkt-promocoes-tipos-por-plataforma', 'mkt-promocoes-acrescentar-existente'],
  },
  {
    id: 'mkt-promocoes-tipos-por-plataforma',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'O que cada plataforma deixa criar (e a Relâmpago da Shopee)',
    rota: '/marketplace/promocoes',
    perguntas: [
      'quais tipos de promocao da para criar',
      'criar promocao relampago na shopee',
      'shopee relampago',
      'criar promocao no mercado livre',
      'shein nao tem criacao de promocao',
      'horario fixo da relampago',
      'estoque reservado na relampago',
      'desconto minimo e maximo da relampago',
      'quais plataformas deixam criar promocao pela api',
      'tipos de promocao disponiveis por loja',
    ],
    resposta:
      'Nem toda plataforma deixa **criar** promoção pela API — algumas só permitem ler o que já existe. Na Shopee e no TikTok Shop dá pra criar **Desconto de loja** e **Relâmpago**; no Mercado Livre só **Desconto individual**; na Shein não dá pra criar nenhuma por aqui. A tela mostra só os tipos que a loja escolhida permite, em vez de deixar preencher o formulário inteiro pra descobrir o erro só no fim.\n\nA **Relâmpago** (Shopee) tem regras próprias: não tem data de início digitada à mão — só existe em faixas fixas de horário que a própria plataforma define, listadas como cartões clicáveis; exige um **estoque reservado** por variação, que começa igual ao estoque atual do anúncio e fica editável linha a linha na prévia; e a Shopee cobra critérios mínimos (desconto dentro de uma faixa, estoque reservado mínimo, nota mínima do produto), que a tela mostra e a prévia confere item por item.',
    relacionados: ['mkt-promocoes-criar-nova', 'mkt-promocoes-margem-ao-vivo'],
  },
  {
    id: 'mkt-promocoes-acrescentar-existente',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'Acrescentar itens a uma promoção que já existe',
    rota: '/marketplace/promocoes',
    perguntas: [
      'acrescentar item a promocao existente',
      'esqueci uma referencia na promocao',
      'juntar itens na mesma promocao',
      'por que nao posso escolher promocao encerrada como destino',
      'adicionar anuncio depois de criar a promocao',
      'destino nova promocao ou existente',
      'duas promocoes com o mesmo nome',
      'campo destino no formulario de promocao',
    ],
    resposta:
      'No passo 1 do fluxo de criação, o campo **Destino** deixa escolher entre "Criar uma promoção nova" ou "Acrescentar a uma existente" — só aparecem como destino as promoções da mesma loja que ainda estão **no ar** ou **agendadas** (oferecer uma já encerrada como destino seria oferecer um envio que a própria plataforma recusaria). O resto do fluxo é igual: selecionar anúncios, escolher a regra de preço e conferir a prévia antes de enviar.\n\nIsso existe porque, antes, esquecer uma referência na hora de criar obrigava a criar outra promoção com o mesmo nome — duas promoções concorrendo pela mesma peça na plataforma.',
    relacionados: ['mkt-promocoes-criar-nova', 'mkt-promocoes-editar-item-painel'],
  },
  {
    id: 'mkt-promocoes-editar-item-painel',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'Painel de uma promoção — editar preços em massa, marcar itens e remover',
    rota: '/marketplace/promocoes',
    perguntas: [
      'editar preco de item ja na promocao',
      'abrir uma promocao para editar',
      'aplicar desconto em todos os itens da promocao',
      'marcar itens da promocao para editar so alguns',
      'tirar item da promocao',
      'itens recusados pela plataforma na promocao',
      'itens sem vinculo na promocao',
      'salvar precos na plataforma',
      'aba itens do painel de promocao',
    ],
    resposta:
      'Clicando num cartão de promoção na lista, abre o painel dela na aba **Itens**: uma tabela com todos os anúncios daquela promoção, preço de origem, preço promocional (editável célula a célula), desconto calculado e margem. A barra de regra em massa aplica desconto percentual, preço fixo ou margem-alvo — nos itens **marcados** com a caixinha da esquerda, ou em todos se nada estiver marcado.\n\nItem sem produto vinculado no sistema aparece com o selo "sem vínculo" e a margem sai como indisponível; item que a plataforma recusou aparece com o selo "recusado" e o motivo, se informado. O botão **Salvar preços na plataforma** só liga quando existe alteração de verdade — e antes de enviar, o sistema confere a margem de novo com os preços que estão nos campos naquele instante, mostrando na confirmação se algum item ficará com prejuízo. **Tirar da promoção** remove os itens marcados direto na plataforma.',
    relacionados: ['mkt-promocoes-margem-ao-vivo', 'mkt-promocoes-acrescentar-existente', 'mkt-promocoes-encerrar-excluir-historico'],
  },
  {
    id: 'mkt-promocoes-encerrar-excluir-historico',
    modulo: 'marketplace',
    tela: 'Promoções',
    titulo: 'Encerrar, editar nome/datas, excluir uma promoção e ver o histórico',
    rota: '/marketplace/promocoes',
    perguntas: [
      'encerrar promocao',
      'editar nome e data da promocao',
      'excluir promocao',
      'por que nao consigo excluir promocao ativa',
      'promocao do mercado livre nao deixa editar janela',
      'historico de alteracoes da promocao',
      'quem alterou o preco da promocao',
      'aba historico da promocao',
      'promocao relampago nao deixa editar horario',
    ],
    resposta:
      'No painel de uma promoção, **Encerrar promoção** tira os itens dela na plataforma (pede confirmação, mostrando nome da promoção e da loja). **Editar nome e datas** só aparece quando a plataforma aceita mexer na janela por fora dos itens — no Mercado Livre a janela vive em cada item, não na promoção, e na Relâmpago da Shopee o horário é fixo desde a criação, então nesses casos o botão nem aparece. **Excluir** só existe pra promoção que ainda não começou (status diferente de "No ar") e também não está disponível pra Mercado Livre.\n\nA aba **Histórico**, dentro do mesmo painel, lista cada alteração registrada — de onde veio (pelo Hub, com o nome de quem mandou, ou direto na plataforma) e quando começou a ser gravada; o que aconteceu antes do início do registro não aparece.',
    relacionados: ['mkt-promocoes-editar-item-painel'],
  },

  // ---------------------------------------------------------------------
  // Saúde da Sincronização — /marketplace/saude
  // ---------------------------------------------------------------------
  {
    id: 'mkt-saude-sincronizacao-o-que-e',
    modulo: 'marketplace',
    tela: 'Saúde da Sincronização',
    titulo: 'O que é a Saúde da Sincronização e o que ela torna visível',
    rota: '/marketplace/saude',
    perguntas: [
      'o que e saude da sincronizacao',
      'pedido que nao entrou no sistema',
      'pedido pago mas nao aparece',
      'por que um pedido sumiu da importacao',
      'conexao parada com o marketplace',
      'venda existe na plataforma mas nao no hub',
      'janela de sincronizacao de 7 dias',
      'estoque e lucratividade incompletos por pedido perdido',
      'por que a saude da sincronizacao existe',
    ],
    resposta:
      'A tela **Saúde da Sincronização** (`/marketplace/saude`) mostra pedidos que falharam ao ser importados de um marketplace e nunca foram tentados de novo — antes dela, o erro de importação ia para um campo que guarda só o último erro e é sobrescrito a cada ciclo (5 minutos), e quando a data do pedido passava dos dias da janela de ressincronização, ele saía da busca automática pra sempre, sem ninguém ser avisado. Uma venda paga pelo cliente simplesmente deixava de existir no sistema, e estoque, lucratividade e conferência passavam a trabalhar em cima de um faturamento incompleto sem sinal nenhum disso.\n\nA tela separa três situações que antes eram tratadas como uma coisa só: **conexão parada** (enquanto estiver assim, nada novo entra por ela), **pedido que falhou mas ainda está na janela** (vai ser tentado sozinho no próximo ciclo) e **pedido que falhou e já saiu da janela** (fica fora até alguém mandar buscar de novo — é o único caso que tem botão de ação).',
    relacionados: ['mkt-saude-sincronizacao-conexoes-paradas', 'mkt-saude-sincronizacao-buscar-de-novo'],
  },
  {
    id: 'mkt-saude-sincronizacao-conexoes-paradas',
    modulo: 'marketplace',
    tela: 'Saúde da Sincronização',
    titulo: 'Indicadores do topo e a tabela de conexões',
    rota: '/marketplace/saude',
    perguntas: [
      'fora do sistema o que significa',
      'ainda vai tentar o que significa',
      'valor que nao entrou',
      'pedido mais antigo pendente',
      'conexao parada sem autorizacao token vencido',
      'sincronizar uma conexao agora',
      'por que a conexao fica vermelha',
      'ultima sincronizacao da loja',
      'valor total que ficou de fora',
    ],
    resposta:
      'Os indicadores do topo resumem o tamanho do problema: **Fora do sistema** (pedidos que falharam e já saíram da janela de ressincronização — não serão procurados sozinhos), **Ainda vai tentar** (falharam mas o pedido ainda está na janela, a sincronização volta sozinha a cada poucos minutos), **Valor que não entrou** (soma dos pedidos com valor conhecido — quando existem pedidos sem valor conhecido, o texto avisa que o total real é maior, nunca soma como R$ 0,00) e **Mais antigo** (data do pedido mais velho ainda faltando).\n\nA tabela **As conexões** lista cada loja conectada com sua situação (parada, sem autorização, token vencido, entre outras) e a última sincronização; linhas em situação ruim ficam destacadas, porque uma conexão parada é considerada pior do que qualquer pedido perdido — enquanto ela estiver assim, nenhum pedido novo entra por ali. O botão **Sincronizar agora** força um ciclo imediato daquela conexão.',
    relacionados: ['mkt-saude-sincronizacao-o-que-e', 'mkt-saude-sincronizacao-buscar-de-novo'],
  },
  {
    id: 'mkt-saude-sincronizacao-buscar-de-novo',
    modulo: 'marketplace',
    tela: 'Saúde da Sincronização',
    titulo: '"Buscar de novo" e "Encerrar" um pedido que não entrou',
    rota: '/marketplace/saude',
    perguntas: [
      'buscar pedido de novo na saude da sincronizacao',
      'encerrar pendencia sem importar',
      'pedido que ja saiu da janela de sincronizacao',
      'tentativas de importacao de um pedido',
      'categorias de erro de importacao',
      'pendencias resolvidas',
      'como saber se o pedido voltou',
      'quantas tentativas o pedido ja teve',
      'encerrar pedido sem importar fica registrado',
    ],
    resposta:
      'Cada linha da lista **Pedidos que não entraram** mostra o erro categorizado (com uma explicação do que fazer) e o texto técnico original, além de quantas tentativas já houve. O botão **Buscar de novo** vai direto na API do marketplace pelo ID do pedido e tenta importar de novo — é o único caminho para os pedidos que já saíram da janela de dias (contada a partir da **data do pedido**, não da data da falha: um pedido antigo que só falhou hoje já pode estar fora da janela). **Encerrar** tira o pedido da lista sem importar — nada é apagado, fica registrado quem encerrou e quando.\n\nA seção recolhida "N pendências resolvidas" guarda o histórico de dias recentes: pedidos que voltaram sozinhos ("importado") ou foram encerrados por alguém ("encerrado por uma pessoa") — é aonde ir pra conferir se o que falhou ontem realmente voltou.',
    relacionados: ['mkt-saude-sincronizacao-o-que-e', 'mkt-saude-sincronizacao-conexoes-paradas'],
  },
];
