// Verbetes do módulo Marketplace — pedidos de marketplace (/marketplace/pedidos,
// origemFiltro="marketplace" de PedidosListPage), Lucratividade de Marketplace
// (/marketplace/lucratividade, origemFiltro="marketplace" de
// RelatorioLucratividadePage — mesmo componente do módulo Vendas, mas aqui
// documento só o que aparece quando a origem é "marketplace": Ads/TACOS/MPA,
// valor recebido/escrow, vincular produto, duplicatas suspeitas, buscar
// pedido por origem, sub-abas Resumo por Produto/Vendas/Não Avaliáveis),
// Métricas de Marketplace (/marketplace/metricas, 11 sub-abas de
// MetricasMarketplacePage), Taxas de Marketplace (/marketplace/taxas,
// RelatorioTaxasPage) e Importar Pedidos (/marketplace/importar-pedidos,
// ImportarPedidosPage — planilha do Mercado Livre, Shopee ou UpSeller).

export const verbetesMarketplace = [
  {
    id: 'mkt-pedidos-listar-filtrar',
    modulo: 'marketplace',
    tela: 'Pedidos de Marketplace',
    titulo: 'Ver e filtrar os pedidos de marketplace',
    rota: '/marketplace/pedidos',
    perguntas: [
      'onde vejo os pedidos de marketplace',
      'pedidos do mercado livre',
      'pedidos da shopee',
      'lista de pedidos de marketplace',
      'filtrar pedidos por plataforma',
      'filtrar pedidos por loja',
      'de quanto em quanto tempo os pedidos chegam',
      'sincronizacao automatica de pedidos',
      'nao tem botao de novo pedido no marketplace',
      'pedidos chegam sozinhos',
      'buscar pedido de marketplace por numero',
    ],
    resposta:
      'A tela **Pedidos de Marketplace** lista os pedidos importados do Mercado Livre, Shopee, TikTok Shop e demais marketplaces conectados. Diferente da tela de Vendas, aqui não tem botão de "Novo pedido": pedidos chegam sozinhos, sincronizados a cada 5 minutos pelas integrações conectadas em **Integrações**, ou por importação de planilha (tela **Importar Pedidos**).\n\nDá pra filtrar por período, plataforma (Mercado Livre, Shopee, TikTok Shop...), loja/integração específica, situação e por texto (número do pedido, cliente etc.). Se a lista estiver vazia, o próprio sistema sugere ir em Integrações pra conectar uma loja.',
    relacionados: ['mkt-importar-pedidos', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-kpis',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Indicadores da Lucratividade de Marketplace (Faturamento, Lucro, Margem...)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'lucratividade de marketplace',
      'lucro dos pedidos de marketplace',
      'faturamento do marketplace',
      'quanto ganhei no mercado livre',
      'quanto ganhei na shopee',
      'margem dos pedidos de marketplace',
      'ticket medio marketplace',
      'roi do marketplace',
      'numero de vendas marketplace',
      'unidades vendidas marketplace',
      'liquido do marketplace',
      'selo de confianca da lucratividade',
      'pedido marcado como estimativa',
      'frete nao entra no faturamento',
    ],
    resposta:
      'A tela **Lucratividade de Marketplace** calcula o lucro real de cada pedido de marketplace: valor de verdade recebido do marketplace (o pagamento no Mercado Livre, a conciliação/escrow na Shopee) menos custo de produção, embalagem e imposto — quando esse valor já está confirmado. Pedido ainda sem confirmação usa uma estimativa baseada no preço de venda, e fica marcado com o selo **estimativa**.\n\n**Indicadores do topo**\n\nFaturamento, Líq. do Marketplace, Lucro Bruto e Margem vêm primeiro; embaixo, Número de Vendas, Unidades Vendidas, Ticket Médio e Retorno Sobre Investimento (ROI). O Frete aparece à parte (não entra no Faturamento — é dinheiro do comprador/transportadora, não da loja).\n\nNo rodapé, o **selo de confiança** mostra sobre quantos pedidos o cálculo foi feito, de quantos existem no período, e quantos ficaram de fora por falta de custo de material cadastrado — com link pra auditoria em Saúde dos Dados.',
    relacionados: ['mkt-lucratividade-ads', 'mkt-lucratividade-recebido-escrow', 'mkt-lucratividade-nao-avaliaveis'],
  },
  {
    id: 'mkt-lucratividade-ads',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Custo de Ads, TACOS, Lucro Pós Ads e MPA',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'tacos',
      'o que e tacos',
      'mpa',
      'o que e mpa',
      'lucro pos ads',
      'valor gasto em ads',
      'custo de publicidade no lucro',
      'como o ads e rateado no lucro',
      'gasto de anuncio nao atribuido',
      'ads sem venda no dia',
    ],
    resposta:
      'Quando existe gasto de Ads sincronizado no período, a Lucratividade de Marketplace mostra mais quatro indicadores: **Valor em Ads** (gasto total, dividido em "atribuído" a alguma venda do dia e "sem venda no dia"), **TACOS** (o gasto de Ads como % do faturamento), **Lucro Pós Ads** (o lucro depois de descontar o Ads) e **MPA** — a margem sobre esse lucro pós Ads.\n\nO rateio do Ads por pedido é o gasto do dia daquele anúncio dividido por todas as unidades vendidas do anúncio naquele dia — pode mudar se a tela for recalculada depois, porque uma venda cancelada altera esse divisor. Quem sincroniza o histórico de gasto por anúncio é a aba **Publicidade** da tela Métricas.',
    relacionados: ['mkt-lucratividade-kpis', 'mkt-metricas-publicidade', 'mkt-lucratividade-resumo-produto'],
  },
  {
    id: 'mkt-lucratividade-recebido-escrow',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Valor recebido, liberado, confirmado e conciliação (escrow)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'valor recebido do marketplace',
      'o que e escrow',
      'conciliacao da shopee',
      'valor liberado no saldo',
      'valor confirmado ainda retido',
      'sem confirmacao ainda',
      'quando o dinheiro do mercado livre cai',
      'quando a shopee libera o pagamento',
      'coluna recebido da tabela de pedidos',
    ],
    resposta:
      '**Valor Liberado no Saldo** é o dinheiro que o marketplace já colocou de fato disponível pra saque/uso; **Valor Confirmado, Ainda Retido** é o que já está confirmado mas ainda preso (prazo de liberação); e **Sem Confirmação Ainda** conta os pedidos que ainda não têm nenhum valor recebido confirmado.\n\nNa coluna **Recebido** da tabela de pedidos, cada linha mostra o valor com o selo **liberado** ou **confirmado** (com a data em que libera, quando ainda está retido) — passando o mouse no cabeçalho da coluna aparece a explicação: é o valor que o marketplace pagou de verdade, o pagamento no Mercado Livre ou a conciliação (escrow) na Shopee. Pedido de plataforma sem repasse rastreado mostra um traço nessa coluna.',
    relacionados: ['mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-vincular-produto',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Vincular ou trocar o produto de um item de pedido',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'vincular produto no pedido de marketplace',
      'item sem vinculo',
      'trocar produto vinculado ao pedido',
      'sku do anuncio nao bate',
      'alterar produto do item',
      'botao vincular na tabela de pedidos',
      'revincular custos e impostos',
      'item fantasma',
    ],
    resposta:
      'Na tabela de pedidos, cada linha tem um botão **Vincular** (quando o item ainda não tem produto associado) ou **Alterar** (quando já tem, mas quer trocar). Ele abre uma janela com todos os itens do pedido: pra cada um, é possível buscar por referência, descrição ou EAN e clicar em **Selecionar** pra ligar aquele item a uma variante do estoque.\n\nO botão **Revincular custos e impostos** (na barra de ações do topo, e também na tela Taxas de Marketplace) tenta vincular em lote todos os itens sem correspondência automática, além de atualizar empresa/% de nota fiscal, corrigir pagamento vinculado errado, preencher ID de anúncio e dado de pacote faltando, e remover item "fantasma" (mesmo SKU duplicado com valor zerado cobrando custo sem receita). Ele mostra um resumo do que foi corrigido ao terminar — se ainda sobrar algo, é só clicar de novo (corrige em lotes).',
    relacionados: ['mkt-lucratividade-nao-avaliaveis', 'mkt-taxas-cobradas'],
  },
  {
    id: 'mkt-lucratividade-nao-avaliaveis',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Não Avaliáveis" — pedidos sem custo cadastrado',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'pedidos nao avaliaveis',
      'pedido sem custo cadastrado',
      'por que um pedido nao entra no total',
      'aba nao avaliaveis',
      'referencia nao cadastrada no pedido de marketplace',
      'sku do anuncio em formato desconhecido',
    ],
    resposta:
      'A sub-aba **Não Avaliáveis** só aparece quando existe pelo menos um pedido com item sem produto vinculado — referência não cadastrada, ou SKU do anúncio num formato que o sistema não reconhece. Sem custo de verdade pra calcular, esses pedidos ficam de fora do total agregado do topo (custo zero não é a mesma coisa que custo baixo).\n\nA lista mostra pedido, data, cliente, receita e o(s) item(ns) sem vínculo. Pra fazer esses pedidos voltarem a entrar na conta, vincule o produto certo na aba Pedidos (botão **Vincular**), ou cadastre a referência que está faltando.',
    relacionados: ['mkt-lucratividade-vincular-produto', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-duplicatas-suspeitas',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Avisos de possível receita duplicada (pacote e troca)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'receita duplicada',
      'venda contada duas vezes',
      'pedido de pacote duplicado',
      'possivel troca suspeita',
      'mesmo comprador mesmo valor dias diferentes',
      'aviso de duplicata no marketplace',
      'excesso de receita possivel',
    ],
    resposta:
      'Quando existe algum caso, dois avisos amarelos podem aparecer no topo da Lucratividade de Marketplace:\n\n**Possível receita duplicada entre pedidos de pacote** — mesmo SKU, preço e quantidade aparecendo em mais de um pedido dentro do mesmo pacote do Mercado Livre; pode ser a mesma venda contada duas vezes.\n\n**Possível receita duplicada por troca** — mesmo comprador, mesmo valor, em dias diferentes; assinatura de uma troca do Mercado Livre que virou pedido novo em vez de ficar vinculada ao original.\n\nOs dois são só informativos: o sistema não tem confiança suficiente pra corrigir sozinho (não confirma o vínculo direto pela API), então nunca desconta nada do total agregado automaticamente. A recomendação é conferir cada caso no painel do Mercado Livre antes de decidir o que fazer.',
    relacionados: ['mkt-lucratividade-buscar-pedido-origem'],
  },
  {
    id: 'mkt-lucratividade-buscar-pedido-origem',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Buscar um pedido do Mercado Livre por número (investigação)',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'buscar pedido do mercado livre por numero',
      'conferir pedido direto no mercado livre',
      'pedido nao apareceu no sistema',
      'item de pacote sumiu',
      'ferramenta de investigacao de pedido',
      'colar numero do pedido do mercado livre',
    ],
    resposta:
      'O link **Buscar pedido do Mercado Livre por número** (acima da tabela de pedidos) abre uma ferramenta de investigação: cole o número de um pedido ou pacote visto direto no painel do Mercado Livre, e ela busca ao vivo na API — mesmo que esse pedido nunca tenha sido importado pra cá — pra conferir se ele existe no sistema, quais itens o Mercado Livre diz que ele tem, e quais outros pedidos do mesmo pacote já estão gravados aqui.\n\nServe principalmente pra achar item de pacote que sumiu: existe no Mercado Livre mas nunca virou pedido/item no sistema. O número também pode ser reconhecido como número de envio ou de pacote, não só de pedido — a ferramenta avisa qual dos três tipos encontrou.',
    relacionados: ['mkt-lucratividade-duplicatas-suspeitas'],
  },
  {
    id: 'mkt-lucratividade-resumo-produto',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Resumo por Produto" — histórico e lucro por produto',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'resumo por produto marketplace',
      'lucro por produto no marketplace',
      'grafico de lucratividade',
      'historico de lucratividade',
      'qual produto mais vendeu no marketplace',
      'representatividade do produto no faturamento',
      'custo de ads por produto',
    ],
    resposta:
      'A sub-aba **Resumo por Produto** mostra um gráfico de área (Faturamento, Líq. do Marketplace e Lucro Bruto ao longo dos dias do período) e, embaixo, uma tabela por produto: preço médio, custo unitário médio, unidades vendidas, total faturado, representatividade no faturamento, lucro bruto, margem bruta e — quando há Ads no período — custo de Ads (rateado por unidade do dia) e lucro/margem pós Ads.\n\nO gráfico e os indicadores de cima (Número de Vendas, Unidades Vendidas, Ticket Médio, ROI, Ads/TACOS/MPA quando houver) podem ser recolhidos clicando na seta, deixando só a tabela por produto visível.',
    relacionados: ['mkt-lucratividade-ads', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-lucratividade-aba-vendas',
    modulo: 'marketplace',
    tela: 'Lucratividade de Marketplace',
    titulo: 'Aba "Vendas" — detalhe de cada venda em cartão',
    rota: '/marketplace/lucratividade',
    perguntas: [
      'aba vendas da lucratividade de marketplace',
      'cartao de venda individual',
      'ver detalhe de uma venda de marketplace',
      'diferenca entre aba pedidos e aba vendas',
    ],
    resposta:
      'A sub-aba **Vendas** mostra os mesmos pedidos do período, só que em formato de cartão (um por pedido) em vez de linha de tabela — útil pra olhar o detalhe de uma venda sem precisar rolar a tabela pro lado. Usa o mesmo filtro de busca por texto e o mesmo período da aba Pedidos, só muda a apresentação.',
    relacionados: ['mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-metricas-visao-geral',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Painel de Métricas de Marketplace — visão geral e por loja',
    rota: '/marketplace/metricas',
    perguntas: [
      'metricas de marketplace',
      'diferenca entre metricas e lucratividade',
      'visao geral de vendas do marketplace',
      'valor total de vendas vs vendas validas',
      'pedidos validos',
      'clientes do marketplace',
      'vendas por cliente',
      'variacao em relacao ao periodo anterior',
      'comparar loja com loja',
    ],
    resposta:
      'A tela **Métricas de Marketplace** é um painel de acompanhamento de vendas — volume, pedidos, clientes, produtos e estoque — separado da Lucratividade (que foca em custo/lucro). Tem 11 sub-abas: as 6 primeiras aparecem direto (Visão Geral, Por Loja, Vendas por Anúncio, Análise ABC, Entrada e Saída, Reputação), e o resto fica agrupado num menu "Mais" (Opiniões, Concorrentes, Publicidade, Categorias, Shopee).\n\nOs indicadores de resumo (Visão Geral e Por Loja) são: **Valor Total de Vendas** e **Total de Pedidos** (todo pedido importado, sem filtrar cancelado), e **Valor de Vendas Válidas** e **Pedidos Válidos** (só pedidos não cancelados — a mesma contagem que aparece no painel do Mercado Livre, agrupada por pacote/carrinho), além de Clientes e Vendas por Cliente. Cada número tem uma variação (%) comparando com o período anterior equivalente. A aba **Por Loja** quebra os mesmos indicadores por loja/canal conectado.',
    relacionados: ['mkt-metricas-vendas-anuncio-abc', 'mkt-lucratividade-kpis'],
  },
  {
    id: 'mkt-metricas-vendas-anuncio-abc',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Abas "Vendas por Anúncio" e "Análise ABC"',
    rota: '/marketplace/metricas',
    perguntas: [
      'vendas por anuncio',
      'quanto cada anuncio vendeu',
      'curva abc de produtos',
      'classificacao abc marketplace',
      'produto classe a b c',
      'anuncio sem id gravado',
      'representatividade acumulada',
    ],
    resposta:
      'A aba **Vendas por Anúncio** mostra, por ID de anúncio do marketplace, quantos pedidos válidos, unidades vendidas, preço médio e total faturado ele teve — item importado antes de o sistema guardar o ID do anúncio aparece marcado "sem ID gravado" e entra agrupado por SKU nesse caso.\n\nA aba **Análise ABC** classifica os produtos pela curva de Pareto sobre o faturamento: classe **A** = produtos que somam até 80% do faturamento acumulado, **B** = até 95%, **C** = o restante — ordenado do que mais fatura pro que menos fatura. Ajuda a enxergar quais produtos merecem mais atenção em estoque, reposição ou campanha.',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-entrada-saida',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Entrada e Saída" — saídas de estoque pelas vendas',
    rota: '/marketplace/metricas',
    perguntas: [
      'entrada e saida de estoque no marketplace',
      'saida de estoque pela venda',
      'quanto saiu de estoque no marketplace',
      'estoque baixado pela venda de marketplace',
    ],
    resposta:
      'A aba **Entrada e Saída** mostra as saídas de estoque geradas pelas vendas de marketplace no período, calculadas direto pela quantidade de itens vendidos — não depende de nenhuma ação manual tipo "Faturar" (que existe só nos pedidos manuais de Vendas). A baixa de estoque de um pedido de marketplace já acontece pela venda em si.',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-reputacao',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Reputação" — nível da conta no Mercado Livre',
    rota: '/marketplace/metricas',
    perguntas: [
      'reputacao da loja no mercado livre',
      'nivel da conta mercado livre',
      'reclamacoes cancelamento atraso',
      'meta de reclamacoes',
      'termometro do mercado livre',
    ],
    resposta:
      'A aba **Reputação** busca, pra cada loja do Mercado Livre conectada, o nível de reputação da conta (de "Crítica" a "Excelente", a mesma escala que aparece no painel do Mercado Livre), o total de vendas, e os percentuais de reclamações, cancelamentos feitos pelo vendedor e despacho com atraso.\n\nAs metas mostradas ao lado de cada percentual (reclamações até 2%, cancelados até 1,5%, despacho atrasado até 10%) são só uma referência visual pra contexto — não vêm da API do Mercado Livre, são um parâmetro fixo do sistema. Exige integração do Mercado Livre conectada e autorizada; sem isso, a aba pede pra conectar em Integrações.',
    relacionados: ['mkt-metricas-opinioes-concorrentes'],
  },
  {
    id: 'mkt-metricas-opinioes-concorrentes',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Abas "Opiniões" e "Concorrentes" (nos mais vendidos do Mercado Livre)',
    rota: '/marketplace/metricas',
    perguntas: [
      'opinioes dos anuncios',
      'avaliacoes dos anuncios mais vendidos',
      'concorrencia dos anuncios',
      'estou ganhando ou perdendo a disputa',
      'modo catalogo mercado livre',
      'preco pra ganhar a disputa',
      'estrelas dos anuncios',
    ],
    resposta:
      'As abas **Opiniões** e **Concorrentes** (dentro do menu "Mais") consultam, item por item, os até 25 anúncios com mais unidades vendidas de uma loja do Mercado Livre — por isso a busca pode demorar um pouco.\n\n**Opiniões** traz a nota média e a distribuição de 1 a 5 estrelas de cada anúncio. **Concorrentes** só funciona pra anúncio que participa do modo catálogo do Mercado Livre (a maioria dos anúncios normais não participa): mostra se está "Ganhando" ou "Perdendo" a disputa de catálogo, o preço atual e o preço que seria preciso pra ganhar.',
    relacionados: ['mkt-metricas-reputacao'],
  },
  {
    id: 'mkt-metricas-publicidade',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Publicidade" (Ads) — campanhas, ROAS e gasto por anúncio',
    rota: '/marketplace/metricas',
    perguntas: [
      'publicidade do marketplace',
      'campanhas de ads',
      'roas',
      'o que e roas',
      'sincronizar historico de ads',
      'gasto por anuncio de publicidade',
      'product ads mercado livre',
      'ads da shopee',
    ],
    resposta:
      'A aba **Publicidade** mostra campanhas de anúncio patrocinado (Mercado Ads/Product Ads e, quando aplicável, Shopee Ads) num período escolhido: custo, cliques, impressões, CPC e **ROAS** (retorno sobre o investimento — receita atribuída dividida pelo gasto; é o indicador que o próprio Mercado Livre passou a priorizar no lugar do ACOS). Uma segunda tabela mostra o gasto detalhado por anúncio — o mesmo dado usado pra ratear o custo de Ads na Lucratividade de Marketplace, pra bater certinho com o que aparece lá.\n\nO botão **Sincronizar histórico (90 dias)** busca até 90 dias pra trás direto na API de publicidade da loja escolhida. Campanha da Shopee sem anúncio identificável entra como "gasto de Ads não atribuído" — some no total do período, nunca é chutado em cima de um pedido específico. Exige Product Ads habilitado na conta do Mercado Livre (com o produto "Publicidade" adicionado no painel de desenvolvedores); sem isso, a busca volta com aviso explicando o que falta.',
    relacionados: ['mkt-lucratividade-ads'],
  },
  {
    id: 'mkt-metricas-categorias',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Categorias" — tendências e distribuição de anúncios',
    rota: '/marketplace/metricas',
    perguntas: [
      'tendencias do mercado livre',
      'termos mais buscados',
      'distribuicao de anuncios por categoria',
      'navegar categorias do mercado livre',
      'popular da semana maior crescimento',
    ],
    resposta:
      'A aba **Categorias** traz dados da plataforma inteira do Mercado Livre (não só da sua loja), atualizados semanalmente pelo próprio Mercado Livre. Tem duas sub-visões:\n\n**Tendência** lista os termos mais buscados — pro Brasil inteiro, ou dentro de uma categoria específica escolhida navegando na árvore de categorias — classificados em "Maior crescimento" (10 primeiros), "Mais buscado" (próximos 20) e "Popular da semana" (últimos 20).\n\n**Distribuição de Anúncios** mostra o % do total de anúncios ativos em cada categoria, com navegação por aprofundamento (clica numa categoria pra ver as subcategorias dela, e assim por diante).',
    relacionados: ['mkt-metricas-visao-geral'],
  },
  {
    id: 'mkt-metricas-shopee',
    modulo: 'marketplace',
    tela: 'Métricas de Marketplace',
    titulo: 'Aba "Shopee" — desempenho, avaliações e devoluções',
    rota: '/marketplace/metricas',
    perguntas: [
      'aba shopee das metricas',
      'saude da conta shopee',
      'avaliacoes dos compradores shopee',
      'devolucoes da shopee',
      'nota geral shopee',
      'falhas de cumprimento shopee',
      'abas da loja shopee dentro de metricas',
    ],
    resposta:
      'A aba **Shopee** mostra o desempenho da loja Shopee a partir dos pedidos já sincronizados (vendas válidas por dia), e três blocos que só existem na API da Shopee — carregados sob demanda porque cada um é uma chamada externa separada:\n\n**Saúde da Conta** — nota geral e falhas de cumprimento, anúncio e atendimento, com métricas comparando período atual, anterior e meta. **Avaliações dos Compradores** — nota média (calculada só sobre as avaliações mais recentes que a API devolve, não o histórico completo da loja) e os comentários recentes. **Devoluções** (últimos 30 dias) — lista só informativa: nenhuma situação de pedido muda por causa dela. Uma devolução aceita já chega ao lucro pelo caminho certo, porque o valor da conciliação (escrow) fica menor.',
    relacionados: ['mkt-lucratividade-recebido-escrow'],
  },
  {
    id: 'mkt-taxas-cobradas',
    modulo: 'marketplace',
    tela: 'Taxas de Marketplace',
    titulo: 'Conferir se a taxa cobrada bate com o esperado',
    rota: '/marketplace/taxas',
    perguntas: [
      'taxas de marketplace',
      'taxa cobrada diferente do esperado',
      'pedido divergente de taxa',
      'comissao errada mercado livre',
      'comparar taxa cobrada com tabela',
      'pedido sem tabela cadastrada',
      'so comissao sem frete',
      'peso do produto nao cadastrado',
    ],
    resposta:
      'A tela **Taxas de Marketplace** compara, pedido a pedido, a taxa que o Mercado Livre/Shopee/TikTok Shop realmente cobrou com o que era esperado pelas tabelas de comissão + frete cadastradas em Configurações → Taxas. Só considera pedidos importados automaticamente das integrações (planilha manual não entra nessa checagem).\n\nCada linha mostra receita, taxa cobrada, taxa esperada, a diferença entre as duas e a situação: **OK**, **Divergente** ou **Sem referência** (quando não existe tabela de comissão cadastrada pra comparar — nesse caso não conta como divergente, pra não acusar diferença falsa contra taxa zero). Pedido sem peso de produto cadastrado mostra "só comissão" na taxa esperada, porque o frete não entrou na conta. Se mais de 80% dos pedidos do período estiverem divergentes, o sistema avisa que provavelmente é a tabela de comissão desatualizada, não cobrança errada pedido a pedido. O botão **Revincular custos e impostos** (o mesmo da Lucratividade de Marketplace) também está disponível aqui.',
    relacionados: ['mkt-lucratividade-vincular-produto'],
  },
  {
    id: 'mkt-importar-pedidos',
    modulo: 'marketplace',
    tela: 'Importar Pedidos',
    titulo: 'Importar pedidos de marketplace por planilha',
    rota: '/marketplace/importar-pedidos',
    perguntas: [
      'importar pedidos de marketplace',
      'importar planilha de vendas',
      'importar pedido do mercado livre por planilha',
      'importar pedido da shopee por planilha',
      'importar upseller',
      'importar tiktok shop',
      'importar shein',
      'pre-visualizar pedidos antes de importar',
      'item sem correspondencia na importacao de pedidos',
    ],
    resposta:
      'A tela **Importar Pedidos** recebe uma planilha .xlsx exportada do Mercado Livre (Vendas → Relatórios → Vendas), da Shopee (Meus Pedidos → Exportar) ou do UpSeller (Pedidos → Exportar — que também cobre TikTok Shop e Shein, sem precisar de API própria pra essas duas).\n\nEscolha a origem da planilha, envie o arquivo e clique em **Pré-visualizar**: nada é gravado ainda nessa etapa. A prévia lista os pedidos encontrados, marca os que já foram importados antes (ficam desmarcados e esmaecidos) e avisa quando algum item não bateu com nenhuma referência/EAN do estoque — esse item entra só com a descrição, sem baixar estoque ao faturar. Marque os pedidos desejados e clique em **Importar N pedido(s) selecionado(s)**: cada um vira um pedido de venda em aberto, igual à sincronização automática.',
    relacionados: ['mkt-pedidos-listar-filtrar'],
  },
];
