// Verbetes do módulo Produto — cadastro, custo e formação de preço de cada
// referência (/produtos, /produtos/:id, /produtos/novo), importação em
// massa (/importacao), kits para marketplace (/kits) e geração de ficha
// técnica pra impressão (/ficha-tecnica). Lido tela por tela antes de
// escrever qualquer verbete — nenhum campo aqui é inventado.
//
// Termos de cálculo (markup, custo indireto, preço mínimo/ideal/premium/
// máximo etc.) já têm verbete próprio no Glossário (geral.js) — aqui só
// aparecem no contexto de "onde essa tela mostra isso", sem repetir a
// definição inteira.

export const verbetesProduto = [
  {
    id: 'produto-listar-filtrar',
    modulo: 'produto',
    tela: 'Produtos / Referências',
    titulo: 'Ver e filtrar a lista de produtos',
    rota: '/produtos',
    perguntas: [
      'como vejo os produtos cadastrados',
      'lista de produtos',
      'onde fica a lista de referencias',
      'filtrar produtos por marca',
      'filtrar produtos por categoria',
      'buscar produto por referencia',
      'buscar produto por codigo',
      'buscar produto por descricao',
      'filtrar so produtos do marketplace',
      'como acho um produto especifico',
      'quantos produtos tenho cadastrado',
      'lista de referencias com preco e margem',
      'tela de produtos',
      'onde vejo status dos produtos',
      'produto aparece com selo de prejuizo',
    ],
    resposta:
      'A tela **Produtos / Referências** lista todo o cadastro, com foto, referência, descrição, marca, categoria, se é produto de marketplace, preço, margem e um selo de status (prejuízo, margem saudável etc.).\n\nDá pra filtrar por marca, categoria e por "somente do marketplace" / "fora do marketplace", e buscar por referência, código ou descrição no campo de busca. Clique em qualquer linha (ou na seta à direita) pra abrir a ficha completa daquele produto.\n\nAs colunas Referência, Descrição, Marca, Categoria, Marketplace, Preço, Margem e Status podem ser ordenadas clicando no título — e a lista dá pra exportar em CSV/XLSX (ver o verbete geral de exportar tabela).',
    relacionados: ['produto-marketplace-selecionar', 'produto-criar-novo', 'geral-tabela-exportar'],
  },
  {
    id: 'produto-criar-novo',
    modulo: 'produto',
    tela: 'Produtos / Referências',
    titulo: 'Cadastrar um produto novo',
    rota: '/produtos/novo',
    perguntas: [
      'como cadastro um produto novo',
      'criar novo produto',
      'novo produto botao',
      'cadastrar referencia nova',
      'adicionar produto',
      'como crio uma referencia',
      'cadastro de produto do zero',
      'campos obrigatorios do produto',
      'referencia e obrigatoria',
      'nao consigo salvar produto novo',
      'onde fica o botao novo produto',
      'cadastrar peca nova',
    ],
    resposta:
      'Na tela de Produtos, clique em **Novo produto** (canto superior direito). Abre a mesma ficha usada pra editar, em branco: preencha ao menos a **Referência** — é o único campo realmente obrigatório pra salvar. Os demais (código, descrição, categoria, marca, coleção, linha, empresa, responsável, peso) são opcionais.\n\nAté você salvar pela primeira vez, ainda não dá pra adicionar foto (o botão fica desabilitado com a dica "Salve o produto primeiro"). Depois de salvar, a tela já mostra o cálculo de custo e preço com o que foi preenchido em Materiais e Custos Industriais — mesmo vazio, o preço mínimo/ideal já aparece com base no que existir de custo indireto e impostos configurados.',
    relacionados: ['produto-editar-dados-basicos', 'produto-foto', 'produto-materiais'],
  },
  {
    id: 'produto-editar-dados-basicos',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Editar os dados básicos de um produto',
    rota: '/produtos',
    perguntas: [
      'como edito um produto',
      'mudar descricao do produto',
      'trocar categoria do produto',
      'trocar marca do produto',
      'mudar codigo do produto',
      'editar referencia',
      'trocar empresa do produto',
      'campo responsavel pela precificacao',
      'peso da peca pra que serve',
      'colecao e linha do produto',
      'onde mudo os dados do produto',
      'atualizar cadastro do produto',
    ],
    resposta:
      'Na ficha do produto (abrir a partir da lista de Produtos), o card do topo tem os dados básicos: Código do Produto, Referência, Descrição, Categoria, Marca, Coleção, Linha, Empresa (define o regime tributário usado no cálculo), Responsável pela Precificação e Peso da peça (opcional, usado na conferência de frete de marketplace).\n\nCategoria, Marca, Coleção e Linha vêm das **Listas** cadastradas em Configurações — se a opção que você precisa não existe ainda, é lá que se adiciona. Depois de editar, clique em **Salvar** no canto do card; nada é gravado antes disso (o recálculo de preço na tela é só uma prévia ao vivo).',
    relacionados: ['produto-criar-novo', 'gloss-regime-tributario'],
  },
  {
    id: 'produto-foto',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Adicionar, trocar ou remover a foto do produto',
    rota: '/produtos',
    perguntas: [
      'como adiciono foto no produto',
      'trocar foto do produto',
      'remover foto do produto',
      'upload de foto',
      'nao consigo add foto',
      'foto do produto obrigatoria',
      'formato de foto aceito',
      'tirar foto do produto',
      'foto aparece na ficha',
      'salvar produto pra add foto',
      'quero subir foto do produto',
    ],
    resposta:
      'No topo da ficha do produto, ao lado dos dados, clique em **Adicionar foto** (ou no botão **Trocar**, se já existe uma). Aceita imagens .jpg, .png ou .webp. Clicando na foto já enviada, ela abre ampliada.\n\nUm produto **novo, ainda não salvo**, não deixa enviar foto — é preciso clicar em Salvar pelo menos uma vez primeiro (o botão de foto fica desabilitado com essa explicação até lá). Pra tirar a foto, use o ícone de lixeira ao lado do botão Trocar — pede confirmação antes de remover.',
    relacionados: ['produto-criar-novo'],
  },
  {
    id: 'produto-materiais',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Adicionar e remover materiais de um produto',
    rota: '/produtos',
    perguntas: [
      'como adiciono material no produto',
      'cadastrar material da peca',
      'remover material do produto',
      'tabela de materiais',
      'quantidade e valor unitario do material',
      'material nao aparece na lista',
      'lista de materiais sugeridos',
      'unidade do material',
      'total de materiais',
      'adicionar tecido na ficha',
      'adicionar aviamento',
      'errei o material na ficha do produto',
    ],
    resposta:
      'No card **Materiais** da ficha do produto, clique em **Adicionar material** pra criar uma linha nova: material (com sugestões da lista já cadastrada, mas você pode digitar um nome novo), unidade, quantidade e valor unitário. O total da linha e o total geral de materiais são calculados sozinhos conforme você digita.\n\nPra remover uma linha, use o ícone de lixeira nela. Qualquer mudança nos materiais já atualiza o preço mostrado na tela na hora (é uma prévia — só fica gravado de verdade quando você clica em **Salvar** no topo da ficha).',
    relacionados: ['produto-custos-industriais', 'produto-calculo-ao-vivo'],
  },
  {
    id: 'produto-custos-industriais',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Adicionar e remover custos industriais de um produto',
    rota: '/produtos',
    perguntas: [
      'como adiciono custo industrial',
      'cadastrar mao de obra da peca',
      'remover custo industrial',
      'tabela de custos industriais',
      'tipo de custo industrial',
      'observacao do custo industrial',
      'total de custo industrial',
      'adicionar etapa de producao',
      'custo de corte e costura onde cadastra',
    ],
    resposta:
      'No card **Custos Industriais** da ficha do produto, clique em **Adicionar custo** e escolha o Tipo (vem da lista cadastrada em Configurações — corte, costura, acabamento e afins, dependendo do que já foi criado), preencha uma Observação/fornecedor opcional e o Valor.\n\nO total de custo industrial soma todas as linhas e entra direto na composição do custo total da peça. Pra remover uma linha, use o ícone de lixeira nela — assim como nos materiais, a mudança só é gravada de verdade ao clicar em Salvar.',
    relacionados: ['produto-materiais', 'gloss-custo-industrial'],
  },
  {
    id: 'produto-calculo-ao-vivo',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Como o preço é recalculado ao vivo na ficha do produto',
    rota: '/produtos',
    perguntas: [
      'o preco muda sozinho na ficha',
      'calculo atualiza sozinho',
      'preco recalcula ao digitar',
      'precisa salvar pra ver o preco',
      'preco muda antes de salvar',
      'previa do calculo',
      'calculo em tempo real',
      'demora pra atualizar o preco',
      'mudei material e o preco nao mudou',
    ],
    resposta:
      'Enquanto você edita a ficha do produto (dados básicos, materiais ou custos industriais), o sistema recalcula o preço automaticamente alguns instantes depois de você parar de digitar — é uma prévia ao vivo, não precisa clicar em nada pra ver o efeito da mudança.\n\nEssa prévia usa os dados que estão na tela naquele momento, mesmo que ainda não tenham sido salvos. Se você sair da tela sem clicar em **Salvar**, nada do que foi digitado é gravado — o cálculo ao vivo é só visual, pra você decidir antes de confirmar.',
    relacionados: ['produto-materiais', 'produto-formacao-preco'],
  },
  {
    id: 'produto-formacao-preco',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Onde vejo o preço praticado, sugerido e a formação de preço',
    rota: '/produtos',
    perguntas: [
      'onde vejo o preco sugerido',
      'preco praticado o que e',
      'como informo o preco de venda do produto',
      'preco em branco usa o que',
      'card formacao do preco',
      'onde vejo custo total da peca',
      'composicao do custo do produto',
      'onde vejo o lucro estimado',
      'preco sugerido versus preco praticado',
      'colocar preco manual no produto',
    ],
    resposta:
      'Na ficha do produto, o card **Custo Total da Peça** mostra a composição (materiais, custo industrial, custo indireto/rateio, subtotal de produção, impostos, taxas de venda) até o custo total. Ao lado, **Formação do Preço** mostra o preço sugerido (calculado pela margem ideal), a faixa mínimo/ideal/premium/máximo, o lucro estimado e o markup.\n\nO campo **Preço praticado** é opcional: se você deixar em branco, o sistema usa o preço sugerido como "preço ativo" do produto (é o que aparece na lista e em outras telas); se você digitar um valor, esse passa a ser o preço ativo, mesmo que diferente do sugerido — é assim que dá pra registrar o preço que está sendo cobrado de verdade.',
    relacionados: ['gloss-precos-referencia', 'gloss-markup', 'produto-calculo-ao-vivo'],
  },
  {
    id: 'produto-indicadores-alertas',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Indicadores e alertas na ficha do produto',
    rota: '/produtos',
    perguntas: [
      'o que sao os indicadores do produto',
      'card de indicadores',
      'roi estimado o que e',
      'peso dos impostos no produto',
      'peso das taxas no produto',
      'card de alertas',
      'alerta de margem no produto',
      'produto com alerta o que significa',
      'tudo dentro do esperado o que quer dizer',
      'lucro liquido estimado',
    ],
    resposta:
      'Abaixo da formação de preço, o card **Indicadores** reúne, num só lugar, markup, margem bruta, margem de contribuição, lucro líquido estimado, ROI estimado, custo industrial, custo administrativo (indireto) e o peso de impostos/taxas/custo indireto sobre o preço daquela referência.\n\nO card **Alertas**, ao lado, lista avisos automáticos sobre a composição daquele produto específico (por exemplo, um custo pesando mais do que o esperado) — quando não há nada a avisar, mostra "Tudo dentro do esperado". Nenhum desses dois cards é editável: eles só refletem o resultado do cálculo com os dados já preenchidos na ficha.',
    relacionados: ['produto-formacao-preco', 'gloss-margem-contribuicao'],
  },
  {
    id: 'produto-excluir',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Excluir um produto',
    rota: '/produtos',
    perguntas: [
      'como excluo um produto',
      'remover produto cadastrado',
      'apagar referencia',
      'deletar produto',
      'excluir produto pede confirmacao',
      'da pra desfazer exclusao de produto',
      'botao remover produto',
    ],
    resposta:
      'Na ficha de um produto já salvo, o botão **Remover** fica junto do Salvar, no canto do card de dados básicos. Ele pede confirmação antes de excluir de verdade ("Essa ação não pode ser desfeita") — depois de confirmado, o produto some do cadastro e você volta pra lista de Produtos.\n\nEssa ação é permanente. Se o produto tem estoque, pedidos ou histórico ligados a ele, considere se realmente é exclusão que você quer, ou se é melhor só tirar da lista do marketplace ou deixar de usar a referência daqui pra frente — a Manu não decide isso por você, só explica onde fica o botão.',
    relacionados: [],
  },
  {
    id: 'produto-historico-preco',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Ver o histórico de preço de um produto',
    rota: '/produtos',
    perguntas: [
      'onde vejo o historico de preco',
      'preco antigo do produto',
      'precos anteriores da referencia',
      'quando o preco mudou',
      'historico de precificacao',
      'card de historico no produto',
      'ver preco de meses atras',
    ],
    resposta:
      'No fim da ficha do produto tem o card de **Histórico de Preço**, com um registro (snapshot) de como o cálculo completo estava salvo em cada momento — toda vez que o produto é salvo, um novo ponto entra nesse histórico. É por ali que dá pra ver como o preço e a composição de custo daquela referência mudaram ao longo do tempo.',
    relacionados: ['produto-formacao-preco'],
  },
  {
    id: 'produto-marketplace-selecionar',
    modulo: 'produto',
    tela: 'Produtos / Referências',
    titulo: 'Marcar produtos como "de marketplace" (individual ou em lote)',
    rota: '/produtos',
    perguntas: [
      'como marco produto como marketplace',
      'tirar produto do marketplace',
      'selecionar varios produtos pro marketplace',
      'marcar em lote como marketplace',
      'produto de marketplace pra que serve',
      'toggle marketplace no produto',
      'selecao em massa na lista de produtos',
      'fichas do marketplace em lote',
      'imprimir fichas de estoque do marketplace',
    ],
    resposta:
      'Individualmente, a ficha do produto tem o campo **Produto de marketplace** (um toggle) — quando ativado, esse produto entra no filtro "somente do marketplace" e nas fichas de estoque em lote pensadas pra conferência de marketplace.\n\nPra marcar vários de uma vez, na lista de Produtos marque as caixinhas das linhas desejadas (ou a caixinha do cabeçalho, que seleciona todos **da página atual**) — aparece uma barra com **Marcar como marketplace** e **Tirar do marketplace** pra aplicar em lote. O link **Fichas do marketplace**, no topo da lista, leva direto pra impressão em lote das fichas de estoque desses produtos.',
    relacionados: ['produto-listar-filtrar'],
  },
  {
    id: 'produto-importacao-massa',
    modulo: 'produto',
    tela: 'Importação em Massa',
    titulo: 'Importar produtos, materiais e custos em massa',
    rota: '/importacao',
    perguntas: [
      'como importo produtos em massa',
      'importar planilha de produtos',
      'importar xlsx de produtos',
      'importar csv de materiais',
      'importar ficha de custo em pdf',
      'importacao aceita quais formatos',
      'cadastro_produto aba da planilha',
      'importar varios produtos de uma vez',
      'importacao do sistema antigo',
      'importar do wiki sistemas',
      'importar ficha da dinamica',
      'planilha de importacao modelo',
    ],
    resposta:
      'A tela **Importação em Massa** aceita três formatos: uma planilha **.xlsx** com as abas Cadastro_Produto, Materiais e/ou Custos_Industriais (mesmo layout da planilha original), um **.csv** com uma dessas três tabelas por vez (você escolhe qual, no campo que aparece ao selecionar um .csv), ou uma **Ficha de Custo em PDF** no formato Wiki Sistemas/Dinâmica, com uma referência por página.\n\nEscolha o arquivo e clique em **Pré-visualizar** — nada é gravado nesse momento, é só uma conferência (ver o verbete sobre a prévia e os erros de importação). Só depois de olhar a prévia e clicar em **Confirmar importação** é que os dados entram de verdade no cadastro.',
    relacionados: ['produto-importacao-erros'],
  },
  {
    id: 'produto-importacao-erros',
    modulo: 'produto',
    tela: 'Importação em Massa',
    titulo: 'Conferir a prévia e os erros antes de confirmar a importação',
    rota: '/importacao',
    perguntas: [
      'importacao deu erro em algumas linhas',
      'linhas com erro na importacao',
      'previa da importacao',
      'o que sera criado ou atualizado na importacao',
      'importacao nao grava direto',
      'quantos produtos serao criados',
      'motivo do erro na importacao',
      'importar so o que estiver certo',
      'confirmar importacao',
    ],
    resposta:
      'Depois de clicar em Pré-visualizar, a tela mostra quatro blocos: produtos que **serão criados**, produtos que **serão atualizados** (referência já existe), materiais válidos e custos industriais válidos — cada um com a contagem e uma amostra das linhas (até 50 por bloco).\n\nSe alguma linha do arquivo tiver problema, aparece um bloco à parte, **Linhas com erro**, com a origem (Produtos/Materiais/Custos Industriais), o número da linha e o motivo — essas linhas específicas **não** são importadas, só as que passaram na conferência. Só depois de olhar tudo isso é que o botão **Confirmar importação** grava de fato no cadastro; até lá, nada muda no sistema.',
    relacionados: ['produto-importacao-massa'],
  },
  {
    id: 'produto-kits-automaticos',
    modulo: 'produto',
    tela: 'Kits para Marketplace',
    titulo: 'Kits automáticos (2 a 8 peças da mesma referência)',
    rota: '/kits',
    perguntas: [
      'o que sao kits automaticos',
      'kit automatico de camiseta',
      'kit automatico de bermuda',
      'kit automatico de polo',
      'kit de 2 a 8 pecas',
      'kit automatico como funciona',
      'preco de kit automatico',
      'margem do kit automatico',
      'kit gerado sozinho pelo sistema',
    ],
    resposta:
      'Os **kits automáticos** são gerados sozinhos pelo sistema pra referências de Camiseta Dryfit, Camiseta Polo e Bermuda: pra cada uma dessas referências cadastradas, o sistema monta kits de 2 a 8 peças da mesma referência, mostrando custo total, soma dos preços avulsos, percentual de desconto, preço sugerido do kit e margem estimada — tudo calculado, sem precisar cadastrar nada manualmente.\n\nSe nenhuma referência de Camiseta Dryfit, Camiseta Polo ou Bermuda estiver cadastrada, esse bloco aparece vazio. Pra combinar referências diferentes num kit, é o kit manual (ver o outro verbete de Kits).',
    relacionados: ['produto-kits-manuais'],
  },
  {
    id: 'produto-kits-manuais',
    modulo: 'produto',
    tela: 'Kits para Marketplace',
    titulo: 'Criar e remover um kit manual',
    rota: '/kits',
    perguntas: [
      'como crio um kit manual',
      'kit manual com referencias diferentes',
      'montar kit combinando produtos',
      'desconto do kit manual',
      'remover kit manual',
      'nome do kit',
      'adicionar referencia no kit',
      'quantidade de itens no kit',
      'kit sortido como monta',
    ],
    resposta:
      'No formulário **Novo kit manual**, dê um nome ao kit, adicione linhas com **Adicionar referência** escolhendo produtos diferentes e a quantidade de cada um, e opcionalmente informe um percentual de desconto próprio pra esse kit (deixando em branco, usa o padrão do sistema). Clique em **Criar kit**.\n\nCada kit manual criado aparece como um card com a lista de itens, custo unitário e preço unitário de cada um, o custo total do kit, a soma dos preços avulsos, o preço sugerido do kit com o desconto aplicado e a margem estimada. Pra remover um kit manual, use o ícone de lixeira no card dele — pede confirmação antes.',
    relacionados: ['produto-kits-automaticos'],
  },
  {
    id: 'produto-ficha-tecnica-gerar',
    modulo: 'produto',
    tela: 'Ficha Técnica',
    titulo: 'Gerar e imprimir a ficha técnica (ficha de custo) de um produto',
    rota: '/ficha-tecnica',
    perguntas: [
      'como gero a ficha tecnica',
      'imprimir ficha tecnica',
      'exportar ficha tecnica em pdf',
      'ficha de custo pra producao',
      'quantas referencias posso gerar de uma vez',
      'ficha tecnica mostra preco de venda',
      'ficha tecnica so mostra custo',
      'selecionar varias referencias pra ficha',
      'gerar ficha de mais de uma referencia',
    ],
    resposta:
      'Na tela **Ficha Técnica**, busque por referência, código ou descrição, e clique em **Adicionar** nos resultados pra selecionar até **5 referências** de uma vez (aparecem como etiquetas, removíveis clicando no X). Clique em **Gerar fichas** pra montar o documento — uma ficha de custo por página, com matéria-prima, custos industriais e o resumo do custo total da peça.\n\nA ficha técnica mostra só o **custo de produção** — nenhum preço de venda aparece aqui, isso fica na Ficha de Venda, dentro de Vendas. Com as fichas geradas, o botão **Imprimir / Exportar PDF** abre a impressão do navegador, pronta pra salvar como PDF.',
    relacionados: ['gloss-ficha-tecnica'],
  },
];
