// Verbetes do módulo Produção — a ordem de produção com grade, roteiro,
// material reservado e custo real comparado ao padrão; a movimentação de
// peças entre etapas e facções; a Ordem de Serviço de facção e a quebra
// medida; a carga por etapa em minutos e o ranking de facção; e a projeção
// de estoque em três camadas por cor/tamanho, com PDF próprio. Lidos por
// completo antes de escrever: ProducaoPage.jsx, MovimentacaoProducaoPage.jsx,
// OrdensServicoPage.jsx, CargaProducaoPage.jsx, ProjecaoEstoquePage.jsx,
// ProducaoKanban.jsx, FaccoesAba.jsx, NovaFaccaoModal.jsx,
// NovaOrdemProducao.jsx e WikImportarProdutosCard.jsx.

export const verbetesProducao = [
  {
    id: 'producao-visao-geral-abas',
    modulo: 'producao',
    tela: 'Produção',
    titulo: 'O que a tela Produção mostra e o que tem em cada aba',
    rota: '/producao',
    perguntas: [
      'o que e a tela de producao',
      'abas da tela producao',
      'onde vejo as ordens de producao',
      'producao ordens roteiro wip faccao',
      'para que serve cada aba da producao',
      'como navego na tela de producao',
      'roteiro e consumo o que e',
      'aba insumos da producao',
      'diferenca entre custo real e custo padrao',
    ],
    resposta:
      'A tela **Produção** (`/producao`) tem seis abas: **Ordens** (a lista das ordens de produção, com lista ou quadro), **Roteiro e consumo** (as operações de cada referência e o consumo de material por tamanho), **Onde está a produção** (o WIP — quanto está parado em cada etapa da fábrica), **Material em facção** (o saldo de insumo e de peça pronta que está com terceiros), **Cadastro de facção** (quem costura, lava, borda ou estampa por fora) e **Insumos**.\n\nO motivo da tela existir, segundo o próprio código, é responder duas coisas que o Wik não separa: o **consumo por tamanho** (lá o GG sai pelo mesmo custo do P, porque o consumo é da grade inteira) e o **custo real da ordem** comparado com o padrão congelado na abertura. A tela lê o custo padrão do motor de cálculo — ela não recalcula preço, margem nem markup, e o custo real de uma ordem não realimenta a ficha do produto sozinho.',
    relacionados: ['producao-custo-real-x-padrao', 'producao-consumo-por-tamanho', 'producao-wip-onde-esta'],
  },
  {
    id: 'producao-quadro-kanban',
    modulo: 'producao',
    tela: 'Produção',
    titulo: 'Ver as ordens em quadro (kanban) e arrastar para mudar a situação',
    rota: '/producao',
    perguntas: [
      'como arrasto uma ordem de producao',
      'quadro kanban de producao',
      'mudar situacao da ordem arrastando',
      'nao consigo concluir arrastando o cartao',
      'diferenca entre lista e quadro na producao',
      'coluna concluida nao aceita cartao',
      'trocar rascunho para planejada',
      'cartao de ordem no kanban o que mostra',
    ],
    resposta:
      'Na aba **Ordens**, o alternador **Lista / Quadro** troca entre a tabela e um kanban com cinco colunas: Rascunho, Planejada, Em produção, Concluída e Cancelada. Arrastar um cartão para outra coluna muda a situação da ordem na hora — e se o servidor recusar, o cartão volta sozinho para onde estava. A escolha entre lista e quadro fica guardada no navegador de cada pessoa.\n\n**Concluir não é arrastar.** A coluna Concluída existe para não esconder a produção do mês, mas ela **não aceita** cartão solto ali — dar entrada das peças no estoque passa pela conferência do financeiro e tem confirmação própria dentro da ordem (ver **Concluir e dar entrada no estoque**). Ordem já concluída também não pode mais ser arrastada. Clicar no cartão (sem arrastar) abre o detalhe da ordem, com a grade, o material e o apontamento.',
    relacionados: ['producao-concluir-ordem', 'producao-nova-ordem-abrir'],
  },
  {
    id: 'producao-nova-ordem-abrir',
    modulo: 'producao',
    tela: 'Nova ordem de produção',
    titulo: 'Abrir uma ordem de produção de uma referência',
    rota: '/producao',
    perguntas: [
      'como abro uma ordem de producao',
      'criar op nova',
      'nova ordem de producao',
      'preencher grade da ordem por cor e tamanho',
      'botao para repetir quantidade na linha',
      'grade da ordem nao digita mais texto livre',
      'escolher faccao na abertura da ordem',
      'salvar ordem como rascunho',
      'diferenca entre rascunho e abrir a ordem',
    ],
    resposta:
      'Clique em **Nova ordem**, na aba Ordens. Escolha a **Referência**: a tela desenha sozinha a matriz de cor × tamanho do cadastro do produto, e você só preenche as quantidades — a grade não é mais digitada em texto livre, porque era assim que "Azul" e "Azl" viravam duas cores diferentes. O botão **=** no fim de cada linha repete, em todos os tamanhos daquela cor, a primeira quantidade que você preencheu na linha.\n\nOs demais campos do cabeçalho são **Facção / oficina** (deixe em branco para produção interna), **Início** e **Chegada prevista** — as duas datas juntas colocam a ordem no calendário como um período; sem a data de chegada, a ordem não entra no calendário e não tem como atrasar. Depois de preencher a grade, use **Ver o que a ficha vai consumir** para ver a explosão de material antes de decidir; então **Salvar como rascunho** (nada é reservado) ou **Abrir a ordem** (situação Planejada).',
    relacionados: ['producao-nova-ordem-previa', 'producao-datas-calendario', 'producao-nova-ordem-kit'],
  },
  {
    id: 'producao-nova-ordem-kit',
    modulo: 'producao',
    tela: 'Nova ordem de produção',
    titulo: 'Abrir uma ordem de produção de kit',
    rota: '/producao',
    perguntas: [
      'como abro ordem de kit',
      'producao de kit de camisetas',
      'ordem de producao com varias referencias',
      'kit cadastrado na ordem de producao',
      'cada referencia do kit vira uma op',
      'kit nao aparece no estoque direto',
      'quantidade de kits so informativo',
      'montar kit na hora sem cadastro',
    ],
    resposta:
      'Em **Nova ordem de produção**, escolha a aba **Kit** em vez de Uma referência. Dá para escolher um **Kit cadastrado** (traz as referências dele de uma vez) ou montar na hora, acrescentando referência por referência em **Acrescentar referência** — cada uma abre a própria matriz de cor × tamanho, preenchida do mesmo jeito que na ordem simples. O campo **Quantos kits** é só informativo: o que a fábrica produz é a peça, não o kit.\n\nCada referência do kit vira uma **ordem de produção completa**, com roteiro, material, movimentação e ordem de serviço próprios — quem entra no estoque no fim é sempre a referência, nunca o kit. A ordem "de kit" existe só para responder se o conjunto está pronto: ao abrir o detalhe dela, a lista **Referências deste kit** mostra a situação e as quantidades de cada uma, e clicar numa linha abre aquela ordem específica.',
    relacionados: ['producao-nova-ordem-abrir', 'producao-grade-planejada-produzida'],
  },
  {
    id: 'producao-nova-ordem-previa',
    modulo: 'producao',
    tela: 'Nova ordem de produção',
    titulo: 'A prévia de material antes de abrir a ordem, e o aviso de material insuficiente',
    rota: '/producao',
    perguntas: [
      'ver o que a ficha vai consumir',
      'previa de material da ordem',
      'explosao da ficha na producao',
      'material insuficiente ao abrir ordem',
      'a ordem trava se faltar material',
      'ficha incompleta abrir mesmo assim',
      'insumo sem custo na previa da ordem',
      'quantas pecas da pra fazer com o material que tem',
    ],
    resposta:
      'Depois de preencher a grade, o botão **Ver o que a ficha vai consumir** pede ao servidor a explosão da ficha técnica e mostra o card **Explosão da ficha**, com os indicadores Peças, Material previsto (por peça e total), e Insumos faltando. Se algum insumo estiver com o saldo próprio de hoje menor do que a ordem precisa, abre o aviso **Material insuficiente**, listando cada insumo, o quanto precisa, o quanto tem, o que falta e até quantas peças dá para fazer com o que existe.\n\n**Isto é só um aviso — não trava.** A casa produz com material chegando no mesmo dia, e travar faria alguém mentir a quantidade só para conseguir abrir a ordem. Reservar o material na abertura pega o que houver e deixa a falta visível, sem criar saldo negativo. Já quando a **ficha em si está incompleta** para aquela grade (insumo sem vínculo, tamanho sem consumo cadastrado), a ordem só pode ser aberta marcando a caixinha **"Abrir mesmo assim. Eu sei que o material desses tamanhos ficou de fora da conta."** — sem isso, os botões de salvar ficam desabilitados.',
    relacionados: ['producao-nova-ordem-abrir', 'producao-material-ordem', 'producao-consumo-por-tamanho'],
  },
  {
    id: 'producao-datas-calendario',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Datas de início e chegada, e por que a ordem entra ou não no calendário',
    rota: '/producao',
    perguntas: [
      'ordem nao aparece no calendario',
      'data prevista da ordem de producao',
      'como muda a data de chegada da op',
      'sem prazo a ordem nao atrasa',
      'salvar datas da ordem',
      'ordem sem data no calendario',
      'inicio e chegada da producao',
      'botao salvar datas desabilitado',
      'ordem entrou no calendario como periodo',
    ],
    resposta:
      'Dentro do detalhe de qualquer ordem, os campos **Início** e **Chegada prevista** ficam no topo, com o botão **Salvar datas** ao lado (só habilitado quando algo muda). É a **Chegada prevista** que coloca a ordem no calendário: sem ela, a ordem não entra e não existe atraso para medir — e é por isso que a tela marca essas ordens com o selo "sem prazo" tanto na lista quanto no cartão do quadro.\n\nCom as duas datas preenchidas, a ordem entra sozinha no calendário como um período (não como um ponto único no dia da entrega). Ao salvar, a mensagem muda conforme o que aconteceu: "colocada no calendário" na primeira vez, "o calendário acompanhou" quando já existia evento e ele foi atualizado, ou o motivo de não ter mexido em nada.',
    relacionados: ['producao-nova-ordem-abrir', 'producao-grade-planejada-produzida'],
  },
  {
    id: 'producao-grade-planejada-produzida',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Ler a grade da ordem: planejadas, produzidas e 2ª qualidade',
    rota: '/producao',
    perguntas: [
      'grade da ordem de producao',
      'quantidade planejada x produzida',
      'o que e segunda qualidade na grade',
      'onde vejo quanto ja foi produzido de cada cor',
      'grade por cor e tamanho da ordem',
      'nao consigo editar a grade direto na tabela',
      'quantidade produzida nao bate com apontamento',
      'tabela grade da ordem colunas',
    ],
    resposta:
      'No detalhe de uma ordem, a tabela **Grade** lista cada combinação de cor e tamanho com três números: **Planejadas** (o que a ordem pretende produzir naquela variante), **Produzidas** (o que já foi apontado como pronto, na última operação do roteiro) e **2ª qualidade** (o que voltou com defeito e foi contado como segunda, não como peça boa).\n\nQuem alimenta essas colunas é o apontamento de produção — não dá para editar a grade diretamente na tabela. Os mesmos números aparecem resumidos nos indicadores **Planejadas** e **Produzidas** no topo do painel da ordem.',
    relacionados: ['producao-apontar-producao', 'producao-nova-ordem-abrir'],
  },
  {
    id: 'producao-custo-real-x-padrao',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Custo real da ordem comparado ao custo padrão da ficha',
    rota: '/producao',
    perguntas: [
      'custo real x custo padrao da op',
      'por que o custo real esta diferente do padrao',
      'de onde vem o custo padrao por peca',
      'custo real incompleto o que significa',
      'como e calculado o custo real da ordem',
      'ordem acima do padrao o que fazer',
      'custo padrao congelado na abertura',
      'custo real ainda nao da o que significa',
      'custo padrao muda depois de aberta a ordem',
    ],
    resposta:
      'O painel de cada ordem mostra dois indicadores lado a lado: **Custo padrão / peça**, que é congelado direto do motor de cálculo no momento em que a ordem é aberta e nunca muda depois — é o retrato contra o qual o real é comparado — e **Custo real / peça**, que soma o material efetivamente reservado (pelo custo do dia da reserva) mais a mão de obra apontada nas operações. Quando o real fica acima do padrão, aparece um aviso com o percentual de diferença; a ficha continua exatamente como está, porque corrigir o cadastro é uma decisão de quem cuida do produto, não desta tela.\n\nO custo real pode aparecer como **"ainda não dá"** ou marcado como **incompleto**: isso acontece quando há insumo sem custo conhecido ou operação sem valor apontado, ou quando nenhuma peça boa foi apontada ainda. O que falta fica de fora da soma — nunca entra como zero, porque um custo incompleto disfarçado de custo fechado seria pior do que não mostrar nada.',
    relacionados: ['producao-levar-custo-ficha', 'producao-material-ordem', 'producao-apontar-producao'],
  },
  {
    id: 'producao-material-ordem',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Material da ordem: origem do consumo, reservar e lançar o que foi gasto de verdade',
    rota: '/producao',
    perguntas: [
      'origem do consumo por tamanho x valor unico',
      'reservar material da ordem',
      'lancar material gasto na ordem',
      'corrigir quantidade de insumo gasto',
      'insumo sem custo na ordem',
      'tirar insumo da ordem',
      'reserva parcial de material',
      'insumo lancado a mao na ordem',
    ],
    resposta:
      'A tabela **Material** de cada ordem mostra, por insumo, a **Origem**: "por tamanho" (a necessidade veio do consumo cadastrado especificamente para aquele tamanho — a conta certa, porque o GG come mais malha que o P) ou "valor único" (veio do consumo geral da ficha, igual para todos os tamanhos — enquanto for assim, o P subsidia o GG). Também mostra o **Necessário**, o **Reservado**, o **Saldo próprio** e o **Custo** — insumo sem custo conhecido aparece com o selo "sem custo", nunca como zero. O botão **Reservar material**, no rodapé, tenta reservar tudo que a ordem precisa; se faltar saldo para alguma linha, a tela lista o que faltou e o saldo disponível, sem travar a reserva do resto.\n\nO campo **Acrescentar ou corrigir insumo gasto** lança o que foi de fato gasto — se o insumo já vinha da ficha, a quantidade digitada aqui **substitui**, não soma, a prevista. Corrigir aqui muda o custo real da ordem e **não** mexe no que já foi reservado, porque reserva é movimento de estoque separado. Um insumo lançado à mão nesta ordem (que não veio da ficha técnica) ganha o selo "à mão" e só pode ser removido enquanto nada dele foi reservado nem consumido.',
    relacionados: ['producao-custo-real-x-padrao', 'producao-consumo-por-tamanho', 'producao-concluir-ordem'],
  },
  {
    id: 'producao-levar-custo-ficha',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Levar o custo apurado da ordem para a ficha do produto',
    rota: '/producao',
    perguntas: [
      'levar custo da ordem para a ficha',
      'atualizar ficha tecnica com o custo real',
      'aplicar custo apurado na ficha',
      'custo real muda o preco de venda automatico',
      'quem decide atualizar a ficha com o custo da ordem',
      'botao levar custo para a ficha nao aparece',
      'vendas antigas mudam depois de atualizar a ficha',
      'fica registrado quem atualizou a ficha pelo custo da ordem',
    ],
    resposta:
      'Quando a ordem tem uma diferença percentual apurada entre o custo real e o padrão, aparece o botão **Levar este custo para a ficha do produto**. Ele pede confirmação explícita, avisando que a ação altera a ficha técnica — o custo e o preço sugerido de toda venda futura daquela referência passam a sair dali; vendas já feitas continuam com o custo que tinham, e cada alteração fica registrada com quem fez e quando.\n\nO sistema não faz isso sozinho: o custo real de uma ordem **nunca** realimenta o cadastro automaticamente, porque uma ordem ruim isolada não pode reescrever o preço da referência inteira. Depois de aplicar, a tela mostra quantas linhas da ficha foram atualizadas e quais ficaram de fora, com o motivo de cada uma.',
    relacionados: ['producao-custo-real-x-padrao'],
  },
  {
    id: 'producao-apontar-producao',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Apontar produção e marcar peças como prontas',
    rota: '/producao',
    perguntas: [
      'como aponto producao',
      'apontamento de operacao',
      'contar peca como produzida',
      'marcar ultima operacao do roteiro',
      'apontar em qual operacao',
      'refugo no apontamento',
      'valor por peca do apontamento',
      'apontamento sem roteiro cadastrado',
    ],
    resposta:
      'No bloco **Apontar produção**, dentro da ordem, você escolhe a **Operação** (ou deixa em branco quando não há roteiro), Cor, Tamanho, quantas **Peças**, quanto de **2ª qualidade** e, opcionalmente, o **R$ por peça** (em branco usa o valor cadastrado no roteiro). A checkbox **"Esta é a última operação: contar estas peças como prontas"** só deve ser marcada na última etapa do roteiro — a mesma peça passa por corte, costura e acabamento, e marcar em todas somaria a peça três vezes.\n\nQuando marcada, cor e tamanho precisam bater com uma linha da grade da ordem; se não baterem, a peça não sobe no total nem entra no estoque na conclusão. Depois de lançar, o histórico de apontamentos fica visível abaixo, com data, operação, cor/tamanho, peças, refugo, valor e quem lançou.',
    relacionados: ['producao-grade-planejada-produzida', 'producao-concluir-ordem', 'producao-roteiro-operacoes'],
  },
  {
    id: 'producao-concluir-ordem',
    modulo: 'producao',
    tela: 'Ordem de produção',
    titulo: 'Concluir a ordem e dar entrada das peças no estoque',
    rota: '/producao',
    perguntas: [
      'como concluo a ordem de producao',
      'dar entrada no estoque pela producao',
      'concluir ordem sem peca apontada',
      'botao concluir esta desabilitado',
      'ordem concluida nao pode mais editar',
      'entrada das pecas prontas no estoque',
      'por que nao consigo concluir a ordem arrastando',
      'concluir ordem passa pelo financeiro',
    ],
    resposta:
      'O botão **Concluir e dar entrada no estoque**, no rodapé do detalhe da ordem, fica desabilitado enquanto nenhuma peça foi apontada como pronta — não há como concluir uma ordem sem produção nenhuma. Concluir é o que efetivamente lança as peças produzidas no estoque; depois disso a ordem fica com a situação **Concluída** e não pode mais ser editada nem arrastada no quadro.\n\nNo quadro (kanban), essa ação está de propósito **fora** do arrastar-e-soltar: a coluna Concluída não aceita cartão solto nela, exatamente para que concluir passe sempre pelo botão dentro da ordem, com a conferência que ele implica.',
    relacionados: ['producao-quadro-kanban', 'producao-apontar-producao'],
  },
  {
    id: 'producao-op-wik-comum',
    modulo: 'producao',
    tela: 'Produção',
    titulo: 'O selo "Wik" na lista de ordens e o que acontece ao editar uma OP espelhada',
    rota: '/producao',
    perguntas: [
      'o que e o selo wik na lista de ordens',
      'ordem espelhada do wik',
      'editar ordem do wik desliga sincronizacao',
      'op do wik atrasada',
      'numero da op diferente entre wik e hub',
      'onde a op do wik esta no fluxo',
      'op vira op comum quando edito',
      'situacao da op no wik aparece no hub',
    ],
    resposta:
      'Na lista de **Ordens**, uma linha com o selo **Wik** (tom neutro) é uma ordem de produção que veio espelhada do Wik Sistemas — a coluna OP mostra o número dela lá, e passando o mouse no selo aparece a situação no Wik e, quando disponível, em quais etapas a produção está. Se houver previsão de entrega já vencida (cálculo feito pelo Hub), soma-se um segundo selo, "atrasada".\n\nO próprio texto do selo avisa: **editar essa ordem aqui desliga a sincronização dela com o Wik** — ela deixa de ser atualizada automaticamente e passa a ser tratada como uma ordem comum do Hub daqui para frente.',
    relacionados: ['producao-visao-geral-abas'],
  },
  {
    id: 'producao-roteiro-operacoes',
    modulo: 'producao',
    tela: 'Roteiro e consumo',
    titulo: 'Cadastrar o roteiro de operações de uma referência',
    rota: '/producao',
    perguntas: [
      'como cadastro o roteiro de uma referencia',
      'operacoes da producao por sequencia',
      'tempo padrao por peca',
      'mao de obra por peca de onde vem',
      'operacao terceirizada no roteiro',
      'setor da operacao',
      'adicionar operacao no roteiro',
      'tempo padrao parcial o que significa',
    ],
    resposta:
      'Na aba **Roteiro e consumo**, escolha a referência e a tabela mostra as operações cadastradas — sequência, nome, setor, tempo em segundos, R$/peça e se é interna ou de qual facção. O formulário no fim da tabela (**Adicionar operação**) cadastra uma nova: nome e sequência são obrigatórios; escolher uma facção no campo marca a operação como terceirizada automaticamente.\n\nOs dois indicadores no topo — **Tempo padrão / peça** e **Mão de obra / peça** — são a soma do tempo e do valor por peça de todas as operações do roteiro. Quando alguma operação está sem tempo ou sem valor cadastrado, o indicador vem marcado como "(parcial)" e o texto explica quantas operações ficaram de fora: o total nesse caso é um piso, não o tempo (ou custo) real da peça — nunca é tratado como zero.',
    relacionados: ['producao-consumo-por-tamanho', 'producao-carga-gargalo'],
  },
  {
    id: 'producao-consumo-por-tamanho',
    modulo: 'producao',
    tela: 'Roteiro e consumo',
    titulo: 'Cadastrar o consumo de material por tamanho',
    rota: '/producao',
    perguntas: [
      'consumo por tamanho o que e',
      'cadastrar consumo diferente por tamanho',
      'gg gasta mais malha que p',
      'celula vazia no consumo por tamanho',
      'material sem insumo vinculado',
      'salvar consumo por tamanho',
      'consumo geral da ficha x consumo por tamanho',
      'referencia sem tamanho cadastrado no consumo',
      'apagar consumo por tamanho volta pro geral',
    ],
    resposta:
      'Ainda em **Roteiro e consumo**, a tabela **Consumo por tamanho** lista cada material da ficha técnica em linhas e cada tamanho da referência em colunas, com a coluna **Ficha (geral)** mostrando o consumo único cadastrado na ficha. Preencher uma célula ali cadastra o consumo daquele material especificamente para aquele tamanho; **célula vazia volta a usar o consumo geral da ficha — que é diferente de consumo zero**. Depois de editar, **Salvar consumo por tamanho** grava, e as próximas ordens dessa referência já usam esse detalhamento.\n\nUma linha da ficha sem vínculo a nenhum insumo cadastrado ganha o selo "sem insumo": ela não é reservada nem custeada em ordem nenhuma, porque não existe insumo do outro lado. Se a referência não tiver tamanhos cadastrados no estoque, a tela avisa que não há por onde detalhar o consumo.',
    relacionados: ['producao-material-ordem', 'producao-roteiro-operacoes'],
  },
  {
    id: 'producao-wip-onde-esta',
    modulo: 'producao',
    tela: 'Onde está a produção',
    titulo: 'Ver onde a produção está parada, etapa por etapa (WIP)',
    rota: '/producao',
    perguntas: [
      'onde esta a producao agora',
      'wip de producao',
      'pecas paradas em cada etapa',
      'peca pronta esperando entrada no estoque',
      'ordem atrasada com peca no meio do caminho',
      'apontamento fora do roteiro',
      'apontamento que nao fecha entre etapas',
      'quanto tempo uma etapa esta sem apontamento',
      'peca sumida no meio da producao',
    ],
    resposta:
      'A aba **Onde está a produção** lê o apontamento já existente como fluxo: as peças "em espera" numa etapa são as que passaram por ela e ainda não foram apontadas na etapa seguinte, descontado o refugo. Os quatro indicadores do topo são **Peças dentro da fábrica** (começaram e não terminaram), **Prontas aguardando entrada** (passaram pela última etapa e ainda não foram lançadas no estoque — geralmente é isto que explica peça que "sumiu"), **Ainda não começaram** e **Ordens atrasadas**. A tabela **Fila por etapa** soma tudo por etapa, com o setor, quantas peças, quantas ordens e há quantos dias a etapa está sem apontamento.\n\nCada ordem aberta ganha seu próprio card com a tabela de etapas do roteiro (passaram, refugo, em espera, último apontamento) — a etapa marcada "última" é onde a peça pronta espera lançamento no estoque. Dois problemas ficam explicitamente à vista, porque são eles que sustentam o número: **apontamento fora do roteiro** (não some da conta, aparece numa lista dentro do card) e **apontamento que não fecha entre etapas** (costurar mais peças do que se cortou é impossível, então vira aviso, nunca vira zero calado, e a ordem fica marcada "apontamento incompleto"). Ordem sem roteiro cadastrado também entra nessa lista de ressalvas, porque sem sequência não há como medir a fila.',
    relacionados: ['producao-apontar-producao', 'producao-carga-gargalo'],
  },
  {
    id: 'producao-material-em-faccao',
    modulo: 'producao',
    tela: 'Material em facção',
    titulo: 'Ver o saldo de material e de peça pronta que está com a facção',
    rota: '/producao',
    perguntas: [
      'quanto de material esta na faccao',
      'saldo de insumo na faccao',
      'peca pronta em faccao conta no estoque',
      'material em faccao sem custo',
      'peca na faccao entra no disponivel para venda',
      'quantas faccoes tem material',
      'aba material em faccao o que mostra',
      'total incompleto no material em faccao',
    ],
    resposta:
      'A aba **Material em facção** mostra dois indicadores: **Material em facção** (o valor do nosso insumo que está fisicamente com terceiros — continua sendo estoque da empresa) e **Peça pronta em facção** (peça acabada que saiu daqui e continua sendo nossa). Os dois contam no total do estoque da empresa, mas **peça pronta em facção não conta no disponível para venda**. Quando algum item está sem custo conhecido, o total de material aparece marcado "(incompleto)" — o que falta fica de fora da soma, nunca vira zero.\n\nA tabela abaixo lista o saldo por facção e por insumo, com quantidade e valor (ou o selo "sem custo" quando não há preço). Essa aba lê o mesmo saldo que a tela **Gerar movimentação** movimenta — o número de peça pronta em facção só existe desde que o estoque ganhou um "lugar" próprio para ela (antes disso a remessa de peça pronta era registrada mas não mexia saldo nenhum).',
    relacionados: ['producao-lancar-movimento-faccao-aba', 'producao-mov-visao-geral'],
  },
  {
    id: 'producao-lancar-movimento-faccao-aba',
    modulo: 'producao',
    tela: 'Material em facção',
    titulo: 'Lançar remessa ou retorno de material ou peça para a facção',
    rota: '/producao',
    perguntas: [
      'lancar remessa de material para faccao',
      'registrar retorno de peca da faccao',
      'mandar material para faccao pela aba material em faccao',
      'buscar peca por referencia na faccao',
      'nota da remessa para faccao',
      'nao consigo mandar insumo e peca no mesmo lancamento',
      'diferenca entre remessa e retorno na aba faccao',
      'lancar movimento de peca pronta para faccao',
    ],
    resposta:
      'No bloco **Lançar movimento** da aba Material em facção, escolha a **Facção**, o **Tipo** (Remessa — sai daqui — ou Retorno — volta pra cá), e **O que está indo**: Material (malha, aviamento) ou Peça pronta. Escolhendo material, aparece um seletor com o catálogo de insumos; escolhendo peça, você digita a referência num campo de busca e aperta Enter, e a tela traz as variantes (cor/tamanho) com o disponível em cada uma para você escolher.\n\nO backend recusa receber insumo e variante de peça no mesmo lançamento de propósito: um movimento é de material **ou** de peça, nunca dos dois, porque misturar faria o saldo mexer em dois lugares por um único evento. Ao lançar peça pronta, o aviso confirma que ela "continua no total do estoque e saiu do disponível para venda"; ao lançar material, confirma que ele "mudou de lugar, não sumiu".',
    relacionados: ['producao-material-em-faccao', 'producao-mov-visao-geral'],
  },
  {
    id: 'producao-cadastro-faccao',
    modulo: 'producao',
    tela: 'Cadastro de facção',
    titulo: 'Cadastrar uma facção, ativar/desativar e gerenciar categorias',
    rota: '/producao',
    perguntas: [
      'como cadastro uma faccao nova',
      'campos do cadastro de faccao',
      'categoria de faccao para que serve',
      'faccao sem categoria',
      'faccao inativa some da lista',
      'indicadores da lista de faccoes',
      'excluir cadastro de faccao',
      'faccao pessoa fisica ou juridica',
      'criar categoria de faccao nova',
      'vincular categoria de faccao a uma etapa do fluxo',
      'quantas faccoes tem em cada categoria',
      'excluir categoria de faccao',
    ],
    resposta:
      'A aba **Cadastro de facção** lista as facções com quatro indicadores no topo — **Facções ativas**, **Peças fora daqui**, **O.S. atrasadas** e **Sem preço cadastrado** — e o botão **Nova facção** abre o formulário completo: identificação (PJ ou PF, nome, razão social, CNPJ/CPF, categoria), contato, endereço, forma de pagamento padrão, PIX ou dados bancários, capacidade por mês, campos adicionais livres (número de máquinas, dia de coleta etc.) e observações. Só o **Nome** é obrigatório para salvar. Desativar uma facção (checkbox **Ativa**, dentro do cadastro) tira ela das listas de escolha sem apagar o histórico; a exclusão de fato não está disponível pela tela.\n\nAs **categorias** (Costureira, Lavanderia, Bordado…) existem porque texto livre não agrupa — sem categoria fixa, "quanto gastei com lavanderia este mês" não tem resposta confiável. O botão **Categorias**, na barra de filtros, abre um painel com cada categoria já cadastrada: o nome (editável direto na célula), a **etapa do fluxo** associada a ela (opcional, também editável) e quantas facções estão naquela categoria — uma categoria nova se cria digitando o nome na linha em branco no fim da tabela e clicando **Criar**, e a exclusão de uma categoria pede confirmação e é permanente. Uma facção sem categoria fica marcada com um aviso na lista principal — o sistema não chuta uma categoria por ela.',
    relacionados: ['producao-ficha-faccao-preco', 'producao-importar-faccoes-wik', 'producao-mov-varios-destinos'],
  },
  {
    id: 'producao-ficha-faccao-preco',
    modulo: 'producao',
    tela: 'Ficha da facção',
    titulo: 'Cadastrar o preço de serviço da facção por etapa',
    rota: '/producao',
    perguntas: [
      'como cadastro o preco da faccao',
      'preco por etapa da faccao',
      'faccao sem preco cadastrado',
      'vigencia do preco da faccao',
      'reajustar preco da faccao sem mudar os antigos',
      'preco so para uma referencia',
      'encerrar preco vigente da faccao',
      'capacidade por mes da faccao',
    ],
    resposta:
      'Ao abrir uma facção na lista, a ficha dela tem a seção **Preço do serviço**: cadastre a **Etapa**, opcionalmente **Só para uma referência** (em branco vale para todas as referências), o **R$ por peça** e a partir de quando ele **Vale**. Esse é o preço que a Ordem de Serviço **congela** no momento da remessa — reajustar depois não reescreve O.S. antiga, e é por isso que cada preço tem vigência: cadastrar um novo não apaga o anterior, só o marca como não vigente a partir de então (ou você mesmo encerra um preço vigente pelo botão **Encerrar**, na linha dele).\n\nUma facção sem nenhum preço vigente cadastrado mostra um aviso explícito: toda O.S. dela vai nascer sem valor, e o custo do serviço aparece como "—" em vez de R$ 0,00 até alguém cadastrar aqui. A ficha também mostra a **Capacidade / mês** da facção (quando declarada), o material nosso que está na mão dela e o histórico de ordens de serviço.',
    relacionados: ['producao-cadastro-faccao', 'producao-mov-custo-remessa', 'producao-os-gerar-titulo'],
  },
  {
    id: 'producao-importar-faccoes-wik',
    modulo: 'producao',
    tela: 'Cadastro de facção',
    titulo: 'Importar facções do Wik (cadastro de Departamento)',
    rota: '/producao',
    perguntas: [
      'importar faccoes do wik',
      'trazer faccoes do departamento do wik',
      'faccao ja existe no wik nao duplica',
      'botao importar do wik na producao',
      'quantas faccoes foram criadas na importacao',
      'importar faccao sobrescreve o que ja editei',
      'faccao vinculada por nome do wik',
      'de onde vem a lista de faccoes do wik',
    ],
    resposta:
      'O botão **Importar do Wik**, na aba Cadastro de facção, traz as facções do cadastro de Departamento do Wik: cria as que ainda não existem no Hub e vincula, por nome, as que já existem — sem sobrescrever o que você já editou aqui. Ao terminar, a tela mostra quantas foram criadas, quantas foram vinculadas e quantas já existiam, do total encontrado no Wik.',
    relacionados: ['producao-cadastro-faccao'],
  },
  {
    id: 'producao-mov-visao-geral',
    modulo: 'producao',
    tela: 'Gerar Movimentação',
    titulo: 'O que a tela Gerar Movimentação faz e como escolher a origem',
    rota: '/producao/movimentacao',
    perguntas: [
      'como movimento pecas de uma etapa para outra',
      'gerar movimentacao de producao',
      'tela de movimentacao de producao',
      'de onde a peca sai na movimentacao',
      'entrada no fluxo o que e',
      'saldo da origem antes de movimentar',
      'ordem nao aparece na movimentacao',
      'posicao completa por etapa e grade',
    ],
    resposta:
      'A tela **Gerar movimentação** (`/producao/movimentacao`) tira peças de uma etapa (ou facção) e põe em outra, em vários destinos de uma vez, como a fábrica de fato trabalha. Toda movimentação acontece **dentro de uma ordem de produção**: escolha a OP primeiro — só aparecem ordens que não estão canceladas nem concluídas, porque essas não movimentam mais.\n\nA coluna **Origem — de onde a peça sai** mostra a posição atual da ordem por etapa e facção, com quantas peças há em cada uma; clicar numa linha (ou escolher no campo **Tirar de**) seleciona aquela origem e carrega o saldo por cor e tamanho, que é conferido antes de qualquer gravação — não se tira do corte o que não está no corte. A opção **"Entrada no fluxo"** é o primeiro movimento de uma ordem nova: não há saldo a conferir, e a grade que aparece para digitar é a **planejada da própria ordem**, porque é a única lista de cor/tamanho que existe antes do primeiro movimento.',
    relacionados: ['producao-mov-varios-destinos', 'producao-mov-tipos-movimento', 'producao-carga-gargalo'],
  },
  {
    id: 'producao-mov-tipos-movimento',
    modulo: 'producao',
    tela: 'Gerar Movimentação',
    titulo: 'Os tipos de movimento: normal, reprocesso e retorno',
    rota: '/producao/movimentacao',
    perguntas: [
      'tipos de movimento na producao',
      'o que e reprocesso na movimentacao',
      'motivo do reprocesso obrigatorio',
      'etapa que identificou o defeito',
      'diferenca entre retorno e reprocesso',
      'peca voltando de fora do fluxo',
      'ranking de qualidade por etapa causadora',
      'tipo de movimento normal o que e',
      'por que a etapa que achou o defeito e separada de quem causou',
    ],
    resposta:
      'Cada destino de uma movimentação tem um **Tipo do movimento**: **Normal** (a peça terminou aqui e segue para a etapa seguinte — o caminho comum), **Reprocesso** (a peça voltou para trás por defeito) e **Retorno** (a peça está voltando de uma etapa externa por fora do fluxo normal da O.S.).\n\nNo reprocesso, dois campos ficam obrigatórios: o **Motivo do reprocesso** (cadastro fechado, não texto livre — é o que permite ranquear defeito por causa) e a **Etapa que identificou o defeito**, que é registrada **separada** da etapa que causou o problema. Sem essa separação, o defeito ficaria sempre contado contra quem revisou a peça — normalmente a etapa de revisão — e o ranking de qualidade apontaria para o lado errado da fábrica.',
    relacionados: ['producao-mov-visao-geral', 'producao-carga-gargalo'],
  },
  {
    id: 'producao-mov-varios-destinos',
    modulo: 'producao',
    tela: 'Gerar Movimentação',
    titulo: 'Mandar peças para vários destinos numa movimentação só',
    rota: '/producao/movimentacao',
    perguntas: [
      'mandar metade das pecas para uma faccao e metade para outra',
      'varios destinos na mesma movimentacao',
      'adicionar destino na movimentacao',
      'etapa de destino gera os',
      'faccao que vai receber obrigatoria',
      'previsao de retorno obrigatoria',
      'cadastrar faccao nova durante a movimentacao',
      'excede o disponivel na origem',
    ],
    resposta:
      'O botão **Adicionar destino** cria mais um cartão de destino na mesma operação — metade da grade pode ir para uma facção e metade para outra, num ato só, e o saldo da origem é conferido contra a **soma de todos os destinos**, não destino por destino. Cada destino escolhe a **Etapa de destino**; quando essa etapa é **externa**, o cartão ganha o selo "gera O.S." e passam a ser obrigatórios a **Facção que vai receber** e a **Previsão de retorno** (sem prazo prometido não existe atraso para medir). Se a facção que você precisa ainda não existe, o botão **Nova**, ao lado do seletor, cadastra sem sair da tela — pedido de quem usa o sistema, para não perder o que já foi digitado no formulário.\n\nSe a soma pedida em algum destino passar do que existe na origem, a tela mostra um bloco de alerta antes de deixar gravar, linha por linha da grade que estourou.',
    relacionados: ['producao-mov-visao-geral', 'producao-mov-custo-remessa', 'producao-cadastro-faccao'],
  },
  {
    id: 'producao-mov-custo-remessa',
    modulo: 'producao',
    tela: 'Gerar Movimentação',
    titulo: 'O preço do serviço e o custo da remessa, antes de gravar',
    rota: '/producao/movimentacao',
    perguntas: [
      'preco do servico aparece antes de gravar',
      'custo da remessa para faccao',
      'faccao sem preco cadastrado na movimentacao',
      'quanto vai custar mandar para a faccao',
      'de onde vem o preco vigente da faccao',
      'custo de servico da operacao inteira',
      'nao dá pra dizer o custo da remessa',
      'custo de servico incompleto na movimentacao',
    ],
    resposta:
      'Para cada destino em etapa externa, a tela busca o **preço vigente** daquela facção naquela etapa (na data escolhida da movimentação) e mostra dois indicadores: **Preço do serviço** (o valor por peça) e **Custo desta remessa** (peças deste destino × preço por peça). É o mesmo preço que a O.S. gerada vai congelar. Quando não há preço cadastrado para aquela combinação de facção e etapa, os dois indicadores aparecem como **"sem preço cadastrado" / "não dá para dizer"**, nunca como R$ 0,00 — um zero ali diria que o serviço não custa nada, e o que existe é apenas a informação faltando.\n\nO indicador **Custo de serviço desta operação**, no topo da tela, soma o custo de todos os destinos externos preenchidos; se algum ficar sem preço, o total é marcado "(incompleto)" e a tela informa quantos destinos ficaram de fora da soma.',
    relacionados: ['producao-mov-varios-destinos', 'producao-ficha-faccao-preco', 'producao-os-visao-quebra'],
  },
  {
    id: 'producao-mov-estornar',
    modulo: 'producao',
    tela: 'Gerar Movimentação',
    titulo: 'Estornar um movimento no extrato da ordem',
    rota: '/producao/movimentacao',
    perguntas: [
      'como estorno uma movimentacao',
      'desfazer movimento de producao',
      'movimento estornado ainda aparece',
      'motivo do estorno obrigatorio',
      'extrato de movimentos da ordem',
      'quem fez a movimentacao aparece no extrato',
      'apagar movimento errado de producao',
      'estorno cria movimento novo ou apaga o antigo',
    ],
    resposta:
      'No card **Extrato desta ordem**, cada movimento tem o botão **Estornar** (indisponível para linhas já estornadas e para o próprio movimento de estorno). Ao clicar, é preciso digitar o motivo — sem ele o botão **Confirmar** do estorno fica desabilitado.\n\n**Movimento não se apaga.** Estornar cria um movimento novo, de pontas invertidas, em vez de apagar o original: a linha estornada fica marcada e riscada no extrato, mas continua lá, com data, de onde para onde foi e quem fez — é isso que responde depois "quem tirou 200 peças do corte na sexta".',
    relacionados: ['producao-mov-visao-geral'],
  },
  {
    id: 'producao-os-visao-quebra',
    modulo: 'producao',
    tela: 'Ordens de Serviço',
    titulo: 'O que é a Ordem de Serviço de facção e como a quebra é medida',
    rota: '/producao/ordens-servico',
    perguntas: [
      'o que e ordem de servico de faccao',
      'como nasce a os de faccao',
      'o que e quebra na os',
      'quebra negativa o que significa',
      'filtrar os atrasadas',
      'filtrar os com quebra',
      'link direto para uma os',
      'os sem preco de servico',
    ],
    resposta:
      'A **Ordem de Serviço** (`/producao/ordens-servico`) é o documento que vai junto com a mercadoria para a facção: o que ela tem que fazer, por quanto e até quando. Ela **nasce sozinha** quando alguém movimenta peça para uma etapa externa, na tela Gerar Movimentação — não existe um botão para criar uma O.S. do zero aqui. A lista traz filtros por número, facção, etapa ou referência, por **Situação** (Aberta, Remetida, Parcial, Concluída, Cancelada), e as caixinhas **Só atrasadas** e **Só com quebra**.\n\nO número que essa tela existe para mostrar é a **quebra**: remetido menos o que voltou bom, menos a segunda qualidade, menos a perda declarada. O que sobra é peça que sumiu — é medida pelo sistema, nunca digitada, e uma quebra **negativa** quer dizer peça a mais do que foi remetido, quase sempre erro de contagem na remessa. O.S. sem preço de serviço cadastrado mostra "—" no valor, nunca R$ 0,00; sem previsão de retorno mostra "sem prazo", nunca zero dia de atraso. Um link com `?os=123` na URL abre direto o detalhe daquela O.S.',
    relacionados: ['producao-os-registrar-retorno', 'producao-mov-custo-remessa', 'producao-ranking-faccao'],
  },
  {
    id: 'producao-os-registrar-retorno',
    modulo: 'producao',
    tela: 'Ordens de Serviço',
    titulo: 'Registrar o retorno de peças da facção',
    rota: '/producao/ordens-servico',
    perguntas: [
      'como registro o retorno da faccao',
      'peca boa segunda e perda no retorno',
      'etapa que recebe a peca boa obrigatoria',
      'excedeu o pendente no retorno',
      'os fecha sozinha quando tudo volta',
      'retorno nao coloca a peca em etapa nenhuma',
      'so etapa interna recebe retorno da faccao',
      'onde digito quebra no retorno',
    ],
    resposta:
      'Ao abrir uma O.S., a tabela de itens tem três colunas de lançamento por linha da grade: **Volta bom**, **Volta 2ª** e **Perdeu**. As três são separadas de propósito — peça boa é serviço a pagar, segunda qualidade sai do fluxo, perda é peça declarada como destruída — e o que não entrar em nenhuma delas vira **quebra sozinho**, porque não existe campo para digitar quebra diretamente.\n\nO campo **Etapa que recebe a peça boa** é obrigatório sempre que há peça boa voltando (a tela pré-escolhe a próxima etapa interna depois da etapa desta O.S., mas pode ser trocado; só etapas internas aparecem na lista, porque mandar para uma etapa externa por aqui seria uma remessa nova, com facção, prazo e preço — não um retorno). Isso foi corrigido depois de um caso em que o campo era opcional e abria vazio: registrar o retorno sem escolher etapa tirava as peças boas da facção sem colocá-las em lugar nenhum, e elas simplesmente somiam do sistema. Se a soma do que está sendo lançado passar do **Pendente** daquela linha, a tela mostra um alerta e não deixa registrar. Quando tudo que foi remetido já voltou de alguma forma, a O.S. é concluída automaticamente.',
    relacionados: ['producao-os-visao-quebra', 'producao-os-gerar-titulo', 'producao-mov-estornar'],
  },
  {
    id: 'producao-os-gerar-titulo',
    modulo: 'producao',
    tela: 'Ordens de Serviço',
    titulo: 'Gerar o título a pagar da facção, com ou sem retenção de INSS',
    rota: '/producao/ordens-servico',
    perguntas: [
      'gerar titulo a pagar da faccao',
      'reter inss na nota de servico',
      'aliquota de inss da faccao',
      'base do titulo da os',
      'segunda qualidade entra no titulo a pagar',
      'preco congelado na remessa para o titulo',
      'vencimento do titulo da faccao',
      'quebra entra no valor do titulo',
      'cessao de mao de obra reter inss',
    ],
    resposta:
      'Dentro da O.S., o botão **Gerar título a pagar** abre o formulário com **Peças boas** (só o que voltou bom é serviço prestado — segunda qualidade e quebra não entram; se a casa decidir pagar a segunda, isso é negociação e entra como ajuste no título), o **Preço por peça** congelado no dia da remessa, e a **Base do título** (peças boas × preço). É obrigatório escolher o **Vencimento** — um título sem vencimento não entra no fluxo de caixa.\n\nA checkbox **"Reter INSS nesta nota de serviço (cessão de mão de obra)"** libera o campo **Alíquota do INSS (%)**. O sistema não decide sozinho se há retenção nem assume uma alíquota padrão — marcar 11% para todo mundo produziria guia errada; essa marcação só deve ser feita quando a contabilidade da empresa disser que aquele caso retém. Ao gerar, a mensagem final mostra o valor bruto, quantas peças boas entraram na conta e, se havia quebra, deixa explícito que ela **não** entrou no valor.',
    relacionados: ['producao-os-registrar-retorno', 'producao-mov-custo-remessa'],
  },
  {
    id: 'producao-os-encerrar-cancelar',
    modulo: 'producao',
    tela: 'Ordens de Serviço',
    titulo: 'Encerrar uma O.S. assumindo a quebra, ou cancelá-la',
    rota: '/producao/ordens-servico',
    perguntas: [
      'os fica parcial para sempre',
      'encerrar os assumindo a quebra',
      'os nao fecha por causa da quebra',
      'como cancelo uma os',
      'os cancelada some da lista',
      'motivo obrigatorio para encerrar ou cancelar',
      'titulo ja gerado ao cancelar a os',
      'os lancada errada como corrijo',
      'quebra continua no ranking depois de encerrar',
    ],
    resposta:
      'Quando uma O.S. tem peça que nunca vai voltar, ela ficaria **parcial para sempre**: o que voltou nunca alcança o remetido, a data de retorno nunca é gravada e o atraso cresce sem fim — o que travaria a conclusão da ordem de produção permanentemente. Para isso existe o botão **Encerrar assumindo a quebra**, disponível quando a O.S. tem quebra e ainda pode receber: ele pede um motivo (por um `prompt` de texto) e encerra a O.S. reconhecendo que a peça não volta — a quebra continua medida e continua entrando no ranking daquela facção; encerrar não apaga o fato de que ela sumiu.\n\nO botão **Cancelar O.S.**, também no rodapé, existe para uma O.S. lançada errada — também pede motivo por texto. Cancelar não apaga a O.S.: ela fica marcada como cancelada, com o motivo registrado. O compromisso previsto com a facção é cancelado junto; um título já firme no financeiro, não — essa decisão é do financeiro, não desta tela.',
    relacionados: ['producao-os-visao-quebra', 'producao-os-gerar-titulo'],
  },
  {
    id: 'producao-carga-gargalo',
    modulo: 'producao',
    tela: 'Carga e Gargalo',
    titulo: 'Carga por etapa em minutos e onde está o gargalo',
    rota: '/producao/carga',
    perguntas: [
      'onde esta o gargalo da producao',
      'carga de trabalho por etapa',
      'minutos de trabalho pendente',
      'etapa sem tempo no roteiro',
      'maior fila em pecas x gargalo por minutos',
      'trabalho pendente incompleto',
      'como e calculada a carga em minutos',
      'tela carga e gargalo o que mostra',
      'barra de carga por etapa',
    ],
    resposta:
      'A tela **Carga e gargalo** (`/producao/carga`) mostra onde a produção está represada, mas em **minutos de trabalho pendentes**, não só em peças — uma etapa com 200 peças de 30 segundos cada está folgada; a mesma quantidade de peças de 8 minutos cada está travada há uma semana. Os indicadores do topo são Peças paradas em alguma etapa, Trabalho pendente (em horas), Gargalo por minutos (a etapa com mais minutos acumulados) e Maior fila em peças — que nem sempre é a mesma etapa do gargalo, porque muita peça rápida atravanca menos que pouca peça lenta.\n\nEtapa cujo roteiro **não tem tempo cadastrado** aparece na tabela **Carga por etapa** com o selo "sem tempo no roteiro" em vez de uma barra ou um valor zerado — zero minuto diria que a etapa está livre, exatamente o contrário do que se sabe sobre ela: não se sabe nada. Para uma etapa entrar nessa conta, é preciso cadastrar o tempo de uma operação do roteiro do produto com o **mesmo nome** da etapa. A barra de cada linha é sempre proporcional à maior carga da fábrica no momento.',
    relacionados: ['producao-roteiro-operacoes', 'producao-wip-onde-esta', 'producao-ranking-faccao'],
  },
  {
    id: 'producao-ranking-faccao',
    modulo: 'producao',
    tela: 'Carga e Gargalo',
    titulo: 'O ranking de facção: quebra, segunda, prazo e custo',
    rota: '/producao/carga',
    perguntas: [
      'ranking de faccoes',
      'qual faccao quebra mais',
      'faccao entrega no prazo',
      'comparar faccoes por qualidade',
      'sem os com prazo o que significa',
      'custo do servico por faccao',
      'onde vejo o ranking de faccao',
      'percentual de segunda qualidade por faccao',
    ],
    resposta:
      'Ainda em **Carga e gargalo**, o card **Ranking de facção** soma todas as ordens de serviço de cada facção e mostra, lado a lado: quantas O.S., o remetido, o que voltou bom, a quebra (em peças e em percentual), o percentual de segunda qualidade, quantas ficaram **No prazo** e o **Custo do serviço** apurado. A coluna de prazo só considera O.S. já **concluída** que tinha previsão de retorno cadastrada — o resto não tem como ser julgado, e aparece como "sem O.S. com prazo" em vez de contar contra a facção.\n\nO ranking só existe a partir do momento em que alguma peça foi remetida a uma etapa externa; sem O.S. nenhuma, a tela explica que não há o que comparar entre facções.',
    relacionados: ['producao-carga-gargalo', 'producao-os-visao-quebra', 'producao-ficha-faccao-preco'],
  },
  {
    id: 'producao-projecao-visao-geral',
    modulo: 'producao',
    tela: 'Projeção de Estoque',
    titulo: 'O que a Projeção de Estoque mostra e as três camadas por referência',
    rota: '/producao/projecao',
    perguntas: [
      'o que e a projecao de estoque',
      'projecao de estoque por cor e tamanho',
      'a producao nao resolve o que significa',
      'estoque projetado bruto e liquido',
      'camada 1 2 3 da projecao',
      'mostrar referencias sem ordem aberta',
      'projetado liquido descontando venda',
      'quatro numeros do topo da projecao',
    ],
    resposta:
      'A **Projeção de Estoque** (`/producao/projecao`) cruza duas perguntas que o sistema já respondia separadas: o que falta (cobertura) e o que está vindo (produção) — a ordem que já está aberta resolve a falta, ou chega curta? Os quatro números do topo são **Estoque hoje**, **Em produção** (soma das ordens vivas), **Projetado** (estoque + produção, bruto e líquido) e **"A produção não resolve"** — variantes que seguem abaixo do ponto de pedido mesmo depois da ordem chegar; esse último número é o motivo de a tela existir, não apenas mais uma tela de somar estoque. Por padrão a lista traz só referências com ordem viva; a caixinha **"Mostrar também referências sem ordem aberta"** amplia para todas.\n\nCada referência, ao expandir, abre em **três camadas**: **Camada 1 — Produção agrupada por referência**, a soma das ordens vivas na mesma grade cor × tamanho da OP, com um chip por ordem mostrando a data prevista (ou "sem data prevista") e quantas peças pendentes. **Camada 2 — Estoque real + em produção**, o saldo físico ao lado do que está a caminho, em azul (E = estoque, +P = produção). **Camada 3 — Estoque projetado após entrega das ordens**, em duas colunas: **Bruto** (o teto, sem descontar nada) e **Líquido**, que desconta a venda prevista até a chegada da última ordem — sem data prevista em alguma ordem, só o Bruto pode ser calculado, e a coluna Líquido fica vazia em vez de inventar uma data.',
    relacionados: ['producao-projecao-ressalvas', 'producao-projecao-exportar'],
  },
  {
    id: 'producao-projecao-ressalvas',
    modulo: 'producao',
    tela: 'Projeção de Estoque',
    titulo: 'As ressalvas da projeção: atraso, sem data, kit, entrega parcial e ordem encerrada',
    rota: '/producao/projecao',
    perguntas: [
      'ordem vencida na projecao',
      'peca vendida em kit nao entra na projecao',
      'possivel entrega parcial nao baixada',
      'ordem encerrada com saldo pendente',
      'por que o liquido saiu igual ao bruto',
      'suspeita de entrega parcial o que significa',
      'referencia sem data prevista na projecao',
      'ordem nao entra na soma da projecao por que',
      'avisos da projecao de estoque',
    ],
    resposta:
      'Cada card de referência pode trazer até cinco ressalvas escritas, nunca escondidas. Quando a data prevista mais distante venceu, a projeção avisa que **não há janela de venda a descontar** e o Líquido sai igual ao Bruto até a data ser replanejada. Havendo ordem **sem data prevista**, a coluna Líquido fica vazia porque não se inventa data. Peças vendidas **em kit** no período não têm cor e tamanho próprios, então a demanda por variante (e o Líquido) fica subestimada — a tela diz quantas peças isso afeta.\n\nA ressalva de **possível entrega parcial não baixada** aparece quando o saldo de alguma variante subiu desde a abertura da ordem, mas a grade continua declarando tudo pendente — um sinal de que as peças podem estar contadas duas vezes, com a lista de quais ordens e até quantas peças. Já **ordem encerrada com saldo pendente** sinaliza uma ordem concluída que deveria ter dado entrada de tudo, mas ficou com pendência — ou a entrada foi parcial, ou a grade não foi fechada; essa ordem **não entra** na soma da projeção enquanto isso não for corrigido.',
    relacionados: ['producao-projecao-visao-geral', 'producao-nova-ordem-abrir'],
  },
  {
    id: 'producao-projecao-exportar',
    modulo: 'producao',
    tela: 'Projeção de Estoque',
    titulo: 'Exportar a Projeção de Estoque em PDF ou Excel',
    rota: '/producao/projecao',
    perguntas: [
      'exportar projecao de estoque em pdf',
      'projecao em excel',
      'pdf da projecao com capa',
      'imprimir a projecao de estoque',
      'swatch de cor no pdf da projecao',
      'gerador proprio do pdf da projecao',
      'botao exportar pdf desabilitado na projecao',
      'exportacao da projecao falhou',
    ],
    resposta:
      'Os botões **Exportar PDF** e **Excel**, no topo da Projeção de Estoque, respeitam os filtros aplicados na hora (período, busca, "mostrar todas") e ficam desabilitados enquanto não há dados carregados. O PDF tem um **gerador próprio** (não o motor genérico de relatório do sistema), com uma referência por página e o swatch de cor pintado na própria célula da tabela — o Excel continua usando o motor genérico de relatório, onde a tabela crua é justamente o que se quer.\n\nSe a geração falhar, a tela mostra o erro explicitamente em vez de deixar a pessoa achar que o arquivo baixou — falhar em silêncio aqui foi tratado como o pior caso possível.',
    relacionados: ['producao-projecao-visao-geral'],
  },
];
