// Verbetes das telas e funções que entraram em setembro/2026: Piso de Preço
// (/marketplace/piso), Planejamento (/producao/planejamento), Pós-venda
// (/marketplace/pos-venda), Matéria-Prima (/producao/materia-prima), Full
// (/marketplace/full), Contas Bancárias (/financeiro/contas-bancarias) e uma
// leva de "como faço" (permissão de módulo, cores e grade do produto,
// devolução, editar anúncio, histórico de alteração, estoque mínimo, Manu
// analista). Cada tela foi lida até o fim antes de escrever o verbete —
// nomes de botão, aba e coluna estão como aparecem no JSX.

export const verbetesSetembro = [
  // -------------------------------------------------------------------
  // Piso de Preço — /marketplace/piso
  // -------------------------------------------------------------------
  {
    id: 'mkt-piso-o-que-e-regras',
    modulo: 'marketplace',
    tela: 'Piso de Preço',
    titulo: 'O que é o piso de preço, como é calculado e onde mudo a regra',
    rota: '/marketplace/piso',
    perguntas: [
      'o que e piso de preco',
      'como e calculado o piso',
      'pra que serve o piso de preco',
      'menor preco que posso vender',
      'margem minima do piso',
      'onde mudo a margem minima',
      'criar regra de piso',
      'nova regra de piso por canal',
      'regra de piso por referencia',
      'piso por classe abc',
      'embalagem entra no custo do piso',
      'quem vendeu abaixo do piso',
      'trava do piso motivo',
      'piso',
    ],
    resposta:
      'O **Piso de Preço** é o menor preço que cada canal aguenta por referência: o preço que ainda deixa a **margem mínima** depois do imposto da empresa, da comissão da faixa do canal (tabela de Taxas de Marketplace), do frete subsidiado pelo peso, das taxas de venda e, quando a regra pede, de publicidade e devolução previstas e da embalagem.\n\nSem regra, vale a margem mínima geral de **Configurações → Parâmetros**. Na aba **Regras**, o botão **Nova regra** refina por **Canal**, **Classe ABC** ou **Referência**, com Margem mínima (%), Publicidade prevista (%), Devolução prevista (%) e a chave "Embalagem entra no custo". A regra mais específica vence: referência, depois canal + classe, canal, classe e a geral. Só quem tem Configurações cria ou desativa regra.\n\n**Trava:** ao alterar o preço (aqui ou em Anúncios) ou criar promoção abaixo do piso, o sistema pede o motivo e grava quem assinou. Tudo aparece em **Quem vendeu abaixo do piso**, na aba Regras.',
    relacionados: ['mkt-piso-auditoria-situacoes', 'mkt-piso-simular-campanha', 'config-parametros-faixas-margem'],
  },
  {
    id: 'mkt-piso-auditoria-situacoes',
    modulo: 'marketplace',
    tela: 'Piso de Preço',
    titulo: 'Auditoria dos anúncios: prejuízo, abaixo do piso, no limite, sem piso e "deixado na mesa"',
    rota: '/marketplace/piso',
    perguntas: [
      'quais anuncios estao abaixo do piso',
      'anuncio com prejuizo',
      'o que e deixado na mesa',
      'na mesa piso de preco',
      'o que significa no limite',
      'por que o anuncio esta sem piso',
      'sem piso o que fazer',
      'auditoria dos anuncios',
      'ajustar preco pelo piso',
      'publicar preco novo na plataforma',
      'margem minima do anuncio',
      'anuncio vendendo abaixo do custo',
    ],
    resposta:
      'A aba **Auditoria dos anúncios** mostra uma linha por anúncio no ar (no Mercado Livre as cores entram juntas; a seta abre as variações). Colunas: Anúncio, Canal, Referência, **Preço → piso**, **Margem / mínima**, Vendas 30 d, **Na mesa** e **Situação**:\n\n- **Prejuízo** — vende abaixo do custo.\n- **Abaixo do piso** — margem menor que a mínima da regra.\n- **No limite** — até 5% acima do piso.\n- **Acima do piso** — tudo certo.\n- **Sem piso** — sem referência vinculada, sem custo ou canal sem tabela; o motivo aparece na linha e a trava não dispara.\n\n**Deixado na mesa** = (lucro no piso − lucro no preço atual) × peças vendidas pelo anúncio em 30 dias. Sem venda ligada aparece "?", que não é zero.\n\nOs quatro números do topo filtram a lista ao clicar (clique de novo para soltar). **Ajustar preço** abre a gaveta com o piso ao lado: digite o preço novo, veja a margem e clique em **Publicar na plataforma**.',
    relacionados: ['mkt-piso-o-que-e-regras', 'mkt-anuncios-editar'],
  },
  {
    id: 'mkt-piso-simular-campanha',
    modulo: 'marketplace',
    tela: 'Piso de Preço',
    titulo: 'Simular uma campanha de desconto e acompanhar concorrentes',
    rota: '/marketplace/piso',
    perguntas: [
      'simular campanha de desconto',
      'vale a pena dar desconto',
      'simulador de cupom',
      'quanto preciso vender a mais com desconto',
      'para empatar o que significa',
      'guardar simulacao',
      'simulacoes guardadas',
      'preco fixo na campanha',
      'acompanhar concorrente',
      'preco do concorrente mercado livre',
      'ler precos agora concorrente',
      'concorrente mais barato que nos',
    ],
    resposta:
      'A aba **Simular campanha** responde "vale a pena esse desconto?" em três passos:\n\n1. **Escolher os anúncios** — clique em **Escolher referências** e marque as linhas (uma por referência e canal; as variações entram juntas; até 300 anúncios).\n2. **A campanha** — Tipo (**Desconto %**, **Cupom %** ou **Preço fixo**), valor, **Taxa da campanha (%)**, **Taxa fixa por peça (R$)** e os dias usados para medir a venda. Clique em **Simular**.\n3. **Resultado** — Sobra por dia hoje, Na campanha (mesmo volume), **Para empatar** (quanto a mais o conjunto precisa vender por dia) e quantos não fecham ou ficam abaixo do piso. A tabela mostra, por anúncio, a sobra por peça hoje e na campanha e o "Precisa vender".\n\nDê um nome e clique em **Guardar** para ir para **Simulações guardadas**.\n\nA aba **Concorrentes** acompanha preço de outros vendedores: **Acompanhar concorrente** liga um link do Mercado Livre a uma referência sua (lido a cada 6 horas; **Ler preços agora** força). Nos outros canais o preço é digitado.',
    relacionados: ['mkt-piso-o-que-e-regras', 'mkt-promocoes-margem-ao-vivo'],
  },

  // -------------------------------------------------------------------
  // Planejamento — /producao/planejamento
  // -------------------------------------------------------------------
  {
    id: 'producao-planejamento-sugestoes',
    modulo: 'producao',
    tela: 'Planejamento',
    titulo: 'O que são as sugestões do Planejamento (OP e compra de tecido) e o lote',
    rota: '/producao/planejamento',
    perguntas: [
      'como planejar compra de tecido',
      'planejar compra de tecido',
      'quanto tecido comprar',
      'planejamento de producao',
      'o que e o planejamento',
      'planejamento sugerido',
      'gerar sugestoes de op',
      'o sistema sugere a op',
      'sugestao de compra de tecido',
      'o que e lote do planejamento',
      'ultima rodada do planejamento',
      'sugestao substituida',
      'por que nao teve sugestao',
      'ja vai faltar planejamento',
      'sazonalidade estacao e datas',
      'fator do mes planejamento',
      'data dupla black friday fator',
    ],
    resposta:
      'O **Planejamento** junta Cobertura, Curva de Tamanho e Matéria-Prima: prevê a venda das próximas semanas com a estação e as datas fortes, monta a OP com grade cor × tamanho e a compra de tecido que ela puxa. Tudo é **sugestão**; só vira OP ou pedido quando alguém aprova.\n\nEscolha o período de venda base (3 meses é o padrão) e clique em **Gerar sugestões**. A frase do topo mostra a **última rodada** (o lote): data, janela de venda usada e quantas referências foram avaliadas. Gerar de novo mantém o que não mudou, com suas edições, e marca o resto como **substituída**. Nada é apagado.\n\nIndicadores: **OPs a aprovar**, **Já vai faltar** (o estoque acaba antes de a OP chegar), **Tecido a comprar** e **Sem sugestão** (clique para ver o motivo de cada referência).\n\nAberta, cada sugestão mostra a conta: vende × estação = vai vender × ciclo = preciso − tenho = produzir. A aba **Estação e datas** ajusta o fator de cada mês e das datas duplas; evento sem fator não entra na conta.',
    relacionados: ['producao-planejamento-aprovar-recusar', 'estoque-cobertura-como-e-calculado', 'producao-materia-prima-referencia'],
  },
  {
    id: 'producao-planejamento-aprovar-recusar',
    modulo: 'producao',
    tela: 'Planejamento',
    titulo: 'Aprovar, editar ou recusar uma sugestão de OP ou de compra de tecido',
    rota: '/producao/planejamento',
    perguntas: [
      'como aprovo a sugestao de op',
      'aprovar op sugerida',
      'abrir op pelo planejamento',
      'abrir como rascunho',
      'recusar sugestao',
      'motivo da recusa',
      'editar grade da op sugerida',
      'voltar a sugerida',
      'escolher faccao na sugestao',
      'aprovar compra de tecido',
      'gerar pedido de tecido',
      'historico do planejamento',
    ],
    resposta:
      'Na aba **Produzir**, clique numa sugestão para abrir. A **Grade da OP** é editável célula por célula (aparece o selo "editada"; **Voltar à sugerida** desfaz). Escolha a **Facção** (ou "decidir depois") e a data em **Chega em**. Depois:\n\n- **Aprovar · abrir OP de N pç** — abre a ordem como planejada, pelo mesmo caminho da Nova Ordem, com evento no Calendário.\n- **Abrir como rascunho** — abre a OP em rascunho.\n- **Recusar** — escreva o motivo (obrigatório) e clique em **Confirmar recusa**.\n\nSe a ficha tiver tamanho sem consumo, o sistema pergunta se abre mesmo assim. Falta de tecido não trava a OP.\n\nNa aba **Comprar tecido**, cada linha (tecido + cor) mostra Preciso, Tenho, Comprar e Fornecedor. Abra, confira Fornecedor, Quantidade, Valor unitário e Previsão de entrega e clique em **Aprovar · gerar pedido**: vira pedido em **rascunho** em Compras. A aba **Histórico** separa Aprovadas, Recusadas e Substituídas, com a OP ou o pedido que cada uma virou.',
    relacionados: ['producao-planejamento-sugestoes', 'producao-nova-ordem-abrir', 'compras-pedido-aprovar'],
  },

  // -------------------------------------------------------------------
  // Pós-venda — /marketplace/pos-venda
  // -------------------------------------------------------------------
  {
    id: 'mkt-pos-venda-painel',
    modulo: 'marketplace',
    tela: 'Pós-venda',
    titulo: 'O painel de Pós-venda: o que exige ação, motivos e "alimenta"',
    rota: '/marketplace/pos-venda',
    perguntas: [
      'o que e pos venda',
      'onde vejo as devolucoes',
      'onde vejo as reclamacoes',
      'perguntas sem resposta',
      'avaliacoes ruins',
      'preciso resolver pos venda',
      'marcar como tratada',
      'classificar motivo da devolucao',
      'o que e alimenta modelagem qualidade',
      'responder pergunta do mercado livre',
      'taxa de devolucao',
      'ler as lojas agora',
      'evento sem vinculo com o produto',
    ],
    resposta:
      '**Pós-venda** junta o que o cliente diz depois de comprar (devolução, reclamação, pergunta e avaliação), ligado à referência, cor e tamanho. **Ler as lojas agora** busca na hora; a leitura automática é de hora em hora. O botão de lojas mostra o que cada loja entrega por API e o erro por escrito.\n\nNo topo: **Preciso resolver**, **Taxa de devolução** (peças devolvidas ÷ vendidas no período), **Nota média** e **Sem vínculo com o produto**.\n\nA aba **Resolver** lista o que exige ação: pergunta sem resposta, reclamação aberta, devolução em andamento, avaliação de até 3★ sem tratar e referência devolvendo demais. Clique para abrir a gaveta: escolha o **Motivo** (Ficou pequeno, Ficou grande, Defeito, Diferente da foto, Peça errada, Atraso…), use **Marcar como tratada** e, no Mercado Livre, responda a pergunta.\n\nCada motivo **alimenta** uma área: Modelagem, Qualidade, Anúncio, Expedição ou Logística. O motivo vem do código da plataforma ou do texto do cliente; o classificado à mão nunca é sobrescrito.',
    relacionados: ['mkt-pos-venda-por-referencia', 'mkt-registrar-devolucao'],
  },
  {
    id: 'mkt-pos-venda-por-referencia',
    modulo: 'marketplace',
    tela: 'Pós-venda',
    titulo: 'Devolução por referência, sinais de modelagem e comparação entre períodos',
    rota: '/marketplace/pos-venda',
    perguntas: [
      'qual referencia devolve mais',
      'taxa de devolucao por referencia',
      'sinal de modelagem',
      'tamanho veste menor que a etiqueta',
      'tamanho veste maior',
      'devolucao por tamanho',
      'amostra pequena devolucao',
      'para quem fala devolucao',
      'comparar dois periodos devolucao',
      'evolucao da taxa de devolucao',
      'devolucao mes a mes',
      'o que perguntam antes de comprar',
    ],
    resposta:
      'A aba **Por referência** mostra, para cada referência com evento no período: **Devolve** (a taxa), Devolvidas, Vendidas, Reclamações, Nota e **Para quem fala** (a área que mais recebe as devoluções). Com menos de 20 peças vendidas aparece o selo **amostra pequena**.\n\nClicando na linha abre a gaveta com os motivos das devoluções, a tabela **Por tamanho** (devolvidas, vendidas, taxa, pequeno, grande, defeito) e o que perguntam antes de comprar. No alto dela ficam os **sinais de modelagem**: num tamanho, pelo menos 3 devoluções por "ficou pequeno" e 3 vezes mais que por "ficou grande" (ou o inverso), como "o M veste menor que a etiqueta". Três ou mais defeitos no mesmo tamanho também viram sinal.\n\nNa gaveta, **Ver os eventos** filtra a aba Eventos pela referência, e **Evolução e comparar períodos** abre a aba **Evolução**: a taxa mês a mês ou semana a semana e o comparador período A × B, com a diferença em pontos percentuais.',
    relacionados: ['mkt-pos-venda-painel', 'estoque-curva-tamanho-visao-geral'],
  },

  // -------------------------------------------------------------------
  // Matéria-Prima — /producao/materia-prima
  // -------------------------------------------------------------------
  {
    id: 'producao-materia-prima-referencia',
    modulo: 'producao',
    tela: 'Matéria-Prima',
    titulo: 'Matéria-Prima por referência: os quadros cor × tamanho e o que preencher',
    rota: '/producao/materia-prima',
    perguntas: [
      'quanto tecido preciso',
      'materia prima por referencia',
      'como cadastro o tecido da referencia',
      'consumo por peca tecido',
      'perda no corte',
      'fornecedor leva dias',
      'ligar cor da peca com cor do tecido',
      'cor do tecido falta',
      'preencher sugestoes cor do tecido',
      'saldo do tecido onde informo',
      'preciso tenho falta produzir',
      'ver catalogo inteiro materia prima',
      'confirmo que e kg ou metro',
    ],
    resposta:
      '**Matéria-Prima** diz quanto tecido cada referência precisa, quanto existe e o que comprar. Clique numa referência para abrir. Em cima ficam os campos a preencher: **Tecido**, **Cada peça gasta**, **Perda no corte** (%), **Fornecedor leva** (dias), **Compra de** (a barca, lote mínimo), **Temporada** (×) e "confirmo que é" kg ou m. Clique em **Salvar**.\n\nAbaixo, três quadros cor × tamanho:\n- **Preciso** — o estoque mínimo;\n- **Tenho** — galpão + facção (o "+" é o que está na facção);\n- **Falta produzir** — por tamanho.\n\nNo cartão **Tecido · o que comprar**, ligue cada **Cor da peça** a uma **Cor do tecido** (**Preencher sugestões** usa as que o sistema achou pelo nome; confira) e informe o saldo em **Tenho**. Clique em **Salvar**. Cor sem cor do tecido ligada não entra no pedido.\n\n**Ver catálogo inteiro** mostra as referências ainda sem tecido. O seletor **Calcular** troca a base: Para produzir o que falta, Para a grade cheia ou Como a planilha calculava.',
    relacionados: ['producao-materia-prima-comprar-por-tecido', 'producao-planejamento-sugestoes', 'compras-insumos-cadastro'],
  },
  {
    id: 'producao-materia-prima-comprar-por-tecido',
    modulo: 'producao',
    tela: 'Matéria-Prima',
    titulo: 'Comprar por tecido: o pedido consolidado e o arredondamento na barca',
    rota: '/producao/materia-prima',
    perguntas: [
      'comprar por tecido',
      'quanto tecido comprar',
      'o que e barca',
      'arredondar pedido na barca',
      'lote minimo do fornecedor tecido',
      'pedido de tecido somado',
      'mesmo tecido em varias referencias',
      'saldo nao sei tecido',
      'falta cadastro materia prima',
      'pedido atrasado tecido',
      'coluna pedir em dias',
      'por que o pedido saiu exato',
    ],
    resposta:
      'O quadro **Comprar por tecido**, no alto da tela, é de onde sai o pedido ao fornecedor: soma o mesmo tecido na mesma cor entre todas as referências que o usam (o selo "N refs" diz quantas). Colunas: Tecido, Cor, **Preciso**, **Tenho**, **Comprar**, **Pedir** (em quantos dias; "há N d" se já passou; "de sobra" acima de 180) e **Situação** (Comprar, Atrasado, No limite, OK, Falta cadastro).\n\n**Comprar** é o que falta depois do saldo e do que já está em compras, **arredondado para cima no múltiplo da barca**. A barca é o campo "Compra de" da referência; entre várias referências, vale a maior. Sem barca cadastrada, o pedido sai exato, sem arredondar.\n\nSaldo em branco aparece como **não sei**, e não como zero, por isso a linha fica em "Falta cadastro". Clique na linha para ver a conta de cada referência (peças × consumo) e avisos de unidade não confirmada ou perda de corte não cadastrada. O "falta" dentro de cada referência é só dela; o pedido é o daqui.',
    relacionados: ['producao-materia-prima-referencia', 'producao-planejamento-aprovar-recusar'],
  },

  // -------------------------------------------------------------------
  // Full — /marketplace/full
  // -------------------------------------------------------------------
  {
    id: 'mkt-full-visao-geral',
    modulo: 'marketplace',
    tela: 'Full',
    titulo: 'A tela Full: saldo no centro de distribuição, quanto dura e quanto mandar',
    rota: '/marketplace/full',
    perguntas: [
      'o que e a tela full',
      'estoque no full',
      'quanto tenho no full do mercado livre',
      'anuncio zerado no full',
      'quanto tempo dura o estoque no full',
      'quanto mandar pro full',
      'envio atrasado full',
      'cor zerada no full',
      'atualizar das lojas full',
      'envio deve durar dias',
      'fulfillment',
      'reposicao do full',
    ],
    resposta:
      'A tela **Full** mostra o estoque que está dentro do centro de distribuição do marketplace. **Atualizar das lojas** lê o saldo de cada loja, a partir dos anúncios que a aba Anúncios já trouxe.\n\nNo topo: **Peças no Full**, **Precisam de envio**, **Zerados no Full**, **Envio atrasado** (a data limite de saída daqui já passou) e **Sem venda para medir**. Cada anúncio aparece em **Cartões** ou **Tabela**, com a situação: Zerado no Full, Envio atrasado, Mandar esta semana, Cor zerada no Full, Planejar envio, Abastecido ou Fora da reposição.\n\nO filtro **envio deve durar** (15 a 90 dias, ou o padrão da loja) muda a quantidade a mandar e a data limite da tela inteira. A velocidade vem da venda recente quando o anúncio está há 30 dias ou mais no Full; abaixo disso, da venda geral do anúncio.\n\nClicando no anúncio abre o painel com Resumo, Vendas, Saldo no Full, Envios, **Cores e tamanhos** (o "mandar" repartido pela grade que vendeu), Composição e Ajustes.',
    relacionados: ['mkt-full-plano-envio', 'mkt-anuncios-publicacao-variacao'],
  },
  {
    id: 'mkt-full-plano-envio',
    modulo: 'marketplace',
    tela: 'Full',
    titulo: 'Montar a reposição do Full: plano de produção, registrar envio e ajustes',
    rota: '/marketplace/full',
    perguntas: [
      'como monto o envio pro full',
      'plano de producao do full',
      'marcar tudo que precisa de envio',
      'imprimir remessa do full',
      'registrar envio para o full',
      'abrir ordem de producao pelo full',
      'vincular referencia no full',
      'nao repor este anuncio',
      'estoque minimo no full',
      'ajustes do full por loja',
      'multiplo de envio',
      'kit no full composicao',
    ],
    resposta:
      'Clique em **Marcar tudo que precisa de envio** (ou marque os cartões um a um) e depois em **Plano de produção**. O plano separa o que precisa ser **enviado**, o que **já está na casa** e o que precisa ser **produzido**. Ali dá para mudar quanto o envio deve durar, **Abrir ordem de produção** (em rascunho, com a grade preenchida), **Ver o papel** e **Imprimir remessa**. Anúncio sem referência aparece em "Precisam de vínculo antes de virar produção": use **Vincular referência** no painel dele.\n\nNo painel do anúncio, a aba **Envios** tem **Registrar um envio** (peças, ou kits, despachadas e a data em que saiu); é isso que faz o "a caminho" abater a reposição. A aba **Ajustes** aceita **Estoque mínimo no Full**, **Quantos dias o envio deve durar** e **Não repor este anúncio**; vazio usa o cálculo. Clique em **Gravar ajustes**.\n\n**Ajustes do Full**, no topo, guarda por loja: envio deve durar, recebimento, segurança, múltiplo de envio e janela de venda.',
    relacionados: ['mkt-full-visao-geral', 'producao-nova-ordem-abrir'],
  },

  // -------------------------------------------------------------------
  // Contas Bancárias — /financeiro/contas-bancarias
  // -------------------------------------------------------------------
  {
    id: 'financeiro-contas-bancarias-cadastrar',
    modulo: 'financeiro',
    tela: 'Contas Bancárias',
    titulo: 'Cadastrar, editar, desativar ou excluir uma conta bancária',
    rota: '/financeiro/contas-bancarias',
    perguntas: [
      'como cadastro conta bancaria',
      'nova conta bancaria',
      'editar conta bancaria',
      'saldo inicial da conta',
      'data do saldo inicial',
      'cadastrar caixa da loja',
      'conta de aplicacao',
      'desativar conta bancaria',
      'excluir conta bancaria',
      'conta vinda do wik travada',
      'saldo por empresa cnpj',
      'conta nao aparece na conciliacao',
    ],
    resposta:
      'Em **Contas Bancárias**, clique em **Nova conta** e preencha: **Empresa (CNPJ)** (não muda depois), **Nome da conta** (ex.: "Itaú — Origem"), **Tipo** (Conta bancária, Caixa / cofre ou Aplicação), Banco, Código do banco, Agência, Conta com dígito, **Saldo inicial** e **Data do saldo inicial**, que é o saldo do extrato naquele dia e a base do saldo atual. Clique em **Salvar conta**.\n\nPara editar, clique no lápis do cartão da conta, mude e clique em **Salvar** (ou Cancelar). Conta **vinda do Wik** tem nome, tipo, agência e conta travados, porque o Wik reescreve; banco, saldo inicial e data são seus.\n\n**Desativar** tira a conta do seletor da Conciliação e da baixa de título sem apagar extrato nem baixas (**Reativar** volta; **Mostrar desativadas** exibe). A lixeira exclui. Cada cartão mostra Saldo atual, Saldo inicial e Último lançamento; no topo, o saldo em conta aparece separado por empresa.',
    relacionados: ['financeiro-conciliacao-importar-ofx', 'financeiro-pagar-baixar'],
  },

  // -------------------------------------------------------------------
  // "Como faço" — permissões, cadastro, devolução, anúncio, histórico
  // -------------------------------------------------------------------
  {
    id: 'config-permissao-modulo-usuario',
    modulo: 'configuracoes',
    tela: 'Acessos — Usuários',
    titulo: 'Dar ou tirar permissão de um módulo para um usuário',
    rota: '/acessos',
    perguntas: [
      'como dou permissao de modulo',
      'liberar modulo para usuario',
      'tirar acesso de um modulo',
      'usuario nao ve o financeiro',
      'dar acesso ao marketplace',
      'permissao de usuario',
      'modulos liberados',
      'perfil limitado ou administrador',
      'como libero a producao pra alguem',
      'funcionario nao ve a tela',
      'acesso por modulo',
    ],
    resposta:
      'Só **administrador** faz isso. Vá em **Acessos**, sub-aba **Usuários**, e ache a pessoa (busca por nome ou e-mail).\n\n1. Confira o **Perfil**: **Administrador** vê tudo; **Limitado** só vê os módulos marcados.\n2. Com perfil Limitado aparece **Módulos liberados**: marque ou desmarque Produto, Estoque, Produção, Vendas, Marketplace, Financeiro, Viagens, Compras, Análises, Calendário e Configurações. Cada clique grava na hora; não tem botão de salvar.\n\nPara alguém novo, **Novo usuário** pede Nome, E-mail, Senha inicial, Perfil, Módulos liberados e Grupos; depois clique em **Criar usuário**.\n\nBom saber: quem tem **Estoque** também enxerga a Produção. Algumas ações pedem um módulo a mais; por exemplo, as Regras do Piso de Preço só são editadas por quem tem Configurações. Grupos servem para o Calendário e não liberam módulo.',
    relacionados: ['config-acessos-usuarios', 'config-acessos-grupos', 'geral-tela-nao-aparece'],
  },
  {
    id: 'produto-cores-e-grade',
    modulo: 'produto',
    tela: 'Ficha do Produto',
    titulo: 'Cadastrar e editar as cores e a grade de tamanhos de um produto',
    rota: '/produtos',
    perguntas: [
      'cadastrar cores do produto',
      'cores do produto',
      'cadastrar cor',
      'grade do produto',
      'cadastrar grade',
      'como cadastro as cores do produto',
      'adicionar cor na referencia',
      'excluir cor do produto',
      'editar grade de tamanhos',
      'adicionar tamanho na grade',
      'onde vejo as cores da referencia',
      'cores e grade do produto',
      'gerar variantes que faltam',
      'puxar cores do estoque',
      'tom da cor bolinha',
      'grade usada na ordem de producao',
      'tirei a cor e ela continua',
    ],
    resposta:
      'Abra a ficha do produto (clique na linha em **Produtos**). Em produto já salvo aparece o cartão **Cores e grade**:\n\n- **Cores**: edite o nome, escolha o **Tom** (a cor da bolinha), use **+ Cor** para acrescentar e a lixeira para tirar.\n- **Grade de tamanhos**: **+ Tamanho** acrescenta, a lixeira tira. A ordem segue a da casa (PP, P, M, G, GG…), não a da digitação.\n\nClique em **Salvar cores e grade**. É essa grade que a ordem de produção usa.\n\nO cadastro é o que a referência **pode** ter; a variante é o que ela **tem**, com EAN e saldo. Tirar uma cor que ainda tem variante no estoque só a **desativa** (a tela avisa em "O que saiu da lista"); sem variante, ela é excluída.\n\n**Puxar do estoque** traz cor e tamanho das variantes que já existem. **Gerar as N variante(s) que faltam** cria no estoque, com saldo zero, as combinações que faltam. A **Grade completa** mostra o saldo de cada cor × tamanho; traço quer dizer que a variante ainda não existe.',
    relacionados: ['produto-editar-dados-basicos', 'estoque-adicionar-variante', 'gloss-grade'],
  },
  {
    id: 'mkt-registrar-devolucao',
    modulo: 'marketplace',
    tela: 'Pós-venda — Devoluções no Hub',
    titulo: 'Registrar uma devolução e dar destino às peças',
    rota: '/marketplace/pos-venda',
    perguntas: [
      'como registro uma devolucao',
      'registrar devolucao',
      'cliente devolveu a peca',
      'devolucao que chegou por fora',
      'devolucao de venda de atacado',
      'peca devolvida volta pro estoque',
      'marcar devolucao como recebida',
      'avaliar e dar destino',
      'segunda qualidade devolucao',
      'descarte de peca devolvida',
      'cancelar devolucao',
      'reembolso da devolucao',
    ],
    resposta:
      'Devolução lida da plataforma já aparece sozinha em **Pós-venda › Eventos**. Para a que chega por fora, ou que a plataforma não avisou, use a aba **Devoluções no Hub**:\n\n1. Clique em **Registrar devolução**.\n2. Digite o **Número do pedido** e clique em **Buscar**.\n3. Escolha o **Motivo** e preencha, se quiser, o que o cliente disse e o **Reembolso (R$)**.\n4. Em **O que voltou**, preencha **Devolve agora** nos itens (a tabela mostra o que foi comprado e o que já foi devolvido).\n5. Clique em **Abrir devolução**.\n\nEla nasce **Aguardando chegar**. Quando a peça chegar, abra e clique em **Chegou — marcar como recebida**. Depois escolha o **Destino** de cada item (**Volta a vender**, **Segunda qualidade**, **Conserto** ou **Descarte**) e clique em **Avaliar e dar destino**. Só a avaliação mexe no estoque: Volta a vender e Segunda qualidade devolvem a peça; Conserto e Descarte não. Dá para **Cancelar** enquanto não foi avaliada.',
    relacionados: ['mkt-pos-venda-painel', 'estoque-movimentar-entrada-saida'],
  },
  {
    id: 'mkt-anuncios-editar',
    modulo: 'marketplace',
    tela: 'Anúncios',
    titulo: 'Editar um anúncio (preço, estoque, título, pausar) direto na plataforma',
    rota: '/marketplace/anuncios',
    perguntas: [
      'como edito um anuncio',
      'mudar preco do anuncio',
      'alterar estoque do anuncio',
      'mudar titulo do anuncio',
      'pausar anuncio',
      'ativar anuncio pausado',
      'alterar na plataforma',
      'editar anuncio mercado livre pelo sistema',
      'mudar preco de uma cor so',
      'preco abaixo do piso pede motivo',
      'onde fica a aba editar',
    ],
    resposta:
      'Em **Marketplace › Anúncios**, clique no cartão do anúncio para abrir o painel lateral e vá na aba **Editar**. Os campos são:\n\n- **Preço** e **Estoque** (mostram o valor de hoje);\n- **Título**;\n- **Situação** — Ativo ou Pausado.\n\nCampo deixado em "não mudar" não é enviado. Clique em **Alterar na plataforma** e confirme: a alteração **vai para o ar na hora** e fica registrada na aba **Histórico** do painel, com o seu nome.\n\nSe o anúncio tem várias variações, preço e estoque vão para **todas**; para mexer numa cor só, use o painel da plataforma. Se o preço novo ficar **abaixo do piso** do canal, o sistema pede o motivo antes de enviar, e sem motivo nada vai para a plataforma.\n\nNum cartão com o selo "N variações", clique primeiro no cartão e depois na variação para chegar ao painel.',
    relacionados: ['mkt-anuncios-publicacao-variacao', 'mkt-piso-auditoria-situacoes'],
  },
  {
    id: 'config-historico-alteracoes',
    modulo: 'configuracoes',
    tela: 'Acessos — Histórico',
    titulo: 'Ver quem alterou um registro (histórico de alteração)',
    rota: '/acessos',
    perguntas: [
      'como ver quem alterou um registro',
      'quem alterou',
      'quem mudou isso',
      'quem alterou esse registro',
      'historico de alteracao',
      'quem mexeu no produto',
      'quem apagou',
      'ver o que mudou antes e depois',
      'log do sistema',
      'quem entrou no sistema',
      'tentativa de login errada',
      'auditoria de usuarios',
      'o que cada pessoa fez',
      'alteracoes nao salvas barra',
    ],
    resposta:
      'Quem alterou o quê fica em **Acessos**, sub-aba **Histórico**, que só **administrador** vê. Cada linha mostra **Quando**, **Quem**, **Ação** (criou, alterou, excluiu, entrou…), **Área** (Produtos, Estoque, Financeiro…), **O que aconteceu** e **Endereço** (IP). Nas linhas com "clique para ver o que mudou", o clique mostra o antes e o depois.\n\nFiltre pela busca (pessoa, descrição, registro), **Usuário**, **Ação**, **Área**, **De**, **Até** e **Só o que falhou** (senha errada, acesso negado). O nome de quem fez fica guardado mesmo se a conta for excluída; senha e token nunca aparecem. O histórico só existe a partir da atualização de segurança.\n\nAlguns registros têm histórico próprio, como a aba **Histórico** do anúncio e o histórico de preço do produto.\n\nNão confunda com a barra de rodapé "**N alterações não salvas**" (com **Descartar**, **Salvar** e Ctrl+S) das telas de Configurações: ela avisa o que você mudou e ainda não gravou.',
    relacionados: ['config-acessos-usuarios', 'produto-historico-preco'],
  },
  {
    id: 'estoque-definir-minimo-referencia',
    modulo: 'estoque',
    tela: 'Cobertura e Reposição',
    titulo: 'Definir o estoque mínimo de uma referência',
    rota: '/estoque/cobertura',
    perguntas: [
      'como defino o estoque minimo',
      'mudar estoque minimo da referencia',
      'onde coloco o estoque minimo',
      'estoque minimo de uma referencia',
      'digitar estoque minimo',
      'estoque de seguranca',
      'minimo muito alto',
      'minimo muito baixo',
      'o que repor estoque minimo',
      'estoque minimo no full',
      'prazo proprio da referencia',
    ],
    resposta:
      'O estoque mínimo de uma referência **não é digitado**: a tela **Cobertura e Reposição** (menu "O que repor") calcula pela venda e pelo prazo. O que você define é o que entra na conta. Abra a linha da referência pela seta e, em **Como esta referência é reposta**, ajuste:\n\n- **Cadência** — Semanal, Quinzenal, Mensal ou Sob demanda; a escolha à mão vence a sugerida e o recálculo não sobrescreve.\n- **Prazo próprio (dias)** — quando a peça demora diferente das outras da mesma cadência.\n- **Nível** — Essencial, Intermediário, Sob demanda ou A descontinuar (classifica e filtra a tela).\n\nCada mudança grava na hora e a tela recalcula; o resultado aparece em **Como cheguei nesse número › Estoque mínimo**. O botão **Prazos de produção** muda os prazos padrão de cada cadência só na tela aberta: ao recarregar, voltam a 7/15/30 + 3/5/7 dias.\n\nEsse mínimo é o "Preciso" da Matéria-Prima. No **Full**, a aba **Ajustes** do anúncio aceita um **Estoque mínimo no Full** digitado.',
    relacionados: ['estoque-cobertura-como-e-calculado', 'estoque-cobertura-cadencia-e-prazos', 'mkt-full-plano-envio'],
  },

  // -------------------------------------------------------------------
  // Manu analista — /ajuda
  // -------------------------------------------------------------------
  {
    id: 'geral-manu-analista',
    modulo: 'geral',
    tela: 'Ajuda',
    titulo: 'Perguntar para a Manu: o que ela responde sobre os números',
    rota: '/ajuda',
    perguntas: [
      'o que a manu sabe responder',
      'perguntar pra manu',
      'manu analista',
      'a manu responde quanto vendi',
      'perguntar numero pra manu',
      'manu nao entendeu minha pergunta',
      'o que a manu nao sabe',
      'resumo do dia manu',
      'manu responde sobre estoque',
      'manu responde sobre producao',
      'exemplos de pergunta pra manu',
      'manu inventa numero',
    ],
    resposta:
      'Digite no campo "Pergunta pra Manu do jeito que quiser…" (na Ajuda ou no botão da Manu). Ela responde por regras fixas, com os números do próprio sistema, sem inventar.\n\nSabe: vendas (ontem, hoje, semana, mês; por canal, loja, vendedor, viagem, kit, referência, cor, tamanho), margem e por que caiu (inclusive mix entre canais), ADS/TACOS, preço, custo e piso, anúncios ativos e mais vendidos, devoluções, reclamações, perguntas e nota, estoque (o que vai zerar, parado, total, por cor e tamanho), produção (OP pelo número, por facção, o que chega na semana, atrasadas), planejamento, saldo de tecido e insumo, contas a pagar e receber, fluxo de caixa, vencidos, envios e coletas, conexões, atrasos e resumo do dia.\n\nAinda não sabe, e avisa com link: previsão de venda, saldo de banco, repasse do marketplace, venda por cliente, cidade ou horário, conferência.\n\nToda resposta tem botão para a tela de origem; "como faço…" vai para os verbetes. Exemplos:\n- Quanto vendi ontem?\n- Por que a margem da OG1620 caiu esse mês?\n- Tem OG1620 preta no M?\n- Qual facção está atrasada?',
    relacionados: ['geral-busca-cmdk', 'producao-planejamento-sugestoes', 'mkt-piso-auditoria-situacoes'],
  },
];
