// Verbetes do módulo Vendas — pedidos lançados manualmente (/pedidos,
// /pedidos/:id, origemFiltro="manual"), clientes (/clientes,
// /clientes/:id), Ficha de Venda (/ficha-venda) e a Lucratividade das
// vendas manuais (/vendas/lucratividade). PedidosListPage e
// RelatorioLucratividadePage são compartilhados com o módulo Marketplace
// (mesmo componente, prop origemFiltro diferente) — aqui só descrevo o
// que aparece quando a origem é "manual"; a versão de marketplace (com
// Ads, TACOS, MPA, escrow, vincular produto etc.) tem verbete próprio no
// módulo Marketplace.

export const verbetesVendas = [
  {
    id: 'vendas-pedidos-listar-filtrar',
    modulo: 'vendas',
    tela: 'Pedidos de Venda',
    titulo: 'Ver e filtrar os pedidos de venda',
    rota: '/pedidos',
    perguntas: [
      'onde vejo os pedidos de venda',
      'lista de pedidos',
      'filtrar pedidos por situacao',
      'buscar pedido por cliente',
      'buscar pedido por numero',
      'pedidos em aberto',
      'pedidos faturados',
      'pedidos cancelados',
      'quantos pedidos tenho',
      'exportar pedidos de venda',
      'pedidos lancados manualmente',
    ],
    resposta:
      'A tela **Pedidos de Venda** lista os pedidos lançados manualmente (loja física, WhatsApp etc. — ainda não emite nota fiscal). Dá pra buscar por cliente ou número do pedido, e filtrar por situação: **Aberto**, **Faturado** ou **Cancelado**.\n\nCada linha mostra número, data, cliente, canal, quantidade de peças, total líquido e situação. A lista pode ser exportada em CSV/XLSX, e clicar em **Novo pedido** cria um pedido em branco e já abre a ficha dele pra começar a lançar itens.',
    relacionados: ['vendas-pedido-criar-lancar-cliente'],
  },
  {
    id: 'vendas-pedido-criar-lancar-cliente',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Criar um pedido e vincular o cliente',
    rota: '/pedidos',
    perguntas: [
      'como crio um pedido novo',
      'novo pedido de venda',
      'vincular cliente no pedido',
      'buscar cliente no pedido',
      'cadastrar cliente direto no pedido',
      'cliente rapido no pedido',
      'trocar cliente do pedido',
      'dados do pedido vendedor operacao canal',
      'condicao e forma de pagamento do pedido',
      'preencher cabecalho do pedido',
    ],
    resposta:
      'Clicando em **Novo pedido**, o sistema já cria o pedido (em aberto) e abre a ficha dele. No card **Cliente**, busque por nome, CPF/CNPJ ou telefone e clique em **Selecionar** — ou, se o cliente ainda não existe, clique em **Novo cliente** pra cadastrar rapidinho (nome, telefone, CPF/CNPJ) sem sair da tela do pedido. Dá pra trocar o cliente depois, enquanto o pedido estiver aberto.\n\nO card **Dados do Pedido** guarda data, empresa emitente, vendedor, operação, canal de venda, condição e forma de pagamento, desconto (em % ou em R$), acréscimo, frete e observação — cada campo salva sozinho ao sair dele (não precisa de um botão Salvar geral). Esses campos só ficam editáveis enquanto o pedido está **aberto**.',
    relacionados: ['vendas-pedidos-listar-filtrar', 'vendas-pedido-lancar-itens'],
  },
  {
    id: 'vendas-pedido-lancar-itens',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Lançar itens num pedido (por EAN ou por busca)',
    rota: '/pedidos',
    perguntas: [
      'como lanco item no pedido',
      'adicionar produto no pedido',
      'bipar item no pedido de venda',
      'buscar referencia pra adicionar no pedido',
      'quantidade e valor unitario do item do pedido',
      'desconto por item no pedido',
      'remover item do pedido',
      'editar item ja lancado',
      'item sem estoque no pedido',
    ],
    resposta:
      'Com o pedido aberto, o card **Lançar Item** tem duas formas de adicionar: bipar/digitar o código de barras (EAN) e a quantidade, ou buscar por referência/descrição e clicar em **Adicionar** no resultado. Cada item lançado mostra a quantidade em estoque disponível daquela variante.\n\nNa tabela **Itens da Venda**, com o pedido ainda aberto, dá pra editar quantidade, valor unitário e desconto (%) direto na linha — o total do item recalcula sozinho. O ícone de lixeira remove um item. Depois de faturado ou cancelado, os itens ficam só pra leitura.',
    relacionados: ['vendas-pedido-criar-lancar-cliente', 'vendas-pedido-faturar'],
  },
  {
    id: 'vendas-pedido-faturar',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Faturar um pedido',
    rota: '/pedidos',
    perguntas: [
      'como faturo um pedido',
      'faturar pedido de venda',
      'botao faturar pedido',
      'faturar baixa o estoque',
      'nao consigo faturar pedido sem item',
      'pedido faturado nao edita mais',
      'faturar pedido pede confirmacao',
    ],
    resposta:
      'Com o pedido aberto e pelo menos um item lançado, clique em **Faturar Pedido**. O sistema pede confirmação avisando que o estoque de cada item será baixado automaticamente — depois de confirmado, o pedido muda para a situação **Faturado** e os campos ficam travados pra edição.\n\nO botão fica desabilitado enquanto não há nenhum item lançado, então não dá pra faturar um pedido vazio.',
    relacionados: ['vendas-pedido-lancar-itens', 'vendas-pedido-cancelar-excluir'],
  },
  {
    id: 'vendas-pedido-cancelar-excluir',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Cancelar ou excluir um pedido',
    rota: '/pedidos',
    perguntas: [
      'como cancelo um pedido',
      'cancelar pedido faturado',
      'cancelar pedido devolve o estoque',
      'como excluo um pedido',
      'excluir pedido em aberto',
      'diferenca entre cancelar e excluir pedido',
      'desfazer pedido faturado',
      'estornar estoque de um pedido',
    ],
    resposta:
      '**Cancelar Pedido** funciona em qualquer situação, menos num pedido já cancelado. Se o pedido já estava **faturado**, cancelar também estorna (devolve) o estoque de cada item automaticamente — o sistema avisa isso antes de pedir confirmação. Se ainda estava aberto, cancelar só muda a situação, sem mexer em estoque (nada tinha sido baixado ainda).\n\n**Excluir** só aparece pra pedidos em **aberto** — remove o pedido de vez ("não pode ser desfeita"). Um pedido faturado ou cancelado não pode ser excluído, só cancelado (se ainda não estiver).',
    relacionados: ['vendas-pedido-faturar'],
  },
  {
    id: 'clientes-listar-filtrar',
    modulo: 'vendas',
    tela: 'Clientes',
    titulo: 'Ver e buscar clientes cadastrados',
    rota: '/clientes',
    perguntas: [
      'onde vejo os clientes',
      'lista de clientes',
      'buscar cliente por nome',
      'buscar cliente por cpf',
      'buscar cliente por telefone',
      'quantos clientes tenho cadastrado',
      'exportar lista de clientes',
      'cliente inativo aparece na lista',
    ],
    resposta:
      'A tela **Clientes** lista o cadastro usado nos pedidos de venda, com nome, CPF/CNPJ, telefone, cidade/UF, vendedor e se está ativo. Busca por nome, CPF/CNPJ ou telefone, colunas ordenáveis e exportação em CSV/XLSX, como nas outras listas do sistema. Clicar numa linha abre a ficha completa daquele cliente.',
    relacionados: ['clientes-cadastrar-editar'],
  },
  {
    id: 'clientes-cadastrar-editar',
    modulo: 'vendas',
    tela: 'Ficha do Cliente',
    titulo: 'Cadastrar ou editar um cliente',
    rota: '/clientes/novo',
    perguntas: [
      'como cadastro um cliente novo',
      'novo cliente',
      'editar dados do cliente',
      'cliente pessoa fisica ou juridica',
      'inscricao estadual do cliente',
      'limite de credito do cliente',
      'vendedor padrao do cliente',
      'tabela de preco do cliente',
      'desativar cliente',
      'remover cliente',
      'campos obrigatorios do cliente',
      'cliente novo como faco o cadastro',
    ],
    resposta:
      'Na ficha do cliente (Novo cliente, ou abrindo um já existente), escolha o **Tipo de Pessoa** (Física ou Jurídica) — isso muda os rótulos e libera Nome Fantasia e Inscrição Estadual (com opção "Isento") pra Pessoa Jurídica. O **Nome** (ou Razão Social) é o único campo obrigatório.\n\nOs demais cards são Contato (telefone/WhatsApp, e-mail), Endereço (com busca automática pelo CEP) e Comercial (vendedor padrão, tabela de preço, limite de crédito e o toggle Ativo — desativar não apaga o cadastro, só tira ele do uso normal). O botão **Remover**, disponível só em clientes já salvos, apaga o cadastro depois de confirmar.',
    relacionados: ['clientes-buscar-cep', 'clientes-listar-filtrar'],
  },
  {
    id: 'clientes-buscar-cep',
    modulo: 'vendas',
    tela: 'Ficha do Cliente',
    titulo: 'Preencher o endereço automaticamente pelo CEP',
    rota: '/clientes/novo',
    perguntas: [
      'como busco endereco pelo cep',
      'buscar cep',
      'busca cep',
      'buscar endereco por cep',
      'preencher endereco automatico',
      'cep nao encontrado',
      'busca de cep nao funciona',
      'preencher cidade e uf pelo cep',
      'endereco veio errado do cep',
    ],
    resposta:
      'No campo **CEP** da ficha do cliente, digite os 8 dígitos e clique no ícone de lupa/pin ao lado — o sistema consulta o CEP (serviço público ViaCEP) e preenche sozinho logradouro, bairro, cidade e UF. Se o CEP não existir ou a consulta falhar (por exemplo, sem internet no momento), aparece um aviso e é só preencher o endereço manualmente — nada trava por isso.',
    relacionados: ['clientes-cadastrar-editar'],
  },
  {
    id: 'vendas-ficha-venda-gerar',
    modulo: 'vendas',
    tela: 'Ficha de Venda',
    titulo: 'Gerar e imprimir a Ficha de Venda (custo + preço)',
    rota: '/ficha-venda',
    perguntas: [
      'como gero a ficha de venda',
      'imprimir ficha de venda',
      'ficha de venda mostra preco',
      'diferenca entre ficha tecnica e ficha de venda',
      'exportar ficha de venda em pdf',
      'selecionar referencias pra ficha de venda',
      'ficha de venda quantas referencias',
    ],
    resposta:
      'A tela **Ficha de Venda** funciona igual à Ficha Técnica (busca por referência/código/descrição, adiciona até 5 de uma vez, **Gerar fichas**, depois **Imprimir / Exportar PDF**), mas o documento gerado é mais completo: além do custo de produção, ele traz também a **Formação de Preço** — preço mínimo, ideal, premium, markup, lucro estimado e o preço de venda praticado, com o selo de status da margem.\n\nÉ a ficha pensada pra quem está vendendo (mostra o preço), diferente da Ficha Técnica do módulo Produto, que mostra só o custo de produção.',
    relacionados: ['gloss-ficha-tecnica', 'produto-ficha-tecnica-gerar'],
  },
  {
    id: 'vendas-lucratividade',
    modulo: 'vendas',
    tela: 'Lucratividade',
    titulo: 'Ver a lucratividade das vendas manuais',
    rota: '/vendas/lucratividade',
    perguntas: [
      'onde vejo a lucratividade das vendas',
      'lucro das vendas manuais',
      'relatorio de lucratividade de vendas',
      'margem das vendas do periodo',
      'filtrar lucratividade por periodo',
      'exportar relatorio de lucratividade',
      'pedido sem custo cadastrado na lucratividade',
      'lucratividade por canal de venda',
    ],
    resposta:
      'A tela **Lucratividade** (dentro de Vendas) mostra o lucro real de cada pedido lançado manualmente: preço de venda menos o custo de produção — o mesmo custo usado na Ficha de Custo, não uma estimativa à parte. Filtra por período, por canal de venda (texto livre) e por busca (número do pedido, cliente, SKU ou referência), e dá pra exportar ou imprimir o resumo.\n\nPedidos com algum item sem produto vinculado aparecem com o aviso "sem custo cadastrado" e ficam de fora do total do topo — receita real com custo zero infla a margem artificialmente, então o sistema prefere excluir esses casos do total em vez de mostrar um número errado. Essa é a versão simples da lucratividade; a versão do módulo Marketplace tem várias seções a mais (Ads, TACOS, vincular produto, valor recebido/escrow) — ver o verbete equivalente lá.',
    relacionados: ['gloss-margem-contribuicao', 'gloss-precos-referencia'],
  },
];
