// Verbetes do módulo Vendas — pedidos lançados manualmente (/pedidos,
// /pedidos/:id, origemFiltro="manual"), clientes (/clientes,
// /clientes/:id), Ficha de Venda (/ficha-venda) e a Lucratividade das
// vendas manuais (/vendas/lucratividade). PedidosListPage e
// RelatorioLucratividadePage são compartilhados com o módulo Marketplace
// (mesmo componente, prop origemFiltro diferente) — aqui só descrevo o
// que aparece quando a origem é "manual"; a versão de marketplace (com
// Ads, TACOS, MPA, escrow, vincular produto etc.) tem verbete próprio no
// módulo Marketplace.

export const verbetesVendas = [
  {
    id: 'vendas-pedidos-listar-filtrar',
    modulo: 'vendas',
    tela: 'Pedidos de Venda',
    titulo: 'Ver e filtrar os pedidos de venda',
    rota: '/pedidos',
    perguntas: [
      'onde vejo os pedidos de venda',
      'lista de pedidos',
      'filtrar pedidos por situacao',
      'buscar pedido por cliente',
      'buscar pedido por numero',
      'pedidos em aberto',
      'pedidos faturados',
      'pedidos cancelados',
      'quantos pedidos tenho',
      'exportar pedidos de venda',
      'pedidos lancados manualmente',
    ],
    resposta:
      'A tela **Pedidos de Venda** lista os pedidos lançados manualmente (loja física, WhatsApp etc. — ainda não emite nota fiscal). Dá pra buscar por cliente ou número do pedido, e filtrar por situação: **Aberto**, **Faturado** ou **Cancelado**.\n\nCada linha mostra número, data, cliente, canal, quantidade de peças, total líquido e situação. A lista pode ser exportada em CSV/XLSX, e clicar em **Novo pedido** cria um pedido em branco e já abre a ficha dele pra começar a lançar itens.',
    relacionados: ['vendas-pedido-criar-lancar-cliente'],
  },
  {
    id: 'vendas-pedido-criar-lancar-cliente',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Criar um pedido e vincular o cliente',
    rota: '/pedidos',
    perguntas: [
      'como crio um pedido novo',
      'novo pedido de venda',
      'vincular cliente no pedido',
      'buscar cliente no pedido',
      'cadastrar cliente direto no pedido',
      'cliente rapido no pedido',
      'trocar cliente do pedido',
      'dados do pedido vendedor operacao canal',
      'condicao e forma de pagamento do pedido',
      'preencher cabecalho do pedido',
    ],
    resposta:
      'Clicando em **Novo pedido**, o sistema já cria o pedido (em aberto) e abre a ficha dele. No card **Cliente**, busque por nome, CPF/CNPJ ou telefone e clique em **Selecionar** — ou, se o cliente ainda não existe, clique em **Novo cliente** pra cadastrar rapidinho (nome, telefone, CPF/CNPJ) sem sair da tela do pedido. Dá pra trocar o cliente depois, enquanto o pedido estiver aberto.\n\nO card **Dados do Pedido** guarda data, empresa emitente, vendedor, operação, canal de venda, condição e forma de pagamento, desconto (em % ou em R$), acréscimo, frete e observação — cada campo salva sozinho ao sair dele (não precisa de um botão Salvar geral). Esses campos só ficam editáveis enquanto o pedido está **aberto**.',
    relacionados: ['vendas-pedidos-listar-filtrar', 'vendas-pedido-lancar-itens'],
  },
  {
    id: 'vendas-pedido-lancar-itens',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Lançar itens num pedido (por EAN ou por busca)',
    rota: '/pedidos',
    perguntas: [
      'como lanco item no pedido',
      'adicionar produto no pedido',
      'bipar item no pedido de venda',
      'buscar referencia pra adicionar no pedido',
      'quantidade e valor unitario do item do pedido',
      'desconto por item no pedido',
      'remover item do pedido',
      'editar item ja lancado',
      'item sem estoque no pedido',
    ],
    resposta:
      'Com o pedido aberto, o card **Lançar Item** tem duas formas de adicionar: bipar/digitar o código de barras (EAN) e a quantidade, ou buscar por referência/descrição e clicar em **Adicionar** no resultado. Cada item lançado mostra a quantidade em estoque disponível daquela variante.\n\nNa tabela **Itens da Venda**, com o pedido ainda aberto, dá pra editar quantidade, valor unitário e desconto (%) direto na linha — o total do item recalcula sozinho. O ícone de lixeira remove um item. Depois de faturado ou cancelado, os itens ficam só pra leitura.',
    relacionados: ['vendas-pedido-criar-lancar-cliente', 'vendas-pedido-faturar'],
  },
  {
    id: 'vendas-pedido-faturar',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Faturar um pedido',
    rota: '/pedidos',
    perguntas: [
      'como faturo um pedido',
      'faturar pedido de venda',
      'botao faturar pedido',
      'faturar baixa o estoque',
      'nao consigo faturar pedido sem item',
      'pedido faturado nao edita mais',
      'faturar pedido pede confirmacao',
    ],
    resposta:
      'Com o pedido aberto e pelo menos um item lançado, clique em **Faturar Pedido**. O sistema pede confirmação avisando que o estoque de cada item será baixado automaticamente — depois de confirmado, o pedido muda para a situação **Faturado** e os campos ficam travados pra edição.\n\nO botão fica desabilitado enquanto não há nenhum item lançado, então não dá pra faturar um pedido vazio.',
    relacionados: ['vendas-pedido-lancar-itens', 'vendas-pedido-cancelar-excluir'],
  },
  {
    id: 'vendas-pedido-cancelar-excluir',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Cancelar ou excluir um pedido',
    rota: '/pedidos',
    perguntas: [
      'como cancelo um pedido',
      'cancelar pedido faturado',
      'cancelar pedido devolve o estoque',
      'como excluo um pedido',
      'excluir pedido em aberto',
      'diferenca entre cancelar e excluir pedido',
      'desfazer pedido faturado',
      'estornar estoque de um pedido',
    ],
    resposta:
      '**Cancelar Pedido** funciona em qualquer situação, menos num pedido já cancelado. Se o pedido já estava **faturado**, cancelar também estorna (devolve) o estoque de cada item automaticamente — o sistema avisa isso antes de pedir confirmação. Se ainda estava aberto, cancelar só muda a situação, sem mexer em estoque (nada tinha sido baixado ainda).\n\n**Excluir** só aparece pra pedidos em **aberto** — remove o pedido de vez ("não pode ser desfeita"). Um pedido faturado ou cancelado não pode ser excluído, só cancelado (se ainda não estiver).',
    relacionados: ['vendas-pedido-faturar'],
  },
  {
    id: 'clientes-listar-filtrar',
    modulo: 'vendas',
    tela: 'Clientes',
    titulo: 'Ver e buscar clientes cadastrados',
    rota: '/clientes',
    perguntas: [
      'onde vejo os clientes',
      'lista de clientes',
      'buscar cliente por nome',
      'buscar cliente por cpf',
      'buscar cliente por telefone',
      'quantos clientes tenho cadastrado',
      'exportar lista de clientes',
      'cliente inativo aparece na lista',
    ],
    resposta:
      'A tela **Clientes** lista o cadastro usado nos pedidos de venda, com nome, CPF/CNPJ, telefone, cidade/UF, vendedor e se está ativo. Busca por nome, CPF/CNPJ ou telefone, colunas ordenáveis e exportação em CSV/XLSX, como nas outras listas do sistema. Clicar numa linha abre a ficha completa daquele cliente.',
    relacionados: ['clientes-cadastrar-editar'],
  },
  {
    id: 'clientes-cadastrar-editar',
    modulo: 'vendas',
    tela: 'Ficha do Cliente',
    titulo: 'Cadastrar ou editar um cliente',
    rota: '/clientes/novo',
    perguntas: [
      'como cadastro um cliente novo',
      'novo cliente',
      'editar dados do cliente',
      'cliente pessoa fisica ou juridica',
      'inscricao estadual do cliente',
      'limite de credito do cliente',
      'vendedor padrao do cliente',
      'tabela de preco do cliente',
      'desativar cliente',
      'remover cliente',
      'campos obrigatorios do cliente',
      'cliente novo como faco o cadastro',
    ],
    resposta:
      'Na ficha do cliente (Novo cliente, ou abrindo um já existente), escolha o **Tipo de Pessoa** (Física ou Jurídica) — isso muda os rótulos e libera Nome Fantasia e Inscrição Estadual (com opção "Isento") pra Pessoa Jurídica. O **Nome** (ou Razão Social) é o único campo obrigatório.\n\nOs demais cards são Contato (telefone/WhatsApp, e-mail), Endereço (com busca automática pelo CEP) e Comercial (vendedor padrão, tabela de preço, limite de crédito e o toggle Ativo — desativar não apaga o cadastro, só tira ele do uso normal). O botão **Remover**, disponível só em clientes já salvos, apaga o cadastro depois de confirmar.',
    relacionados: ['clientes-buscar-cep', 'clientes-listar-filtrar'],
  },
  {
    id: 'clientes-buscar-cep',
    modulo: 'vendas',
    tela: 'Ficha do Cliente',
    titulo: 'Preencher o endereço automaticamente pelo CEP',
    rota: '/clientes/novo',
    perguntas: [
      'como busco endereco pelo cep',
      'buscar cep',
      'busca cep',
      'buscar endereco por cep',
      'preencher endereco automatico',
      'cep nao encontrado',
      'busca de cep nao funciona',
      'preencher cidade e uf pelo cep',
      'endereco veio errado do cep',
    ],
    resposta:
      'No campo **CEP** da ficha do cliente, digite os 8 dígitos e clique no ícone de lupa/pin ao lado — o sistema consulta o CEP (serviço público ViaCEP) e preenche sozinho logradouro, bairro, cidade e UF. Se o CEP não existir ou a consulta falhar (por exemplo, sem internet no momento), aparece um aviso e é só preencher o endereço manualmente — nada trava por isso.',
    relacionados: ['clientes-cadastrar-editar'],
  },
  {
    id: 'vendas-ficha-venda-gerar',
    modulo: 'vendas',
    tela: 'Ficha de Venda',
    titulo: 'Gerar e imprimir a Ficha de Venda (custo + preço)',
    rota: '/ficha-venda',
    perguntas: [
      'como gero a ficha de venda',
      'imprimir ficha de venda',
      'ficha de venda mostra preco',
      'diferenca entre ficha tecnica e ficha de venda',
      'exportar ficha de venda em pdf',
      'selecionar referencias pra ficha de venda',
      'ficha de venda quantas referencias',
    ],
    resposta:
      'A tela **Ficha de Venda** funciona igual à Ficha Técnica (busca por referência/código/descrição, adiciona até 5 de uma vez, **Gerar fichas**, depois **Imprimir / Exportar PDF**), mas o documento gerado é mais completo: além do custo de produção, ele traz também a **Formação de Preço** — preço mínimo, ideal, premium, markup, lucro estimado e o preço de venda praticado, com o selo de status da margem.\n\nÉ a ficha pensada pra quem está vendendo (mostra o preço), diferente da Ficha Técnica do módulo Produto, que mostra só o custo de produção.',
    relacionados: ['gloss-ficha-tecnica', 'produto-ficha-tecnica-gerar'],
  },
  {
    id: 'vendas-lucratividade',
    modulo: 'vendas',
    tela: 'Lucratividade',
    titulo: 'Ver a lucratividade das vendas manuais',
    rota: '/vendas/lucratividade',
    perguntas: [
      'onde vejo a lucratividade das vendas',
      'lucro das vendas manuais',
      'relatorio de lucratividade de vendas',
      'margem das vendas do periodo',
      'filtrar lucratividade por periodo',
      'exportar relatorio de lucratividade',
      'pedido sem custo cadastrado na lucratividade',
      'lucratividade por canal de venda',
    ],
    resposta:
      'A tela **Lucratividade de Vendas** mostra o que sobra da venda direta depois de tudo, em cinco abas: **Resumo**, **Comissão por Vendedor**, **Pedidos**, **Produtos** e **Canais e Tabelas**.\n\nO Resumo traz a conta inteira em cascata, de cima para baixo: faturamento, menos custo da peça (o mesmo da Ficha de Custo, não uma estimativa), menos impostos → **lucro bruto**; menos a **comissão dos vendedores** → lucro depois da comissão; menos a **publicidade do mês** (lançada em Vendas › Publicidade e Despesas) → **lucro líquido**. As três margens aparecem lado a lado, em vez de um número só.\n\nDuas ressalvas ficam escritas na própria tela: pedido com item sem produto vinculado aparece marcado "sem custo" e fica **fora do total** (receita real com custo zero infla a margem); e pedido cuja comissão é sobre o lucro, num pedido sem custo, é contado como **"não calculável"** em vez de entrar como comissão zero.',
    relacionados: ['vendas-comissao-vendedor', 'vendas-publicidade', 'gloss-margem-contribuicao'],
  },
  {
    id: 'vendas-vendedor-vincular',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Vincular o vendedor que fez a venda',
    rota: '/pedidos',
    perguntas: [
      'como vinculo o vendedor na venda',
      'quem vendeu esse pedido',
      'cadastrar vendedor',
      'criar vendedor no sistema',
      'vendedor sem login',
      'pedido sem vendedor',
      'vendedor nao aparece no pedido',
    ],
    resposta:
      'O vendedor é escolhido no card **Quem compra e quem vende**, dentro do pedido. A lista vem do cadastro em **Configurações › Vendedores** (a mesma tela aparece como sub-aba de Acessos › Vendedores).\n\nVendedor pode existir **com ou sem login** no sistema. Quando ele tem uma conta ligada, todo pedido que ele criar já nasce no nome dele, sem ninguém precisar escolher. Cliente que tem vendedor fixo no cadastro também traz o vendedor junto ao ser selecionado.\n\nPedido sem vendedor continua valendo e contando no faturamento — só fica de fora do relatório de comissão, e a tela avisa isso antes de faturar.',
    relacionados: ['vendas-comissao-vendedor', 'vendas-tabela-preco-pedido'],
  },
  {
    id: 'vendas-comissao-vendedor',
    modulo: 'vendas',
    tela: 'Vendedores',
    titulo: 'Definir a comissão de cada vendedor',
    rota: '/configuracoes/vendedores',
    perguntas: [
      'como defino a comissao do vendedor',
      'comissao por vendedor',
      'comissao sobre o lucro ou sobre a venda',
      'comissao por peca',
      'meta do vendedor',
      'quanto pagar de comissao no mes',
      'relatorio de comissao',
    ],
    resposta:
      'Em **Configurações › Vendedores**, cada pessoa tem uma regra própria, de três formatos: **% sobre o faturamento** do pedido, **% sobre o lucro** (receita menos custo da peça e imposto) ou **R$ por peça** vendida. Também dá pra marcar que a comissão só conta **depois que o pedido é faturado** (é o padrão) e definir uma **meta de faturamento no mês**, que vira barra de progresso na tela e no relatório.\n\nO valor a pagar aparece na aba **Comissão por Vendedor** da Lucratividade, com pedidos, peças, receita, lucro, comissão e quanto sobra depois dela.\n\nUm cuidado que a tela declara: comissão **sobre o lucro** de um pedido com item sem custo cadastrado não pode ser calculada — ela aparece como **"não calculável"** e é contada à parte, em vez de virar zero e fazer você pagar a menos sem perceber.',
    relacionados: ['vendas-vendedor-vincular', 'vendas-lucratividade'],
  },
  {
    id: 'vendas-tabela-preco-pedido',
    modulo: 'vendas',
    tela: 'Tabelas de Preço',
    titulo: 'Tabelas de preço — atacado, lojista, varejo',
    rota: '/configuracoes/tabelas-preco',
    perguntas: [
      'como crio uma tabela de preco',
      'preco de atacado e varejo',
      'desconto por tipo de cliente',
      'preco diferente para lojista',
      'preco travado para uma referencia',
      'vincular tabela de preco na venda',
      'refazer os precos do pedido com outra tabela',
      'importar tabela de preco da planilha',
    ],
    resposta:
      'Em **Configurações › Tabelas de Preço** você cadastra quantas tabelas quiser (Atacado, Lojista, Varejo…). Cada uma tem um **desconto geral** — em **%** ou em **R$ por peça** — e pode ter **preço próprio por referência**: desconto específico ou **preço travado**, que ignora o desconto geral.\n\nA prioridade é sempre do mais específico para o mais geral: preço travado da referência → desconto da referência → desconto geral da tabela → preço cheio.\n\nNo pedido, a tabela é escolhida no card **Quem compra e quem vende** e vale para as próximas peças lançadas. Trocando a tabela no meio da venda, o sistema pergunta se quer **refazer os preços** das peças já lançadas. Uma tabela pode ser marcada como **padrão**: aí todo pedido novo já nasce com ela.\n\nImportante: a tabela **não** mexe em custo, margem, markup nem preço sugerido. Ela parte do preço que o sistema já calcula e aplica o desconto comercial em cima — a mesma conta que era feita à mão no balcão. Para carregar muitas referências de uma vez, existe o botão **Colar lista da planilha** (uma referência por linha); referência que não existe no cadastro é relatada, nunca casada por semelhança de nome.',
    relacionados: ['vendas-vendedor-vincular', 'config-taxas-venda'],
  },
  {
    id: 'vendas-bipar-camera',
    modulo: 'vendas',
    tela: 'Pedido de Venda',
    titulo: 'Bipar a peça com a câmera do celular',
    rota: '/pedidos',
    perguntas: [
      'bipar com a camera do celular',
      'ler codigo de barras pela camera',
      'vender pelo celular',
      'leitor de codigo de barras na venda',
      'camera nao abre pra bipar',
      'nao consigo bipar pelo celular',
      'lancar peca sem etiqueta',
    ],
    resposta:
      'Dentro do pedido, o card **Lançar peça** aceita três caminhos: bipar com um leitor comum (ele digita no campo e dá Enter), **tocar no botão da câmera** e ler a etiqueta pelo celular, ou procurar pela referência/descrição na busca logo abaixo — que mostra o estoque e o preço que aquela peça vai entrar, já com a tabela do pedido aplicada.\n\nNa leitura por câmera, cada bipe lança uma peça e o mesmo código só conta de novo depois de cerca de 2 segundos — sem isso, uma etiqueta parada na frente da câmera lançaria a mesma peça dezenas de vezes. Se a câmera não abrir, a mensagem diz o motivo (permissão negada, câmera ocupada por outro app, ou navegador sem suporte) e o campo de digitar continua funcionando.',
    relacionados: ['vendas-pedido-criar-lancar-cliente', 'estoque-bipagem-conferir'],
  },
  {
    id: 'vendas-publicidade',
    modulo: 'vendas',
    tela: 'Publicidade e Despesas',
    titulo: 'Lançar a publicidade do mês e as despesas da venda',
    rota: '/vendas/despesas',
    perguntas: [
      'onde lanco a publicidade do mes',
      'gasto com anuncio na venda direta',
      'quanto gastei de impulsionamento',
      'despesa de feira e brinde',
      'publicidade entra no lucro',
      'rateio da publicidade por dias',
    ],
    resposta:
      'A tela **Vendas › Publicidade e Despesas** é onde entra o que a venda direta gasta fora do custo da peça: impulsionamento de Instagram, Google, panfleto, feira, brinde, frete pago pela loja. O lançamento é por **mês de competência**, com valor, canal e uma descrição.\n\nEsse valor é o que a **Lucratividade** desconta do lucro. Quando o período que você escolher no relatório pega só parte de um mês, o valor daquele mês entra **rateado por dias** (dias dentro do período ÷ dias do mês) e a tela diz, linha por linha, quanto entrou e por quê — mostrar a publicidade do mês inteiro dentro de uma semana inventaria despesa, e escondê-la inventaria lucro.',
    relacionados: ['vendas-lucratividade', 'vendas-metricas'],
  },
  {
    id: 'vendas-metricas',
    modulo: 'vendas',
    tela: 'Métricas de Vendas',
    titulo: 'Painel de Métricas de Vendas',
    rota: '/vendas/metricas',
    perguntas: [
      'metricas de vendas',
      'quanto vendi no mes',
      'quanto cada vendedor vendeu',
      'ranking de vendedores',
      'curva abc das vendas',
      'clientes que pararam de comprar',
      'vendas por forma de pagamento',
      'ticket medio da loja',
      'comparar com o mes passado',
    ],
    resposta:
      'A tela **Métricas de Vendas** é o painel de volume da venda direta — o irmão do painel de Marketplace. Tem seis abas:\n\n· **Visão Geral** — vendido, pedidos, peças, ticket médio, preço médio por peça e clientes, cada um com a variação contra o período anterior de mesma duração; gráfico do vendido por dia com a linha do período anterior por cima; e a tabela dia a dia.\n· **Por Vendedor** — quanto cada um vendeu, em gráfico e em tabela, com ticket médio, desconto concedido e o quanto ficou **sem vendedor vinculado** (que é o que fica de fora da comissão).\n· **Produtos e ABC** — o que saiu, com curva de Pareto (A até 80% do faturamento, B até 95%, C o resto) e os tamanhos mais vendidos de cada referência.\n· **Clientes** — quem comprou, quanto, ticket médio, última compra e **há quantos dias não compra**.\n· **Canais e Pagamento** — quebras por canal, forma e condição de pagamento, tabela de preço, operação e empresa.\n· **Saída de Estoque** — quantas peças a venda tirou do estoque, separando o que já foi baixado (pedido faturado) do que ainda não foi.\n\nOs filtros do topo valem em todas as abas: período, vendedor, canal, tabela de preço, forma de pagamento e situação.',
    relacionados: ['vendas-lucratividade', 'mkt-metricas-visao-geral'],
  },
];
